### DISCUSSION TITLE
Why docker swarm route requests to unhealthy containers?

### DISCUSSION THREAD

**Discussion by fannyfan414** [moby/moby#44745] [Q&A]
Hey, i have my_app with 2 routes: **/ping** and **/home**
I create service with 2 replicas and setup healthcheck

```
services:
  my_app:
    networks:
      - app_network
    stop_grace_period: 20s    
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1    
    healthcheck:
      test: curl -sS http://127.0.0.1:80/ping | grep "pong"
      interval: 1s
      timeout: 2s
      retries: 3
      start_period: 30s
```
      
Then i connect to my containers and edit web server config, so http://127.0.0.1:80/ping started to return "error" message
After that, I saw that the containers got the status **"unhealthy"** 

But if i try to make request to **http://my_app:80/home** , then i got success response even though all containers are unhealthy

I expected swarm to **stop sending requests** to such containers
Swarm v20.10.22
