### DISCUSSION TITLE
Docker Containers fails with dependency after updating RHEL8 kernel

### DISCUSSION THREAD

**Discussion by st3v1s** [moby/moby#45105] [Q&A]
The following docker-compose.yml successfully starts up 3 containers when running on RHEL8 kernel 4.18.0-425.3.1.el8.x86_64.

docker-compose.yml:

```yaml
version: "2.1"
services:
  auth:
    image: nuwcdivnpt/stig-manager-auth
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    ports:
      - 50001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=stigman
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE

  api:
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=http://IP/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=IP
      - STIGMAN_DB_PORT=50001
      - STIGMAN_DB_PASSWORD=stigman
      - STIGMAN_INIT_IMPORT_STIGS=true
      - STIGMAN_CLIENT_OIDC_PROVIDER=http://IP/realms/stigman
    init: true
    ports:
      - 54000:54000
    depends_on:
      - auth
      - db
```

 I bring down the containers with command:  docker compose stop and run yum update --security, reboot, run docker compose start
I get an error with the auth container regarding "Could not parse MediaTypes"

```
Docker Engine - Community
Client/Server Version: 20.10.21
API: 1.41
```
RHEL8.7, fapolicy disabled, selinux enforcing

Thoughts on what it could be?  I have tried removing the images/containers and importing images and starting up but no luck.
