### DISCUSSION TITLE
Rootless mode can not expose any port or ip, and I can not access my containers

### DISCUSSION THREAD

**Discussion by granxavi** [moby/moby#47725] [Q&A]
When I install docker rootless on my Linux Server (inside Oracle Cloud) I can not expose any of my containers. Docker runs and the containers have communication among them. But I can not access them by any external means. I have tried multiple network drivers and configurations but nothing seems to work. I have noticed that in rootless mode the interfaces docker0 and veths that are normally built by docker are not shown unless you run the command. 
`nsenter -U --preserve-credentials -n -t $(pgrep dockerd) ip a `

I can connect to my server using http://MY_SERVER_IP:1880/ or using ssh `ssh -L 1880:MY_SERVER_IP:1880  -i /c/Users/MyUser/Desktop/ssh-key-file.key user@MY_SERVER_IP`  with http://localhost:1880/  

But once I install docker rootless. I can not access any of my services. Docker compose runs, and it does not show any log errors. If I go inside them with `docker exec -it <containername> bash ` I can see (when I am deploying more services) that they can talk with each other. But I can not access them using localhost or my server IP. Also when I try to reach it with http://localhost:1880 my console shows the following  `channel 7: open failed: connect failed: No route to host`

This is my docker-compose.yml
```
networks:
  my_net:
    name: my_network
    driver: bridge

services:
  nodered:
    container_name: Node-red
    image: nodered/node-red:3.1.9-18-minimal
    restart: always
    ports:
      - 1880:1880
    networks:
      my_net:
        aliases:
          - nodered_network
```

Is it possible what I am trying to do? I am a newbie with docker however I have found multiple discussions about the same problem, nothing works for me and the only solution that I have found is to give up rootless mode. Please help. I understand nothing! 

https://github.com/moby/moby/issues/43116
https://github.com/moby/moby/issues/41904
https://github.com/qoomon/docker-host/issues/49
https://github.com/madnificent/docker-ember/issues/36

**Comment by AkihiroSuda** [comment]
The containers have no reachable IPs, but the ports are still accessible with `docker run -p 8080:80`.

**Reply by granxavi** [reply]
I can not access them.  I will explain more about what I am doing.
If I run docker with docker compose up, everything works fine. 
I can connect to my server using http://MY_SERVER_IP:1880/ or using ssh `ssh -L 1880:MY_SERVER_IP:1880  -i /c/Users/MyUser/Desktop/ssh-key-file.key user@MY_SERVER_IP`  with http://localhost:1880/  

But once I install docker rootless. I can not access any of my services. Docker compose runs, and it does not show any log errors. If I go inside them with `docker exec -it <containername> bash ` I can see (when I am deploying more services) that they can talk with each other. But I can not access them using localhost or my server IP. Also when I try to reach it with http://localhost:1880 my console shows the following  `channel 7: open failed: connect failed: No route to host`

This is my docker-compose.yml
```
networks:
  my_net:
    name: my_network
    driver: bridge

services:
  nodered:
    container_name: Node-red
    image: nodered/node-red:3.1.9-18-minimal
    restart: always
    ports:
      - 1880:1880
    networks:
      my_net:
        aliases:
          - nodered_network
```
