### DISCUSSION TITLE
Mirror registry for docker images

### DISCUSSION THREAD

**Discussion by saireddyb** [moby/moby#49191] [Q&A]
When using mirror registry do we have to prepend the the docker image name with registry name or just with docker image name can I pull the images.
Eg
Consider this image alpine:latest
By default this will pull from docker hub
But when configured mirror registry
Is there any way to pull by just docker pull alpine:latest can this image be pulled from private repos ?

I have followed this article

https://docs.docker.com/docker-hub/image-library/mirror/

Setting-up a local mirror for Docker Hub images
and started docker registry
with this command

`$ docker run -d -p 5000:5000 --restart always --name registry registry:2`
But is there any specific config required in registry container to tell this is a mirror registry.
This is my current config.

```
/ # cat /etc/docker/registry/config.yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxies:
  default:
    remoteurl: https://registry-1.docker.io
```
