### ISSUE TITLE
Docker Security Profiles (seccomp, apparmor, etc)

### ISSUE THREAD

**Issue by icecrime** [moby/moby#17142]
As mentioned in our [ROADMAP.md](https://github.com/docker/docker/blob/master/ROADMAP.md#11-security), we'd like to progress toward [seccomp](https://en.wikipedia.org/wiki/Seccomp) support in Docker 1.10.

As a phase 1, I propose allowing the Engine to accept a seccomp profile at container run time. In the future, we might want to ship builtin profiles, or bake profiles in the images: design work about that future would be a plus.

Ping @jfrazelle who's interested to look into that!

**Comment by jfrazelle** [comment]
Lol little did you know I have a design doc ready

**Comment by jfrazelle** [comment]
## [RFC] Docker Security Profiles

**Assumptions**

- no one is going to sit and write out all the syscalls/capabilities their app needs
- automatic profiling would be super cool but like `aa-genprof` it is never
    perfect, leads to pain or removing the profile altogether, and an
    unmaintainable config file (we can always attempt this later)

**Goals**

- maintainable config
- readable by humans and not a linux syscall/cap nerd
- something an app developer would _want_ to write
- someone who did not right the config should be able to understand, at 
    least at a high level, what is restricted

**Inspiration**

- [iOS Permissions/Capabilities](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AboutEntitlements.html)
- [Android Permissions](https://developer.android.com/guide/topics/manifest/permission-element.html)
- [`tame`](https://marc.info/?l=openbsd-tech&m=143725996614627&w=2)



**Grouping into categories**

High level things you would want to configure should be generic and limited
to (for example):

- Networking
- Filesystem (Disk)
- Runtime (CPU/Memory operations)
- User Operations
- Misc

**Defining Permissions**

The cool thing about [`tame`](https://marc.info/?l=openbsd-tech&m=143725996614627&w=2)
I think we should implement are what they refer to as "flags". It's a set of
syscalls that they allow for a common goal, such as `TAME_RW` will allow all
the syscalls for i/o operations but `TAME_RPATH` only allows the syscalls that
will enable `read-only` effects on the filesystem.

We can have this same concept and define them w syscalls and capabilities.

We would need to discuss what these were and find the most common use cases for
them.

**Behaviors**

- If one permission denies a syscall and another allows it, the
deny should _always_ override the allow.
- Passing an empty config drops everything and nothing is allowed

**Super super super alpha example**

Kinda like [`jfrazelle/bane`](https://github.com/jfrazelle/bane) but better.

```toml
[Networking]
Flags = [
    # this will allow sendto(2), recvfrom(2), socket(2), connect(2)
    "dns",
    # adds CAP_NET_RAW
    "ping"
]

[Filesystem]
Flags = [
    # will allow lstat(2), chmod(2), chflags(2),
    # chown(2), unlink(2), fstat(2) on /tmp
    "tmp"
]
# filepaths where you would like to log on write
LogOnWrite = [
    "/etc/**",
    "/root/**"
]
# read-only filepaths
ReadOnly = [
    "/sys/**"
]

[Runtime]
Flags = [
    # allows getentropy(2), madvise(2), minherit(2),
    # mmap(2), mprotect(2), mquery(2), munmap(2)
    "malloc"
]

[User]
Flags = [
    # allows getuid(2), getgid(2), setuid(2), setugid(2)
    "create"
]
```

**Backends**

Will use whatever is installed on the system so if they have apparmor but no seccomp, then it will use apparmor (which can technically do all the syscall, cap, and filesystem privileges).

- AppArmor
- Seccomp
- Capabilities

**File Globbing**

Taken from apparmor profiles file globbing.

| Glob Example  | Description |
| ------------- | ------------- |
| `/dir/file` |   match a specific file |
| `/dir/*`        | match any files in a directory (including dot files) |
| `/dir/a*`      | match any file in a directory starting with a |
| `/dir/*.png`    | match any file in a directory ending with .png |
| `/dir/[^.]*`   | match any file in a directory except dot files |
| `/dir/`        | match a directory |
| `/dir/*/`       | match any directory within /dir/ |
| `/dir/a*/`     | match any directory within /dir/ starting with a |
| `/dir/*a/`     | match any directory within /dir/ ending with a |
| `/dir/**`       | match any file or directory in or below /dir/ |
| `/dir/**/`     | match any directory in or below /dir/ |
| `/dir/**[^/]`   | match any file in or below /dir/ |
| `/dir{,1,2}/**` | match any file or directory in or below /dir/, /dir1/, and /dir2/ |

**Questions**

- Should we allow people to define their own `flags` (or whatever we end up calling them)?
    I think yes. It could be cool to have a way to do it with a `define` in `text/template` I believe this is possible if it is implemented the way I am thinking ;)
