### ISSUE TITLE
Collecting CPU usage metrics when a container exits

### ISSUE THREAD

**Issue by delcypher** [moby/moby#18166]
Hi,

When using docker I'd like the ability to see what resources (specifically CPU user and system time) were used by that container when it exits.

I had a read of https://docs.docker.com/engine/articles/runmetrics/#collecting-metrics-when-a-container-exits

This document seems out of date because AFAIK libcontainer is now the default (and preferred way of using Docker). Further more it looks like libcontainer has [data structures (`CpuUsage`)](https://github.com/docker/libcontainer/blob/master/cgroups/stats.go#L15) that provide this information.

Unfortunately Docker doesn't seem to expose this information and it also removes the cgroup that is used by the container on exit so I can't read the `/sys/fs/cgroup/cpuacct/docker/<ID>/cpuacct.stat` file after the container finishes.

I thought that the `docker stats` command might provide that but it just blocks when you give it a stopped container (presumably its waiting for resource information to be streamed to it).

So I'd like to propose that metrics of a container be available as the output of `docker inspect <ID>` under the `"State":` key. I.e. something like

``` yaml
    "State": {
        "Status": "exited",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-23T13:02:03.369615678Z",
        "FinishedAt": "2015-11-23T13:02:08.73097369Z"
       # New Key value pairs
       # This would be accumulated values across the life time of the container
       # i.e. starting, stopping and starting again would not reset these counters.
       "AccumulatedUserCPUTime": 4.5 # In Seconds
       "AccumulatedSysCPUTime":  1.0 # In Seconds
    },
```

I can understand why something like this hasn't been a priority for Docker. Most users I suspect care about long running services and so only care about stats whilst the container runs, not when it exits.

My use case for Docker is a little different however. I am using it to benchmark various applications in a way that is easy to reproduce with resource limiting (i.e. cpu and memory limits) features.

Can anyone comment on the feasibility of adding the feature I've suggested?
