### ISSUE TITLE
Initializing docker compose volumes

### ISSUE THREAD

**Issue by gittycat** [moby/moby#20390]
With Docker 1.10.0, Named volumes are now initialized from the docker container that they are first mounted on. https://github.com/docker/docker/issues/18670

This means that after doing `docker run -v data:/usr/lib alpine /bin/true`, a volume named `data` is created which contains whatever the alpine image has at `/usr/lib`.

This isn't clear with docker compose. In the following docker-compose file for instance, we don't know which service will initialize the volume `data`.

```
version: '2'
services:
    app1:
        image: imageA
        volumes:
            - data:/var/myapp
    app2:
        image: imageB
        volumes:
            - data:/var/myapp
volumes:
    data:
```

There are hacks to get around this (creating services only for the purpose of initializing volumes) but is there any plan to have a simpler and more elegant way to specify how a volume is initialized?
