### ISSUE TITLE
Port forwarding problems on Ubuntu 14.04 with 100+ containers running

### ISSUE THREAD

**Issue by anttiviljami** [moby/moby#22325]
**Output of `docker version`:**

```
lient:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 138
Images: 293
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 569
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 10
Total Memory: 13.7 GiB
Name: dockertest.anttiviljami.com
ID: XOJO:TPPD:TXB4:7Z4Z:MH4L:LKFV:BMPG:3K4Z:ZPSF:Y7EU:JQMU:HW7P
Username: dockeruser
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Upcloud scalable VPS

**Steps to reproduce the issue:**
1. Have 100+ containers running, each with unique ports forwarded with `-p 127.0.0.1:<unique port between 30000-50000>:80`
2. Select one of the containers and run `docker kill` and `docker rm` on it. Do a `docker run` again with all the same parameters and unique port number as originally run for the container.

**Describe the results you received:**
After doing this, you will find that exactly one of the other assigned ports, that we didn't touch, will also now be pointing to the newly started container's port 80. 

It seems completely random which port will be the one mapped incorrectly. You have to find it by checking each assigned port individually.

The workaround is to simply restart the docker daemon and magically without any configuration changes, all ports will be mapped correctly again after this.

**Describe the results you expected:**
The only port that should be pointing to the new container, should be the one assigned to it. None of the previous port forwardings should be affected.

**Additional information you deem important (e.g. issue happens only occasionally):**
The Docker daemon is running with custom opts to bind running containers to the old default 127.17.421/16 address space.

```
--bip 172.17.42.1/16
```

**Comment by thaJeztah** [comment]
Wonder if this is similar to https://github.com/docker/docker/issues/21699, looking at your description it sounds a bit similar (but the other issue was really confusing).

Is there a way to easily reproduce this? Would you be able to test if this is still reproducible on docker 1.10 or 1.11 (in a test-setup)?

**Comment by Ara4Sh** [comment]
Same problem : 
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64
```

I have multiple web application containers with ports 80 / 8000 / 8080 and all of them redirect only to container with port 80 I checked nat rules all ok 

what do you suggest ? 

thank you

**Comment by Ara4Sh** [comment]
Similar error on Docker 1.11.1 
```Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Comment by anttiviljami** [comment]
@Ara4Sh can you demonstrate steps to reproduce the issue in your case? I was unable to reproduce this problem in a fresh install of docker-engine. I wasn't able to test with more than 30 containers though, due to the VM limitations.

**Comment by anttiviljami** [comment]
Also, a matter that might turn out to be relevant here for troubleshooting is that in addition to the http service we are running on each container that gets mapped from container to ports 30000-49999, we are also running a separate service on another port that gets mapped to 10000-29999. 

In these cases, both forwardings were affected, and were routed to the same wrong container.

**Comment by Ara4Sh** [comment]
Hello 
here is environment details : 
```
uname -a :  Linux 1-vm-mesos-esxa04-a01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
lsbrelease -a :
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.4 (jessie)
Release:	8.4
Codename:	jessie
```
you can see docker information above docker 1.11.1 

im using docker-compose : 
```
docker-compose version:
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

here is our first app : 
```
database:
  image: percona:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=XXXXXXX
  command: mysqld
  volumes:
    - /datastore/xxxx.com/mysql:/var/lib/mysql
    - /datastore/xxxx.com/share:/share
  ports:
    - "3306:3306"

appx:
  image: arash/nginx-hhvm
  links:
    - database:mysql
  environment:
    - SITE_NAME=xxxx.com
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /datastore/7sobh.com/public_html:/var/www
    - /datastore/7sobh.com/logs:/var/log/nginx
```
another web app : 

```
db:
  image: percona:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=XXXXXXX
  command: mysqld
  volumes:
    - /datastore/dev.banifilm.ir/mysql:/var/lib/mysql
    - /datastore/dev.banifilm.ir/share:/share
  ports:
    - "3307:3306"

appz:
  image: arash/nginx-hhvm
  links:
    - db:mysql
  environment:
    - SITE_NAME=zzzz.ir
  ports:
    - "8000:80"
    - "4433:443"
  volumes:
    - /datastore/zzzz.ir/public_html:/var/www
    - /datastore/zzzz.ir/logs:/var/log/nginx
    - /datastore/zzzz.ir/share:/share

```
so after starting each webapplications host:3307 sucessfully mapped to container:3306
but host:8000 is not mapped to containerappz:80 its forwarded into host:80 i guess . 

I checked with both docker 1.11.0 and 1.11.1 problem exists
