### ISSUE TITLE
Change default application bundle name for docker deploy command

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#24249]
Docker version `1.12.0-rc2-beta17`

Use the following `docker-compose.yml`:

```
version: "2"
services:
  db:
    container_name: "db"
    image: arungupta/oreilly-couchbase:latest
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210
  web:
    image: arungupta/oreilly-wildfly:latest
    depends_on:
      - db
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
```

Generate a Distributed Application Bundle as `docker-compose bundle`:

```
hello-javaee > docker-compose bundle
WARNING: Unsupported key 'depends_on' in services.web - ignoring
WARNING: Unsupported key 'container_name' in services.db - ignoring
Wrote bundle to hellojavaee.dsb
```

Give the command `docker deploy` in the same directory:

```
docker deploy
"docker deploy" requires exactly 1 argument(s).
See 'docker deploy --help'.

Usage:  docker deploy [OPTIONS] STACK

Create and update a stack
```

It would simplify the command usage if the default project name is automatically chosen. The current default is `STACK.dsb`. It would be great if in this case it is defaulted to `hellojavaee.dsb`.
