### ISSUE TITLE
Setting OOM score for ready process caused "write /proc/5578/oom_score_adj: invalid argument"

### ISSUE THREAD

**Issue by alfonsoperez** [moby/moby#25099]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 7
 Paused: 0
 Stopped: 9
Images: 72
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 332
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: Z3AR:3OHB:47FY:H22B:IWGM:IFLR:T7SP:IRUW:SOSA:43U6:D77Z:B2HP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 82
 System Time: 2016-07-27T00:02:38.724549572Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: alfonsoperez
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker for mac

**Steps to reproduce the issue:**
1.  `docker-compose ..../docker-compose.yml up web`

**Describe the results you received:**

```
ERROR: for web  oci runtime error: process_linux.go:295: setting oom score for ready process caused "write /proc/5578/oom_score_adj: invalid argument"
```

**Describe the results you expected:**

Starting the container

**Additional information you deem important (e.g. issue happens only occasionally):**

Tried restarting docker / removing the containers several times

**Comment by justincormack** [comment]
Sorry, we would need more information about your compose file to be able to replicate this.

**Comment by alfonsoperez** [comment]
Hi @justincormack , here you go.

```
web:
  image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/xxxx:xxxx
  command: bundle exec foreman start web -f /pocket_change/Procfile -p 3000
  env_file: env
  volumes:
    - ../..:/pocket_change
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL: postgis://postgres@postgres/pocket_change_development
    REDSHIFT_DATABASE_URL: redshift://xxxxxx:xxxxxxxx@xxxxxxx.xxxxxxx.us-east-1.redshift.amazonaws.com:5439/dev
    OPENREDIS_URL: redis://redis:6379
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    RABBITMQ_MANAGEMENT_URL: http://rabbitmq:15672/api
  links:
    - postgres
    - redis
    - rabbitmq

approvals:
  image: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/xxxxxxx:development
  ports:
    - "7070:7070"
  environment:
    NODE_ENV: development

subscription:
  image: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxxx/xxxxxx
  ports:
    - "9090:9090"
  environment:
    NODE_ENV: development

nervecenter:
  image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxxx/xxxxxx:development
  ports:
    - "8090:8090"
  environment:
    NODE_ENV: development

authfilter:
  image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/authfilter
  ports:
    - "3456:80"
  environment:
    AUTH_SERVICE_HOST: authservice
    AUTH_SERVICE_PORT: 8443
    APP_HOST: web
    APP_PORT: 3000
    APP_PROTOCOL: 'http'
  links:
    - authservice
    - web

authservice:
  image: xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxx/auth-service
  environment:
    DATABASE_URL: postgres://postgres:@postgres/development
  ports:
    - "8080:8080"
    - "8443:8443"
  links:
    - postgres

postgres:
  image: mdillon/postgis:9.5
  ports:
    - "5432:5432"
  volumes_from:
    - postgresdata

rabbitmq:
  image: rabbitmq:3.4.4-management
  ports:
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:2.8.19
  ports:
    - "6379:6379"

bundle:
  image: busybox
  volumes:
    - /bundle

postgresdata:
  image: busybox
  volumes:
    - ../pgdata:/var/lib/postgresql/data
```

Thanks
