### ISSUE TITLE
[BUG] Docker-proxy binds on ports but no container is running (anymore)

### ISSUE THREAD

**Issue by nagua** [moby/moby#25981]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 93
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 211
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.748 GiB
Name: motocom.2hg.org
ID: O4YH:4KEL:GEY3:C26M:QWMN:PCLK:RF6E:DQSG:XPWG:SSBE:FVE3:GWBL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a dedicated server running Debian Jessie. Everything up to date.

```
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

```
# netstat -ap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 *:3389                  *:*                     LISTEN      890/openvpn
tcp        0      0 localhost:mysql         *:*                     LISTEN      1276/mysqld
tcp        0      0 *:ssh                   *:*                     LISTEN      727/sshd
tcp        0    336 xxx:ssh     ip1f10d8b9.dynami:60637 ESTABLISHED 1641/sshd: xxx
tcp        0      1 xxx:ssh     116.31.116.52:53774     FIN_WAIT1   -
tcp6       0      0 [::]:smtp               [::]:*                  LISTEN      6346/docker-proxy
tcp6       0      0 [::]:5280               [::]:*                  LISTEN      6366/docker-proxy
tcp6       0      0 [::]:imaps              [::]:*                  LISTEN      6316/docker-proxy
tcp6       0      0 [::]:5443               [::]:*                  LISTEN      6356/docker-proxy
tcp6       0      0 [::]:xmpp-client        [::]:*                  LISTEN      6386/docker-proxy
tcp6       0      0 [::]:submission         [::]:*                  LISTEN      6326/docker-proxy
tcp6       0      0 [::]:imap2              [::]:*                  LISTEN      6336/docker-proxy
tcp6       0      0 [::]:xmpp-server        [::]:*                  LISTEN      6376/docker-proxy
[...]
```

**Steps to reproduce the issue:**
1. I upgraded from version 1.12.0 to 1.12.1.
2. I tried to restart my containers but they failed to allocate ports.
3. The ports are allocated by `docker-proxy` but no container is running.

**Describe the results you received:**
I can not start the containers because the ports are already in use.

**Describe the results you expected:**
Docker-proxy does not allocate ports docker does not use.

**Additional information you deem important (e.g. issue happens only occasionally):**

I already tried to restrict docker to ipv4 but this was not changing anything. I also tried to restart docker/server but docker also allocates many ports. I use docker-compose to manage my containers if this matters.

Are there more information needed? Is there a quick workaround available make docker think that the ports are not needed anymore?

**Comment by amitkumarj441** [comment]
Hey @nagua,

It isn't really possible to simply close a port from outside the application that opened the socket listening on it. The only way to do this is to completely kill the process that owns the port. Then, in about a minute or two, the port will become available again for use. Here's what's going on (if you don't care, skip to the end where I show you how to kill the process owning a particular port):

Anyway, here's how to kill a process that owns a particular port:

`sudo netstat -ap | grep :<port_number>`

That will output the line corresponding to the process holding port . Then, look in the last column, you'll see /. Then execute this:

`kill  <pid>`

For more info: #5666 and #6682

**Comment by nagua** [comment]
I now moved /var/lib/docker away, restarted docker and copied the volumes directory back in the newly created docker folder. Now everything is working again. If you need some files from there for debug purposes, i have the old docker folder lying around.

**Comment by sanimej** [comment]
@nagua I am not able to recreate this. I had some containers running with port published. When I restart the daemon `docker-proxy` processes also go down and the ports are available. I didn't try the upgrade from 1.12.0 to 1.12.1. But it shouldn't be very different from a daemon restart. Did you notice when the `docker-proxy` processes moved to zombie state ?

**Comment by kossmoss** [comment]
Have same problem running docker (v 1.12.1) via docker-compose inside virtual machine running on Vagrant.
Noticed this problem several times after restarting virtual machine (probably this is sign of incorrect terminating docker daemon processes).
I have several occupied ports (and docker ps shows no any actual docker containers running at the same time)
Simple killing processes and restarting docker service (or even whole virtual machine) doesnt solve the problem. Every time docker daemon restarts, it brings those zombie docker-proxy processes again and ports are still unavailable for new containers.

I'm going to try to solve problem by saving virtual machine snapshot and after that will try to clear /var/lib/docker as @nagua did.

**Comment by cpuguy83** [comment]
@kossmoss Can you explain the "zombie docker-proxy processes" comment?
Do you see `docker-proxy` running while the daemon is not up?

**Comment by nagua** [comment]
@kossmoss When I started the docker daemon it starts up the docker-proxy processes. For ports where no container exists anymore that uses these ports. Trying to kill the docker-proxy processes doesn't help because they do not exit and ends up in a zombie process state. So they do not release the ports.

So I had no way to use the ports again while docker was running.

**Comment by hopeseekr** [comment]
We have this same problem. It's binding to ports 3306 and 5900 that containers usually bind, but now none of those containers will start. Help!

**Comment by jwodder** [comment]
We appears to be experiencing this same problem.

Docker 1.12.0
Ubuntu 16.04
Kernel: 4.4.0-36-generic

After restarting the Docker daemon (in order to fix a presumably unrelated problem with an unstoppable container) on an instance with 70 containers, approximately 44 of which have exposed ports, four of the containers were unable to start (even after deleting & recreating them) because their ports were in use by `docker-proxy` instances.  I tried killing one of the instances, but it just became a zombie, which Docker still hasn't reaped after about 10 minutes.

**Comment by kossmoss** [comment]
@cpuguy83 sorry for the late reply. Probably, "zombie" is not proper definition for that - I was limited in time and didn't performed too much of investigations and can't say how exactly we need to call those processes. My way to look on currently opened ports is **sudo netcat -tunlp** command or **sudo service docker status**.  In both cases, after docker daemon started, I see those docker-proxy processes occupying the ports, but in the same time see no any running docker containers in **docker ps** output.

When I kill docker-proxy process, it actually destroyed and port is not occupied until next docker daemon restart.

When docker daemon is stopped, there's no any running docker-proxy processes. They only running when docker daemon is running. Seems they are starting automatically at some point of docker daemon starting procedure. This also seems like docker holds those processes' state somewhere when stopped and brings them live when started, but does not link those processes to any running docker containers. 

Maybe this problem caused by starting containers via docker-compose instead of simple docker run? @hopeseekr are you using docker-compose?

**Comment by rdavaillaud** [comment]
Well, we've got the same problem, with compose 1.8, docker 1.12.1 on fedora 24.

**Comment by rdavaillaud** [comment]
Well, I managed to find a workaround:

- stop docker
- remove all internal docker network: rm /var/lib/docker/network/files/
- start docker

**Comment by sanimej** [comment]
@rdavaillaud @kossmoss I couldn't recreate the issue. But I wasn't using compose. All the reported occurrences seem to be happening with compose. Can you give the exact steps you are using that results in the issue ?

**Comment by chione** [comment]
I work with rdavaillaud and we have 4 pc using this docker and compose configuration, and this happend to only one of the pc one day after a computer reboot.

So we don't really know how to reproduce.

**Comment by rdavaillaud** [comment]
This is our docker-compose.yml, nothing fancy here I think, and no network definition.
```yaml
version: '2'
services:
  frontal:
    build:
      context: ./Docker/frontalWeb
    container_name: frontal
    extra_hosts:
     - "app.dev.local:127.0.0.1"
     - "www.app.dev.local:127.0.0.1"
     - "ws.app.dev.local:127.0.0.1"
    image: local/frontalweb
    links:
      - bdd:HBS-BDD
      - tilecache:carto.app.dev.local
      - tilecache:carto1.app.dev.local
      - tilecache:carto2.app.dev.local
      - tilecache:carto3.app.dev.local
      - tilecache:carto4.app.dev.local
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/var/www/app/app-source
      - ./../app-datas:/var/local/app-datas
      - ./System/apache/:/etc/httpd/sites-enabled/
      - ./Docker/frontalWeb/docker-entrypoint.d:/docker-entrypoint.d
      - ./app.crt:/etc/ssl/app.com/app.com.cer
      - ./app.key:/etc/ssl/app.com/app.com.key
      - ./app.crt:/etc/ssl/app.com/app.crt

  tilecache:
    build:
      context: ./Docker/tilecache
    container_name: tilecache
    links:
      - mapserver:carto.app.dev.local
      - mapserver:carto1.app.dev.local
      - mapserver:carto2.app.dev.local
      - mapserver:carto3.app.dev.local
      - mapserver:carto4.app.dev.local
    ports:
      - "82:80"
    volumes:
      - ./Carto:/var/www/app/app/Carto
      - ./../mapfiles/app:/var/local/spatial/app
      - ./../app-datas:/var/local/app-datas
      - ./Docker/tilecache/docker-entrypoint.d:/docker-entrypoint.d

  mapserver:
    build:
      context: ./Docker/mapserver
    container_name: mapserver
    links:
      - bdd:HBS-BDD
    ports:
      - "81:80"
    volumes:
      - ./Carto:/var/www/app/app/Carto
      - ./../mapfiles/app:/var/local/spatial/app
      - ./../app-datas:/var/local/app-datas
      - ./Docker/mapserver/docker-entrypoint.d:/docker-entrypoint.d

  bdd:
    build:
      context: ./Docker/postgresql
    cap_add:
      - SYS_ADMIN
    container_name: bdd
    ports:
      - "5432:5432"
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./DataBase:/var/www/app/app/DataBase
      - ./../app-datas-bdd:/var/local/app-datas
      - ./Docker/postgresql/docker-entrypoint.d:/docker-entrypoint.d
```

The docker containers are built from official centos7-systemd image.
The hosts are on Fedora 24, Docker-engine 1.12.1 and Compose 1.8.

We will tell you if it happens again.
