### ISSUE TITLE
Potential format for specifying deploy-time parameters for DABs

### ISSUE THREAD

**Issue by techninja1008** [moby/moby#26748]
Currently, DABs can only store portable information about a deployment, that is, they cannot store things such as bind mounts, or any type of mounts for that matter.

The main problem here is that people want to do operations such as map ports (#25594), specify volume names and options, scale services, and more. These pieces of information would never belong in a DAB.

The proposition I am making is for a second file-format (a commonly suggested and hinted idea), that holds this information, in relation to names of services **within** an existing DAB. This format could be called an **A**pplication **S**ettings **B**undle, and could be specified when deploying a stack, or at a later time (as all parts of it would be condensable into `docker service update` commands). Also, it would help if docker-compose could export relevant settings from a `docker-compose.yml` file.
It would also help if it was YAML formatted, as in most cases it would be assembled by the end user.

Relates to #26327

**Comment by thaJeztah** [comment]
Also relates to https://github.com/docker/docker/issues/26327

**Comment by techninja1008** [comment]
Proposed non-exhaustive example, in YAML:
```yaml
version: '1'

services:
    web: # Able to specify any parameters suppliable to 'docker service update'
        ports:
        - 80:80
        env:
            HOST: 'www.example.com'
        deploy-mode: replicated
        replicas: 7
    db:
        env:
            MYSQL_ROOT_PASSWORD: abc123
        mounts: # Map based on 'dst' field
            '/var/lib/mysql':
                type: volume
                name: some_db_volume

volumes:
    some_db_volume:
        driver: local
        options: # Map equivalent to --opt on 'docker volume create'
            type: nfs
            o: addr=192.168.1.1,rw
            device: ':/some/data/directory'

networks:
    database:
        driver: overlay # Implied option
        ipv6: true
        options: # Driver specific options
        # subnet:
        # ipam-driver:
        # etc.
        
```
