### ISSUE TITLE
Feature Request: Please add support for extends when deploying a stack from a compose-file

### ISSUE THREAD

**Issue by marascha** [moby/moby#29304]
In v1.13.0-rc3 it's not possible to deploy a stack using a compose-file that contains services extending other services using  _extends_.

**Example** 
compose.yml:
```
version: '3.0'
    services:
      service2:
        extends:
           file: ../common-services.yml
           service: service1
        deploy:
            replicas: 2
```
Docker  responses with the following error message when running 

> docker stack deploy --compose-file compose.yml my_stack
```
Compose file contains unsupported options:

extends: Support for `extends` is not implemented yet. Use `docker-compose config` to generate a configuration with all `extends` options resolved, and deploy from that.
```
The workaround with 'docker-compose config' is not really an option, as version 3.0 is not supported by docker-compose and _deploy_ is not available in version 2.1 of docker-compose.

It will be great if the support for extend could be added soon.
