### ISSUE TITLE
Deploy to swarm from multiple compose files

### ISSUE THREAD

**Issue by Parnswir** [moby/moby#30127]
I'm currently testing the new `--compose-file` parameter for `docker stack deploy` in 1.13.0-rc6, but my use case requires deploying from multiple compose files (as possible with `docker-compose -f base.yml -f additionalService.yml -f production.yml`). At the moment, using globs or multiple `--compose-file` is not supported as far as I can see. Are there plans to support this in future releases? 

A simple workaround/implementation strategy is to merge the compose files before deploying, but I would rather want to avoid using temporary files.

**Comment by vsellier** [comment]
I have exactly the same problem.

As a workaround, I'm using : 
``docker-compose -f compose1.yml -f compose2.yml bundle -o myfile.dab ``

It generates a stack file you can pass to docker stack :
``docker stack deploy --bundle-file myfile.dab mystack``

**Comment by Parnswir** [comment]
As far as I can see, (as of docker-compose 1.10.0) bundles [do not support all features](https://docs.docker.com/compose/bundles/) of the compose file format (network aliases, deployment, for example), which is why I use an external yaml merge tool as a workaround.

**Comment by bvis** [comment]
@Parnswir do you have an example of the usage of this tool?

**Comment by Parnswir** [comment]
`npm i -g merge-yaml`
`merge-yaml -i base.yml foo-*.yml -o /tmp/bundle.yml && docker stack deploy --compose-file=/tmp/bundle.yml deployment`

**Comment by mahnunchik** [comment]
Any news?

**Comment by bvis** [comment]
This is not a problem for us anymore.

As a rule of thumb now we define the production configuration in the `docker-compose.yml` file. In case you need some variables you just need to add them with a default value for production.

Typically 

```
services:
  my-service:
    build:
      context: .
    image: private.registry.mine/my-stack/my-service:${MY_SERVICE_VERSION:-latest}
...
```

And we have another file `docker-compose.override.yml` with development values (mount code volumes, etc).

This allows us to simplify things. When you are developing something locally you just do:
```bash
$ docker-compose up -d
```
When you want to deploy to your cluster, we have this command in our CI/CD pipeline:
```bash
$ docker stack deploy my-stack --compose-file docker-compose.yml --with-registry-auth
```

**Comment by teohhanhui** [comment]
@bvis But that doesn't always work. What if we need some overrides in the production environment?

**Comment by bvis** [comment]
@teohhanhui I'm not sure I understand you, but what I mean is the the `docker-compose.yml` file contains your productive configuration, no more, no less. Imagine this file as something that is not useful for development and it just works in production, initially.

But.. what if my CI/CD pipeline requires an staging step? No problem! environment variables come to rescue!

From my example you can use more variables to define your stack behaviour, for example imagine that you need a different API endpoint when your app is being deployed to staging. You could save this with just this variable:

```yml
...
services:
  my-service:
    build:
      context: .
    image: private.registry.mine/my-stack/my-service:${MY_SERVICE_VERSION:-latest}
    environment:
      API_ENDPOINT: ${API_ENDPOINT:-https://production.my-api.com}
...
```
*Remember*: Your `docker-compose.yml` file should be deployable in production, then use as defaults your productive values.

First you build and push your images (the same images are used on ANY environment)

``` bash
export MY_SERVICE_VERSION=1.2.3
docker-compose -f docker-compose.yml build
docker-compose -f docker-compose.yml push
```

But this would work in your staging environment (even development!) just defining an environment variable before launching your stack there:

``` bash
export MY_SERVICE_VERSION=1.2.3
export API_ENDPOINT=http://staging.my-api.com
docker stack deploy my-stack --compose-file docker-compose.yml --with-registry-auth
```

On other hand you need something for development, isn't it? You can define your environment variables adapted for DEV and you can use the `docker-compose.override.yml` for those things that are not just based on environment variables, like mounting volumes for the source code you are working on. It's as simple as redefine just for development in the `docker-compose.override.yml`:

``` yaml
...
services:
  my-service:
    ports:
      - 80:80
    environment:
      API_ENDPOINT: https://devel.my-api.com
    volumes:
      - ./:/project/src
...
```
And you can enjoy developing with you well known compose command:

``` bash
docker-compose up -d
```
It will take care of merge your productive definition (`docker-compose.yml`) with your development configuration (`docker-compose.override.yml`).

I hope this more detailed description helps. If you have doubts or suggestions just tell me.

**Comment by teohhanhui** [comment]
Let me describe what I'm currently doing (with `docker compose up -d`):

In my project, `docker-compose.override.yml` is git-ignored. I provide dist files, for example `docker-compose.override.prod.yml` and `docker-compose.override.dev.yml`, which I then copy to `docker-compose.override.yml` and customize to my needs.

With the above in mind, this is the approach I've tried:

```sh
docker-compose config > docker-stack.prod.yml
docker stack deploy --compose-file docker-stack.prod.yml mystack
```

It seems to work well.

**Comment by ph-One** [comment]
@teohhanhui I'm having issues with that approach -- using `config` to concat the files. It seems that `config` changes the `ports` section to use published/target syntax, versus "80:80" syntax, which `stack` seems to not like too much...

```
ports:
    - published: '12181'
      target: '2181'
    - published: '12888'
      target: '2888'
    - published: '13888'
      target: '3888'
```
```
services.{service-name-here}.ports.0 must be a string or number
```
