### ISSUE TITLE
Updating swarm services

### ISSUE THREAD

**Issue by mahmoudmahdi24** [moby/moby#30635]
Hello,

I am facing a serious problem with docker swarm mode (docker version :  1.13.0).

If i create a stack with 2 services with a docker-compose (v3), they get perfectly created in a swarm mode.

If i update my docker compose file and add a third service and relaunch the command " docker stack deploy --compose-file=docker-compose.yml <name_stack> ", it says that it's updating the old services  and creating the new one, but when i check the list of the services, i get only the two old services.

If i restart the docker-engine and relaunch the deployment of the services, i get the three services up and running.

Is it normal that i have to restart the docker-engine everytime I add a new service or modify my current stack ? 

Here's my docker-compose file : 
```
version: "3"
services:
  frontend:
    image: atlassian/confluence-server
    expose:
      - 8090
    ports:
      - 8090:8090
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: postgres:9.4
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - /Users/pc/postgresData:/var/lib/postgresql/data


  proxy:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

```
Thanks,

**Comment by gianarb** [comment]
Hello @mahmoudmahdi24 thanks for your report! Can you run `docker system info` into the node master?

Just to double check. You are starting a service with `backend` and `fronted` after that, you add `proxy` run `docker stack update` and you get the problem described. is it right?

**Comment by mahmoudmahdi24** [comment]
Yes that's the scenario ! In fact, to update a stack (referring to the official documentation of docker), i have to relaunch the command :
```docker stack deploy ```
and that's what i have done, but it doesn't update my stack ( it doesn't add the proxy ).
It only works if i restart my docker-engine ! and relaunch the whole stack ..

Here's my docker system info : 
```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 6
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ptdcg4mhp0q0swqykqkmo3aw3
 Is Manager: true
 ClusterID: 807cfeer9ddqggh2e6pehb04z
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: BZJU:AZHZ:Y6AR:LX3K:WWZV:K6O2:2V7G:ZYII:UVDA:BLA3:NVXT:LXMN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 57
 Goroutines: 164
 System Time: 2017-02-01T17:12:24.961184233Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanks,

**Comment by arhea** [comment]
@mahmoudmahdi24 I was attempting to reproduce the issue and it I ran into an issue with the docker-compose.yml file. Legacy `restart` flags to the `backend` and `proxy` services which may be an issue. However, when running on my local machine with Docker for Mac it just hung. My file was as follows:

```yaml
version: "3"
services:
  frontend:
    image: atlassian/confluence-server
    expose:
      - 8090
    ports:
      - 8090
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: postgres:9.4
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=test_user"
      - "POSTGRES_PASSWORD=test_pass"
    volumes:
      - /var/lib/postgresql/data

  proxy:
    image: grafana/grafana
    ports:
      - 3000
```
