### ISSUE TITLE
CloudWatch driver for docker service logs

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#30691]
Deployed a Compose application to a Docker cluster created using Docker for AWS. Deployed a Compose application:

```
version: '3'
services:
  web:
    image: arungupta/couchbase-javaee:travel
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - db
  db:
    image: arungupta/couchbase:travel
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
```

`docker service logs webapp_web` does not show any logs. By default, Docker for AWS is configured to logs to CloudWatch. Based upon discussion in Slack channel, it seems like CloudWatch driver for `docker service logs` need to be built.

@kencochrane FYI
