### ISSUE TITLE
templated volume name syntax not supported in compose v3 format?

### ISSUE THREAD

**Issue by hairyhenderson** [moby/moby#30770]
**Description**

Trying to play with the new templating features in 1.13, I wanted to template a volume name in a `docker-compose.yml` file for deployment with `docker stack deploy`. I got an `undefined volume` error, however.

**Steps to reproduce the issue:**
1. Create a v3 `docker-compose.yml` file:
```yaml
version: '3.1'
services:
  redis:
    image: redis
    volumes:
      - "redisVol-{{.Task.Slot}}:/data"
volumes:
  redisVol-1:
    driver: local
```
2. Attempt to deploy this:
```console
$ docker stack deploy -c docker-compose.yml redis
undefined volume: redisVol-{{.Task.Slot}}
```

**Describe the results you received:**

An error: `undefined volume: redisVol-{{.Task.Slot}}`

**Describe the results you expected:**

Expected the volume reference to match ;)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 32
 Running: 7
 Paused: 0
 Stopped: 25
Images: 250
Server Version: 1.13.1-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: pxwtehg7hjvgrzd7z1yhwrna8
 Is Manager: true
 ClusterID: xerj566k9hqteqrznvkyg3z6f
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.6-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 72VG:JFL4:ITTA:T6HT:HZ6S:3XKE:ASDY:YB3S:32EF:FQJS:AVHS:HFQQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 90
 Goroutines: 199
 System Time: 2017-02-06T20:13:35.084216266Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: hairyhenderson
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac Version 1.13.1-rc1-beta40 (15241)

**Comment by dnephin** [comment]
The volume name under `services` in a Compose file is not the actual volume name. It's a reference to a volume defined in the top level `volumes` section of the Compose file.

It might work if you add:

```yaml
volumes:
  'redisVol-{{.Task.Slot}}': {}
```

Otherwise you might have to use external volumes:

```yaml
volumes:
  redisVol:
    external:
      name: 'redisVol-{{.Task.Slot}}'
```

**Comment by hairyhenderson** [comment]
thanks @dnephin.

This doesn't work:

```yaml
version: '3.1'
services:
  redis:
    image: redis
    volumes:
      - "redisVol-{{.Task.Slot}}:/data"
volumes:
  'redisVol-{{.Task.Slot}}': {}
```

```console
$ docker stack deploy -c c.yml redis
redisVol-{{.Task.Slot}} Additional property redisVol-{{.Task.Slot}} is not allowed
```

BUT! This works!

```yaml
version: '3.1'
services:
  redis:
    image: redis
    volumes:
      - redisVol:/data
volumes:
  redisVol:
    external:
      name: 'redisVol-{{.Task.Slot}}'
```

```console
$ docker stack deploy -c c.yml redis
Creating network redis_default
Creating service redis_redis
$ docker volume ls | grep redis
local               redisVol-1
```

I didn't realize external volumes would be created automatically, but I guess that makes sense.

Scaling works too:

```console
$ docker service scale redis_redis=3
redis_redis scaled to 3
$ docker volume ls | grep redis     
local               redisVol-1
local               redisVol-2
local               redisVol-3
```

:tada:

**Comment by hairyhenderson** [comment]
I was about to close this, but then I realized that this causes a problem if I want to deploy the stack multiple times with different stack names (because the volume is `external`).

I suppose for this to work as expected it'd have to be possible to set the name of the volume separately from the key:

```yaml
volumes:
  redisVol:
    name: redisVol-{{.Task.Slot}}
    driver: local
```

I'd then expect a volume to be created named `<stack name>_redisVol-1`

(obviously, this doesn't work)

**Comment by hairyhenderson** [comment]
Ok, did a little more playing around and this seems to work (though TBH feels a little far from ideal):

```yaml
version: '3.1'
services:
  redis:
    image: redis
    volumes:
      - redisVol:/data
volumes:
  redisVol:
    external:
      name: '{{index .Service.Labels "com.docker.stack.namespace"}}_redisVol-{{.Task.Slot}}'
```

```console
$ docker stack deploy -c docker-compose.yml redis
Creating network redis_default
Creating service redis_redis
$ docker volume ls | grep redis
local               redis_redisVol-1
$ docker exec $(docker inspect $(docker service ps redis_redis -q) -f "{{.Status.ContainerStatus.ContainerID}}") touch /data/hello_world
$ docker run -v redis_redisVol-1:/tmp alpine ls -alh /tmp/hello_world
-rw-r--r--    1 root     root           0 Feb  7 01:37 /tmp/hello_world
```

This is at least _workable_ for now.

**Comment by mvdstam** [comment]
@hairyhenderson I cannot find any documentation regarding this feature. Can you clarify how you came across this?

**Comment by hairyhenderson** [comment]
@mvdstam @ddebroy told me about it in the [Docker Community Slack](https://community.docker.com/registrations/groups/4316) instance

It's documented here: https://docs.docker.com/engine/reference/commandline/service_create/#/create-services-using-templates

It was introduced in 1.13.0, listed in the release notes under the `Swarm Mode` section:
- Add support for templating service options (hostname, mounts, and environment variables) #28025

😁

**Comment by MarkusMattinen** [comment]
This works with the default "local" driver, but defining both "external" and "driver" options for a volume definition is not supported in Compose v3.2.

So with a driver defined the name cannot be overridden and as a result templating cannot be used in the volume name. Without "external.name" the key in the volumes dictionary is used as the name and the dictionary has restrictions on what characters the keys can contain.

@dnephin, any ideas? Is overriding the name intended to be supported for volume definitions with a driver, or is this something that is only going to be implemented in Compose v4 in "mounts" under the service definition?

**Comment by MarkusMattinen** [comment]
Example that does NOT work, because `external` and `driver` cannot be used together in volume definitions:

```
version: '3.2'
volumes:
  consul_data:
    driver: "rexray/ebs"
    external:
      name: "consul_data_{{ .Task.Slot }}"
services:
  consul:
    volumes:
      - type: volume
        source: "consul_data"
        target: "/consul/data"
    image: "consul:0.8.0"
```

**Comment by thaJeztah** [comment]
When using `external`, the volume is expected to be created up-front ("external"). Having `.Task.Slot` in the template for an external volume won't work, because that information is not available for a global "volume" definition, but only for a "task" that _uses_ the volume.

**Comment by stealthybox** [comment]
just an additional data point -- this does not work with bind mounts either:
```yaml
version: '3.2'
services:
  hello:
    image: alpine
    command: sh -c 'ls -l /hello && sleep 10'
    volumes:
    - source: '{{ .Task.Slot }}'
      target: /hello
      type: bind
```

```
jhf8dkd6ltkm4a6pgi0sua72w   mounts_hello.1       alpine:latest@sha256:b09306f2dfa3c9b626006b2f1ceeeaa6fcbfac6037d18e9d0f1d407260cb0880   moby                Ready      
Rejected 1 second ago    
"invalid bind mount source, must be an absolute path: C:\Users\leigh\repos\test_mounts\{{ .Task.Slot }}"
```

**Comment by xask00** [comment]
This is really needed for scalable stateful docker 'services'
Each task in a service should be able to specify its own persistent volume.

Since this is already supported by the docker service command line using templates for volumes, there should be some way to specify it via the docker compose YML file as well.(when deployed using docker stack deploy)

From the 'docker for azure' docs -
https://docs.docker.com/docker-for-azure/persistent-data-volumes/#use-a-unique-volume-per-task

```
docker service create \
  --replicas 5 \
  --name ping2 \
  --mount type=volume,volume-driver=cloudstor:aws,source={{.Service.Name}}-{{.Task.Slot}}-vol,destination=/mydata \
  alpine ping docker.com
```
There is currently no way to achieve this via docker stack deploy using the compose YML file.
As pointed out in the discussion it is possible to use 'local' volume and bind mounts but not custom volume drivers like rexray/ebd or cloudstor:aws etc.
Looks like a bug to me.

**Comment by dnephin** [comment]
Thanks. I created https://github.com/docker/cli/issues/274 to add support for a custom name for non-external volumes.

**Comment by gartz** [comment]
This is super helpful information, it should be in the docker-compose reference docs.

**Comment by thaJeztah** [comment]
@gartz agreed, that some of this could be included in the documentation; could you open an issue in the documentation issue tracker (and link to this issue)? https://github.com/docker/docker.github.io/issues

**Comment by chrisbecke** [comment]
Docker 20.10 finally gave us hostnames that resolve.

So deployments like this, that used to require 4 services, are now almost possible :-

```yaml
services:
  minio:
    image: "minio/minio"
    hostname: "minio{{.Task.Slot}}"
    command: "server http://minio{1...4}/data"
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    volumes:
    - "disk{{.Task.Slot}}:/data"
    deploy:
      replicas: 4
volumes:
  disk1:
  disk2:
  disk3:
  disk4:
```

**Comment by MarkusMattinen** [comment]
@chrisbecke Great! When you say almost possible, what is still missing?
I haven't tried this in a while, but you should be able to combine the volume definitions into one (disk1..disk4 to just disk) if you put the `{{.Task.Slot}}` into the volume name there. `command` should also support it.

**Comment by chrisbecke** [comment]
Unless there is a neater way of doing this:

```
volumes:
  data:
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}_disk{{.Task.Slot}}'
```

is a bit janky. But it does actually work. And the more I roll it around my head the more I prefer it - being able to use a single volume declaration is much more in line with how a stack compose file should work.

**Comment by chrisbecke** [comment]
Principally the problem remaining with trying to do deployments like the above, seems to be with trying to ensure that when deploying a clustered service, the same instance lands on the same node reliably. One might want to try do something like this for etcd:

```yaml
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.labels.etcd{{.Task.Slot}}==true
```

ensuring that docker nodes are labeled "etcd1=true", "etcd2=true", "etcd3=true" etc.

Personally I feel it would be more elegant to label the nodes:

```bash
docker node update node_x --label-add "etcd=etcd1"
docker node update node_y --label-add "etcd=etcd2"
docker node update node_z --label-add "etcd=etcd3"
```

and then use something like this

```yaml
      hostname: {{index .Service.Labels node.labels.etcd}}
      deploy: 
        placement:
          constraints:
          - node.labels.etcd       
```

The problem in the first case is that placement constraints don't honor go template parameters. In the 2nd, there is no apparent way to test for the existence of a label other than to check its value for an exact equality (or inequality) with a non empty string.
