### ISSUE TITLE
Muti-host networking with overlay (docker compose on swarm failing)

### ISSUE THREAD

**Issue by jonathan-kosgei** [moby/moby#30868]
**Description**

I'm using compose to launch a number of apps on a two-node swarm node on AWS. I have a flask container scheduled on one node and a redis container scheduled on the other node. However the flask app fails with a connection error while trying to connect to the redis instance.

**Steps to reproduce the issue:**
My compose file:

```
version: '3'
volumes:
  poc:

networks:
 default:
    driver: overlay
    ipam:
      config:
        - subnet: 100.64.0.0/16
services:
  redis:
    image: 172.31.25.208:5000/redis
    logging:
        driver: journald
    volumes:
      - poc:/redis
  flask:
    image: 172.31.25.208:5000/flask
    depends_on:
      - redis
      - stunnel
      - pgbouncer
    logging:
        driver: journald
    deploy:
      placement:
        constraints:
          - node.hostname == ip-172-31-25-208
```

**Describe the results you received:**
```
ConnectionError: Error 110 connecting to redis:6379. Connection timed out.
[pid: 12|app: 0|req: 1/1] 127.0.0.1 () {34 vars in 390 bytes} [Thu Feb  9 10:36:04 2017] GET / => generated 291 bytes in 254573 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```
**Describe the results you expected:**

Tranparency, the flask app should connect to the redis app as though they were all on the same node.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Fri Jan 27 21:54:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Fri Jan 27 21:54:54 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 35
 Running: 19
 Paused: 0
 Stopped: 16
Images: 191
Server Version: 1.13.1-rc1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: cbtslk7duprzq29i530f4i8y5
 Is Manager: true
 ClusterID: 0i22jyym0uiwvzkf3ehud7kub
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.25.208
 Manager Addresses:
  172.31.25.208:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-172-31-25-208
ID: 5TRV:4MMS:OASJ:YC7Q:Y6K4:CO5M:PKMS:MQR3:PH6A:Y2U3:PBSJ:2OGW
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 172.31.25.208:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Setup on AWS
