### ISSUE TITLE
Docker Volume Plugin - infinit- VOLUME NAME

### ISSUE THREAD

**Issue by RotemEmergi** [moby/moby#30937]
Hi ,

I have 3 ubuntu server (16.10) with docker 1.13 and docker-compose 1.8 .
I run swarm on top of the server .
I'm using docker-compose version '3'.
File format `version: '3'
```
networks:
  test:
    external: true
volumes:
  test-user/test-volume:
    driver: infinit     
services:
  webapps:
    image: xxxxxxxxxxx
    networks:
        - test
    ports:
        - "80:8080"
        - "443:8443"
    volumes:
        - test-user/test-volume:/var/lib/jetty/webapps
        - test-user/test-volume:/var/lib/jetty/etc
        - test-user/test-volume:/var/lib/jetty/agents
```
When I run `sudo docker stack deploy -c docker-compose-stack.yml test`
I get the error 
test-user/test-volume Additional property test-user/test-volume is not allowed.

Also tried to run `docker run -it --rm --volume-driver infinit -v test/test-volume:/path/to/mount alpine ash`

I get the same error .

Best Regards

**Comment by cpuguy83** [comment]
1. I think volumes need to be quoted (the whole string)
2. Looks like you have an extra `:` in there for the 2nd and 3rd volumes.
3. The volume name is likely to cause trouble, I'd suggest just giving a name with no path.

**Comment by RotemEmergi** [comment]
Hi , 
I copy by mistake with double ':'.
The volume name is from the infinit creation i didn't select it  . 
[https://infinit.sh/get-started/linux](url)
And for the quoted you can put them or no .. it's not bother.

**Comment by thaJeztah** [comment]
I think that part of the Infinit documentation needs an update, because slashes are invalid in volume names.

```bash
$ docker volume create --name test/test-volume
Error response from daemon: create test/test-volume: "test/test-volume" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
```

ping @mycure

**Comment by cadeuh** [comment]
Hi @RotemEmergi,

Can you tell me what version of Infinit you're using? Just to be sure.

I just tried to reproduce your `docker run` on a fresh Ubuntu install and it works with the same Docker and Compose versions. 

- Do you get the same exact error message (`test-user/test-volume Additional property test-user/test-volume is not allowed`) when doing the `docker run` command?
- Is the Infinit daemon running?

**Comment by RotemEmergi** [comment]
Hi @cadeuh !

I am using this guide [https://infinit.sh/get-started/linux](url) fir install infinit .
And yes and yes .

**Comment by cadeuh** [comment]
In your compose file, can you try updating the `volumes` section like this (with the Infinit daemon still running):

```
volumes:
  ghost-volume:
    external:
      name: test-user/test-volume
```

**Comment by RotemEmergi** [comment]
but the volume name is like this example : 

> $> docker run -it --rm --volume-driver infinit -v alice/my-volume:/path/to/mount alpine ash

I tried to create a new volume : 

> sudo docker create -d infinit --name rotem

I get : 
> Error response from daemon: create test: Post http://%2Frun%2Fdocker%2Fplugins%2Finfinit.sock/VolumeDriver.Create: dial unix /run/docker/plugins/infinit.sock: connect: co
nnection refused

**Comment by cadeuh** [comment]
Yeah the Infinit volume name needs an "/" but it should work if you name it and declare it external (because the volume needs to be created outside Compose. Like this:

```
networks:
  test:
    external: true
volumes:
  test-volume:
    external:
      name: test-user/test-volume   
services:
  webapps:
    image: xxxxxxxxxxx
    networks:
        - test
    ports:
        - "80:8080"
        - "443:8443"
    volumes:
        - test-volume:/var/lib/jetty/webapps
        - test-volume:/var/lib/jetty/etc
        - test-volume:/var/lib/jetty/agents
```

Also, with the Infinit daemon running, you should see your Infinit volume when doing:
```
# docker volume ls
DRIVER              VOLUME NAME
infinit             <your_user>/<your_volume>
```

**Comment by thaJeztah** [comment]
w.r.t.;

> I think that part of the Infinit documentation needs an update, because slashes are invalid in volume names.

Turns out I was confused there; that restriction only applies to the _local_ driver; plugins have more freedom w.r.t. naming of volumes (see https://github.com/docker/docker/pull/17213). Which _does_ look a bit confusing though; wondering if we should change that (but that's orthogonal to this issue)

**Comment by RotemEmergi** [comment]
Hi,

This is not work .. 

> reactor.test.http] [request 0x2776be0] HttpServer(port=0): handle request from 0x2776be0: /VolumeDriver.Mount {
} POST
[reactor.test.http] [request 0x2776200] HttpServer(port=0): handle request from 0x2776200: /VolumeDriver.Mount {
} POST
/opt/infinit/bin/infinit-volume: fatal error: user "sec" does not exist
[ infinit-daemon  ] [request 0x2776be0]   infinit-volume for "test-infi-rotem/test-volume" not running
[reactor.test.http] [request 0x2776be0] HttpServer(port=0): internal error: unable to mount test-infi-rotem/se
cupi-volume
/opt/infinit/bin/infinit-volume: fatal error: user "sec" does not exist
[ infinit-daemon  ] [request 0x2776200]   infinit-volume for "test-infi-rotem/test-volume" not running
[reactor.test.http] [request 0x2776200] HttpServer(port=0): internal error: unable to mount test-infi-rotem/se
cupi-volume
[reactor.test.http] [request 0x2776be0] HttpServer(port=0): handle request from 0x2776be0: /VolumeDriver.Get {} 
POST
[reactor.test.http] [request 0x2776be0] HttpServer(port=0): handle request from 0x2776be0: /VolumeDriver.Get {} 
POST
[reactor.test.http] [request 0x2776200] HttpServer(port=0): handle request from 0x2776200: /VolumeDriver.Mount {
} POST
[reactor.test.http] [request 0x277e090] HttpServer(port=0): handle request from 0x277e090: /VolumeDriver.Mount {
} POST
/opt/infinit/bin/infinit-volume: fatal error: user "sec" does not exist
[ infinit-daemon  ] [request 0x2776200]   infinit-volume for "test-infi-rotem/test-volume" not running
[reactor.test.http] [request 0x2783310] HttpServer(port=0): handle request from 0x2783310: /VolumeDriver.Get {} 
POST
[reactor.test.http] [request 0x2776200] HttpServer(port=0): internal error: unable to mount test-infi-rotem/se
cupi-volume
/opt/infinit/bin/infinit-volume: fatal error: user "sec" does not exist
[ infinit-daemon  ] [request 0x277e090]   infinit-volume for "test-infi-rotem/test-volume" not running


from the commend I get : 

>  "VolumeDriver.Mount: unable to…"

**Comment by diddledan** [comment]
regarding the slash in volume name, and @thaJeztah's comment above about the restriction only applying to local volume names, this is not shown by my experience:

docker log:
```
Feb 26 12:56:29 valhala dockerd[1911]: time="2017-02-26T12:56:29.283104016Z" level=error msg="fatal task error" error="create diddledan/caddy-conf: \"diddledan/caddy-conf\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intented to pass a host directory, use absolute path" module="node/agent/taskmanager" task.id=pg14smucv4os1ghd9cc9uqv3v
```

docker-compose:

```
version: "3"
services:
    caddy-gen:
        image: alexanderjulo/caddy-gen:latest
        environment:
            - 'LETSENCRYPT_EMAIL=daniel@bowlhat.net'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - caddy-config:/etc/caddy
    caddy:
        image: alexanderjulo/caddy
        command: caddy -restart=inproc -http2=false
        ports:
            - 80
            - 443
        networks:
            - web
        volumes:
            - caddy-config:/srv
            - sslcerts:/root/.caddy/letsencrypt
networks:
    web:
        driver: overlay
volumes:
    caddy-config:
        external:
            name: diddledan/caddy-conf
    sslcerts:
        external:
            name: diddledan/caddy-ssl
```
