### ISSUE TITLE
Docker stack improvements

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#30977]
Hi,

Some improvements about docker stack :
~~1. docker stack ls => the result is not sorted~~ #31085
~~2. docker stack rm is limited to only one stack label~~ #32110
3. docker stack start/stop add the possibility to stop a stack without remove it
4. The env variable is not available with external network :
I create an overlay network : 
```
docker network create --driver overlay nginx_network
```
i create a file docker-compose.yml

```
version: '3'
networks:
     ${NETWORKNAME}:
       external: true
services:
  nginx:
    image: nginx:latest
    networks:
    - ${NETWORKNAME}
```

I try to run it
```
NETWORKNAME=nginx_network docker stack deploy NGINX_STACK -c docker-compose.yml
```
I get

> Creating network NGINX_STACK_nginx_network
> invalid network: nginx_network

If i change the env variable with envsubst : 
```
export NETWORKNAME=nginx_network
cat docker-compose.yml | envsubst > docker-compose-new.yml
docker stack deploy MYSTACK -c docker-compose-new.yml
```
i get : 

> Creating service MYSTACK_nginx

**Comment by dnephin** [comment]
1 and 2 seem reasonable

> 3. docker stack start/stop add the possibility to stop a stack without remove it

There is no "disabled" state for services, networks or volumes, so this doesn't really make sense for stacks. What's the use case? Why not just remove it and re-create it when you need it?

(4) is by design. You can't use variables in keys. If you want to change the name of something use the stack name. Or if you want an external network name, use this:

```yaml
networks:
  something:
    external:
      name:  ${NETWORKNAME}

services:
  nginx:
    image: nginx:latest
    networks:
    - something
```

@sylvainmouquet  please use triple backticks (```) for code formatting, instead of single backticks:
