### ISSUE TITLE
Docker 1.13 overwrite/remove named volume when stack deploy/update 

### ISSUE THREAD

**Issue by BastienAr** [moby/moby#31095]
Currently there is no option when updating a stack (`docker stack deploy`) to overwrite a named volume created by this stack. In a same way, there is no option (such -v) to remove named volume associated with a stack when you remove the stack, other than removing the volumes with `docker volume rm`.

Here is a usecase :

Given this file:
```yaml
version: '3'

services:
  config:
    image: test/config-hoster:1.3
    volumes:
      - volume_config:/datas
    deploy:
      mode: global
      restart_policy:
        condition: none
  nginx:
    image: nginx
    volumes:
      - volume_config:/datas:ro
    depends_on:
      - config


volumes:
  volume_config:
```

where *config-hoster* is a from scratch image, exposing a volume with the config files in it, and *nginx* a service used just for testing the correct mapping.

When I first deploy this stack, everything is fine, the volume is created **and** filled with the config files of the *config* service. But if I change the version (tag) of the config service, when I update the stack the volume is not deleted, so datas inside are obviously not overwrited. Same behavior if I rm and redeploy the stack.

Since this is a named volume, not directly bounded to an host directory, and not created externaly, I see no problem to erase or overwrite this volume when the stack is removed or updated.
