### ISSUE TITLE
deploying spark cluster through docker stack in dock swarm mode fails

### ISSUE THREAD

**Issue by infsaulo** [moby/moby#31202]
I'm trying to deploy my apache spark cluster using the `docker-compose` file as defined [here][1] across machines working in docker swarm mode. 

I'm invoking `docker stack deploy -c compose-file.yml spark_cluster` at my docker swarm manager machine to deploy my services as defined but I'm getting the following scenario when I hit `docker stack ps spark_cluster`:

    ID            NAME                        IMAGE                           NODE           DESIRED STATE  CURRENT STATE               ERROR                             PORTS
    iy255fvx5ub8  spark_cluster_master.1      sauloricci/docker-spark:latest  manager-swarm  Running        Running 20 seconds ago
    mrr6p9dmodh5   \_ spark_cluster_master.1  sauloricci/docker-spark:latest  worker2-swarm  Shutdown       Rejected 35 seconds ago     "invalid mount config for type�"
    u1daipeekanv   \_ spark_cluster_master.1  sauloricci/docker-spark:latest  worker2-swarm  Shutdown       Rejected 40 seconds ago     "invalid mount config for type�"
    9yup3zxpk4ur   \_ spark_cluster_master.1  sauloricci/docker-spark:latest  worker2-swarm  Shutdown       Rejected 45 seconds ago     "invalid mount config for type�"
    is4dib7wmb61   \_ spark_cluster_master.1  sauloricci/docker-spark:latest  worker1-swarm  Shutdown       Rejected 50 seconds ago     "invalid mount config for type�"
    y80py4s4hny8  spark_cluster_worker.1      sauloricci/docker-spark:latest  manager-swarm  Running        Running about a minute ago

It seems the swarm just accepted the services running at my swarm manager node and rejected at my worker swarm nodes.

How could I manage to find the logs associated with this scenario? Where could I check the logs related with this deployment if that's the case? I'd like to know what exactly means the message in the error column. 

  [1]: https://github.com/infsaulo/docker-spark/blob/master/docker-compose.yml

**Comment by AkihiroSuda** [comment]
```yaml
        volumes:
            - ./conf/master:/conf
            - ./data:/tmp/data
```

I guess failure is because bind-mounts are composed of relative paths.
Absolute path or volumes should work

**Comment by catinthesky** [comment]
@infsaulo, this might related to storage driver you are using, I checked at centos, when using "devicemapper" as its storage driver, the problem occurred, but using "ovf", such as using " dockerd --storage-driver vfs" to start docker daemon, it can work.

Please share much more information concerning docker information (command: docker info), and more error (command: journalctl -u docker [if using systemd start the docker daemon]).

**Comment by thaJeztah** [comment]
> How could I manage to find the logs associated with this scenario?

The _daemon_ logs can be found on the node itself, but you can see the un-truncated error message for the services that fail to start using the `--no-trunc` option on `docker stack ps` / `docker service ps`. You should also be able to get the full error message by inspecting the service (`docker service inspect`).

> I guess failure is because bind-mounts are composed of relative paths. Absolute path or volumes should work

@AkihiroSuda in `docker-compose` files, paths are specified relative to the `docker-compose` file. Docker/Docker Compose will expand the path to an absolute path before deploying.

_However_ there are some things to take into account when using bind-mounted host directories;

Bind mounting host-directories is always done on the host that the _daemon_ (`dockerd`) runs on, **not** from the local host that you deploy from. If those directories / files do not exist on the host that the service is deployed on, service creation will fail.

In general, bind-mounting host directories is therefore discouraged when using services, as they are "non-portable" (i.e., you need to prepare each host, and create the directories or files before you're able to deploy a service).

Looking at the `docker-compose` file;

- the "master" and "worker" share a single data directory. Instead of using a bind-mounted host-directory, you can use a named volume for this. Take into account, that the default ("local") volume driver is not a multi-host driver. In other words; each host will get an "independent" volume, and docker does not automatically sync data inside those volumes between nodes. Various volume drivers exist though, and nfs can also be an option for some use cases.
- the stack has a configuration file for "master" and "worker". Instead of using bind-mounts, you can use the "secrets" feature to pass those configuration files to the services.


For example, to pass the configuration to the services (just a quick 'mock up', nothing really functional);

```yaml
version: "3.1"
services:
  worker:
    image: nginx:alpine
    deploy:
      replicas: 1
    secrets:
      # Configuration can be found at /run/secrets/worker_config
      # inside the container
      - worker_config
  master:
    image: nginx:alpine
    deploy:
      replicas: 1
    secrets:
      # Configuration can be found at /run/secrets/spark-defaults.conf
      # inside the container
      - source: master_config
        target: spark-defaults.conf
        mode: 0440

secrets:
  worker_config:
    file: ./conf/worker/spark-defaults.conf
  master_config:
    file: ./conf/master/spark-defaults.conf
```
