### ISSUE TITLE
When I run two node.js environment in a same container or two seperated containers,it stucked.

### ISSUE THREAD

**Issue by tanhuiya** [moby/moby#31322]
I used docker-compose ,compose.yml is below:
```
version: '2'
services:
  node_his:
    build: ./node
    working_dir: /home/node/Orange-HIS/frontend
    ports:
      - "8010:8010"
    volumes:
      - ../Front/Orange-HIS:/home/node/Orange-HIS
    command: npm run dev

  node_oa:
    build: ./node_latest
    ports:
      - "8000:8000"
    working_dir: /home/node/OA-HIS
    volumes:
      - ../Front/OA-HIS:/home/node/OA-HIS
    command: npm run dev
```

When I run it ,It  stucked.
If I run one node application first and it works well ,then run other It will effects the first application too.
what's wrong ?

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- since this is using `docker-compose`, provide the output of `docker-compose version`
- the example you provided above uses custom images, and bind-mounted directories from the host. We don't have access to that source, or images, so we are not able to reproduce your situation
- "It stucked" is very broad; what _exactly_ did you see? Do the daemon logs show anything usefull?

Without more information we won't be able to look into this, or confirm if this is a bug or something related to your setup / configuration. It's also possible this is a bug in docker-compose, not docker, but without more information that's hard to tell.

I'll close this issue because we need more information, but can reopen once you provided.

**Comment by tanhuiya** [comment]
```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: XGO2:ZZRV:DVUM:3DEM:BFQL:UKCJ:G2Q6:DV5H:GCSV:VAUW:4HJU:6MEQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 33
 System Time: 2017-02-24T12:55:09.178987939Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://7eba5309.m.daocloud.io
Live Restore Enabled: false


$ docker-compose version
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```


And this is my Dockerfile 
```
FROM node:latest
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
CMD npm run dev
```

If i run the first application with composefile like below (service node_oa  was commented).it runs well.

```
version: '2'
services:
  node_his:
    build: ./node
    working_dir: /home/node/Orange-HIS/frontend
    ports:
      - "8010:8010"
    volumes:
      - ../Front/Orange-HIS:/home/node/Orange-HIS
    command: npm run dev

#  node_oa:
#    build: ./node_latest
#    ports:
#      - "8000:8000"
#    working_dir: /home/node/OA-HIS
#    volumes:
#      - ../Front/OA-HIS:/home/node/OA-HIS
#    command: npm run dev
#

  nginx:
    build: ./nginx
    ports:
      - "8001:80" # oa 项目
      - "8002:81" # his 项目
    links:
      - phpfpm
    restart: always
    volumes_from:
      - phpfpm
    volumes:
      - ./nginx/logs:/var/www/html/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d

  phpfpm:
    build: ./php
    ports:
      - "9000:9000"
    restart: always
    links:
      - mysql
    volumes:
      - ../yg-oa-api:/var/www/html/yg-oa-api
      - ../yg-bclient-api:/var/www/html/yg-bclient-api
      - ./phpMyAdmin:/var/www/html/yg-oa-api/webroot/phpMyAdmin

  mysql:
    image: mysql:5.6
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
```

Then I write another composefile  run  `node_oa` , It  stucked , and the application before can't runs well . the same result  I use command (ignore the directory)
```
docker run -d -i -p 8000:8000 -w /home/node/yg-oa -v /Users/tanhui/dockers/yg/yg-oa:/home/node/yg-oa node:latest  npm run dev
```

Then I attach to the container , Run it mannually , It stucked at 'listening  at localhost:8080' ,then Killed, I donn't know Why.
![1j 7ef3 i d2 _5dnugy](https://cloud.githubusercontent.com/assets/10923091/23304609/98364d94-fad5-11e6-9e63-5d82e1378874.jpg)


@thaJeztah
