### ISSUE TITLE
Compose file parsing can't read json data

### ISSUE THREAD

**Issue by alambike** [moby/moby#31605]
**Description**
I was trying to launch in docke-for-azure swarm cluster a bunch of services with a previously working docker-compose file, that has json data in some points, for example to override **ports** config in an worker container:

```yaml
version: "3"
networks:
  backend:
  frontend:
services:
  promotor: &1
    command: /root/start.sh
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_TYPE: UTF-8
    image: my_private_registry/prefapp/promotor
    networks:
    - backend
    ports:
    - 3000:80
    working_dir: /home/prefapp/promotor
  promotor_sidekiq:
    <<: *1
    command: bundle exec sidekiq -r ./promotor_worker.rb -L log/sidekiq.log -P tmp/sidekiq.pid
    ports: []
```

**Describe the results you received:**
Running docker stack deploy -c my_dockercompose.yml fails to recognize '[]' json empty list specification
```
docker stack deploy -c docker-compose-test.yml my-test-stack
services.promotor_sidekiq.ports must be a list
```
If I can't overide ports in worker container, the service fails to start because external port is in use

**Describe the results you expected:**
In docker-compose the support for json in yaml works as expected

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:34:06 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 12
 Running: 7
 Paused: 0
 Stopped: 5
Images: 10
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: oksjof3mcd7j2ukx1teztw1kf
 Is Manager: true
 ClusterID: athqfp2s6po5dontmlf4yuqsg
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.6
 Manager Addresses:
  10.0.0.6:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.11-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.354 GiB
Name: swarm-manager000000
ID: WXYH:JIBR:P4DP:P55I:Z3SC:SXNH:GVAR:FZEE:WXID:TKW3:GPXH:XCKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 85
 Goroutines: 193
 System Time: 2017-03-07T12:48:20.543372613Z
 EventsListeners: 1
Username: alambike
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I was using Docker-for-Azure

**Comment by cpuguy83** [comment]
Curious, why do you need to provide an empty list?

**Comment by alambike** [comment]
Hi @cpuguy83 , I need to provide an empty list in **promotor_sidekiq**, to override the promotor service **ports** definition.
If I can't overide ports in **sidekiq** container, the service fails to start because external port is in use by **promotor** service.

**Comment by cpuguy83** [comment]
Ah makes sense.
ping @vdemeester

**Comment by dnephin** [comment]
> If I can't overide ports in worker container, the service fails to start because external port is in use

I'm not sure what you mean by this. This is not the error message you have pasted.

Can you try running `docker-compose config` on this file and pasting the output here?

**Comment by alambike** [comment]
Hi @dnephin , the quote phrase is a response to @cpuguy83 to explain why I'm need to provide an empty port list to the promotor_sidekiq service.   
The error is about launching ```docker stack``` with this docker-compose file.

Anyway this is the ```docker-compose config``` output
```yaml

$ docker-compose config 
networks:
  backend: {}
  frontend: {}
services:
  promotor:
    command: /root/start.sh
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_TYPE: UTF-8
    image: my_private_registry/prefapp/promotor
    networks:
      backend: null
    ports:
    - 3000:80
    working_dir: /home/prefapp/promotor
  promotor_sidekiq:
    command: bundle exec sidekiq -r ./promotor_worker.rb -L log/sidekiq.log -P tmp/sidekiq.pid
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_TYPE: UTF-8
    image: my_private_registry/prefapp/promotor
    networks:
      backend: null
    ports: []
    working_dir: /home/prefapp/promotor
version: '3.0'
volumes: {}
```
