### ISSUE TITLE
IP address is unstable in the swarm mode overlay network 

### ISSUE THREAD

**Issue by yuyi** [moby/moby#31798]
**Description**
The IP address of a container is randomly changed in the overlay network. It will cause many problems in cluster.

**Steps to reproduce the issue:**
1. Deploy the stack.yml
```
version: "3"

services:
  cassandra:
    image: dockly/docker-cassandra
    environment:
      - CASSANDRA_SERVICE_NAME=cassandra
    volumes:
      - /data/cassandra:/var/lib/cassandra
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.app.cassandra == true
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
```
2. Wait for a day
3. The container's IP will be changed again and again.

**Describe the results you received:**

```
# nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.0.1.3   4.73 GiB   256          50.7%             d03d68af-6a97-4464-8a39-895d1325ce36  rack1
UN  10.0.1.22  4.84 GiB   256          51.4%             0dbf73fb-e94e-45eb-83b1-d00a471e9ec1  rack1
UN  10.0.1.7   4.28 GiB   256          48.7%             27a423fa-d812-4318-840e-54d6366f5913  rack1
UN  10.0.1.8   4.29 GiB   256          48.8%             78b2114a-84a0-45a1-928e-3656ba1f2544  rack1
UN  10.0.1.25  4.91 GiB   256          49.7%             c2d715e6-7dc9-40b6-9ebe-d8b677668583  rack1
UN  10.0.1.26  4.97 GiB   256          50.8%             c9f7f9d1-daaf-4b4d-bfe5-c0613274742e  rack1
```

```
# dig +short tasks.cassandra
10.0.1.9
10.0.1.26
10.0.1.25
10.0.1.22
10.0.1.7
10.0.1.8
10.0.1.3
10.0.1.12
```

**Describe the results you expected:**
Stable container's IP or user-assigned static IP.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 13
 Running: 8
 Paused: 0
 Stopped: 5
Images: 72
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: js0nmzo37j8dkgnzbl4ei46k9
 Is Manager: true
 ClusterID: 6jqfeovu5ggdwjvmz3773lsm3
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.100.0.11
 Manager Addresses:
  10.100.0.11:2377
  10.100.0.12:2377
  10.100.0.13:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: T-01
ID: 7454:3PJX:NZKM:AYA6:BIKO:U4UA:OID2:5GLG:HXXC:B4A4:GYT7:DSBI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mosh
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vultr VPS
