### ISSUE TITLE
Packages don't appear to be installed.  Multiple images created unexpectedly.

### ISSUE THREAD

**Issue by dyerrington** [moby/moby#31978]
**Description**
It was suggested that I attempt to cross post here.  My original thread about this problem can be found here: 
 
https://github.com/docker/compose/issues/4612

Basically, what is happening is that when I `docker-compose build`, a bunch of "none" containers are loaded up, however, without any of the packages that I specified from my DockerFile.  When I try to run the same docker-compose yml and DockerFile on a Windows machine and an Ubuntu machine on AWS, packages seem to work fine and my startup scripts seem to load as expected.  On my OSX machine, when I attempt to build and run my images / containers, my startup file can't file the package `gunicorn`.

Here is my `docker-compose.yml`:

```
version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: blablablablabla
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: maxlabs

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    command: /bin/bash /code/start_maxlabs.sh
    ports:
      # - "85:80"
      - "8001:8000"
      - "8002:8005"
    expose:
      - "8000"
    links:
      - db:mysql
    volumes:
      - .:/code
      - /usr/src/app
      - /usr/src/app/static
      - /usr/share/nginx/html
```

My `DockerFile`:

```
FROM python:2.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD environment.yml /code/
ADD requirements.txt /code/
ADD start_maxlabs.sh /code/
RUN chmod +x /code/start_maxlabs.sh
RUN apt-get update && \
    apt-get install -y python-pip python-dev build-essential \
                       libmysqlclient-dev \
                       gunicorn \
                       libcairo2-dev \
                       libjpeg62-turbo-dev \
                       libpango1.0-dev \
                       libgif-dev \
                       build-essential \
                       g++ \
                       python-imaging
RUN pip install -U pip \
                   mysql-python \
                   gunicorn
RUN pip install -r requirements.txt
ADD . /code/
ADD maxlabs /code/
ADD webapp /code/
```

After "web" comes online, it can't find "gunicorn".  I've logged into the various containers that this creates (why so many?), and all of the additional packages I've specified (including gunicorn), don't appear on the images that are less than 2GB in size, but of course show up just fine on the 2GB images.

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
webapp              temp                f1f9947510b4        3 days ago          182 MB
<none>              <none>              32ceaf408d67        3 days ago          2.3 GB
web_web             latest              d22d7cc3d6a9        4 days ago          182 MB
<none>              <none>              d2de20e4ae8f        4 days ago          2.3 GB
<none>              <none>              8acf304d1da3        4 days ago          182 MB
<none>              <none>              22b3ec7f248f        4 days ago          2.3 GB
python              2.7                 ca388cdb5ac1        2 weeks ago         676 MB
nginx               latest              6b914bbcb89e        3 weeks ago         182 MB
mysql               latest              22be5748ecbe        3 weeks ago         406 MB
```

**Steps to reproduce the issue:**
1. docker-compose build
2. docker-compose up

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 40
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: 6F7B:QENP:CEE4:T6GN:2O3Y:IUD2:L4K4:BGBN:ECZN:YACU:XUCJ:GBCR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-03-21T18:08:17.054722215Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: dyerrington
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
