### ISSUE TITLE
ndots:0

### ISSUE THREAD

**Issue by ylavoie** [moby/moby#32093]
Docker imposes ndots:0 in current resolv.conf
This conflicts with search option and prevent containers from finding nodes in an intranet using short names.
Removing the ndots:0 option fixes that, so there should be a way to override it. Providing a different ndots value currently results in:
```
cat /etc/resolv.conf
search mynetwork.net
nameserver 127.0.0.11
options ndots:15 ndots:0
```

**Comment by cpuguy83** [comment]
This is what I see on 17.03:
```
docker run -it --rm --dns-option ndots:15 busybox cat /etc/resolv.conf
nameserver 192.168.65.1
options ndots:15
```

**Comment by mavenugo** [comment]
@cpuguy83 the nameserver is `127.0.0.11` and that means @ylavoie is using a custom network (not docker0).

@ylavoie yes. that is the intended behavior. @sanimej can add more details to it.

**Comment by ylavoie** [comment]
I agree that resolving in the docker domain is a must. Whether it must happens first or last is still to debate, all dns offers the possibility.

I indeed use a private network, I wanted to integrate that docker project into my local network. It is a Selenium test grid, running Linux Alpine containers, and served on a small Ubuntu server, to minimize the memory requirements. I am using Docker 17.03.0-ce, build 60ccb22, docker-compose version is 1.11.2, build dfed245. The grid containers are based on alpine:edge.

Docker itself is started with systemd: `ExecStart=/usr/bin/docker daemon --dns=192.168.30.253 --dns-opt=ndots:15 -H fd://`

Here are the relevant parts of my docker-compose.yml:
```
version: '2.1'

services:

  hub:
    image: ylavoie/hub
    container_name: hub
    privileged: true
    mem_limit: 200m
    memswap_limit: 400m
    ports:
      - 4422:4444
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub

  firefox:
    image: ylavoie/node-firefox
    container_name: firefox
    privileged: true
    mem_limit: 500m
    memswap_limit: 1g
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

networks:
  default:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 192.168.34.0/24
```

The commands to restart the application are, to make sure that the network is created anew each time:
```
docker-compose kill
docker-compose rm -f
docker network rm selenium_default
docker-compose up -d
```

And, although it has been failing for the last week, it now works without obvious changes, except a restart of the docker daemon to include the -D switch, as you required. I have removed it now, still working.

I am lost and may have to put that on hold until I can make it fail again.
