### ISSUE TITLE
WIndows 10 Localhost Issue with Docker-Compose

### ISSUE THREAD

**Issue by seivad** [moby/moby#32404]
Hey after getting everything working in OSX, I switched to my bootcamp partition and installed docker and the same project from OSX. I've googled this to death now and still can't get the site to load in a browser. PHP works, MySQL works, just the port forwarding does not!

I don't seem to have a Docker Machine IP when running this...
```
docker-compose up -d
```

I get this:

```
docker-machine ip
Error: No machine name(s) specified and no "default" machine exists
```

So then I try the following after checking docker ps -a:
```
docker inspect docker_web_1
```

and can see the IP Address of 172.18.0.5 which I try in the browser as-is and with :8080 and nothing works. It was 10x easier to get this going on Mac so far than Windows. Please help. Docker-compose.yml file below:

```
version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  cache:
    image: redis:3.0
    ports:
      - "63791:6379"
  database:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  dbdata:
```

**Comment by friism** [comment]
This issue is most likely related to either Docker Toolbox or Docker for Windows. Could you please re-open the issue with details on the repo for the software you used to setup Docker?

**Comment by jasonterando** [comment]
What happens if you browse to 127.0.0.1:8080?

**Comment by seivad** [comment]
@jasonterando I get the same 502 Bad Gateway issue from Nginx. This works perfectly on OSX though and from what I've read on Windows you need to go directly to the IP Address but that doesn't work. And I can't find any info online about using docker-compose, everything I read is docker run but I bought up using ```docker-compose up -d``` so there is no ```docker-machine ip``` unfortunately.

I used the Stable version of Docker for Windows directly from Docker website. 

What have others used to access websites on Windows 10 Pro using Docker for Window?

**Comment by jasonterando** [comment]
I am using the httpd (Apache) not Nginx (sorry) and I'm running Apache containers in most recent Docker for Windows - using a bridge (not host) network.  In doing so, I browser to 127.0.0.1 on the host machine and I get to Apache.  

In my docker-compose.yaml file, I defined my own bridge network like so:

networks:
  local:
    driver: bridge

And then in service definition, I add:

    networks:
      - local

**Comment by seivad** [comment]
@jasonterando can you post your full docker-compose.yml file please?

**Comment by jasonterando** [comment]
Here is the "gist" of it...

```
version: '3'

services:
  client:
    build: 
       context: .
       dockerfile: ./build/Dockerfile.client
    environment:
      APP_SITE_ENV: local
    networks:
      - local
    ports:
      - "443:443"
    volumes:
      - c:/projects/myproject/source/client:/usr/local/apache2/htdocs/
      - c:/projects/myproject/config/client:/usr/local/apache2/htdocs/app/config
  server:
    build: 
       context: .
       dockerfile: ./build/Dockerfile.server
    environment:
      APPLICATION_ENV: local
      XDEBUG_CONFIG: remote_host=10.254.254.254
    networks:
      - local
    ports:
      - "8443:8443"
    volumes:
      - c:/projects/myproject/prism/source/server:/var/www/prism-server/
      - c:/projects/myproject/prism/config/server/config/autoload/local:/var/www/server/config/autoload/local
      - c:/data:/data
  websocket:
    build: 
       context: ./
       dockerfile: ./build/Dockerfile.websocket
    environment:
      APPLICATION_ENV: local
    networks:
      - local
    ports:
      - "9001:9001"
    volumes:
      - c:/projects/myproject/prism/source/websocket:/var/www/websocket/
      - c:/projects/myproject/prism/config/websocket/config/autoload/local:/var/www/websocket/config/autoload/local
      - c:/data:/data  

networks:
  local:
    driver: bridge
```

**Comment by friism** [comment]
@seivad When using Docker for Windows, exposed ports for running containers are available on `localhost`: https://docs.docker.com/docker-for-windows/#explore-the-application-and-run-examples

**Comment by dprothero** [comment]
Indeed, they *should* be, but don't seem to be when used with `docker-compose`. I'm having the same issue, http://localhost:8000/ does not load anything for me. Here's my `docker-compose.yml`:

```
version: '3'

services:
  db:
    image: postgres:9.6
    restart: always

  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
```
