### ISSUE TITLE
Incorrect behavior on docker stack update

### ISSUE THREAD

**Issue by santiagopoli** [moby/moby#32522]
Hi,

I'm experiencing some weird behaviors when using docker stack update with a compose file. Every time I scale a service (up or down) instead of adding / removing containers, docker swarm takes down all the containers for that service and creates new ones.

So for example if I have a service named 'api' scaled to 2 and I change my docker-compose.yml to scale it to 3, Docker swarm removes all the 'api' services and then creates 3.

I think this has to do with https://github.com/docker/docker/issues/30844, but that issue was closed.

Another issue that comes to my mind is https://github.com/docker/docker/issues/29676, since I'm working with private images.

Im using Docker version 17.03.1-ce, build c6d412e

P.S: Using docker service scale directly works as expected

**Comment by thaJeztah** [comment]
What does your docker-compose.yml look like? Can you provide an minimal example? (mainly interested if you're using environment variables, labels, etc)

**Comment by santiagopoli** [comment]
version: '3'

services:

  ## INFRASTRUCTURE/MONITORING SERVICES

  dashboard:
    image: bargenson/docker-swarm-visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager


  ## APPLICATION SERVICES

  api:
    image: docker.etermax.net/voxsy/voxsy-api:staging
    ports:
      - '8087:8080'
    networks:
      - proxy
      - dynamo
    environment:
      - ENV_NAME=staging
      - REPOSITORY=dynamo
      - DYNAMO_HOST=dynamo:8000
      - AWS_ACCESS_KEY_ID=dummy 
      - AWS_SECRET_ACCESS_KEY=dummy
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager

  voxtool:
    image: docker.etermax.net/voxsy/voxtool:staging
    ports:
      - '3000:3000'
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role != manager
          
  dynamo:
    image: fitz/dynamodb-local
    ports:
      - '8000:8000'
    networks:
      - dynamo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    command: -inMemory


networks:
  proxy:
    driver: overlay
  dynamo:
    driver: overlay

**Comment by santiagopoli** [comment]
```
version: '3'

services:

  ## INFRASTRUCTURE/MONITORING SERVICES

  dashboard:
    image: bargenson/docker-swarm-visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager


  ## APPLICATION SERVICES

  api:
    image: docker.etermax.net/voxsy/voxsy-api:staging
    ports:
      - '8087:8080'
    networks:
      - proxy
      - dynamo
    environment:
      - ENV_NAME=staging
      - REPOSITORY=dynamo
      - DYNAMO_HOST=dynamo:8000
      - AWS_ACCESS_KEY_ID=dummy 
      - AWS_SECRET_ACCESS_KEY=dummy
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager

  voxtool:
    image: docker.etermax.net/voxsy/voxtool:staging
    ports:
      - '3000:3000'
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role != manager
          
  dynamo:
    image: fitz/dynamodb-local
    ports:
      - '8000:8000'
    networks:
      - dynamo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    command: -inMemory


networks:
  proxy:
    driver: overlay
  dynamo:
    driver: overlay

```
