### ISSUE TITLE
Containers are not starting, giving error 'starting container failed address already in use'

### ISSUE THREAD

**Issue by gouravgupta92** [moby/moby#32548]
Hi,

I am using `Docker version 17.03.0-ce, build 60ccb22`.
I am deploying simple node based application, with mongo using the below docker-compose file

```
version: "3"
services:
  mongo:
    image: registry.evfapp.dev/alpine-mongo
    networks:
      - refapp
    ports:
      - "27017"

  web:
    entrypoint: sh tools/startup.sh
    image: registry.evfapp.dev/testapp:latest
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
    environment:
      VIRTUAL_HOST: "https://testapp.evfapp.dev,testapp.evfapp.dev"
      SERVICE_PORTS: "3000"
      FORCE_SSL: "yes"
    networks:
      - refapp
      - router_network
    healthcheck:
      test: "curl http://0.0.0.0:3000/login"
      interval: 1m30s
      timeout: 3s
      retries: 5

networks:
  refapp:
  router_network:
    external: true
```
I am deploying app using commad `docker stack deploy -c docker-compose.yml refapp`.

It is working sometimes but sometimes it's giving error `starting container failed address already in use` while starting up the service.

below is the response of 'docker service ps refapp_mongo' command.

```
ID                         NAME                           IMAGE                                                                                                            NODE                           DESIRED STATE  CURRENT STATE                   ERROR                                                PORTS
nnmji59yrgr3liq37tg31dirq  refapp_mongo.1      registry.evfapp.dev/alpine-mongo:latest@sha256:9ef3849fc30591b353373464710052c2e632f84294202d6981476924f0ce3279  EVBLESESAPL293  Running        Running less than a second ago
r04166ol875f9gflp46uk367j   \_ refapp_mongo.1  registry.evfapp.dev/alpine-mongo:latest@sha256:9ef3849fc30591b353373464710052c2e632f84294202d6981476924f0ce3279  EVBLFUTIAPL292  Shutdown       Failed 11 minutes ago           "starting container failed: Address already in use"
o92gnzcr9zh7fcswhaf0nt9cb   \_ refapp_mongo.1  registry.evfapp.dev/alpine-mongo:latest@sha256:9ef3849fc30591b353373464710052c2e632f84294202d6981476924f0ce3279  EVBLFUTIAPL292  Shutdown       Failed 11 minutes ago           "starting container failed: Address already in use"
gy2bawbmrjgf8krow68f7ijnv   \_ refapp_mongo.1  registry.evfapp.dev/alpine-mongo:latest@sha256:9ef3849fc30591b353373464710052c2e632f84294202d6981476924f0ce3279  EVBLFUTIAPL292  Shutdown       Failed 11 minutes ago           "starting container failed: Address already in use"
l9hzwlt5fya53qitx0jzytggj   \_ refapp_mongo.1  registry.evfapp.dev/alpine-mongo:latest@sha256:9ef3849fc30591b353373464710052c2e632f84294202d6981476924f0ce3279  EVBLFUTIAPL292  Shutdown       Failed 12 minutes ago           "starting container failed: Address already in use"
```

'docker network inspect refapp_refapp' is giving the following output : 
```
[
    {
        "Name": "refapp_refapp",
        "Id": "6wtegyv9z5z6owkojqh7e3ay0",
        "Created": "2017-04-12T19:20:42.707564338+05:30",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.2.0/24",
                    "Gateway": "10.0.2.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "93a6b4641705650f3a1a5972cb03a96060ce00aebf408b7fa285fd550c8d7815": {
                "Name": "refapp_mongo.1.nnmji59yrgr3liq37tg31dirq",
                "EndpointID": "4444304f8ccee32b1966e0456f1077dac209546113a6d27059a0a7ed8074d4fa",
                "MacAddress": "02:42:0a:00:02:05",
                "IPv4Address": "10.0.2.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4099"
        },
        "Labels": {
            "com.docker.stack.namespace": "refapp"
        },
        "Peers": [
            {
                "Name": "EVBLESESAPL293-87074368cab6",
                "IP": "10.73.96.215"
            }
        ]
    }
]

```

<b>Please tell how to resolve error 'starting container failed address already in use'.</b>
