### ISSUE TITLE
Containers not removed after docker stack rm

### ISSUE THREAD

**Issue by gouravgupta92** [moby/moby#32620]
Hi,

I am using `Docker version 17.03.0-ce, build 60ccb22`.
I had deployed one service using `docker stack deploy -c stack_file.yml STACK_NAME`.

To remove stack i am using `docker stack rm STACK_NAME`.
After running this command i am not able to see stack name in `docker stack ls` and services of stack is also not present in `docker service ls`.
but some containers related to stack services are still present, now if i am trying to remove the container using `docker rm` its again restarting those containers due to resiliency.

How to stop those dangling containers.

**Comment by vdemeester** [comment]
/cc @aaronlehmann @dnephin 

@gouravgupta92 could you provide more information about your setup ? (like `docker info`, `docker node ls`, the compose file if possible, etc..)

**Comment by gouravgupta92** [comment]
these are the setup configurations : 

output of ```docker info```
```
Containers: 430
 Running: 49
 Paused: 0
 Stopped: 381
Images: 125
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: vgpool-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 94.88 GB
 Data Space Total: 123.7 GB
 Data Space Available: 28.81 GB
 Metadata Space Used: 34.6 MB
 Metadata Space Total: 218.1 MB
 Metadata Space Available: 183.5 MB
 Thin Pool Minimum Free Space: 12.37 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 56
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: sqcyhkxht42axyia3kgyihk20
 Is Manager: true
 ClusterID: pdd77r1ffau5m0dcyciit54rh
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.73.96.121
 Manager Addresses:
  10.73.53.144:4000
  10.73.96.121:4000
  10.73.96.215:4000
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: BLFUTIAPL279.ad.test.com
ID: 6LS2:RTLU:2VGN:KOPX:KHWC:QM54:4GT3:BNH4:Q4KL:3ZPP:FGJT:JJIH
Docker Root Dir: /datadisk/paas/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://paas2:123++++@10.68.248.34:80
Https Proxy: http://paas2:123++++@10.68.248.34:80
No Proxy: .testapp.dev,.testapp.qa,.testapp.aqua,10.73.97.3,10.73.97.4,10.73.97.5,ad.test.com,10.73.96.121,,10.73.96.214,,10.73.96.215
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


output for ```docker node ls```
```
ID                           HOSTNAME                       STATUS  AVAILABILITY  MANAGER STATUS
4lhviefqpqttasxy2c3zltkti    BLFUTIAPL859.ad.test.com  Down    Active        Unreachable
qourzshjrinf895nsdmiv47u9    BLESESAPL293.ad.test.com  Down    Active        Leader
sqcyhkxht42axyia3kgyihk20 *  BLFUTIAPL279.ad.test.com  Ready   Active        Reachable



compose file : 

```
version: "3"
services:
  mongo:
    image: registry.evfapp.dev/alpine-mongo
    networks:
      - refapp
    ports:
      - "27017"

  web:
    entrypoint: sh tools/startup.sh
    image: registry.evfapp.dev/testapp:latest
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
    environment:
      VIRTUAL_HOST: "https://testapp.evfapp.dev,testapp.evfapp.dev"
      SERVICE_PORTS: "3000"
      FORCE_SSL: "yes"
    networks:
      - refapp
      - router_network
    healthcheck:
      test: "curl http://0.0.0.0:3000/login"
      interval: 1m30s
      timeout: 3s
      retries: 5

networks:
  refapp:
  router_network:
    external: true
```
