### ISSUE TITLE
Docker Plugin `rexray/ebs` duplicates volumes when used in Docker Stack Volumes Declaration

### ISSUE THREAD

**Issue by marcellodesales** [moby/moby#32931]
# Bug Reports

When used in `docker stack`, the plugin `rexray/ebs` creates multiple volumes with the same name instead of re-using the same stacks. (Or is there a switch for that?)

## Version

Installed as Docker Plugin

```shell
docker plugin ls
ID                  NAME                DESCRIPTION              ENABLED
377f763d1293        rexray/ebs:latest   REX-Ray for Amazon EBS   true
```

```shell
[ec2-user@ip-xxx-yyy-184-139 ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: jrbxrq636fohf84dtdvwsbcy8
 Is Manager: true
 ClusterID: 7d1q6eg0ngqsaltt7emd61bdg
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.102.184.139
 Manager Addresses:
  xxx-yyy.184.139:2377
  xxx-yyy.186.180:2377
  xxx-yyy.186.25:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.518GiB
Name: ip-10-102-184-139.vpc.internal
ID: QTWH:M25F:SC2E:NWQX:KFY7:XHJU:Z3YH:JDXF:QB4S:FS5Q:4GFP:A7DL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

## Expected Behavior
Since the initial volumes were created with `docker stack create -c registry.yml`, and given that the volumes in question were declared in the `registry.yml` file (Compose V3), I would expect that if there's such a volume with the given name, the RexRay orchestration would reuse the existing ones instead of creation new ones.

## Actual Behavior
New Volumes are created with the same name as before.

<img width="1260" alt="screen shot 2017-04-28 at 10 40 57 pm" src="https://cloud.githubusercontent.com/assets/131457/25553302/b5a7d4e0-2c64-11e7-9fcf-bd267d61f57f.png">

* The `available` volumes were previously created in the first run of `docker stack create`, while the ones `in-use` are the ones with the second `docker stack create`.

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. Install

```
docker plugin install --grant-all-permissions rexray/ebs EBS_ACCESSKEY=A********A EBS_SECRETKEY=4G******LL EBS_REGION=****
latest: Pulling from rexray/ebs
bbf138eca3af: Verifying Checksum
bbf138eca3af: Download complete
Digest: sha256:4af99fcfa0cb1a2b0a28f562ce70a1979321ff607370fd9cb37a5caf130652ee
Status: Downloaded newer image for rexray/ebs:latest
Installed plugin rexray/ebs
```
2. Create the stack file `registry.yml` (See below)

3. `docker stack deploy -c registry.yml registry`

4. `docker stack rm  registry`    <<<<----- Good! Did NOT delete the volumes

5. `docker stack deploy -c registry.yml registry`   <<<------ Creates New instead 

## Configuration Files

```yml
version: '3'

services:

  registry:
    image: registry:2
    ports:
      - "80:80"
    volumes:
      - configs:/conf/stack
      - configs:/datastorage
    deploy:
      replicas: 1
      labels: [APP=REGISTRY]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "registry"
    labels:
      net.company.docker.hub.type: "Database"
      net.company.docker.hub.info: "Docker Registry MySQL Server"
    deploy:
      replicas: 1
      labels: [APP=MYSQL]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

volumes:
  configs:
    driver: rexray/ebs

  mysql-data:
    driver: rexray/ebs
```

Questions
------

* Is this the designed intention? What if I need to re-stack my entire cluster? Refreshes?
* Is there anything to do in the plugin to avoid this problem?

**Comment by marcellodesales** [comment]
Referring to https://docs.docker.com/compose/compose-file/#external, I'm now attempting to use the following volumes leads to just one volume being mounted/mapped.

1. Changed the volume `external: true` and commented out `driver`
2. Started the stack

Existing Volumes
-----

```shell
[ec2-user@ip-10-102-184-139 ~]$ docker volume ls
DRIVER              VOLUME NAME
rexray/ebs:latest   registry_configs
rexray/ebs:latest   registry_mysql-data

[ec2-user@ip-xxx.yyy-184-139 ~]$ docker volume inspect registry_configs
[
    {
        "Driver": "rexray/ebs:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/86452e75daf7ecc6e95f29616510a1fb9812701524ef955148bfce65982d826c/rootfs",
        "Name": "registry_configs",
        "Options": {},
        "Scope": "global",
        "Status": {
            "availabilityZone": "us-west-2a",
            "fields": null,
            "iops": 0,
            "name": "registry_configs",
            "server": "ebs",
            "service": "ebs",
            "size": 16,
            "type": "standard"
        }
    }
]
```
Changed the stack file
----

```yml
  web:
    image: registry:2
    ports:
      - "80:80"
    volumes:
      - registry_configs:/conf/stack
      - registry_configs:/datastorage
    depends_on:
      - "mysql"
...
...
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - registry_mysql-data:/var/lib/mysql
    environment:
...
...
volumes:
  registry_configs:
    #driver: rexray/ebs
    external: true
  registry_mysql-data:
    #driver: rexray/ebs
    external: true
```

Only One volume mounted
-----

Not sure why, but only one volume was loaded.

```shell
[ec2-user@ip-xxx.yyy-184-139 ~]$ docker service inspect registry_web
[
    {
        "ID": "gjqrr0k4cxy5v989tprv7pzal",
        "Version": {
            "Index": 260
        },
        "CreatedAt": "2017-04-29T14:21:32.875060037Z",
        "UpdatedAt": "2017-04-29T14:21:32.878843515Z",
        "Spec": {
            "Name": "registry_web",
            "Labels": {
                "APP": "REGISTRY",
                "com.docker.stack.namespace": "registry"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "registry:2@sha256:c49e8a41f360f3e3942bc6f149b7111a1a9bcaa939eb2feaae8c19c97f601e57",
                    "Labels": {
                        "com.docker.stack.namespace": "registry"
                    },
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "registry_configs",
                            "Target": "/conf/stack",
                            "VolumeOptions": {}
                        },
                        {
                            "Type": "volume",
                            "Source": "registry_configs",
                            "Target": "/datastorage",
                            "VolumeOptions": {}
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {},
```

Question
-----

Am I missing anything?
