### ISSUE TITLE
Provide a way to config default overlay network

### ISSUE THREAD

**Issue by xianlubird** [moby/moby#32962]
When I use `docker stack deploy` command, every stack will have a default overlay network. But its config is immutable. I can't change config of the default network. Should we provide a way to config this default overlay network?

**Proposal**
We provide a keyword in compose yaml file.
```
version: "3"
services:
    nginx:
        image: nginx
        ports:
          - 80
        deploy:
          mode: replicated
          replicas: 3
networks:
  nginx_default:
	config:xxxxx
```
If we find user has defined the `nginx_default` networks, we should create this network as user's mind.
