### ISSUE TITLE
Support network_mode in docker stack deploy

### ISSUE THREAD

**Issue by D3nn** [moby/moby#33055]
I'd like to request that the "network_mode" from the docker-compose file be supported. I know that there's already been some discussion around this from those who'd like to use it for network_mode:host capabilities, but personally I'm more interested in the `network_mode:"service:<svc name>`".

I'd also like to see this supported in the docker service create command or at least have the `--network` option be able to include the same semantics as the network_mode does in the compose file.

The use cases I see for this are:

* launching containers that share the same network stack so that applications can communicate with each other over a loopback interface.  This would allow lower-latency communications between the containers and also obviate service discovery requirements for such containers.
* launching a container which contains a network toolset so that I can do some network diagnostics on processes that run in containers derived from "scratch" (such as containers running go programs).

The first use case would definitely benefit from reviving container affinity constraints from the old swarm, but that could be worked around for now using the supported placement constraints from v3 compose format (or by making the network_mode:service<svcname> itself be a deployment constraint).

**Comment by cirocosta** [comment]
As of https://github.com/moby/moby/issues/25873#issuecomment-319109840 I'd say that this can be closed 🤔  

With 

```
version: '3.3'
services:
  nginx:
    image: 'nginx:alpine'
    networks:
      - 'outside'

networks:
  outside:
    external:
      name: 'host'
```

you can get `            "NetworkMode": "host", ` 👍  

---

```
Client:
 Version:      17.07.0-ce-rc2
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:42:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce-rc2
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:48:34 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by D3nn** [comment]
I don't think so for this issue.  I was looking more for the equivalent of "network_mode:service <service id/name>".  Unless it would be possible to have the following network config:

```
networks:
  outside:
    external:
      name: 'service: <svc name/id>'
```

**Comment by cirocosta** [comment]
Oh, sorry, I misunderstood. That makes sense 👍

**Comment by djmaze** [comment]
I'd like to add the `network_mode: none` is also missing (and there is no equivalent in swarm mode afaik). This is e.g. useful for services which operate on volumes only.

**Comment by wlan0** [comment]
+1 

ping - any working on this issue - In addition to support for 

```
networks:
  outside:
    external:
      name: 'service: <svc name/id>'
```

I'd also like to request support for
```
networks:
  outside:
    external:
      name: 'container: <name>'
```
so that multiple containers can share the same net namespace. Similar to `network_mode: container:name`
