### ISSUE TITLE
Ping could not reach a container on overlay network when service updated

### ISSUE THREAD

**Issue by alu** [moby/moby#33076]
**Description**
Ping could not reach a container on overlay network when service updated. 

**Steps to reproduce the issue:**
1. Create swarm cluster
2. Create overlay network to swarm scope
3. Deploy a service (as stack)
4. Update the service
5. ping to the service container

I tried above steps with this sample.

```sh
# Create swarm cluster
docker-machine create node-01
docker-machine create node-02

MANAGER_IP=$(docker-machine ip node-01)

eval $(docker-machine env node-01)
docker swarm init --advertise-addr ${MANAGER_IP}
JOIN_TOKEN=$(docker swarm join-token -q worker)

eval $(docker-machine env node-02)
docker swarm join --token ${JOIN_TOKEN} ${MANAGER_IP}:2377

# Create overlay network to swarm scope
eval $(docker-machine env node-01)
docker network create --driver overlay shared

# Deploy a service (as stack)
docker stack deploy app --compose-file ./app.yml 

# Update the service
docker service update app_test --force --detach=false

# ping to the service container
docker stack deploy watcher --compose-file ./watcher.yml 
```

```yml
# app.yml
version: '3.2'
services:
  test:
    image: busybox
    command: /bin/sh -c 'while true; do sleep 60s; done'
    networks:
      shared:
    deploy:
      replicas: 2

networks:
  shared:
    external: true
```

```yml
# watcher.yml
version: '3.2'
services:
  test:
    image: busybox
    command: /bin/sh -c 'while true; do ping -c 1 -w 1 $$(nslookup tasks.app_test | sed -e "1,4d" | cut -d " " -f 3 | head -n 1); sleep 1s; done'
    networks:
      shared:
    deploy:
      replicas: 1

networks:
  shared:
    external: true
```

and then, update `app_test` while follow `watcher_test` logs.

```sh
docker service update app_test --force
docker service logs -f watcher_test
```

Then `100% packet loss` output from `watcher_test`  when app_test service updated.

```
watcher_test.1.s4uncdk44td9@node-01    | --- 10.0.0.7 ping statistics ---
watcher_test.1.s4uncdk44td9@node-01    | 1 packets transmitted, 0 packets received, 100% packet loss
watcher_test.1.s4uncdk44td9@node-01    | PING 10.0.0.7 (10.0.0.7): 56 data bytes
```

**Describe the results you received:**
ping command result is 100% packet loss.

**Describe the results you expected:**
ping command result is 0% packet loss.

**Additional information you deem important (e.g. issue happens only occasionally):**
I guess the problem will happen when `watcher_test` and `app_test` deployed to same node.
So if `watcher_test` in node-01, ping to `app_test` in node-02 is not problem, but ping to `app_test` node-01 will happen the problem.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 3w1osxs6az3fub7qp8to5vu72
 Is Manager: true
 ClusterID: msvvzjjxr0qpgz76f50hf87bb
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.104
 Manager Addresses:
  192.168.99.104:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.66-boot2docker
Operating System: Boot2Docker 17.05.0-ce (TCL 7.2); HEAD : 5ed2840 - Fri May  5 21:04:09 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: node-01
ID: FL37:LRC5:KK54:FTIF:N4U4:LOJ7:BVQ7:RQRP:LT4K:SUYD:MB5I:WAAX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 102
 Goroutines: 247
 System Time: 2017-05-08T04:47:32.054364346Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker-machine
