### ISSUE TITLE
Docker stack deploy - swarm mode - replicated containers hostnames are not predictable

### ISSUE THREAD

**Issue by wavenator** [moby/moby#33078]
I'm using a `docker-compose.yml` version 3 file.
When doing a `stack deploy` with this attached yaml, and actually with any other docker-componse.yml I've used, the created containers hostnames can not be predictable.

docker-compose.yml
```
version: "3"
services:
    node:
        image: ubuntu
        deploy:
            replicas: 3
            restart_policy:
                condition: any
        logging:
            driver: json-file
            options:
                max-size: 10m
        networks:
            - nodes
        command: >
            bash
        stdin_open: true
        tty: true

networks:
    nodes:
        external: false
```

```
$  docker stack deploy -c docker-compose.yml nodes
Creating network nodes_nodes
Creating service nodes_node
```

```
$  docker ps -a
CONTAINER ID        IMAGE                                                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
56cf59404a6c        ubuntu@sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028   "bash"                   14 minutes ago      Up 14 minutes                           nodes_node.3.llfbbt1jndnsaouygwwic7ad7
bf6b45094b62        ubuntu@sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028   "bash"                   14 minutes ago      Up 14 minutes                           nodes_node.1.pd81fyj7rhd2gfzomowznq9n5
67e4606b55e5        ubuntu@sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028   "bash"                   14 minutes ago      Up 14 minutes                           nodes_node.2.icxpmbycra2jnrmvk7aeu1z1y
```

```
$  docker attach 56cf59404a6c
root@56cf59404a6c:/# 
root@56cf59404a6c:/# ping node
PING node (10.0.0.2) 56(84) bytes of data.
64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=0.065 ms
^C
--- node ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.065/0.065/0.065/0.000 ms
root@56cf59404a6c:/# ping node-1
ping: unknown host node-1
root@56cf59404a6c:/# ping node-2
ping: unknown host node-2
root@56cf59404a6c:/# ping node-3
ping: unknown host node-3
root@56cf59404a6c:/# ping node.3
ping: unknown host node.3
```

As opposed to what's written here: https://docs.docker.com/docker-cloud/apps/service-links/#discovering-containers-on-the-same-service-or-stack

> container can always discover other containers on the same stack using just the container name as hostname. This includes containers of the same service. Similarly, a container can always discover other services on the same stack using the service name.

> For example, a container webapp-1 in the service webapp can connect to the container db-1 in the service db by using db-1 as the hostname. It can also connect to a peer container, webapp-2, by using webapp-2 as the hostname.

> A container proxy-1 on the same stack could discover all webapp containers by using the service name webapp as hostname. Connecting to the service name resolves as an A round-robin record, listing all IPs of all containers on the service webapp.

As you can see, resolving `node` which is the service name, succeeded and resolved 10.0.0.2.
Trying to resolve the replicated containers has failed.

```
$  docker --version
Docker version 17.03.1-ce, build c6d412e
```
