### ISSUE TITLE
99% performance loss when using encrypted overlay network in swarm mode

### ISSUE THREAD

**Issue by mortensteenrasmussen** [moby/moby#33133]
**Description**
When running in swarm mode with an encrypted network, the bandwidth between containers on different nodes is around 1% of the performance compared to a non-encrypted network. The encryption is supposed to take around 10% of the performance, but not 99%.

On an encrypted (overlay) network:
`bw = 262 KB/sec`

On a non-encrypted (overlay) network:
`bw = 113 MB/sec`

An additional oddity is that the slow measurements only happen when the containers talk directly to other containers (e.g., using the container IP). If I expose ports and use the hosts IP, I get the full speed (like on an unencrypted network). I assume this is because that traffic exits the overlay network on the host of the requesting container, and then runs host->host, and therefore isn't using the overlay network.

**Steps to reproduce the issue:**
1. Create a swarm with two nodes
node1: `docker swarm create --advertise-addr 192.168.62.144`
node2: `docker swarm join --token <token> 192.168.62.144:2377`
2. Create a network (encrypted)
Node1: `docker network create --driver overlay --opt encrypted nettest`
3. Save the following YAML file as qperf.yml on node1

```
version: '3.1'

networks:
  nettest:
    external: true

services:
  qperf-server:
    image: arjanschaaf/centos-qperf
    command: [-lp,"4000"]
    networks:
      - nettest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.role == manager

  qperf-client:
    image: arjanschaaf/centos-qperf
    command: [qperf-server,-v,-lp,"4000",-ip,"4001",tcp_bw,tcp_lat]
    networks:
      - nettest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.role == worker
```

4. Stack deploy the YAML file to run qperf server and client (server on manager, client on worker)
node1: `docker stack deploy -c qperf.yml qperf`
5. Check docker logs on the client after a few seconds
node2: `docker ps -qa --filter "label=com.docker.swarm.service.name=qperf_qperf-client" | xargs docker logs`
NOTE: The logs command only works if you deploy through docker stack deploy and give the stack the name "qperf"
6. Remove the stack and network and repeat steps 2-5 without an encrypted network.
node1: `docker stack rm qperf`
node1: `docker network rm nettest`
Goto step 2 (for the network creation, remove `--opt encrypted`.

**Describe the results you received:**
On an encrypted (overlay) network:
`bw = 262 KB/sec`

On a non-encrypted (overlay) network:
`bw = 113 MB/sec`

**Describe the results you expected:**
I expected no more than ~10% loss of performance. This result points to something severely wrong.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
sysadm@144-host1:~$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
sysadm@144-host1:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: noifpa7jyesgumvox3t1z50s5
 Is Manager: true
 ClusterID: wt45sg3pt4fymjrb98efav1b6
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.62.144
 Manager Addresses:
  192.168.62.144:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-36-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.945 GiB
Name: 144-host1
ID: HPWQ:WE5B:GD3V:KJRQ:VSD3:EJUS:56CS:VL2G:2FRT:7BX6:DIFS:YTG2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 docker-repo:5000
 docker-repo.local:5000
 127.0.0.0/8
Registry Mirrors:
 http://docker-hub-mirror.local:5000/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I tried this on physical machines as well as on Xenserver VMs with the same result.

Running a fairly new Ubuntu 16.04.2:
```
sysadm@144-host1:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

sysadm@144-host1:~$ uname -a
Linux 144-host1 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I can replicate this issue 100% of the time, and have tested with two Docker versions and two Ubuntu versions, as well as on physical machines and XenServer VMs. 

If you need any additional information, please let me know!

Thanks in advance.
