### ISSUE TITLE
Start multiple services exposing the same port on different nodes

### ISSUE THREAD

**Issue by galindro** [moby/moby#33160]
**Description**

I wan't to know why isn't possible to start two services that exposes the same tcp port (80 for example) on **different nodes**, I mean, using different constraints that guarantee that each service tasks of each service will run on different worker nodes.

**Steps to reproduce the issue:**
1. Create two docker-compose.yml files:

- docker-compose-moon.yml

```yaml
version: "3.2"
networks:
  ext:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16

services:
  proxy:
    image: nginx
    deploy:
      placement:
        constraints:
          - engine.labels.MOON == true
    networks:
      - ext
    ports:
      - "80:80"
```

- docker-compose-sun.yml

``` yaml
version: "3.2"
networks:
  ext:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.200.0.0/16

services:
  proxy:
    image: nginx
    deploy:
      placement:
        constraints:
          - engine.labels.SUN == true
    networks:
      - ext
    ports:
      - "80:80"
```

2. Create two stacks based on the above yaml files:

```bash 
docker stack deploy -c docker-compose-sun.yml sun
docker stack deploy -c docker-compose-sun.yml mon
```

**Describe the results you received:**
```bash
docker stack deploy -c docker-compose-sun.yml sun
Creating service sun_proxy
docker stack deploy -c docker-compose-moon.yml moon
Creating network moon_ext
Creating service moon_proxy
Error response from daemon: rpc error: code = 3 desc = port '80' is already in use by service 'sun_proxy' (fna548be0fn2csj1g54irsfbe)
```

**Describe the results you expected:**
Creation of the two services withou any tcp port conflict as soon each of services tasks will run on different nodes

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 5
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ua111soaexg1mepfit0i6jl52
 Is Manager: true
 ClusterID: z7sbuvbnbncbqmh4i3f2pxl39
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.3.101
 Manager Addresses:
  10.0.1.103:2377
  10.0.2.102:2377
  10.0.3.101:2377
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.6MiB
Name: swarm-manager-001
ID: PT4G:CMUG:DDRH:M45E:OTTE:ESJD:TGPA:SJHA:6GN4:TZ66:HSDM:LCCR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=sa-east-1
 availability_zone=sa-east-1c
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Amazon AWS EC2

**Comment by thaJeztah** [comment]
That's expected; when deploying swarm services, a port that is published by a service is accessible through _any_ node in the swarm, and is routed through the ingress network / routing mesh to the node where an actual container runs that's backing the service (see the "routing mesh" section in the documentation; https://docs.docker.com/engine/swarm/ingress/)

If you want to publish a service only on the node that a task runs, you can use `mode=host` publishing, which will only expose the port on the actual host that the container ("task") runs.

There is an outstanding issue that doesn't allow you to do so when using multiple services publishing the same port, but this is being worked on, and likely to be part of Docker 17.06

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Comment by mingliu** [comment]
@thaJeztah with mode=host publishing, it is still not allowed to publish same service port with different services on different nodes by node label constraints. I tested this with Docker 17.03.
Is this expected and will this be allowed in 17.06 or future versions? Sorry not convenient to deploy  17.06 yet.
Thanks

**Comment by mingliu** [comment]
Found the issue https://github.com/moby/moby/issues/31249
Strange I tried to create service on a 17.06 manager node, but still got this error:
> Error response from daemon: rpc error: code = 3 desc = port '23222' is already in use by service ...

docker@c782mkx:/data01/docker-run> docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by thaJeztah** [comment]
@mingliu I'm not able to reproduce that; here's running on Docker 17.06 (all workers are 17.06 as well)

```bash
$ docker service create --name one --constraint=node.hostname==swarm-test-02 --publish mode=host,target=80,published=9000 nginx:alpine
$ docker service create --name two --constraint=node.hostname==swarm-test-03 --publish mode=host,target=80,published=9000 nginx:alpine

$ docker service ps one two

ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
zhtss955g05d        two.1               nginx:alpine        swarm-test-03       Running             Running 4 seconds ago                        *:9000->80/tcp
si3ynisy5gij        one.1               nginx:alpine        swarm-test-02       Running             Running 12 seconds ago                       *:9000->80/tcp

```

**Comment by mingliu** [comment]
@thaJeztah thanks for your time.
It probably is because I use a cluster with two nodes using 17.06, and two nodes still using old version. I tried to create services from one manager node which is 17.06
I will try this again after I have a complete good cluster with all nodes having new version.

**Comment by thaJeztah** [comment]
Thanks! Let me know how it went :+1:

**Comment by swaroopkundeti** [comment]
I could produce this issue

```v# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false```

```
# docker login -u abcs -p xyz https://abc.com && docker stack deploy -c abc-dev.yml abc  --with-registry-auth
Login Succeeded
Creating service service-fibro_fibro-test-server-dev
Creating service service-fibro_fibro-service-dev
root@lspidbsdco01:~/app-stacks-dev#
root@lspidbsdco01:~/app-stacks-dev# docker service ls
ID                  NAME                               MODE                REPLICAS            IMAGE            PORTS
sojb6p68vxz5        abc_test-server-dev                replicated          1/1                 abc:v1.0.1       *:8888->8080/tcp
tan28a8y8yj4        abc_test2-service-dev              replicated          1/1                 abc:v1.0.1       *:80->8080/tcp
root@lspidbsdco01:~/app-stacks-dev#
Login Succeeded
Creating service abc_test-server-staging
Creating service abc_test-server-staging
Error response from daemon: rpc error: code = 3 desc = port '8888' is already in use by service 'abc_test-server-dev' (sojb6p68vxz5tmhs2b1al9xe6) as an ingress port```

**Comment by swaroopkundeti** [comment]
This is fixed.

After upgrading docker to 17.06, we need to restart docker on the hosts. 

Also I was using docker-compose version 3 and changed it to version 3.2 which started creating stacks.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by albertorm95** [comment]
I'm having this issue, I have two .yml files for a stack:

101-app.yml
```yml
version: "3.4"
services:
  econfig-app-service-dallas:
    build:
      context: .
      dockerfile: service.Dockerfile
    image: ${IP}:5000/ecfg/econfig-app:${BUILD_NUMBER}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == server101.com
    ports:
      - "443:443"
    working_dir: "/app"
    command: "node app.js"
```
301-app.yml
```yml
version: "3.4"
services:
  econfig-app-service-sydney:
    build:
      context: .
      dockerfile: service.Dockerfile
    image: ${IP}:5000/ecfg/econfig-app:${BUILD_NUMBER}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == server301.com
    ports:
      - "443:443"
    working_dir: "/app"
    command: "node app.js"
```

Both nodes server101.com and server301.com are managers on the swarm.

```
[admin@server101 stack]$ sudo docker stack deploy -c 101-app.yml --with-registry-auth 101-app
Ignoring unsupported options: build
Updating service 101-app_econfig-app-service-dallas (id: tpfe9h7zqbukwusnri1f8xhjj)
```
```
[admin@server101 stack]$ sudo docker stack deploy -c 301-app.yml --with-registry-auth 301-app
Ignoring unsupported options: build

Creating service 301-app_econfig-app-service-sydney
failed to create service 301-app_econfig-app-service-sydney: Error response from daemon: rpc error: code = InvalidArgument desc = port '443' is already in use by service '101-app_econfig-app-service-dallas' (tpfe9h7zqbukwusnri1f8xhjj) as an ingress port
```

```
[admin@server101 stack]$ sudo docker node ls
ID                            HOSTNAME                             STATUS              AVAILABILITY        MANAGER STATUS
uf3r2gzyt1pbnqmhmhjlysctx *   server101.com   Ready               Active              Leader
0vz9t80ogfg8ivx52mrnro2y7    server301.com   Ready               Active              Reachable
```
server101
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
server301
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

Some idea?

**Comment by thaJeztah** [comment]
@albertorm95 

```yaml
ports:
      - "443:443"
```

You are publishing the services using the routing mesh, so the service is accessible on port 443 on every node in the swarm. Read the discussion above; you'll have to use `host` mode publishing so that the service is only accessible on port 443 on the node that it is running on.

**Comment by eromoe** [comment]
@thaJeztah How do I make a port not only accessed by every node in the swarm, but also access by the `host_ip:port` ? I need access the same port from outside.

**Comment by thaJeztah** [comment]
@eromoe that's what this option does; it publishes a port on each node in the swarm, and makes it accessible from the outside. This _does_ assume the node's network interface is externally accessible.

**Comment by eromoe** [comment]
@thaJeztah Since you said 
> you'll have to use host mode publishing so that the service is only accessible on port 443 on the node that it is running on

And my 
```
  demo-lb:
    image: ${PRIVATE_REGISTRY}/${HAPROXY_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - demo
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
```

didn't publish 8000，  which make me think `host mode` only work on external .

**Comment by thaJeztah** [comment]
Yes; if you read that article;

> This issue affects the Docker Engine in Docker EE 17.03 and lower.

...

> The only way to specify host mode networking is to utilize compose v3.2, which is only supported in Docker Engine 17.04 and higher.

If you are running Docker Engine 17.04 or higher, ensure you've configured the version: section of the compose file to:version: 3.2.

**Comment by eromoe** [comment]
OK,  I  thought `version: '3'` would automatically refer to the laster sub version before.

**Comment by thaJeztah** [comment]
No "3" refers to "3.0"

**Comment by sky93** [comment]
I want to expose the port to 127.0.0.1 only. How can I do this in host mode?
```yml
    ports:
      - target: 80
        published: 127.0.0.1:8000
        protocol: tcp
        mode: host
```

This is not working. `It says services.my_service.ports.0.published must be a integer`
