### ISSUE TITLE
Stack deploy for docker-compose.yml doesn't pick node

### ISSUE THREAD

**Issue by adityacs** [moby/moby#33223]
When trying to deploy service with docker stack deploy, docker is not able to pick node.
![image](https://cloud.githubusercontent.com/assets/7681197/26105171/8f9c084a-3a5e-11e7-9d14-fb96137ebb10.png)
When I try to create the service manually it works correctly.
![image](https://cloud.githubusercontent.com/assets/7681197/26105199/ae32c456-3a5e-11e7-9620-54aa2bdefa2b.png)

Kindly help me with this.

**`docker version`:**
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr 26 23:09:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr 26 23:09:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**`docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.12-coreos
Operating System: Container Linux by CoreOS 1395.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.865GiB
Name: blrswarmdev002
ID: MPWK:IK7C:MQQJ:LBVI:M7AD:VPTO:6OGV:QTQ6:CZPP:PLCW:LJNJ:FHRR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry.igloo.vztelematics.in:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
It may help to `docker service inspect` the service that is failing, as it may show the reason _why_ it's not deploying. Having said that, without access to your `docker-compose` file, or an example compose file to reproduce the issue, it will be difficult for others to help you.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Comment by adityacs** [comment]
Below is the compose file which I used.

```
version: '3'
services:
  portainer:
    image: portainer/portainer
    hostname: portainer
    networks:
     - ext-proxy
    ports:
     - "9000:9000"
    volumes:
     - portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    deploy:
      placement:
        constraints:
         - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

volumes:
  portainer:
    driver: convoy

networks:
  ext-proxy:
    external: true

```
