### ISSUE TITLE
oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

### ISSUE THREAD

**Issue by EskenderTamrat** [moby/moby#33266]
Hi all,

I have this docker-compose file which worked perfect on my local machine, but produced the following error while trying to run it in aws.

**container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"**

I have the following Dockerfile for neo4j 
```
FROM java:7-jdk

RUN wget -O - http://debian.neo4j.org/neotechnology.gpg.key| apt-key add -
RUN echo 'deb http://debian.neo4j.org/repo stable/' > \
	/etc/apt/sources.list.d/neo4j.list
RUN apt-get update; apt-get -y upgrade ; apt-get -y autoclean
RUN apt-get -y install neo4j
ENV NEO4J_HOME=/var/lib/neo4j
ADD neo4j.sh /tmp/
RUN chmod u+x /tmp/neo4j.sh
RUN /tmp/neo4j.sh setup
EXPOSE 7474
EXPOSE 1337
CMD /tmp/neo4j.sh start
```

There is another Dockerfile for node express.

```
FROM node:latest
RUN adduser --disabled-password --gecos "Web App" app
RUN adduser app sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN npm install -g --save mocha
RUN npm install supertest --save-dev
RUN npm install express-session
WORKDIR /home/app
EXPOSE 3000
```

The docker-compose file content

```yaml
app:
    image: telehealth/node
    ports:
        - 3000:3000
    volumes:
        -  /home/eskender/Desktop/GRAPH_MEDELERT/medelert/medelert_Node:/home/app
    command: node bin/www
    links:
        - neo4jdb:neo4jdb
        - redisdb:redisdb

neo4jdb:
    image: telehealth/neo4j
    ports:  # This port is forwarded for visualization only
        - "8888:7474"

redisdb:
    image: redis
```

Whenever I try to build the two Dockerfiles, I get the error message of **oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"**. 

I have trying to look similar questions but nothing worked for me (from running it with 'sudo' to clearup unwanted docker containers & restarting) At first I get the error message when I try to run the docker-compose file, but it reproduced to the Dockerfiles itself when I clear the previous images.

Thanks.
