### ISSUE TITLE
Docker SWARM labels on nodes are not recognized after update to docker v17.05.0-ce with docker stack deploy and yaml

### ISSUE THREAD

**Issue by gdeverlant** [moby/moby#33338]
**Description**

This seems to be a BUG

After upgrading from 17.03 to 17.05 the same yaml file I used is not deployed as expected by docker.
I have 5 nodes on 10 in my swarm which have the following label constaints on each node:

- node.labels.arch==arm64
- node.labels.isDBReplicate==true
- node.labels.hasHDD==true

The last service from the YAML gets deployed on the node number 8 only.
When I update that service to 5 replicas the 5 replicas are deployed on the same node which should not happen. Docker should find the 4 other nodes with the same node labels and spawn one service on each node. 

**Steps to reproduce the issue:**
1. Copy thi YAML file

```
version: "3"

services:

  agency: 
    image: arangodb/arangodb
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address tcp://{{.Service.Name}}:8529 --server.authentication false --agency.size 1 --agency.activate true --agency.supervision true --log.file /var/log/arangodb3/arangod.log
    volumes:
      - datas:/var/log/arangodb3
    networks:
      - myingress-net
    deploy:
        placement:
            constraints:
                - node.labels.isAgency==true
                - node.labels.arch==arm64
                - node.labels.hasHDD==true
                
  coordinator:
    image: arangodb/arangodb
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://{{.Service.Name}}:8529 --cluster.my-local-info {{.Service.Name}} --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
      - datas:/var/lib/arangodb3
      - datas:/var/lib/arangodb3-apps
      - datas:/var/log/arangodb3
    networks:
      - myingress-net
    deploy:
        placement:
            constraints:
                - node.labels.arch==arm64
                - node.labels.isCoordinator==true
                - node.labels.hasHDD==true
    ports: ['8529:8529']
    depends_on:
      - agency
      
  cluster:
    image: arangodb/arangodb
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://cluster{{.Task.Slot}}:8529 --cluster.my-local-info cluster{{.Task.Slot}} --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
      - datas:/var/lib/arangodb3
      - datas:/var/log/arangodb3
    networks:
      - myingress-net
    deploy:
        placement:
            constraints:
                - node.labels.arch==arm64
                - node.labels.isDBReplicate==true
                - node.labels.hasHDD==true    
    depends_on:
      - agency
      - coordinator

networks:
    myingress-net:
        external: true
            
volumes:
  datas:
    driver: local
    driver_opts:
        type: volume 
        mountpoint: /mnt/virtual/docker/volumes/arangodb3
```

2. set 5 nodes in the cluster with node label constraints like:
```
node.labels.arch==arm64
node.labels.isDBReplicate==true
node.labels.hasHDD==true
```

```
server8
[
    {
        "ID": "jwyju7toczd0p5exe8yqi8k5g",
        "Version": {
            "Index": 2903
        },
        "CreatedAt": "2017-05-21T22:10:42.676208648Z",
        "UpdatedAt": "2017-05-22T09:22:26.81705998Z",
        "Spec": {
            "Labels": {
                "arch": "arm64",
                "hasHDD": "true",
                "isDBReplicate": "true"
            },
            "Role": "worker",
            "Availability": "active"
```

```
server9
[
    {
        "ID": "90dnan6z170sfq99i87lalugt",
        "Version": {
            "Index": 2902
        },
        "CreatedAt": "2017-05-21T22:10:42.593800182Z",
        "UpdatedAt": "2017-05-22T09:20:54.078629647Z",
        "Spec": {
            "Labels": {
                "arch": "arm64",
                "hasHDD": "true",
                "isDBReplicate": "true"
            },
            "Role": "worker",
            "Availability": "active"
```

```
server10
[
    {
        "ID": "31xv25iscsrvgbkt1sua7c1k0",
        "Version": {
            "Index": 2901
        },
        "CreatedAt": "2017-05-21T22:10:42.691917737Z",
        "UpdatedAt": "2017-05-22T09:19:54.598566476Z",
        "Spec": {
            "Labels": {
                "arch": "arm64",
                "hasHDD": "true",
                "isDBReplicate": "true"
            },
            "Role": "worker",
            "Availability": "active"
```

```
server11
[
    {
        "ID": "w1s3l7mpkhic3gzt4nc3r75tq",
        "Version": {
            "Index": 2900
        },
        "CreatedAt": "2017-05-21T22:10:42.573110065Z",
        "UpdatedAt": "2017-05-22T09:13:40.239399757Z",
        "Spec": {
            "Labels": {
                "arch": "arm64",
                "hasHDD": "true",
                "isDBReplicate": "true"
            },
            "Role": "worker",
            "Availability": "active"
```

```
server12
[
    {
        "ID": "thx1jzja5qx87i7e20sm5wz68",
        "Version": {
            "Index": 2849
        },
        "CreatedAt": "2017-05-21T22:10:42.539686875Z",
        "UpdatedAt": "2017-05-22T08:59:06.582647575Z",
        "Spec": {
            "Labels": {
                "arch": "arm64",
                "hasHDD": "true",
                "isDBReplicate": "true"
            },
            "Role": "worker",
            "Availability": "active"
```

3. docker stack deploy -c docker-compose.yml arangodb3
4. docker service scale arangodb3_cluster =5

**Describe the results you received:**

[screenshot](https://files.gitter.im/gdeverlant/ls4T/blob)

**Describe the results you expected:**

The scaling should not happen on the same node with 5 instance of the same service but rather the 4 other nodes individually

**Additional information you deem important (e.g. issue happens only occasionally):**

This problem appeared when I upgraded docker 17.03-ce to 17.05-ce

**Output of `docker version`:**
Manager host
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:28:23 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:28:23 2017
 OS/Arch:      linux/arm
 Experimental: false
```

**Output of `docker info`:**
Manager host
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 379
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 520
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: x81ofqv53z0n66vvjrrs8i38s
 Is Manager: true
 ClusterID: vg6cba4lt2zpdhywscrdyevex
 Managers: 1
 Nodes: 12
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.3
 Manager Addresses:
  192.168.1.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.10.104
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 940.9MiB
Name: bambuserver1
ID: 7GHE:CHRG:TDC4:UOTO:3JWM:2ZYU:CHBN:AMIE:W45Y:I5G7:AMSK:ETMY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Manager host
```
uname -a
Linux server1 3.10.104 #1 SMP PREEMPT Fri Apr 14 22:52:56 CEST 2017 armv7l GNU/Linux
```
Worker nodes 
```
uname -a
Linux bambuserver12 3.14.79-109 #1 SMP PREEMPT Thu Mar 16 20:05:25 BRT 2017 aarch64 GNU/Linux
```
