### ISSUE TITLE
network does not work on docker stack deploy with v3 compose.yaml 

### ISSUE THREAD

**Issue by ljfuyuan** [moby/moby#33351]
docker version 17.03.1.ce-17.05.0.ce

my .yaml file:

```
version: '3'
services:
    redis:
        image: '192.168.10.241:7000/redis:latest'
        command: ['redis-server','--appendonly','yes']
        environment:
            - SERVICE_ID=redis
        volumes:
            - '/db1:/data'
        networks:
            - redis_${ZONE}
networks:  
    redis_${ZONE}:
```

then do `export ZONE=1` first
and ` docker stack deploy -c server.yaml server`, i got this:

> Creating network server_redis_1
> service redis: undefined network "redis_1"

network is given a name based on the “project name”,but the network `server_redis_1` can't work on redis_1

is there something wrong?
