### ISSUE TITLE
Compose v3.2 endpoint_mode not working with dnsrr (related #32575)

### ISSUE THREAD

**Issue by cr0hn** [moby/moby#33353]
**Description**

The issue #32575 is not solved in release 17.05, as the release note says. I downloaded this release and when try to deploy a service with the option **dnsrr** the daemon raises the error: *endpoint_mode Additional property endpoint_mode is not allowed*.

**Steps to reproduce the issue:**
1. Create a Swarm compose with a the option *endpoint_mode* setted *dnsrr* in any service.
2. Try to deploy the stack
3. Get the error

**Describe the results you received:**

```
> docker stack deploy -c my_compose asdf
endpoint_mode Additional property endpoint_mode is not allowed
```

**Describe the results you expected:**

The expected result is that the stack runs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 79
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 30znk5pf8ttrc3c1icrkpdlmf
 Is Manager: true
 ClusterID: n1dbqd4aibhkhry76rk11fbhl
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.1.227
 Manager Addresses:
  172.16.1.227:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1016-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: idsFreeMaster
ID: 4IPU:EKIY:XGOI:OQA7:YQN3:DOBO:D4SG:35Y6:WJ4M:IQOK:73WW:QASP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Swarm Compose content**

```
networks:
  IDSFREE_SCAN_xkCXb_hSBwq: {external: true}
  mynet: {internal: true}
  registry: {driver: overlay, internal: true}
  traefik: {internal: true}
services:
  docker-empty:
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy: {condition: on-failure}
    image: registry:2
    networks: [IDSFREE_SCAN_xkCXb_hSBwq]
  docker-registry:
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy: {condition: on-failure}
    image: registry:2
    networks: [registry, IDSFREE_SCAN_xkCXb_hSBwq]
  redis:
    deploy: {endpoint_mode: dnsrr}
    image: redis
    networks: [IDSFREE_SCAN_xkCXb_hSBwq]
  registry-ui:
    deploy:
      endpoint_mode: dnsrr
      labels: [traefik.port=80, 'traefik.frontend.rule=Host:registry.91k.es', traefik.docker.network=traefik]
      replicas: 1
      restart_policy: {condition: on-failure}
    environment: [ENV_DOCKER_REGISTRY_HOST=docker-registry, ENV_DOCKER_REGISTRY_PORT=5000]
    image: konradkleine/docker-registry-frontend:v2
    networks: [registry, traefik, IDSFREE_SCAN_xkCXb_hSBwq]
version: '3'

```

**Comment by cirocosta** [comment]
Hey @cr0hn , I might be wrong but I think this is due to using an old `docker-compose` version. Which one are you using?

**Comment by thaJeztah** [comment]
Yes, this option was added in a later version of the `docker-compose` file format;

```yaml
version: '3'
services:
  foo:
    deploy:
      endpoint_mode: dnsrr
    image: nginx:alpine
```


```bash
$ docker stack deploy -c docker-compose.yml repro-33353
endpoint_mode Additional property endpoint_mode is not allowed
```

Updating the version to 3.2 makes this work;

```yaml
version: '3.2'
services:
  foo:
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
    image: nginx:alpine
```

```bash
$ docker stack deploy -c docker-compose.yml repro-33353
Creating network repro-33353_default
Creating service repro-33353_foo
```

I'll close this because this is not a bug, but feel free to continue the conversation
