### ISSUE TITLE
Networking mode (net: host) in docker stack file not working

### ISSUE THREAD

**Issue by aczarnecki** [moby/moby#33393]
**Description**

Hi all,

I'm trying to deploy some stateful application using docker stack. To achieve this I need to implement session stickiness and connection draining. Session stickiness can be achieved using ex. dockercloud/haproxy, but connection draining is more problematic. I thought about using external LB with this feature already in place but for that I need ports to be published only on hosts where the service is deployed (meaning that I'm not using routing mesh for that service) 

According to documentation for Docker stack file (https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#net) there should be two networking modes supported: host and bridge.

> net
> Networking mode. Only “bridge” and “host” options are supported for now.
> `net: host`

But when I enter this into stack file I receive:
`net Additional property net is not allowed`

```
  ab:
    image: my/image
    ports:
     - 8280:80
    networks:
      - AB
    net: host
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.type == ab
          - node.role == worker
```

**Steps to reproduce the issue:**
1. Create stack file
2. Enter `net: host` into one of the services.
3. Deploy stack

**Describe the results you received:**
`net Additional property net is not allowed`

**Describe the results you expected:**
Expected ports to be published on the host running the service.

**Additional information you deem important (e.g. issue happens only occasionally):**
AWS, Docker stack
**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: oh5o6gz6fkwvqacaogb6fqsz1
 Is Manager: true
 ClusterID: w5x6m47p2xeof0rjp8iqctwal
 Managers: 1
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.0.195
 Manager Addresses:
  10.10.0.195:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.36-8-default
Operating System: openSUSE Leap 42.2
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951 GiB
Name: ip-10-10-0-195
ID: LIZB:FREV:3DEJ:6YE5:7RSY:KV4G:CBQB:QSQH:HWLK:A3HF:UE4W:ZWTM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, Docker stack

**Comment by cpuguy83** [comment]
Host mode networking is not really what you want here and is not supported on services.
If you use the expand port syntax (you'll need to upgrade to 17.05, I think?) you can use host-mode port forwarding rather than the built-in ingress LB.

Here's an example from the CLI: https://docs.docker.com/engine/swarm/services/#example-run-a-nginx-web-server-service-on-every-swarm-node

**Comment by aczarnecki** [comment]
Updated to 17.05. The expanded syntax didn't work.
`services.master.ports.0 must be a string or number`

I tried this configuration:
```
version: "3"
services:
  master:
    image: tomcat:8.5-jre8-alpine
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - xCenter
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

  worker:
    image: tomcat:8.5-jre8-alpine
    ports:
      - 8080:8080
    networks:
      - xCenter
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
networks:
  xCenter:
```

I can do something like this after I deploy the stack:
`sudo docker service update --publish-rm 8080 --publish-add mode=host,target=8080,published=8080 test_worker`
but it will restart the service, and is not persisted when doing an update with another `docker stack deploy`.
