### ISSUE TITLE
level=error msg="fatal task error" error="task: non-zero exit (1)"

### ISSUE THREAD

**Issue by kaasia** [moby/moby#33397]
i want create a mysql service ,then i got this error:
```
May 25 08:03:57 localhost dockerd: time="2017-05-25T08:03:57.464472299-04:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module="node/agent/taskmanager" task.id=tbniz8vqkue3ecpgx1wtsoj94

May 25 08:03:58 localhost dockerd: time="2017-05-25T08:03:58.354676838-04:00" level=warning msg="failed to deactivate service binding for container bb_mysql.1.lq53yrk3nf4wljq05yohrsnhg" error="network sandbox does not exist for container bb_mysql.1.lq53yrk3nf4wljq05yohrsnhg" module="node/agent"
```

```
Version:      17.03.1-c
 OS/Arch:      linux/amd64   centos7
```

parts of yml file 
```
  mysql:

    image: 192.168.51.232:5000/mysql:latest

    deploy:

      resources:

        limits:

          cpus: "0.3"

          memory: 150M

    networks:

      - webnet
```
 
command :  `docker stack deploy -c docker-compose.yml aa`
