### ISSUE TITLE
Can't rollback service automatically after update 

### ISSUE THREAD

**Issue by omauger** [moby/moby#33427]
Hi,
I don't know why, I can't rollback service after an update failed.

My version :
```
Client:
Version: 17.03.1-ce
API version: 1.27
Go version: go1.7.5
Git commit: c6d412e
Built: Mon Mar 27 17:14:09 2017
OS/Arch: linux/amd64

Server:
Version: 17.03.1-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: c6d412e
Built: Mon Mar 27 17:14:09 2017
OS/Arch: linux/amd64
Experimental: false
```
My docker compose :

```yaml
version: '3.1'
services:
web:
image: chrch/docker-pets:1.0
deploy:
mode: replicated
replicas: 3
update_config:
parallelism: 1
delay: 10s
max_failure_ratio: .3
ports:
- 8080:5000
healthcheck:
interval: 10s
timeout: 2s
retries: 2
```

I use the command : `docker stack deploy -c pets.yml pets`

And I have this result :
```
docker service ps pets_web
ID NAME IMAGE NODE DESIRED STATE CURRENT STATE ERROR PORTS
jc7mlgac0ick pets_web.1 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Running Running 59 seconds ago
zp8slw5v6xag pets_web.2 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Running Running 58 seconds ago
owr6whar0nzj pets_web.3 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Running Running 58 seconds ago
```
When I do the command : `docker service update --rollback --image chrch/docker-pets:broken pets_web`
I have this result : `service does not have a previous specification to roll back to`

I force an update with command : `docker service update --force pets_web`
And I restart update image with rollback option : `docker service update --rollback --image chrch/docker-pets:broken pets_web`
And the image failed but never rollback :
```
docker service ps pets_web
ID NAME IMAGE NODE DESIRED STATE CURRENT STATE ERROR PORTS
soqmoxdybjma pets_web.1 chrch/docker-pets:broken omauger-ThinkPad-T550 Running Starting 17 seconds ago
szws2gcovtbu _ pets_web.1 chrch/docker-pets:broken omauger-ThinkPad-T550 Shutdown Failed 22 seconds ago "task: non-zero exit (137): do…"
bilkbge1ram5 _ pets_web.1 chrch/docker-pets:broken omauger-ThinkPad-T550 Shutdown Failed 58 seconds ago "task: non-zero exit (137): do…"
kkr04y1dphi7 _ pets_web.1 chrch/docker-pets:broken omauger-ThinkPad-T550 Shutdown Failed about a minute ago "task: non-zero exit (137): do…"
z1lbk20kkuaj _ pets_web.1 chrch/docker-pets:broken omauger-ThinkPad-T550 Shutdown Failed 2 minutes ago "task: non-zero exit (137): do…"
vks2jv7rmm7k pets_web.2 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Running Running 3 minutes ago
zp8slw5v6xag _ pets_web.2 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Shutdown Shutdown 3 minutes ago
sjz2ukhfqqsq pets_web.3 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Running Running 3 minutes ago
owr6whar0nzj _ pets_web.3 chrch/docker-pets:1.0 omauger-ThinkPad-T550 Shutdown Shutdown 4 minutes ago
```
I miss something or it's a bug ?

**Comment by thaJeztah** [comment]
When using the `--rollback` option, you're rolling back to the previous definition of the service. Based on the error message, there is no previous version, because you probably just _created_ the service for the first time.

Also note that, when using `--rollback`, that option should not be combined with other options to _update_ the service. The `--rollback` option is to _manually_ rollback to the previous version (implemented in https://github.com/moby/moby/pull/26421). _Automatic_ rollback (i.e. when the service fails to be updated to a new version) was added in docker 17.04 through https://github.com/moby/moby/pull/31108, which added the `rollback` option to `--update-failure-action`, so is not yet available in the version you're running.

As a quick example how to use the manual `--rollback` option;

First deploy your service/stack;

```yaml
version: '3.1'
services:
  web:
    image: chrch/docker-pets:1.0
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        max_failure_ratio: .3
    ports:
      - 8080:5000
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 2
```

Deploy the stack, and verify it's deployed;
```bash
docker stack deploy -c pets.yml pets

docker stack ps pets
ID            NAME        IMAGE                  NODE                DESIRED STATE  CURRENT STATE          ERROR  PORTS
z0ocbik0tm8e  pets_web.1  chrch/docker-pets:1.0  ubuntu-2gb-ams3-01  Running        Running 2 seconds ago
abad69ph8lu5  pets_web.2  chrch/docker-pets:1.0  ubuntu-2gb-ams3-01  Running        Running 2 seconds ago
4q0p4ilj8hxe  pets_web.3  chrch/docker-pets:1.0  ubuntu-2gb-ams3-01  Running        Running 2 seconds ago
```

Once the service is deployed, update your stack to use the "faulty" image;

```yaml
version: '3.1'
services:
  web:
    image: chrch/docker-pets:broken
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        max_failure_ratio: .3
    ports:
      - 8080:5000
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 2
```

Update the service by re-deploying the stack;

```bash
$ docker stack deploy -c pets.yml pets
Updating service pets_web (id: t5npiwkpn09ogxe51es965th7)
```

You see that the new image is broken; tasks fail

```bash
$ docker service ps pets_web
ID            NAME            IMAGE                     NODE                DESIRED STATE  CURRENT STATE              ERROR                             PORTS
z0ocbik0tm8e  pets_web.1      chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Running        Running 4 minutes ago
r50vt8gq6glw  pets_web.2      chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Running        Starting 12 seconds ago
z6lckrh0y7zg   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed 17 seconds ago      "task: non-zero exit (137): do…"
noarg5wdc1rq   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed 54 seconds ago      "task: non-zero exit (137): do…"
3bs439iw5lwf   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed about a minute ago  "task: non-zero exit (137): do…"
abad69ph8lu5   \_ pets_web.2  chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Shutdown       Shutdown 2 minutes ago
4q0p4ilj8hxe  pets_web.3      chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Running        Running 4 minutes ago
```

So to revert (rollback) to the previous version, you can use the `--rollback` option;

```bash
$ docker service update --rollback pets_web
pets_web
```

The service-definition is reverted to the previous version, so the `1.0` image is used again;

```
docker service ps pets_web
ID            NAME            IMAGE                     NODE                DESIRED STATE  CURRENT STATE              ERROR                             PORTS
z0ocbik0tm8e  pets_web.1      chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Running        Running 5 minutes ago
3zw8046w2zob  pets_web.2      chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Running        Running 1 second ago
e2l1q1qmzt55   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Shutdown 13 seconds ago
uwmyig0kezug   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed 33 seconds ago      "task: non-zero exit (137): do…"
r50vt8gq6glw   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed about a minute ago  "task: non-zero exit (137): do…"
z6lckrh0y7zg   \_ pets_web.2  chrch/docker-pets:broken  ubuntu-2gb-ams3-01  Shutdown       Failed about a minute ago  "task: non-zero exit (137): do…"
4q0p4ilj8hxe  pets_web.3      chrch/docker-pets:1.0     ubuntu-2gb-ams3-01  Running        Running 5 minutes ago
```

Don't forget to update your docker-compose file as well, otherwise running `docker stack deploy` would update the service to the faulty image again.
