### ISSUE TITLE
Docker secrets deployed without swarm

### ISSUE THREAD

**Issue by carlioth** [moby/moby#33519]
**Description**

We are using Docker secrets to distribute our secrets in our Swarm. 
We also run our service without Swarm by running docker-compose up -d

We don't expect the secrets to work / get deployed in non Swarm mode after reading the documentation: 
https://docs.docker.com/engine/swarm/secrets/

> Note: Docker secrets are only available to swarm services, not to standalone containers. To use this feature, consider adapting your container to run as a service with a scale of 1.

But the secrets do get deployed.

**Steps to reproduce the issue:**
1. Run docker-compose up -d
2. docker exec -it <container> bash
3. cd /run/secrets

**Describe the results you received:**
The secrets are now here deployed

**Describe the results you expected:**
That the secrets didn't get deployed

**Additional information you deem important (e.g. issue happens only occasionally):**
Short version of our docker-compoose.yml file: 
```
version: "3.1"

services:
  auth:
    # A service handling authentication and JWT generation.
    image: <image name
    secrets:
      - cert-secret.crt
      - github_client_id
      - github_client_secret
      - jwt_secret
      - cookie_signing
    environment:
      GITHUB_CLIENT_ID_FILE: /run/secrets/github_client_id
      GITHUB_CLIENT_SECRET_FILE: /run/secrets/github_client_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      COOKIE_SIGNING_FILE: /run/secrets/cookie_signing
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  github_client_id:
    file: ./secrets/GITHUB_CLIENT_ID
  github_client_secret:
    file: ./secrets/GITHUB_CLIENT_SECRET
  jwt_secret:
    file: ./secrets/JWT_SECRET
  cookie_signing:
    file: ./secrets/COOKIE_SIGNING
  cert-secret.crt:
    file: ./secrets/cert-secret.crt

```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
 Dirs: 660
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 2TIT:W67T:T5VI:YZSI:2SCL:QJ6C:HF47:BQQS:WUGI:BEQE:GMGQ:NYCP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
