### ISSUE TITLE
Docker Compose Variable substitution - can't use a variable in a yaml/compose key

### ISSUE THREAD

**Issue by netflash** [moby/moby#33540]
**Description**

I'm trying to use variables in my compose file.
According to https://docs.docker.com/compose/compose-file/#variable-substitution

I can do something like this:

```
services:
  someservice:
    volumes:
      - "${VOLUME_NAME}:/mnt/volume"
```

I assumed that I also can use variable substitution in volume name in the volumes section:

```
---
version: 3.1

volumes:
  "${VOLUME_NAME}":
    driver: cloudstor:aws

services:
  someservice:
    ...
    volumes:
      - "${VOLUME_NAME}:/mnt/volume"
```

But it doesn't work.
I get error:

```
${VOLUME_NAME} Additional property ${VOLUME_NAME} is not allowed
```

Is it a bug or a feature ?

**Steps to reproduce the issue:**
1. Create a compose yaml file with content

```
---
version: "3.1"

volumes:
  "${VOLUME_NAME}":
    driver: cloudstor:aws

services:
  metadata:
    image: hello-world
    entrypoint: /bin/true
    volumes:
      - "${VOLUME_NAME}:/mnt/volume"
```

2. Deploy the stack 

```
VOLUME_NAME=volume1 docker stack deploy --compose-file compose.yml someservice
```

**Describe the results you received:**

```
${VOLUME_NAME} Additional property ${VOLUME_NAME} is not allowed
```

**Describe the results you expected:**
The yaml/compose key has been substituted by the env variable and stack has been deployed.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: =-=-=-=-= cleaned from the output =-=-=-=-
 Is Manager: true
 ClusterID: =-=-=-=-= cleaned from the output =-=-=-=-
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: =-=-=-=-= cleaned from the output =-=-=-=-
 Manager Addresses:
  =-=-=-=-= cleaned from the output =-=-=-=-
  =-=-=-=-= cleaned from the output =-=-=-=-
  =-=-=-=-= cleaned from the output =-=-=-=-
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.19-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: =-=-=-=-= cleaned from the output =-=-=-=-
ID: =-=-=-=-= cleaned from the output =-=-=-=-
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 176
 Goroutines: 298
 System Time: 2017-06-06T13:23:51.776737874Z
 EventsListeners: 2
Username: =-=-=-=-= cleaned from the output =-=-=-=-
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region==-=-=-=-= cleaned from the output =-=-=-=-
 availability_zone==-=-=-=-= cleaned from the output =-=-=-=-
 instance_type=t2.xlarge
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by composer22** [comment]
Gonna expand a bit on what we are trying to do.

We'd like to assign a volume name to a cloudstor volume so we can share that with other services,

Like this in compose + swarm mode
```
version: "3.1"

volumes:
   metadata:
     external:
         name: ${UNIQUE_NAME} 
     driver: cloudstor:aws

services:
  metadata:
    image: hello-world
    entrypoint: /bin/true
    volumes:
      - metadata:/mnt/volume
```

Unfortunately, external/name + driver decls do not work together.

The only way to do this is to assign the unique name as an attribute. But the following is not workable syntax since var names cannot be attr
```
version: "3.1"

volumes:
   ${UNIQUE_NAME} :

     driver: cloudstor:aws

services:
  metadata:
    image: hello-world
    entrypoint: /bin/true
    volumes:
      - ${UNIQUE_NAME}:/mnt/volume
```
Using a template mechanism like m4 can work but it is hacky:

```
version: "3.1"

volumes:
   UNIQUE_NAME :
     driver: cloudstor:aws

services:
  metadata:
    image: hello-world
    entrypoint: /bin/true
    volumes:
      - UNIQUE_NAME:/mnt/volume
```
So the overarching question put forward

Is there a way to assign a sharable dynamic name on startup using parameters?
