### ISSUE TITLE
Docker stack deploy cannot deploy service to different node in swarm cluster, always report that ingress network overlap

### ISSUE THREAD

**Issue by lnshi** [moby/moby#33626]
I use `docker stack deploy` with `docker-compose.yml v3`, like below:

```
version: '3'
networks:
  _0:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
services:
  registry:
    image: registry:2
    networks:
      - _0
    ports:
      - '7777:5000'
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server-cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/server-cert-private-key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: 94f9b4f9ddae40ed96bbb753b9ed4d14
    volumes:
      - /home/leonard/docker_data_only_container/tls/*.sgdev.vcube.com/server:/certs
      - /home/leonard/docker_data_only_container/registry/auth:/auth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.name == micro02
      restart_policy:
        condition: any
  portainer:
    image: portainer/portainer
    networks:
      - _0
    ports:
      - '7778:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
```

Then do `docker stack deploy --compose-file docker-compose.yml dev` to deploy this stack to the docker swarm cluster:

if I use the same `constraints` for these two services in the deploy placement, like both `engine.labels.name == micro02`, that means these two services will be located at exactly same node, then it works totally fine,

but if I use different `constraints` for these two services in the deploy placement, like one `engine.labels.name == micro02`, another one `node.role == manager`, coz the `micro02` node is not manger, that means the service will be located at different node,  then I will 100% get error:

```
"Err": "starting container failed: subnet sandbox join failed for \"10.255.0.0/16\":
    overlay subnet 10.255.0.0/16 failed check with host route table:
    requested network overlaps with existing network",
```

Which the `10.255.0.0/16` network is turned to be the `ingress` network, the `NetworkAttachments` part from the `docker inspect` service command is as follow:

```

"NetworksAttachments": [
        {
            "Network": {
                "ID": "fz2dzdj0oceyxxoh6ndg94pfo",
                "Version": {
                    "Index": 6
                },
                "CreatedAt": "2017-06-10T02:44:27.422796031Z",
                "UpdatedAt": "2017-06-10T02:44:27.441022671Z",
                "Spec": {
                    "Name": "ingress",
                    "Labels": {},
                    "DriverConfiguration": {},
                    "Ingress": true,
                    "IPAMOptions": {
                        "Driver": {},
                        "Configs": [
                            {
                                "Subnet": "10.255.0.0/16",
                                "Gateway": "10.255.0.1"
                            }
                        ]
                    }
                },
                "DriverState": {
                    "Name": "overlay",
                    "Options": {
                        "com.docker.network.driver.overlay.vxlanid_list": "4096"
                    }
                },
                "IPAMOptions": {
                    "Driver": {
                        "Name": "default"
                    },
                    "Configs": [
                        {
                            "Subnet": "10.255.0.0/16",
                            "Gateway": "10.255.0.1"
                        }
                    ]
                }
            },
            "Addresses": [
                "10.255.0.6/16"
            ]
        },
        {
            "Network": {
                "ID": "z7x8t42lc9rscns1u1tvmauq5",
                "Version": {
                    "Index": 105031
                },
                "CreatedAt": "2017-06-11T03:22:01.312281009Z",
                "UpdatedAt": "2017-06-11T03:22:01.313259979Z",
                "Spec": {
                    "Name": "dev_stg_registry__0",
                    "Labels": {
                        "com.docker.stack.namespace": "dev_stg_registry"
                    },
                    "DriverConfiguration": {
                        "Name": "overlay"
                    },
                    "IPAMOptions": {
                        "Driver": {
                            "Name": "default"
                        },
                        "Configs": [
                            {
                                "Subnet": "172.31.0.0/24",
                                "Gateway": "172.31.0.1"
                            }
                        ]
                    }
                },
                "DriverState": {
                    "Name": "overlay",
                    "Options": {
                        "com.docker.network.driver.overlay.vxlanid_list": "4097"
                    }
                },
                "IPAMOptions": {
                    "Driver": {
                        "Name": "default"
                    },
                    "Configs": [
                        {
                            "Subnet": "172.31.0.0/24",
                            "Gateway": "172.31.0.1"
                        }
                    ]
                }
            },
            "Addresses": [
                "172.31.0.3/24"
            ]
        }
    ]
```

Docker swarm cluster is provisioned by using docker-machine with generic driver.

Output of `docker info` from the docker which is used in the docker swarm:

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: vq9b76vp4wuj7qwoxr87w4w6z
 Is Manager: true
 ClusterID: n6ekfek40unb602r2zphmgutd
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.3.159
 Manager Addresses:
  10.0.3.159:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-100-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: micro01.sgdev.vcube.com
ID: DDWK:3I3I:GIOH:NS3C:BNUI:CX2I:6ANQ:MCBL:K4FL:2QE2:K5AH:C3VL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 name=micro01
 provider=generic
Experimental: false
Insecure Registries:
 micro02.sgdev.vcube.com:7777
 127.0.0.0/8
Live Restore Enabled: false
```
