### ISSUE TITLE
Failed to start container xxx: service endpoint with name rabbit_master_1 already exists

### ISSUE THREAD

**Issue by Slably** [moby/moby#33796]
**Description**

After restarting docker service (while there is running container) by:

`sudo systemctl restart docker`

cannot start again container using docker-compose. It fails with error:

`Failed to start container xxx: service endpoint with name rabbit_master_1 already exists`

Used command:
`docker-compose -f compose.yml start`

**Content of compose.yml:**
```
version: '2'
services:
    rabbit_xxx_1:
        image: 10.0.0.12:5000/xxx/rabbitmq:latest
        container_name: rabbit_master_1
        ports:
          - "10.0.0.12:5672:5672"
        restart: unless-stopped
        read_only: true
        networks:
            default:
                ipv4_address: "xxx"
networks:
    default:
        external:
            name: sg-network

```
Error happens occasionally and is hard to reproduce.

**Steps to reproduce the issue:**

1. Run container (docker-compose -f compose.yml start)
2. Restart Docker service (sudo systemctl restart docker)
3. Try to run again container (docker-compose -f compose.yml start)

**Describe the results you received:**

Got error message:
Failed to start container xxx: service endpoint with name rabbit_master_1 already exists

**Describe the results you expected:**

Expect container starts successfully.

**Additional information you deem important:**

Issue happens only occasionally.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
**Output of `docker info`:**

```
WARNING: bridge-nf-call-ip6tables is disabled
d: 2
Images: 18
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26 GiB
Name: xxx
ID: xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 containerslots=25
Experimental: false
Cluster Store: consul://10.42.240.77:8500
Cluster Advertise: 10.0.0.172:2375
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```
