### ISSUE TITLE
Incorrect swarm load balancing behavior when selective ports are open

### ISSUE THREAD

**Issue by bufnitza** [moby/moby#33806]
Hello,

While setting up a clusterized graylog on docker swarm, I have crossed across a weird behavior in the swarm.

Here is the setup:

I have 2 docker hosts, one manager and one worker, set up in a swarm, running on CentOS 7 and Docker 17.05.0-ce.

On this swarm, I am running the following service:
```
  graylog:
    image: graylog2/server:2.2.3-1
    deploy:
      mode: global
    volumes:
      - /opt/data/graylog:/usr/share/graylog/data/config
      - graylogjournal:/usr/share/graylog/data/journal
    ports:
      - "2080:9000" # WWW
      - "9301:9301" # Embedded Elasticsearch client on first node
      - "9302:9302" # Embedded Elasticsearch client on second node
      - "2500:2500" # Inputs begin here
      - "2500:2500/udp"
      - "2501:2501"
      - "2501:2501/udp"
      - "2502:2502"
```

Now, it's worth noting a few things:
* As a global service, in this case, there are 2 replicas of this container
* I am using an external Elasticsearch cluster to store and index data. However, Graylog uses its own embedded Elasticsearch to join that cluster as "clients", for optimization of operations.
* In order for this to happen, the external ES cluster must be accesibile by the embedded ES instances (which is obvious) but also the embedded ES instances must be accessible by the external ES cluster (not so obvious). Why Elasticsearch has designed it this way is beyond my understanding and also out of the scope of the issue.
* To achieve this, I have made a clever configuration which will start the embedded ES on the replica 1 on port 9301 and the embedded ES on the replica 2 on port 9302. The swarm service is obviously publishing both these ports.

Now, here's the deal breaker: One would expect that when I point a TCP connection to a node on port 9301, this connection would always be forwarded to the container running on node 1. Same correspondence would be expected for port 9302 and the container on node 2.

However, this is not the case, as it seems that the swarm forwarded blindly sends any connection to the containers in a round robin fashion, regardless if a container is listening or not on that port.
This results in the connections failing 50% of the time with "Connection refused", which I assume happens whenever the swarm is forwarding a connection on port 9301 to the container on node 2 and a connection on port 9302 to the container on node 1. 

"50% is ok, just let ES retry and don't bother", I hear you say. Well, scale that to 4, 8, 12 containers and you can see why it becomes a problem.

To me, this looks like a bug in the routing mechanism, as the swarm should check availability on port level, and not simply trust the state of the replica (Running).

Please let me know your thoughts. 

Best regards,
Claudiu

Here is some relevant output (trimmed):

```
root@docker-corp-1:~# netstat -ntpl
tcp6       0      0 :::9301                 :::*                    LISTEN      5933/dockerd
tcp6       0      0 :::9302                 :::*                    LISTEN      5933/dockerd
```

netstat in container running on node 1
```
bash-4.3# netstat -ntpl
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::9301                 :::*                    LISTEN      28/java
```

netstat in container running on node 2
```
bash-4.3# netstat -ntpl
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::9302                 :::*                    LISTEN      28/java
```

```
root@docker-corp-2:~# telnet docker-corp-1 9301
Trying 10.25.8.41...
Connected to docker-corp-1.
Escape character is '^]'.
Connection closed by foreign host.
root@docker-corp-2:~# telnet docker-corp-1 9301
Trying 10.25.8.41...
telnet: connect to address 10.25.8.41: Connection refused
root@docker-corp-2:~# telnet docker-corp-1 9301
Trying 10.25.8.41...
Connected to docker-corp-1.
Escape character is '^]'.
Connection closed by foreign host.
root@docker-corp-2:~# telnet docker-corp-1 9301
Trying 10.25.8.41...
telnet: connect to address 10.25.8.41: Connection refused
```
