### ISSUE TITLE
cpuset Additional property cpuset is not allowed with docker-compose v3.2

### ISSUE THREAD

**Issue by lnshi** [moby/moby#33858]
**docker stack deploy** with **cpuset** get error:

```
cpuset Additional property cpuset is not allowed
```

Actually I globally searched [here](https://github.com/docker/compose/tree/master/compose/config), for `v3.*` there is totally no `cpuset` scheme definition there, only have 🙃

```
"resource": {
  "id": "#/definitions/resource",
  "type": "object",
  "properties": {
    "cpus": {"type": "string"},
    "memory": {"type": "string"}
  },
  "additionalProperties": false
},
```

docker-compose.yml

```
version: '3.2'

networks:
  default:
    external:
      name: gate_services_stack

services:

  ms-auth-jwt:
    image: ${REGISTRY}/auth-${SERVICE_TAG_SUFFIX}
    environment:
      SERVICE_NAME: auth-${SERVICE_TAG_SUFFIX}
      MS_SERVICE_TAG: auth-${SERVICE_TAG_SUFFIX}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpuset: 0,1
      restart_policy:
        condition: any
```

docker --version

```
Docker version 17.05.0-ce, build 89658be
```

docker info

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 152
Server Version: 17.06.0-ce-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: f4mk4ieawb4ogctjcry6xna1u
 Is Manager: true
 ClusterID: uhavxasxi7p5gnlvv75nekfjz
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 4J46:TBGI:L5TE:CB4A:FM54:H3VH:N2OM:D4RO:5YI2:3WBI:A44A:63KI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 53
 Goroutines: 170
 System Time: 2017-06-28T04:23:10.794513225Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 micro02.sgdev.vcube.com:7777
 127.0.0.0/8
Live Restore Enabled: false
```
