### ISSUE TITLE
Inter-container communication fails after restarting swarm manager node

### ISSUE THREAD

**Issue by andrius-kulbis** [moby/moby#33872]
**Description**

Having a the following swarm setup:
```
ID                HOSTNAME      STATUS       AVAILABILITY  MANAGER
az8ptk865hkvbb    web1-dev      Ready        Active        Leader
cohv346j0f4p3s    web2-dev      Ready        Active
```

And the service description:
```
version: '3'
services:
  master:
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis-master
    deploy:
      placement:
        constraints:
          - node.role == manager

  slave:
    image: redis:alpine
    command: redis-server --slaveof redis-master 6379 --slave-read-only no
    networks:
      default:
        aliases:
          - redis-slave
    deploy:
      placement:
        constraints:
          - node.role == worker

```

Redis slave-master communication fails after restarting the manager swarm node docker process until worker node process is not restarted.

**Steps to reproduce the issue:**
1. Setup docker swarm consisting of 1 manager and 1 worker
2. Deploy service using `docker stack deploy -c redis-setup.yml redis`
3. Restart docker `service docker restart` on manager node

**Describe the results you received:**
Executing `docker exec -it <redis_master_container> ping redis-slave` gives me and error:

**`ping: bad address 'redis-slave'`**

**Describe the results you expected:**
Executing `docker exec -it <redis_master_container> ping redis-slave` shows the ping packets reaching redis-slave as a sign of inter-container communication working between containers in different nodes.

**Additional information you deem important (e.g. issue happens only occasionally):**
After restarting the worker node ping is working as expected again.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
