### ISSUE TITLE
Container start/restart takes a very long time

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#33901]
**Description**
When running a container that is attached to a stack or service, it takes over 3 minutes for it to start or restart.

**Steps to reproduce the issue:**
(Running commands in PowerShell.)
1. running the command: 'docker stack deploy -c [composefile].yml --with-registry-auth [stackname]
or with a running container: 'docker restart [container]'
2. if you run the stack deploy command, a 'docker container list [|-a]' will be delayed until the container starts (over 3 minutes).
3. if you run a 'docker restart' command it takes over 3 minutes to start the container and give the shell prompt again. 

**Describe the results you received:**
any 'docker container' command is delayed until the container starts, but other commands seem to work ('docker logs [container]' command works for a started container while the first container is starting. 'docker container list [|-a]' always lists the starting container as "up for less than a second" once the container starts and the list command goes through.

**Describe the results you expected:**
starting a container should take a few seconds at most.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on Windows Server 2016 Core, I stopped the docker service and replaced the 17.03-ee version of the docker.exe and dockerd.exe binaries with the version I'm currently running (see below).
I have not tried running a container outside of stack to see if the problem persists, though I will try that and post the results.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: lpiiypps4syxypp0he5xfex5d
 Is Manager: true
 ClusterID: e1t83w9bh5ipu0ellmg4gxkwf
 Managers: 4
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.3.233
 Manager Addresses:
  10.0.3.169:2377
  10.0.3.224:2377
  10.0.3.233:2377
  10.0.3.249:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2GiB
Name: GPSDWZ-IA
ID: MF3L:JAY7:AOEM:WK7Y:BNPS:4JBG:JETJ:YWTU:AGH3:WR4S:RHCA:JDWU
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry1:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Vacant0mens** [comment]
Update: this problem does not occur with a 'docker run' command.

**Comment by Vacant0mens** [comment]
please add the swarm and/or stack/compose labels.

**Comment by thaJeztah** [comment]
`docker run` always starts your container on the local node, whereas `docker stack deploy` deploys a cluster in your swarm, which may mean the container is started on one of your other nodes.

If the image that you're using for your image is not present in that node, the image will be pulled first, before the service is started, which (especially with Windows images, which can be quite large), can take a while.

If you suspect this is not the reason you're seeing this delay, please provide more information, and the _exact_ steps to reproduce (including a sample `docker-compose.yml` that can be used to reproduce the issue)

**Comment by Vacant0mens** [comment]
Here's my compose.yml file. Seems wrong to have to re-cache the image every single time the service starts though. Even over a local network getting the image and then extracting it can take a long time (depending on the image). Seems like it should cache it only the first time and then hold on to the cache until a new version of the service (with a new image) is deployed. In my system, even running a restart on the container associated with the service takes a very long time. Maybe the service pulling image isn't the problem? (I've been using a local registry.)
And honestly, other than the following compose file and the deploy command (using -c and --with-registry-auth) I don't think I'm doing anything out of the ordinary. My compose file has some deploy constraints for different servers (since the back-end servers are in the same swarm as the front-end), but this is mostly to keep things organized, and that shouldn't affect the container start, right?
```
version: '3.3'
services:
#Begin application.webapi
#
  applicationweb:
    image: registry1:5000/application/web:1.2017.0628.2
# credential_spec may get ignored until it's fully supported (should be in 17.06)
    credential_spec:
      file: "gMSA-125.json"
    environment:
      - APPLICATIONSETTINGS__ENVIRONMENT=Dev
      - CONNECTIONSTRINGS__CREDENTIALSCONNECTIONSTRING=Data Source=dbserv-125;Initial Catalog=Vault;Integrated Security=True
      - ASPNETCORE_URLS=http://*:80
      - SERILOG__MINIMUMLEVEL=Verbose
      - SERILOG__WRITETO__0__NAME=Seq
      - SERILOG__WRITETO__0__ARGS__SERVERURL=http://Devlogs:5500
      - SERILOG__WRITETO__0__ARGS__APIKEY=5nNfgHm81wo09EknmmDt
      - SERILOG__PROPERTIES__INSTITUTIONID=125
      - SERILOG__PROPERTIES__ENVIRONMENT=Dev
      - BUSSETTINGS__CREDENTIALSID=Bus
      - BUSSETTINGS__HOSTNAME=MQ1.hostname.com
      - BUSSETTINGS__VIRTUALHOST=125
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.servertype==web
#End application.webapi
#Begin NGinX
#
  nginx1:
    image: registry1:5000/nginx/nanoserver
    volumes:
      - E:\Dev\125:C:\nginx\xconf
    ports:
      - "10125:10125"
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.servertype==web
         - node.labels.serverletter==a
  nginx2:
    image: registry1:5000/nginx/nanoserver
    volumes:
      - E:\Dev\125:C:\nginx\xconf
    ports:
      - "20125:20125"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.servertype==web
         - node.labels.serverletter==b
#End NGinX
#End of file
```
