### ISSUE TITLE
Compose3 fill a variable on use

### ISSUE THREAD

**Issue by frimdo** [moby/moby#33904]
**Feature idea**
Sometimes you need to generate a variable to use in compose file. 

**Example**
When deploying etcd, you need to pass a unique discovery address. The best way to do it is to generate it with command `curl -w "\n" 'https://discovery.etcd.io/new?size=1'`. Right now, I do it by using environment variable in compose file:
```
  etcd:
    image: elcolio/etcd:latest
    deploy:
      replicas: 1
    command: -name etcd -discovery=${ETCD_DISCOVERY:-UNSET}
```
and deploy stack using command:
```
ETCD_DISCOVERY=$(curl -w "\n" 'https://discovery.etcd.io/new?size=1') \
bash -c 'docker stack deploy -c semaphore.yml semaphore'
```
I think this should have an simpler solution. For example if I could do 
```
...
command: -name etcd -discovery=$(curl -w "\n" 'https://discovery.etcd.io/new?size=1')
```
