### ISSUE TITLE
Add support for network_mode in docker stack deploy

### ISSUE THREAD

**Issue by groyee** [moby/moby#33915]
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

Currently network_mode is not supported in docker stack deploy with docker-compose file.

`docker stack deploy -c docker-compose.yml prod`

What other options are available for mass deployment if all containers are using --network=host?

--network=host is already supported in docker 17.06. Is there a reason it is not supported in docker-compose 3.3?

**Comment by thaJeztah** [comment]
This is supported in the compose file format by creating a network that's marked as "external", see https://github.com/moby/moby/issues/25873#issuecomment-319109840

```yaml
version: '3.3'

services:
  web:
    image: "nginx:alpine"
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"
```


closing because this is supported, but feel free to continue the conversation
