### ISSUE TITLE
`Docker stack deploy` creates and attaches to network even if none is specified

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#34012]
**Description**
Using `docker stack deploy` creates and attaches to network even none is specified in YAML file

**Steps to reproduce the issue:**
1. Yaml File 
```
version: '3.2'
services:
   webredirect:
      image: 014589826424.dkr.ecr.us-east-1.amazonaws.com/webredirect:latest
      ports:
        - target: 80
          published: 8080
          protocol: tcp
          mode: host
      volumes:
        - type: volume
          source: webredirect
          target: c:\inetpub\logs\host
      deploy:
        mode: global
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        placement:
          constraints: [node.role != manager]
volumes:
  webredirect:
    external: true
```
2. Using `docker stack deploy --with-registry-auth --compose-file webredirect/docker-stack.yml webredirect` with YAML above
3. Generated service will have following entry in `network` section
```
                "Networks": [
                    {
                        "Target": "llsk28zg08hhrr3dju4h1sknj",
                        "Aliases": [
                            "webredirect"
                        ]
                    }
                ],

```

**Describe the results you received:**
Service tries to create a new network called `webredirect` and attach to it when none is specified. 

**Describe the results you expected:**
Do nothing and use `host` mode as specifed.  Executing the same command via `docker service create` does not show this issue and works fine
`docker service create --with-registry-auth --name webredirect --mode global --mount "type=volume,src=webredirect,dst=c:\inetpub\logs\host" --constraint 'node.role != manager'  --publish "mode=host,target=80,published=8080" "014589826424.dkr.ecr.us-east-1.amazonaws.com/webredirect:latest"`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: 8n7pyjd7hpffj5wj7txcajatk
 Is Manager: true
 ClusterID: xytins5n0gu8ibfrk8z6lh12m
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.45.122.87
 Manager Addresses:
  10.45.122.87:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: SWARMMANAGER1
ID: 74ZU:HG6T:36VE:ERM5:XGTI:QIYK:LXVM:ZB3X:YIPL:VHZP:DWZP:TDLN
Docker Root Dir: E:\images
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
