### ISSUE TITLE
swarm stack deploy with command override dont use environment variables

### ISSUE THREAD

**Issue by omerh** [moby/moby#34034]
I have a use case for running migration for a service in a swarm cluster.
So I wanted to use the exact compose file and just override the command, but I've found that the override command dont get the environment variables from the compose file.

So, I've created the following compose file to check it:
```
version: "3"

services:
  some-service-migrations:
    image: nginx
    environment:
      - RAILS_ENV=production
      - DBHOST=dbhost
    healthcheck:
      disable: true
    command: echo "starting app with $RAILS_ENV $DBHOST"
```

And I've empty echo for the environment variable

```
test_some-service-migrations.1.o8veqbspoqof@swarm-manager03    | starting app with
``` 

If ill start the application with env command i see the environment variables:
```
version: "3"

services:
  some-service-migrations:
    image: nginx
    environment:
      - RAILS_ENV=production
      - DBHOST=dbhost
    healthcheck:
      disable: true
    command: env
```
Log output:
```
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | HOSTNAME=4840e77db257
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | DBHOST=dbhost
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | RAILS_ENV=production
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | NGINX_VERSION=1.13.2-1~stretch
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | NJS_VERSION=1.13.2.0.1.11-1~stretch
test_some-service-migrations.1.rbgqerh6o5x5@swarm-manager01    | HOME=/root
```

This is not an expected behaviour, I expect that the compose will set all environment variables and then execute the command, so the container will inherit the env configuration before running the command.

**Comment by thaJeztah** [comment]
This is due to using the wrong notation in the compose file;

First of all, you need to escape the `$` in the compose file, otherwise the variable is interpolated during deploy, and the _local_ environment variables are used;

With this docker-compose file:

```yaml
version: "3"

services:
  some-service-migrations:
    image: nginx:alpine
    environment:
      - RAILS_ENV=production
      - DBHOST=dbhost
    healthcheck:
      disable: true
    command: echo "starting app with $RAILS_ENV $DBHOST"
```

Running `docker stack deploy` with the `$RAILS_ENV` and `$DBHOST` environments set in your shell;

```bash
RAILS_ENV=hello DBHOST=world docker stack deploy -c docker-compose.yml foobar
```

You see that the environment variables are substituted for their value set in the shell:

```bash
docker inspect -f '{{json .Config.Cmd}}' 77a38a2d4cf6
["echo","starting app with hello world"]
```

To prevent this, escape the `$` using YAML notation (i.e. `$$`);

```yaml
version: "3"

services:
  some-service-migrations:
    image: nginx:alpine
    environment:
      - RAILS_ENV=production
      - DBHOST=dbhost
    healthcheck:
      disable: true
    command: echo "starting app with $$RAILS_ENV $$DBHOST"
```

Re-deploying (even with these variables set in your shell), and inspecting a task (container) for the service;

```bash
$ docker inspect -f '{{json .Config.Cmd}}'  df0ef3bdbd60
["echo","starting app with $RAILS_ENV $DBHOST"]
```

However, looking at the logs for that container, you'll see that the  _literal_ names of the environment variables are printed.;

```bash
$ docker logs df0ef3bdbd60
starting app with $RAILS_ENV $DBHOST
```

This is because variables expansion is done by the _shell_, not by the `echo` command; if you want the environment-variables to be expanded with their value _inside the container_, the echo command must run in a shell;

```bash
version: "3"

services:
  some-service-migrations:
    image: nginx:alpine
    environment:
      - RAILS_ENV=production
      - DBHOST=dbhost
    healthcheck:
      disable: true
    command: /bin/sh -c 'echo "starting app with $$RAILS_ENV $$DBHOST"'
```

Deploying this, and inspecting a task (container) for the service;

```bash
$ docker inspect -f '{{json .Config.Cmd}}' 083bdca5ec4a
["/bin/sh","-c","echo \"starting app with $RAILS_ENV $DBHOST\""]
```

And viewing the container's logs;

```bash
$ docker logs 083bdca5ec4a

starting app with production dbhost
```

I'll close this issue, because this is not a bug, but feel free to continue the conversation
