### ISSUE TITLE
Add option in Stack YAML file to specify subnet for default stack network on creation

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#34062]
It would be a super great feature to add an optional stack/yaml configuration for specifying the subnet configuration for the `[stackname]_default` stack network. That way you could choose (if desired) the subnet for the stack's default network.

Something like this:
```
version: '3.3'
subnet: 10.0.255.0/24
services: 
  service1:
    image: image1:1.2.3.4
```

I'm requesting this because in a stack with an nginx proxy on a 'host' port mapping (single port pointing to nginx who reverse-proxy's to multiple stack applications), nginx sends the `WHO HAS X.X.X.X` requests to the host's network first rather than the internal stack network. Usually the host's network doesn't have the same subnet as the stack's network, but in a medium to large Enterprise environment where `10.x.x.x` subnets are common, there is a bigger chance. If the requested IP address doesn't exist in the host's network, there's no problem getting the stack service's address, but if not, nginx will proxy traffic to the wrong place.

I realize this use case will become irrelevant when routing-mesh for Docker EE becomes available, but I thought this might be an easier feature to develop than that in the mean time, and useful after.

**Comment by thaJeztah** [comment]
This should already work;

```yaml
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.255.0/24
```
