### ISSUE TITLE
Sending Webhooks on Deploy state changes

### ISSUE THREAD

**Issue by srevenant** [moby/moby#34128]
have the ability to configure webhook endpoints when deploy actions happen.  Perhaps defined like:

```yaml
version: '3.x'
 services:
   name:
     deploy:
       notification: http://this.host/asdf/this-service
```

With metadata similar to the event stream info, sent as a json object.
