### ISSUE TITLE
Update paused due to failure or early termination of task

### ISSUE THREAD

**Issue by MLescaudron** [moby/moby#34245]
Hi,
**Description**

After 10-15 min of inactivity on a server, when I update a service with this command :  
`docker service update --image pseudo/image:tag --with-registry-auth service_name --detach=false`

I have this error every time: 
```
overall progress: 0 out of 4 tasks 
1/4: preparing [=================================>                 ] 
2/4:   
3/4:   
4/4:   
service update paused: update paused due to failure or early termination of task usuj4mrmk7x7z2a1vpvob569n
```

And if I restart the command again, it works ...
And if I leave for 15min and I start again, I have to run again the command twice.

I don't know why and it's very frustrating.

**Steps to reproduce the issue :**

I'm using private image with a nodejs express server. I'm using 1 docker swarm cluster and 1 node on a different machine.

The command to deploy : 
`docker stack deploy --with-registry-auth --compose-file dev.compose.yml custom_name`

dev.compose.yml
```
version: "3.3"

services:
  server:
    image: pseudo/image:tag
    ports:
      - 8080:8080
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 4
  mongo:
    image: mongo:3.4.6
    logging:
      driver: none
```

Docker version : 
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Any idea of what am I doing wrong ?
