### ISSUE TITLE
awslogs driver repeating last event

### ISSUE THREAD

**Issue by pgeez** [moby/moby#34292]
I'm running Docker 17.06.0-ce on Ubuntu 16.04 (on AWS) and have noticed that the `awslogs` logdriver is endlessly re-logging the last received event. As a repro, I am running the following simple Flask app:

```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
        return "Hello World!"

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

with the following `Dockerfile`:

```
FROM python:3.6-slim

RUN pip install flask
ADD app.py app.py
CMD ["python", "app.py"]
```

and the following `docker-compose.yaml`:

```
version: "2"

services:
  flask:
    build: .
    image: pgflask
    ports:
      - 5010:5000
    logging:
       driver: awslogs
       options:
         awslogs-region: "us-west-2"
         awslogs-group: "flask_loggroup"
         awslogs-stream: "flask_stream"
         awslogs-datetime-format: "%Y-%m-%d %H:%M:%S"
```

After `curl localhost:5010`, I see the following in my AWS CloudWatch console:

![image](https://user-images.githubusercontent.com/1369475/28702616-a949fdce-734d-11e7-8a78-c38f9ad67622.png)

**NOTE:** the `Running on http://...` message is from the Flask app startup and is also repeated.

I've tried using `syslog` and `json-file` log drivers but have not seen this behavior locally which leads me to believe there's an issue with `awslogs`. Any thoughts?? I really appreciate your help!

Docker Info:

`docker info`

```
Containers: 104
 Running: 1
 Paused: 0
 Stopped: 103
Images: 505
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 473
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1013-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-10-0-2-147
ID: KWYK:BVW4:YJAS:2WC7:6F5X:FHDH:HE3J:FE7V:VR7X:UCCP:7HFC:YMOC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
