### ISSUE TITLE
Host Port Bindings on Custom Stack Networks

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#34335]
**Description**
I am creating a stack with a custom network that I named `[stackname]_ingress` as follows:
```
version: '3.3'
networks:
  ingress:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.254.0.0/16
nginx:
    image: registry1:5000/nginx/windowsservercore
    volumes:
      - E:\Dev\125:C:\nginx\xconf
    ports:
      - target: 80
        published: 10125
        mode: host
    dns:
      - "10.254.0.1"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.servertype==web
    networks:
      - ingress
```
But when I deploy the stack, this particular service goes into a creation loop (creating new containers every 5-6 seconds, but never actually starting them). They have a status of 'Created' until they get deleted (retention of 5). I get nothing from `docker service logs [stackname]_nginx`

**Steps to reproduce the issue:**
1. Use stack file above
2. run `docker stack deploy -c [stackfile].yml --with-registry-auth [stackname]`
3. check container status with `docker container list -a`

**Additional information you deem important (e.g. issue happens only occasionally):**
In my environment, included in this stack, there are two more services that come up with no problems using the custom network. This particular service is set up to be a proxy and requires a host port binding (other services are websites/webapps), the other two services are the same except for the port binding (they have none), and the DNS (they don't need it).

I'll post debug logs as soon as I can get them.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 34
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: pending
 NodeID: xwpog62lnvwgfbs9ld858lcda
 Error: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 10.0.3.150
 Manager Addresses:
  10.0.1.230:2377
  10.0.3.150:2377
  10.0.3.61:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1480.amd64fre.rs1_release.170706-2004)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2GiB
Name: GPSDWZ-IA
ID: MF3L:JAY7:AOEM:WK7Y:BNPS:4JBG:JETJ:YWTU:AGH3:WR4S:RHCA:JDWU
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 gpsovermindlcl:5000
 127.0.0.0/8
Live Restore Enabled: false
```
