### ISSUE TITLE
Add support for OR constraint for placement in compose

### ISSUE THREAD

**Issue by omerh** [moby/moby#34433]
I am looking for a way run a service on couple for labels with OR
I am running swarm on AWS Auto scale, each autoscale group has its engine label and launch.
so I have 2 Autoscale groups with 2 engine labels
1. aws-instance=prod-spot-xl 
2. aws-instance=prod-xl

Before running sports I was doing something like this:
```
version: "3"
services:
  app:
    image: nginx:latest
    ports:
      - "86:80"
    deploy:
      placement:
        constraints:
          - engine.labels.aws-instance == prod-xl
      mode: global
```

And now I want to run the same service on the 2 labels with mode global for doing autoscale easy.
But, Constraints logic is with AND and not OR

So I want to do something like this:
```
version: "3"
services:
  app:
    image: nginx:latest
    ports:
      - "86:80"
    deploy:
      placement:
        constraints:
          or:
            - engine.labels.aws-instance == prod-xl 
            - engine.labels.aws-instance == prod-spot-xl
      mode: global
```

Am I missing something or this feature is not possible?

I am running latest swarm version:
```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Info:
```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: aj52ywaiwn7lvd261cjr8bmq5
 Is Manager: true
 ClusterID: 8780czo41mcbjd71n0458aaiy
 Managers: 3
 Nodes: 31
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.19.12.21
 Manager Addresses:
  172.19.10.213:2377
  172.19.11.175:2377
  172.19.12.21:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: swarm-manager03
ID: QF2R:TWS4:ECJZ:R5OZ:6SPH:QIIC:XQID:47Q4:2EOY:OAKP:SX6B:JNFJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
