### ISSUE TITLE
Mounted file is not in sync with its container's copy

### ISSUE THREAD

**Issue by OnkelTem** [moby/moby#34490]
I've just asked this question on StackOverflow, but then realized it could be a bug. Here is the link to my question: 
https://stackoverflow.com/questions/45645274/the-same-file-on-host-and-inside-container-is-different-it-is-not-in-sync-with

Steps to reproduce the behavior.

1. Mount a file in rw-mode inside a container.

I do this in my `docker-composer.yml`:

```yml
version: "3"
services:
  web:
    volumes:
      - "../composer.json:/path/to/composer.json"
```

2. Edit the file on the host.

3. Now check to see if the content of the file is changed in the container. In my case it isn't changed making it obvious that the file and its copy are not in sync.

docker version: 17.06.0-ce, build 02c1d87
system: Ubuntu 14.04
