### ISSUE TITLE
Swarm Services die when 1 of 3 managers rebooted

### ISSUE THREAD

**Issue by tomthetommy** [moby/moby#34502]
**Description**

Hi All,

I have 3 managers, and 3 workers.

Across all managers I have deployed traefik which listens on ports 80, 8080 and 443. I have also deployed various nginx apps.

I am having an issue with rebooting any of the managers. If I do so, it causes traefik to die a death on ALL the other managers, even though they were running OK previous to the reboot of a node.

**Steps to reproduce the issue:**
1. 3 Manager Swarm + 3 Workers
2. Deploy traefik, exposing local ports 80 8080 443.
3. Kill any 1 of the manager nodes.

**Describe the results you received:**

All the traefik instances across the rest of the 2 managers failed and stopped running. "docker service ls" shows them runnng however. Netstat shows that the ports are no longer being listened to.

**Describe the results you expected:**

I would expect the other services on the nodes to remain running and not stop just because 1 manager has been rebooted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.05.0-ce
Storage Driver: zfs
 Zpool: storage
 Zpool Health: ONLINE
 Parent Dataset: storage/docker
 Space Used By Parent: 475390976
 Space Available: 51270176768
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: uui1u8l0dxa783u3pysp20d3h
 Is Manager: true
 ClusterID: eij0epox3ph0o07ksu0nl6u5e
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.30.3.93
 Manager Addresses:
  10.30.3.93:2377
  10.30.3.94:2377
  10.30.3.95:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: docker-manager1
ID: D7PP:ZFEF:USX5:2BI3:KUAT:MIT4:HWAH:VCFZ:IKWX:VAQW:ROG2:M32W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tomthetommy** [comment]
I've also seen a lot of these errors on the managers:

level=warning msg="failed to deactivate service binding for container core_traefik.uui1u8l0dxa783u3pysp20d3h.yxkdsdbsdsjvh6ixu5kynamdk"

**Comment by thaJeztah** [comment]
How is the traefik service configured (i.e. what options are passed to create the service, is it using a custom network, are ports published using `host` mode, or through the routing mesh, etc); how many instances are running?

**Comment by tomthetommy** [comment]
`version: "3.2"

services:
  traefik:
    image: traefikprod:1.2.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /storage/dockerfs/traefik/logs
        target: /var/log/traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any
  visualiser:
    image: visualiser:latest
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any

networks:
  traefik-net:
    external: true`

**Comment by tomthetommy** [comment]
`version: "3.2"

services:
  traefik:
    image: traefikprod:1.2.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /storage/dockerfs/traefik/logs
        target: /var/log/traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any
  visualiser:
    image: visualiser:latest
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any

networks:
  traefik-net:
    external: true`

**Comment by tomthetommy** [comment]
``version: "3.2"

services:
  traefik:
    image: traefikprod:1.2.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /storage/dockerfs/traefik/logs
        target: /var/log/traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any
  visualiser:
    image: visualiser:latest
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any

networks:
  traefik-net:
    external: true

**Comment by tomthetommy** [comment]
This is basically the docker-compose.yml file.

```
version: "3.2"

services:
  traefik:
    image: traefikprod:1.2.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /storage/dockerfs/traefik/logs
        target: /var/log/traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any
  visualiser:
    image: visualiser:latest
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      restart_policy:
        condition: any

networks:
  traefik-net:
    external: true
```
