### ISSUE TITLE
Container Ports Not Mapping to Host - Docker-EE on SLES12

### ISSUE THREAD

**Issue by jimjdaniels** [moby/moby#34523]
**Description**

**Steps to reproduce the issue:**
1. Install SLES12 Minimal -  SLE-12-SP2-Server-DVD-x86_64-GM-DVD1.iso 
2. Install docker -EE  -- 17.03.2-ee-5
3. Init Swarm Mode 
4. docker stack deploy -c filename.yml   <stackname>
5. http://ip_of_swarm_host/consul
    (note: my httpd container has an endpoint the redirects to my consul container)

**Describe the results you received:**
This site can’t be reached
10.12.16.213 refused to connect.

**Describe the results you expected:**
I expect to see consul ui as I do on exact same CentOS installation.. 

**Additional information you deem important (e.g. issue happens only occasionally):**
----------------------------------------------------------------------------------------------------------
This problem is reproducible every time..
Below is the workaround , running this on the Host machine fixes the problem:

HTTPD=$(docker ps | grep va_httpd | awk '{print $NF}')
HTTPD_IP=$(docker exec $HTTPD ip addr | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | grep 172)
HOST_IP=$(getent hosts $HOSTNAME | awk '{print $1}')

echo "NAT Forward $HOST_IP:8080 to $HTTPD_IP:80"

sudo iptables -t nat -A PREROUTING -p tcp -i br0 --dport 8080 -j DNAT --to-destination $HTTPD_IP:80
sudo iptables -A FORWARD -p tcp -d $HTTPD_IP --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -A POSTROUTING -d $HTTPD_IP -p tcp --dport 80 -j SNAT --to-source $HOST_IP

echo "NAT Forward $HOST_IP:8443 to $HTTPD_IP:443"

sudo iptables -t nat -A PREROUTING -p tcp -i br0 --dport 8443 -j DNAT --to-destination $HTTPD_IP:443
sudo iptables -A FORWARD -p tcp -d $HTTPD_IP --dport 443 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -A POSTROUTING -d $HTTPD_IP -p tcp --dport 443 -j SNAT --to-source $HOST_IP

sudo iptables -t nat -L -n

----------------------------------------------------------------------------------------------------------

**Output of `docker version`:**

```
demo@linux-p1cu:~> docker version
Client:
 Version:      17.03.2-ee-5
 API version:  1.27
 Go version:   go1.7.3
 Git commit:   fa09039
 Built:        Thu Jul 20 00:24:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ee-5
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   fa09039
 Built:        Thu Jul 20 00:24:03 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
demo@linux-p1cu:~> docker info
Containers: 58
 Running: 6
 Paused: 0
 Stopped: 52
Images: 57
Server Version: 17.03.2-ee-5
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2+20151002
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 1dm5lwuz0qrfhetv5o079nltl
 Is Manager: true
 ClusterID: geeer7st9jwxygejcckzo0k0c
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.12.34.250
 Manager Addresses:
  10.12.34.250:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.74-92.32-default
Operating System: SUSE Linux Enterprise Server 12 SP2
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.7 GiB
Name: linux-p1cu
ID: ZFMI:4IPI:XI66:2CRR:XBGT:IZZW:T3Y7:3JON:WHZR:EXE2:RZBD:3QPV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is running on a VM in VMware VSphere..

Below is my stack file  va_config.yml:
```
networks: {}
services:
  configuration:
    depends_on:
    - authorization
    - consul
    - logon
    - postgres
    - rabbitmq
    image: docker.sas.com/pdt/sas-configuration:17w12
  consul:
    environment:
      CONSUL_BIND_EXTERNAL: eth0
      CONSUL_SERVER_LIST: consul
      CONSUL_BOOTSTRAP_EXPECT: 1
    image: docker.sas.com/pdt/sas-consul:17w12
  httpd:
    depends_on:
    - consul
    - postgres
    - rabbitmq
    environment:
      CONSUL_BIND_EXTERNAL: eth2
      CONSUL_SERVER_LIST: consul
    image: docker.sas.com/pdt/sas-httpd:17w12
    ports:
    - 443:443/tcp
    - 80:80/tcp
  logon:
    depends_on:
    - consul
    - postgres
    - rabbitmq
    extra_hosts:
      ldap.fyi.sas.com: 10.15.xx.xx
    image: docker.sas.com/pdt/sas-logon:17w12
  postgres:
    depends_on:
    - consul
    environment:
      CONSUL_BIND_EXTERNAL: eth0
      CONSUL_SERVER_LIST: consul
    image: docker.sas.com/pdt/sas-postgres:17w12
  rabbitmq:
    depends_on:
    - consul
    environment:
      CONSUL_BIND_EXTERNAL: eth0
      CONSUL_SERVER_LIST: consul
      RABBITMQ_USE_LONGNAME: 'FALSE'
    image: docker.sas.com/pdt/sas-rabbitmq:17w12
version: '3'
volumes: {}
```
