### ISSUE TITLE
Docker Compose Volume Long Syntax documentation is incorrect

### ISSUE THREAD

**Issue by tarunlalwani** [moby/moby#34643]
**Description**

The docker compose documentation shows an example of Volume long syntax as below

```yaml
version: "3.2"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"

networks:
  webnet:

volumes:
  - type: volume
    source: mydata
    target: /data
    volume:
      nocopy: true
  - type: bind
    source: ./static
    target: /opt/app/static
```
> Note: The long syntax is new in v3.2

I believe this format is only valid for volumes property of the service. Please correct me that is not the case 

**Steps to reproduce the issue:**
$ docker-compose config
ERROR: In file './docker-compose.yml', volume must be a mapping, not an array.

**Describe the results you received:**
ERROR: In file './docker-compose.yml', volume must be a mapping, not an array.

**Describe the results you expected:**
Documentation examples should work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
vagrant@vagrant:~/so/volumes$ docker info
Containers: 44
 Running: 5
 Paused: 0
 Stopped: 39
Images: 92
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 355
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: smh2288801wg3b15f0twxaew1
 Is Manager: true
 ClusterID: 3pqs1zxfxe76sb3r462engtfa
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.33.100
 Manager Addresses:
  192.168.33.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: vagrant
ID: H5PY:YSAS:TWDZ:HRHQ:7WPR:GAOZ:5PNY:YZTD:UB2K:QDDD:DVY5:OJF3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: tarunlalwani
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ docker-compose --version
docker-compose version 1.15.0, build e12f3b9
```

**Comment by vdemeester** [comment]
> I believe this format is only valid for volumes property of the service. Please correct me that is not the case

This is strange indeed if the example do not work...
/cc @shin- @thaJeztah @mstanleyjones

**Comment by vanniszsu** [comment]
That's because your indent is incorrect，  it should be 

version: "3.2"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"

    networks:
       webnet:

    volumes:
       - type: volume
         source: mydata
         target: /data
         volume:
            nocopy: true
       - type: bind
         source: ./static
         target: /opt/app/static

**Comment by vanniszsu** [comment]
That's because your indent is incorrect， it should be

version: "3.2"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"

    networks:
      webnet:

    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./static
        target: /opt/app/static

**Comment by thaJeztah** [comment]
Thanks for reporting! 

This looks like a duplicate of https://github.com/docker/compose/issues/5092, reported in the docker compose issue tracker, and I see that's been fixed through https://github.com/docker/docker.github.io/commit/65fdf795f4143d627a9e5988e37720870e1f3d72 (https://github.com/docker/docker.github.io/pull/4142) in the documentation repository

I'm closing this because this looks to be fixed, but feel free to comment if there's something that's still incorrect 👍

**Comment by moonlight16** [comment]
I'm still seeing this issue with compose v3.6.

Here's the relevant parts of my YML file:

```
version: '3.6'

volumes:
   my_volume:
      name: "my_volume"
      driver: "local"

   mongodb:
      build: ./mongo
      image: my_mongo:${DOCKER_VERSION}
      container_name: my_mongo
      restart: always
      volumes:
         - type: volume
            source: my_volume
            target: /data

```
And I'm still getting this error:

```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 21, column 19

```
Here's my code version:

```
$ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true

```

**Comment by shin-** [comment]
@moonlight16 Your indentation is broken: `source` and `target` should start on the same column as `type`.

**Comment by moonlight16** [comment]
Too bad.  I actually liked the idea of indenting the parms for each volume, so that when defining multiple volumes the parms for each volume are separated off.

For example, this looks a lot cleaner:

```
      volumes:
         - type: bind
            source: ./dash
            target: /home/project/dash_app
         - type: volume
            source: my_volume
            target: /data

```

as opposed to:

```
      volumes:
         - type: bind
         source: ./dash
         target: /home/project/dash_app
         - type: volume
         source: my_volume
         target: /data

```

Nevertheless, I tried this and now I'm getting this error:

```
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 24, column 10
expected <block end>, but found '?'
```

No idea why its telling me it found a '?'.

**Comment by mistyhacks** [comment]
I can understand why you might like it better, but indentation is significant in YAML (just like in Python too). Each volume has a type, source, and target. Your syntax implies that each volume has a type, and each type has a source and target. I think your `-` on `type` is also extraneous, but @shin- should verify.

**Comment by moonlight16** [comment]
I still get an error if I remove the ```-```:

```
      volumes:
         type: bind
         source: ./dash
         target: /home/project/dash_app
         type: volume
         source: my_volume
         target: /data
```

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.dash.volumes contains an invalid type, it should be an array
```

This also doesn't work:

```
      volumes:
         type: bind
         source: ./dash
         target: /home/project/dash_app
      volumes:
         type: volume
         source: lctrader_volume
         target: /data

```

(same error as above)

**Comment by shin-** [comment]
Sorry, should have been more explicit. Here's what you want:
```yaml
version: '3.6'

volumes:
   my_volume:
      name: "my_volume"
      driver: "local"

services:
   mongodb:
      build: ./mongo
      image: my_mongo:${DOCKER_VERSION}
      container_name: my_mongo
      restart: always
      volumes:
         - type: volume
           source: my_volume
           target: /data
```

All elements of the mapping should be on the same indentation level.
