### ISSUE TITLE
Docker Swarm : Load testing Spikes after Concurrent users reach to 400+ irrespective of service scaling, worker nodes used.

### ISSUE THREAD

**Issue by abhishek-galoda** [moby/moby#34663]
**Load Testing on Docker Swarm hits spike once the number of users reaches 400 or so irrespective of service scaling, worker nodes used**

We are experiencing a strange issue where the number of users once it reaches 400 or so, everything suddenly starts behaving weirdly. The response time increases suddenly from 600ms to  4 secs and then it keep going worse.  We have checked there are no CPU/Memory issues starvation and no swapping happening either. In fact the CPU % used was like 15%.
Also Checked if there were any limits set on max connection etc but none.

So we have tried the following things

1> Increasing the Containers instances (scaling up the service to 2 on the same machine) -> No effect
2> Increasing the Worker nodes from 1 to 2 and also scaling the service to 2  ->No effect
3> Tried with just a plain tutum/hello-world image still same issue persist.
4> Testing standalone nginx on the same manager node which is not a docker container doesn't get affected even after 1000 users.

Our set up is 1 Manager and 1 Worker Node( Tried 2 also for this test)

**Steps to reproduce the issue:**
1. Create the Docker Swarm with One Manager and 1/2 Worker nodes
2.Use the below docker-compose.yml 
```
version: "3"

services:


  travelstudio:
    image: nevado/travelstudio-api:0.0.1
    depends_on: 
      - fluentd
    networks:
      - net
    ports:
      - "9020"  
    environment:
      - "SPRING_PROFILES_ACTIVE=dev" 
    deploy:
      restart_policy:
           condition: on-failure
           delay: 20s
           max_attempts: 3
           window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 30s
      labels:
        - "traefik.docker.network=belmond_net"
        - "traefik.port=9020"
        - "traefik.frontend.rule=PathPrefix:/travelstudio/"
        - "traefik.backend.loadbalancer.method=drr"

  loadbalancer:
    image: traefik
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --web \
      --loglevel=DEBUG
    ports:
      - 80:80
      - 25581:8080   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
           condition: on-failure
           delay: 20s
           max_attempts: 3
           window: 120s
      mode: global # one container per manager node
      update_config:
        delay: 2s
      placement:
         constraints: [node.role == manager]
    networks:
      - net


networks:
  net:
  

```
  
3.Deploy the stack using _docker login -u #USERNAME -p #Password registry.hub.docker.com/nevado && docker stack deploy -c docker-swarm.yml belmond --with-registry-auth_ ( ### I have made the nevado/travelstudio public) so wont require password.

4> Test the service at URL  http://#domain-name#/travelstudio/
Load 500 virtual users with in a span of 5 mins .

**Results  received:**

As you can see the spike 

**1 Worker nodes, 1 master. Service replicas/scaled to 1 instance ** 
![image](https://user-images.githubusercontent.com/16354558/29833030-053bfb5c-8ce2-11e7-9b8f-8bd40c0e1da9.png)

**2 Worker nodes, 1 master. Service replicas/scaled to 2** 
  
![image](https://user-images.githubusercontent.com/16354558/29831919-8a2f8e18-8cde-11e7-9009-77af3cb8ab83.png)
as you can see no difference even if the service is scaled

**Describe the results you expected:**
We were expecting that the spike should happen only when the resource starvation occurs like CPU, memory, or swapping happens. Adding more nodes and scaling the services should increase the load capability.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
This is the docker version we are using
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`: FOR MANAGER NODE **

```
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 16
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: qhkqtl18tpu6022f8equan2gj
 Is Manager: true
 ClusterID: ofg263tkff9s63zvzde2b7fvl
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.199.4
 Manager Addresses:
  172.16.199.4:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.852GiB
Name: d-lnx-dkm-01
ID: XYO7:DO43:ANTH:IVGI:2CJA:F65Y:SE6J:J7HN:OWSJ:CZVI:FL5C:XQ7E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nevadobuild
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

**Docker Info FOR WORKER NODE**
```
```
 
`Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: rqfq83j39569kq0jdocxdf4pq
 Is Manager: false
 Node Address: 172.16.199.5
 Manager Addresses:
  172.16.199.4:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.852GiB
Name: d-lnx-dkm-02
ID: NV3R:GSU7:SYUW:C2AD:RYXS:ODVW:33JV:ORHB:6NHB:CJEM:EBUP:LPQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nevadobuild
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.`
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
   Static hostname: d-lnx-dkm-01
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 178967cfd7be4997b65b07da8d461f2d
           Boot ID: d9b64156b306495e8b20dff328d42a92
    Virtualization: microsoft
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.26.2.el7.x86_64
      Architecture: x86-64
