### ISSUE TITLE
Unable to specify interface for port long syntax

### ISSUE THREAD

**Issue by asbjornenge** [moby/moby#34851]
Hi!

I need to do a port binding using `mode:host` for a swarm stack, and bind to a specific interface. According to [docs](https://docs.docker.com/compose/compose-file/#ports) and the [code](https://github.com/moby/moby/blob/master/api/types/swarm/network.go#L31), seems this is currently not possible?

```
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
```

No way to specify `interface` or `ip` ??? 

HALP 😱
