### ISSUE TITLE
add bind-propagation to docker-compose

### ISSUE THREAD

**Issue by rdxmb** [moby/moby#34936]
```
version: '3.3'

services:

  container:
    image: phusion/baseimage
    container_name: mycontainer
    volumes:
    - type: bind
      source: /mnt
      target: /mnt
      bind-propagation: shared
```
the last line seems to be ignored when running `docker-compose up` , as the propagation when starting the container is `rprivate` - which is the default. When running the service with

`docker service create --mount type=bind,src=/mnt,target=/mnt,bind-propagation=shared --name bind-propagation phusion/baseimage`

the propagation indeed is `shared`.

This can be checked via
`docker inspect --format "{{json .Mounts}}" <CONTAINER>`

```
root@docker-single-host:~# docker-compose --version
docker-compose version 1.16.1, build 6d1ac21
root@docker-single-host:~# docker --version
Docker version 17.06.2-ce, build cec0b72
```

**Comment by cpuguy83** [comment]
This should already be supported:

```yaml
volumes:
    - type: bind
      bind:
          propagation: shared
```

**Comment by cpuguy83** [comment]
Closing since this works on `stack deploy`.

**Comment by rdxmb** [comment]
Thanks to @cpuguy83 !

**Comment by chetabahana** [comment]
Referring to [configure bind propagation](https://docs.docker.com/storage/bind-mounts/configure-bind-propagation)

Try to use [version: "3.2"](https://docs.docker.com/compose/compose-file/) for both `docker-compose.yml` and `docker-compose.override.yml`
```
version: "3.2"

services:
  container:
    volumes: 
      - /tmp/volume/media/:/app/media:rw,rshared
```

Describe volume
```
$ docker inspect container_1
..
..
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/tmp/volume/media",
                "Destination": "/app/media",
                "Mode": "rw,rshared",
                "RW": true,
                "Propagation": "rshared"
            }


```
