### ISSUE TITLE
Docker service break down after docker restart

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#35006]
I create a docker stack service with traefik only.
I remove the stack and try to recreate it. Traefik provide a response until it is break down
If i reboot docker daemon, traefik provides a response until it's broken again

```
docker version
Client:
 Version:      17.09.0-ce-rc3
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   2357fb2
 Built:        Thu Sep 21 02:31:18 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce-rc3
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   2357fb2
 Built:        Thu Sep 21 02:36:52 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

`./run_traefik.sh `
```shell
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
Error response from daemon: network with name outside already exists
Creating service traefik_traefik
wait 10s
success : 404
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 10s
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
...
RESTART DOCKER DAEMON

success : 404
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 10s
success : 404
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 10s
success : 404
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 10s
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
...
```

The source code: 

`run_traefik.sh`
```bash
#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

docker swarm init
docker network create -d overlay outside

while [ true ];
do
	docker stack deploy --compose-file traefik.yml traefik
	echo "wait 10s"
	sleep 10
	while [ "$response" != 404 ];
 	do
		response=$(curl --max-time 5 --connect-timeout 5 -s -o /dev/null -w "%{http_code}" http://localhost)
		if [ $response == 404 ];
		then
			echo -e "${GREEN}success${NC} : $response"
		else
			echo -e "${RED}failure${NC} : $response"
		fi
		sleep 1
	done
	response=0

	docker stack rm traefik
	echo "wait 2s"
	sleep 2
done
```

`traefik.yml`
```yml
version: "3"
services:
  traefik:
    image: traefik:v1.4.0-rc3
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.enable=false"
    networks:
      - outside
    deploy:
      replicas: 1
networks:
  outside:
    external: true
```

Another example :

```bash
#!/bin/bash


RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


docker swarm init
docker network create -d overlay outside --attachable

while [ true ];
do
	docker stack deploy --compose-file traefik.yml traefik
	#docker-compose -f traefik.yml start
	echo "wait 2s"
	sleep 2
	
	while [ "$response" != 302 ];
 	do
		response=$(curl --max-time 5 --connect-timeout 5 -s -o /dev/null -w "%{http_code}" http://localhost:8080)
		if [ $response == 302 ];
		then
			echo -e "${GREEN}success${NC} : $response"
		else
			echo -e "${RED}failure${NC} : $response"
		fi
		
		sleep 1
	done
	response=0
	
	docker stack rm traefik
	echo "wait 2s"
	sleep 2
done
```

result : 
./run_traefik.sh 

```bash
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
Error response from daemon: network with name outside already exists
Updating service traefik_traefik (id: 5ee5s9bfi9z1jocqbwn2wn4h5)
wait 2s
failure : 000
success : 302
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 2s
success : 302
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 2s
failure : 000
success : 302
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 2s
success : 302
Removing service traefik_traefik
wait 2s
Creating service traefik_traefik
wait 2s
failure : 000
failure : 000
failure : 000
...
```

Another example with nginx

nginx.yml

```yml
version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - outside
    deploy:
      replicas: 1
      
networks:
  outside:
    external: true

```

run_nginx.sh

```bash
#!/bin/bash


RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


docker swarm init
docker network create -d overlay outside --attachable

while [ true ];
do
	docker stack deploy --compose-file nginx.yml nginx
	echo "wait 2s"
	sleep 2
	
	while [ "$response" != 200 ];
 	do
		response=$(curl --max-time 5 --connect-timeout 5 -s -o /dev/null -w "%{http_code}" http://localhost:8080)
		if [ $response == 200 ];
		then
			echo -e "${GREEN}success${NC} : $response"
		else
			echo -e "${RED}failure${NC} : $response"
		fi
		
		sleep 1
	done
	response=0
	
	docker stack rm nginx
	echo "wait 2s"
	sleep 2
done
```

./run_nginx.sh 

 ``` bash
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
Error response from daemon: network with name outside already exists
Creating service nginx_nginx
wait 2s
success : 200
Removing service nginx_nginx
wait 2s
Creating service nginx_nginx
wait 2s
success : 200
Removing service nginx_nginx
wait 2s
Creating service nginx_nginx
wait 2s
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
failure : 000
...
```

In the container, the nginx process returns a response 

```bash
root@c0212ae1a706:/# curl --max-time 5 --connect-timeout 5 -s -o /dev/null -w "%{http_code}" http://localhost
200
```
