### ISSUE TITLE
docker volume ls -q -f dangling=true shows active volumes

### ISSUE THREAD

**Issue by huegelc** [moby/moby#35013]
**Description**

`docker volume ls -q -f dangling=true`  shows active volumes

**Steps to reproduce the issue:**
1. install some containers
2. docker volume ls -q -f dangling=true
3. show output

**Describe the results you received:**
```
docker volume ls -q -f dangling=true
gitlab
gitlab-runner
prometheus

docker ps -a 

CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                  PORTS                                                                 NAMES
2c420bfeb6cb        gitlab/gitlab-runner:alpine              "/usr/bin/dumb-ini..."   36 hours ago        Up 14 hours                                                                                   gitlab-runner
7ddd23eb3770        gitlab/gitlab-ce:latest                  "/assets/wrapper"        38 hours ago        Up 14 hours (healthy)   0.0.0.0:2224->22/tcp, 0.0.0.0:32771->80/tcp, 0.0.0.0:32770->443/tcp   gitlab_web_1
591ca712cad3        prom/prometheus                          "/bin/prometheus -..."   38 hours ago        Up 14 hours             0.0.0.0:9090->9090/tcp                                                prometheus
```

**Describe the results you expected:**
active volumes should not be listed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: btrfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.3-041303-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.762GiB
Name: nas-10-prod
ID: NAMQ:3ESS:BM5N:GSI5:54YE:MLMP:FSL2:JLIR:D4SV:WCSD:QZLQ:C3W2
Docker Root Dir: /storage/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I'm not able to reproduce. These are the steps I used to reproduce;

```bash
$ docker volume create myvolume
myvolume

$ docker volume ls

DRIVER              VOLUME NAME
local               myvolume

$ docker volume ls -f dangling=true

DRIVER              VOLUME NAME
local               myvolume
```

now start a container using that volume:

```bash
$ docker run -dit --name foo -v myvolume:/foo busybox
53ec2bc5cacf7117f8f815e1d1a1784633574ae9159797c2ef99da00d259b5ae
```

Check volumes with/without dangling filter:

```bash
$ docker volume ls
DRIVER              VOLUME NAME
local               myvolume

$ docker volume ls -f dangling=true
DRIVER              VOLUME NAME
```

stop, and remove the container:

```bash
$ docker stop foo && docker rm foo
foo
foo
```

Check volumes with/without dangling filter:

```bash
$ docker volume ls
DRIVER              VOLUME NAME
local               myvolume

$ docker volume ls -f dangling=true
DRIVER              VOLUME NAME
local               myvolume
```


Can you verify those volumes are actually used by your containers? You can verify this by inspecting those containers, for example (formatted for readability):

```bash
$ docker inspect -f '{{json .Mounts}}' container1 container2
[
  {
    "Type": "volume",
    "Name": "myvolume",
    "Source": "/var/lib/docker/volumes/myvolume/_data",
    "Destination": "/foo",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  }
]
[
  {
    "Type": "volume",
    "Name": "myvolume",
    "Source": "/var/lib/docker/volumes/myvolume/_data",
    "Destination": "/foo",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  }
]
```

**Comment by huegelc** [comment]
Thanks for your reply.


```
docker inspect -f '{{json .Mounts}}' gitlab-runner prometheus gitlab_web_1
[
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/gitlab-runner",
      "Destination":"/etc/gitlab-runner",
      "Mode":"",
      "RW":true,
      "Propagation":"rprivate"
   },
   {
      "Type":"volume",
      "Name":"31a2fdc908bb7a7168c69babc1d619418167e5d10b8fa708fd08f3abbaf9a24d",
      "Source":"/storage/docker/volumes/31a2fdc908bb7a7168c69babc1d619418167e5d10b8fa708fd08f3abbaf9a24d/_data",
      "Destination":"/home/gitlab-runner",
      "Driver":"local",
      "Mode":"",
      "RW":true,
      "Propagation":""
   }
][
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/prometheus/etc",
      "Destination":"/etc/prometheus",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   },
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/prometheus/prometheus_data",
      "Destination":"/prometheus",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   }
][
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/gitlab/logs/reconfigure",
      "Destination":"/var/log/gitlab/reconfigure",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   },
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/gitlab/data",
      "Destination":"/var/opt/gitlab",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   },
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/gitlab/config",
      "Destination":"/etc/gitlab",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   },
   {
      "Type":"bind",
      "Source":"/storage/docker/volumes/gitlab/logs",
      "Destination":"/var/log/gitlab",
      "Mode":"rw",
      "RW":true,
      "Propagation":"rprivate"
   }
]
```
```
docker volume ls
DRIVER              VOLUME NAME
local               02aa526db5c03821f1ad7d69a28ef335efd23b51c6395d4fc76c51e16c205646
local               0c7f6456b0c7007c6fa05c4cfbea5d4ae334128541ba88232acfc769ae428010
local               31a2fdc908bb7a7168c69babc1d619418167e5d10b8fa708fd08f3abbaf9a24d
local               5db112e8ee48ab4aed4bb7075641826c32c8d939dc58ad4aed6efc600b47d05a
local               6070b0042a1dce7f02f89226a0c96a3b0e2b95b2bf3e3a36704391bc1253433e
local               7b54769280830539899d2f44ec8d1711f14329279da69053f0da73955fc1f70d
local               7e5dec7ea47fdd34ffe74c038e60de741fc257da990047505f25a6ae3bd71c55
local               f8fa96ebc36cc42ab87a314f9f23920a120172acdf008061a40d6d9e7afcf66d
local               gitlab
local               gitlab-runner
local               prometheus
```

Those containers where created with docker-compose. 
```
version: '3'
services:
 web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'nas-10-gitlab'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url "http://nas-10-gitlab"
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
    VIRTUAL_HOST: nas-10-gitlab
    VIRTUAL_PORT: '80'
  ports:
    - '80'
    - '2224:22'
    - '443'
  volumes:
    - '/storage/docker/volumes/gitlab/config:/etc/gitlab'
    - '/storage/docker/volumes/gitlab/logs:/var/log/gitlab'
    - '/storage/docker/volumes/gitlab/data:/var/opt/gitlab'
    - '/storage/docker/volumes/gitlab/logs/reconfigure:/var/log/gitlab/reconfigure'
networks:
  default:
    external:
      name: nginxproxyssl_nginx-net
```
```
version: '3'

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /storage/docker/volumes/prometheus/etc/:/etc/prometheus/
      - /storage/docker/volumes/prometheus/prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-web.console.libraries=/usr/share/prometheus/console_libraries'
      - '-web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == <hostname where the prometheus config file in>
#  node-exporter:
#    container_name: node-exporter
#    image: prom/node-exporter
#    volumes:
#     - /proc:/host/proc:ro
#     - /sys:/host/sys:ro
#     - /:/rootfs:ro
#    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
#    expose:
#      - 9100
#    networks:
#      - back-tier
#    deploy:
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /storage/docker/volumes/prometheus/alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
          - node.hostname == <hostname where alertmanager config file in>
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - /storage/docker/volumes/prometheus/grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
```
and the gitlab-runner with:

```
docker run -d       --name gitlab-runner       --restart always       --network gitlab-runner-net       -v /storage/docker/volumes/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml       -e DOCKER_HOST=tcp://gitlab-dind:2375       gitlab/gitlab-runner:alpine
```

`/var/lib/docker` is symlinked to `/storage/docker`

This happened to me once while removing the volumes with:

`docker volume rm `docker volume ls -q -f dangling=true`

which resulted in wiping the volumes for those containers and none could start anymore.
