### ISSUE TITLE
can't remove container

### ISSUE THREAD

**Issue by yiv** [moby/moby#35164]
I follow the official instruction to install the docker, [Get Docker CE for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository)
this is my docker version
```
ubuntu@tpserver1:/data/docker/compose$ sudo docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker-compose.yml
```
version: '3'
services:
cockroach1:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - /data/docker/data/cockroach/roach1:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - cocknetwork
    restart: always
  cockroach2:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach2
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - /data/docker/data/cockroach/roach2:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
  cockroach3:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach3
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - /data/docker/data/cockroach/roach3:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
networks:
  cocknetwork:
    driver: bridge
```

cockroach2 is down, but its status is still up, I can't stop it or remove it, I must restart the docker service to do so.

```
ubuntu@tpserver1:/data/docker/compose$ sudo docker exec -it compose_cockroach2_1 /bin/sh
rpc error: code = 2 desc = containerd: container not found

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,   

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose stop cockroach2
Stopping compose_cockroach2_1 ... done

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose rm cockroach2
No stopped containers

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,  
```

after asked help from gitter, Sheogorath @SISheogorath suggest I put stop and rm command in one line , I try like below, still not work
```
ubuntu@tpserver1:/data/docker/compose$ sudo docker stop compose_cockroach2_1 && sudo docker rm compose_cockroach2_1
compose_cockroach2_1
Error response from daemon: You cannot remove a running container 5b6550b3ec9bff0be8eea857de9a954b6d67e75f1f1fce483468b89e9b943270. Stop the container before attempting removal or force remove

ubuntu@tpserver1:/data/docker/compose$ sudo docker stop compose_cockroach2_1 && sudo docker rm compose_cockroach2_1
compose_cockroach2_1
Error response from daemon: You cannot remove a running container 5b6550b3ec9bff0be8eea857de9a954b6d67e75f1f1fce483468b89e9b943270. Stop the container before attempting removal or force remove
ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose stop cockroach2 && sudo docker-compose rm cockroach2
Stopping compose_cockroach2_1 ... done
No stopped containers

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,
```
