### ISSUE TITLE
[Windows] exec bash exits after a few seconds

### ISSUE THREAD

**Issue by amorel-ljsl** [moby/moby#35196]
Hi.

I'm running Docker for Windows latest version on W10 Pro.

I built a container with this simple docker-compose file:

```
version: '3'

services:
   wp:
     image: wordpress:latest
     volumes:
       - ../themes:/var/www/html/wp-content/themes
     ports:
       - "32799:80"
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: 
```

I get into the container with the following command:

`docker exec -ti docker_wp_1 bash`

It works, I get there, but **after a random time between 2 and 10 seconds, it silently leaves and comes back to my Powershell prompt**

Looks like a bug to me, but there may be an explanation.
