### ISSUE TITLE
Stack deploy of a global service weird behaviour after terminating some workers 

### ISSUE THREAD

**Issue by omerh** [moby/moby#35207]
As @thaJeztah requested, opening another issue.

When running a service in `mode: global` using stack deploy with 5 nodes. 
```
version: "3"
services:
  webserver:
    image: nginx:1.12.1-alpine
    deploy:
      mode: global
      update_config:
        parallelism: 1
```

Ill have as expected 5 nodes running nginx:1.12.1-alpine.

Ill terminate 3 worker nodes of the cluster and run stack deploy with image update
```
version: "3"
services:
  webserver:
    image: nginx:1.13.3-alpine
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
```

Docker will wait for the nodes to become online so the stack deploy will hang.

Version
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Info
```
Containers: 10
 Running: 4
 Paused: 0
 Stopped: 6
Images: 51
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 659
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: fzguxyh0ctr0r5k3n2j3oap21
 Is Manager: true
 ClusterID: dltf6mz0ihg4t9q6z4xaedjad
 Managers: 3
 Nodes: 15
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.30.1.97
 Manager Addresses:
  10.30.1.49:2377
  10.30.1.97:2377
  10.30.2.48:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1013-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: swarm-manager01-stg
ID: 4SQ4:AUUE:VBIH:GQJ7:BTIZ:WZOF:6ZVN:WRD4:L3X7:BOCN:DCWU:U6FJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
