### ISSUE TITLE
Secret names should be able to include variables

### ISSUE THREAD

**Issue by rgardam** [moby/moby#35229]
Docker secrets being used in a docker-compose file should be able to handle the use of variables.

This would be really handy to be able to systematically update a secret in the next "version" of the container

**Steps to reproduce the issue:**
1. deploy a stack with docker secrets with variables
**Describe the results you received:**
postgres_passwd-${DEPOY_VERSION:-default} Additional property postgres_passwd-${DEPOY_VERSION:-default}   is not allowed

**Describe the results you expected:**
deployment is successful 

**Additional information you deem important (e.g. issue happens only occasionally):**
```
--- docker-compose.yml ---
version: '3.1'
services:
  postgres:
    image: "postgres:10"
    environment:
       POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd-${DEPOY_VERSION:-default}
    secrets:
      - postgres_passwd-${DEPOY_VERSION:-default}
secrets:
  postgres_passwd-${DEPOY_VERSION:-default}:
    external: true

```
**Output of `docker version`:**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker swarm

**Comment by drnybble** [comment]
Is there a reason why variable substitution can't occur before .yml parsing? There are numerous annoying places where you can't do environment variable substitution; for instance you can't use variables to specify # of replicas.

**Comment by rgardam** [comment]
This also affects configs. 
Same thing. 

This completely breaks rotating both secrets and configurations in any sensible way

**Comment by Mobe91** [comment]
This would be really important as it would allow the reuse of a docker-compose.yml in multiple environments for deploying swarm stacks. E.g. one could have a `STAGE` environment variable and define the secrets as follows:
```yml
secrets:
  service1.${STAGE}.secret:
    external: true
```

**Comment by alexanderkjeldaas** [comment]
The exact same reasoning applies to config files. 

Since config files cannot be updated for a service, the only reasonable approach, and also the documented approach, is to version them.

Without interpolation in the name, that's out of the window in the docker-compose format.

**Comment by drnybble** [comment]
I ended up using bash to perform the interpolation, then you can substitute environment variables anywhere.

**Comment by alexanderkjeldaas** [comment]
A workaround is:

```
<source .env and export all required vars>
envsubst "$(env | cut -d= -f1 | while read a; do echo -n '$'$a' '; done)" < docker-compose.yml >tmp-docker-compose.yml
docker stack deploy ...
```

The complex envsubst is to only expand exported variables, and leave `command:` strings which are bash commands inside the docker-compose, alone.
```

**Comment by thaJeztah** [comment]
This is resolved in Docker 17.12 and up (see https://github.com/docker/cli/issues/667 / https://github.com/docker/cli/pull/668 (secrets and configs), https://github.com/docker/cli/issues/274 / https://github.com/docker/cli/pull/306 (volumes), and https://github.com/docker/cli/pull/711 (networks);

This allow you to do something like (be sure to select the right `version` for the compose-file format (think it's version 3.5 and up):

```yaml
version: "3.5"

secrets:
  my-secret:
    name: my-secret-${VERSION} # name of the Docker Secret with variable interpolation
    file: ./secret.html

configs:
  my-config:
    name: my-config-${VERSION} # same thing for configs
    file: ./default.conf

services:
  web:
    image: nginx:1.13.6-alpine
    ports:
      - "80:80"
    secrets:
      - source: my-secret # reference by the name of the key, consistent with how it is for volumes now in 3.4
        target: /usr/share/nginx/html/index.html
    configs:
      - source: my-config
        target: /etc/nginx/conf.d/default.conf

```

Closing this issue,  because this should be resolved, but feel free to comment if I mis-interpreted
