### ISSUE TITLE
what is "swarm_test1 Additional property swarm_test1 is not allowed"

### ISSUE THREAD

**Issue by zwchen1981** [moby/moby#35233]
```yaml
version: '3'
services:
  tomcat:
    image: tomcat
    volumes:
      - /opt/files/web.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
      - /opt/files/server.xml:/usr/local/tomcat/conf/server.xml
      - /opt/files/test.jsp:/usr/local/tomcat/webapps/ROOT/test.jsp
    ports:
      - 8080:8080
    networks:
      - swarm_test1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mycentos:
    image: mycentos
    ports:
      - 8000:8000
    networks:
      - swarm_test1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - tomcat
    command: python app.py
    hostname: mycentos1
  networks:
    swarm_test1:
      driver: overlay
      attachable: true
```
run this command:
docker stack deploy -c tomcat2.yml newtes

error is :
swarm_test1 Additional property swarm_test1 is not allowed

**Comment by thaJeztah** [comment]
This is because the indentation level for the last `networks:` block is incorrect. The `networks:` block to _define_ networks must be at the same level as `services`. To _use_ a network, a `networks:` list must be nested under a service. 

Your compose-file should look like this;

```yaml
version: '3'
services:
  tomcat:
    image: tomcat
    volumes:
      - /opt/files/web.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
      - /opt/files/server.xml:/usr/local/tomcat/conf/server.xml
      - /opt/files/test.jsp:/usr/local/tomcat/webapps/ROOT/test.jsp
    ports:
      - 8080:8080
    networks:
      - swarm_test1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mycentos:
    image: mycentos
    ports:
      - 8000:8000
    networks:
      - swarm_test1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - tomcat
    command: python app.py
    hostname: mycentos1
networks:
  swarm_test1:
    driver: overlay
    attachable: true
```

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍
