### ISSUE TITLE
Multiple Stacks in Swarm Throws 'HNS Failed with error: The parameter is incorrect'

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#35272]
**Description**
When running two stacks that create services on the same hosts in the swarm, the second stack's services throw this error:
`HNS failed with error : The parameter is incorrect`

The stack files are virtually identical, and have no reference to networking, which causes the stack to create a `[stack]_default` network with the overlay driver, but all of the services in the stack throw the error.

**Steps to reproduce the issue:**
1. deploy stack1
2. deploy stack2
3. check a service in stack2 with `docker service ps [service] --no-trunc`

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:01:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-3
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   915cbaa
 Built:        Thu Sep 21 23:10:04 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: rhqqftwn1zar823f8wzy7olvq
 Is Manager: true
 ClusterID: 9mox3tvpue2pjxjjtw3tclwiq
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.1.230
 Manager Addresses:
  10.0.1.230:2377
  10.0.3.157:2377
  10.0.3.169:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-1700)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4GiB
Name: GPSDAZ-IB
ID: Z2CZ:S4X7:UK55:STYT:INYK:MQID:DIHM:WY7Y:M7X3:6FBB:GC36:F3YW
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 regserver:5000
 127.0.0.0/8
Live Restore Enabled: false
```

If you need to see the stack files, I can pastebin them. They include a lot of services, so I didn't want to put them in the initial post.

**Comment by thaJeztah** [comment]
ping @friism @johnstep PTAL

**Comment by friism** [comment]
@Vacant0mens does this reproduce also with just a very simple compose-file with few services, or only with your more complicated compose files?

**Comment by Vacant0mens** [comment]
One is about 8-9 services. The other is only 5 or so. the shorter one is the one with the problem, but they're generated exactly the same way, and they have the same services running the same environment variable sets with only slight variations.

**Comment by friism** [comment]
@Vacant0mens can you reproduce the problem with a set of simple compose files that you can share with us?

**Comment by Vacant0mens** [comment]
I'll try it out.

**Comment by Vacant0mens** [comment]
This stack is having the same problem:
```
version: '3.3'
services:
  auditloggerservice:
    image: regserver:5000/gpsauditlogger/service:1.2017.1002.1-2
    credential_spec: 
      file: "serviceuser.json"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.servertype==app
  institutionsetupservice:
    image: regserver:5000/gpsinstitutionsetup/service:1.2017.1020.2
    credential_spec: 
      file: "serviceuser.json"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.servertype==app
```
