### ISSUE TITLE
Docker stack deploy doesn't work when using awslog driver tags

### ISSUE THREAD

**Issue by rgardam** [moby/moby#35292]
**Description**

Docker stack deploy doesn't work when using awslog driver tags.

This is a supported feature of the AWS log driver
https://docs.docker.com/engine/admin/logging/awslogs/#tag

Tag is overwritten if `awslogs-stream` is present in the yaml

**Steps to reproduce the issue:**
1. Use The AWS logdriver in your docker-compose.yml file
2. Use Tags instead of the aws-logs

**Describe the results you received:**
docker stack deploy --compose-file ./docker-compose.yml blah-deployment
yaml: line 10: did not find expected key

**Describe the results you expected:**
Successful deployment. 

**Output of `docker version`:**
```
14:10 $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker-compose.yml
```
version: '3.2'
services:
  bar:
    image: imagefoo
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: blah
        awslogs-create-group: 1       
        tag: "{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}"
```
