### ISSUE TITLE
solution for large port range in docker stack deploy  ?

### ISSUE THREAD

**Issue by mahald** [moby/moby#35321]
I want to deploy a container with a big udp port range inside a v3 yml file.

```
  my-server:
    image: myreg/some/server
    ports:
      - "60000-62000:60000-62000/udp"
```

this range maybe even too small and should get bigger for production.

This fails due to a timeout.
im aware of this "docker-big-port-range-problem" for docker (not swarm) there i used `--net=host` for services meanwhile it's possible to add `--network=host`.

As the server must be able to access the internal network of the stack deploy i really want to deploy it with stack deploy. Is there any solution for a docker stack with such large port ranges ?

**Comment by thaJeztah** [comment]
You can use host-networking with services as well

**Comment by mahald** [comment]
but not in in yml v3 files, thats the problem

**Comment by thaJeztah** [comment]
That's supported now (I think since Docker 17.06.1) through https://github.com/moby/moby/pull/32981;


```yaml
version: '3.3'

services:
  web:
    image: "nginx:alpine"
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"
```

**Comment by mahald** [comment]
ok, thanks a lot.

is it right that it isn't possible to access the internal network then anymore (as it is using host networking) ?

tried things such as (default or also a userdefined name and defined it in `networks`):
```
  myserver:
    image: xxxx/yyyy/zzzz
    networks:
      - outside
      - default
```
but the container isn't starting anymore then. with: `container cannot be disconnected from host network or connected to host network`

so i will need to expose the ports the container `myserver` needs access to, using `ports:`  and then access it via 127.0.0.1 or the external ip.

at least this way it's possible to add it to a yml file with some quirks and security issues.

there isn't a bettter way for big port ranges, right ?
