### ISSUE TITLE
docker stack and service dsn aliases

### ISSUE THREAD

**Issue by mathroc** [moby/moby#35450]
when you deploy a stack, other services can be reached with their service name

however if 2 services from different stacks have the same name, a 3rd service that have a network in common with both of them will not be able to distinguish between both services, eg:

```yml
# docker-compose-stack-1.yml
version: "3"
services:
  web:
    image: nginx
    networks:
      - default
      - proxy
    depends_on: app
  app:
    image: php:7-alpine-fpm
```

```yml
# docker-compose-stack-2.yml
version: "3"
services:
  app:
    image: some-app
    networks:
      - proxy
```

if both stack are deployed, the `web` service from `stack1` wants to access the `app` from its stack (eg: `proxy_pass http://app;`) but then `app` could also be the app from `stack2` as it’s also on the `proxy` network. 

Is there a DNS alias for same stack services only ? eg : `service.stack`
Or is that something that would be considered to be added ?
