### ISSUE TITLE
Can't trigger an automatic roll back after a service update

### ISSUE THREAD

**Issue by De1taE1even** [moby/moby#35498]
**Description**
Now that the update-failure-action supports 'rollback', I'm trying to incorporate it into our services.  For testing purposes, I'm trying to trigger an automatic rollback, to get an idea of the flow.  No matter what I try, I can't get docker to roll my service back.

I apologize in advance for how light my info is below, but our swarm runs on an air-gapped offline network, so it is not easy to copy/paste docker command outputs here.

**Steps to reproduce the issue:**
1.  `docker stack deploy -c metricsStack.yml metricsStack`
2.  verify the service is running successfully
3.  perform a `docker service update` command that causes the service to fail
4.  the service fails, but is not rolled back

**Describe the results you received:**
The service fails, as expected, but is not rolled back

**Describe the results you expected:**
Once the service update causes a a service to Fail, I would expect docker to roll back the service to the previous config

**My compose file:**
```
version: '3.4'

networks:
  myOverlay:
    external: true

services:
  metrics:
    image: our-offline-repo/metrics/metrics
    healthcheck:
      test: ["CMD", "/bin/sh","-l","-c","/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 3
    user: johndoe
    networks:
      - myOverlay
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
        failure_action: rollback
```

**Output of `docker version`:**

```
Client:
  Version: 17.09.0-ce
  API version: 1.32
  Go version: go1.8.3
  Git commit: afdb6d4
  Built: Tue Sep 26 22:41:23 2017
  OS/Arch: linux/amd64

Server:
  Version: 17.09.0-ce
  API version: 1.32 (minimum version 1.12)
  Go version: go1.8.3
  Git commit: afdb6d4
  Built: Tue Sep 26 22:41:23 2017
  OS/Arch: linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
I'm not going to hand-type all the docker info.  Hopefully we can resolve without it.
```
