### ISSUE TITLE
Feature request: combined global scale mode in swarm

### ISSUE THREAD

**Issue by segler-alex** [moby/moby#35550]
i have proposal: a combination of global mode with scaling applied.
this would mean, that in your docker-compose file you could do something like:

```
web:
   image: nginx
   deploy:
      replicas: 3
      mode: global
```

this would automatically ensure 3 running containers on each added host.
so the total number of containers will grow if the number of machines grows.
and it will decrease if the total number of machines decrease.
this would greatly help on doing some kind of scaling a service.
