### ISSUE TITLE
ONBUILD in wrong folder with compose file

### ISSUE THREAD

**Issue by luckydonald** [moby/moby#35565]
**Description**

**Steps to reproduce the issue:**

`docker-compose.yml`:
```yml
services:
  bot:
    image: luckydonald/telegram-bot:python3.6-stretch-onbuild
    build:
      context: ./stuff/
```
**Describe the results you received:**
```
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

But when removing the build context, the `ONBUILD` trigger go off in the wrong directory

`docker-compose.yml`:
```yml
services:
  bot:
    image: luckydonald/telegram-bot:python3.6-stretch-onbuild
```

**Describe the results you expected:**

Same result as 

`docker-compose.yml`:
```yml
services:
  bot:
    build: ./stuff/
```

`stuff/Dockerfile`:
```Dockerfile
FROM luckydonald/telegram-bot:python3.6-stretch-onbuild
```

- the `ONBUILD` trigger should be executed inside the `stuff/` folder
    - I know, a creative folder name
-  instead it get's executed in the same directory as the compose file

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:19 2017
 OS/Arch:      linux/amd64
```

`docker-compose.yml` format 2.0

**Additional environment details (AWS, VirtualBox, physical, etc.):**
generic
