### ISSUE TITLE
Replica Specific Docker Stack/Compose Configuration

### ISSUE THREAD

**Issue by RehanSaeed** [moby/moby#35784]
I'm trying to run a RabbitMQ cluster using a Docker stack/compose file. Unfortunately, this means I can't use the `replicas` function to scale the number of containers up or down, I have to use multiple services like so:

```
    version: '3.3'
    
    services: 
      rabbit_node_1:
        image: rabbitmq:3.7.0-management-alpine
        environment:
          - RABBITMQ_ERLANG_COOKIE=foo
        hostname: rabbit_node_1
        ports:
          - "15672:15672"
          - "5672:5672"
        networks:
          - myoverlay
        tty: true
    
      rabbit_node_2:
        image: rabbitmq:3.7.0-management-alpine
        environment:
          - RABBITMQ_ERLANG_COOKIE=foo
        hostname: rabbit_node_2
        depends_on:
          - rabbit_node_1
        ports:
          - "15673:15672"
          - "5673:5672"
        networks:
          - myoverlay
        tty: true
```

The only difference between the services is the `hostname` and I am supplying a custom configuration file like so:

```
    [ { rabbit, [ 
      {cluster_nodes, {['rabbit@rabbit_node_1', 'rabbit@rabbit_node_2'], disc}}, 
      { loopback_users, [ ] } ] } 
    ].
```

Is there some way to collapse these two separate Docker services down to a single `rabbitmq` service and somehow use the replica number to drive the differences in each instance? Something like this (See `${replica_ip_address}` and `${replica_number}`):

    version: '3.3'
    
    services: 
      rabbitmq:
        image: rabbitmq:3.7.0-management-alpine
        environment:
          - RABBITMQ_ERLANG_COOKIE=foo
          - REPLICA_IP_ADDRESS=${replica_ip_address}
        hostname: rabbit_node_${replica_number}
        ports:
          - "15672:15672"
          - "5672:5672"
        networks:
          - myoverlay
        tty: true
