### ISSUE TITLE
Shared volume access not propagated to container intended to provide the filesystem

### ISSUE THREAD

**Issue by OJFord** [moby/moby#35816]
I'm trying to setup some dockerised NAS, with mergerfs and samba:

```yaml
services:

  mergerfs:
    build: ./mergerfs  # just debian and install latest release
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - media:/mnt/pool
      - /mnt/data0:/mnt/data0
      ...
   ...

  samba:
    image: dperson/samba
    command: ﻿﻿-s'media;/srv/media;yes;no;yes'  # guest allowed, not RO
    ﻿﻿volumes:
      - media:/srv/media
    depends_on:
      - mergerfs
    ...

volumes:
  media:
```

**Describe the results you received:**

The problem is that, while I can read/write to `/srv/media` on `samba`, it doesn't get through to `/mnt/pool` on `mergerfs`.

(I can see this by watching `docker-compose logs mergerfs` while doing `docker-compose exec samba sh -c "echo 'foobar' > /srv/media/test.txt"` which shows nothing in logs, versus the equivalent `exec mergerfs` which does.)

If I change the named volume `media` for a path on the host machine I get the same affect: writes to `samba` make it to the host mount, can be read back, but are not propagated to `/mnt/pool` in `mergerfs`.

It seems as if when I run `/usr/bin/merger/fs ... /mnt/pool` it's actually shadowing the mount, and completely disengaged from it.

In  summary:
  - Writing to samba writes through to the host mount (that should be the pool mount)
  - Writing to mergerfs pool writes to the host physical disk mounts, but not the pool mount on host

**Describe the results you expected:**

Reading and writing `media` named volume or another bind to host system access the `fuse.mergerfs` file system it's bound to in the `mergerfs` service.

**Output of `docker version`:**
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec  70 10:15:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec  70 10:15:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 102
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.472GiB
Name: musa
ID: XFOT:WUHZ:NJAS:PFCA:QET2:5OEU:QEJM:OZ6Y:F52O:PU7Y:WEUP:CJLI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical.
