### ISSUE TITLE
container not exporting ports missing from network

### ISSUE THREAD

**Issue by ctaggart** [moby/moby#35864]
**Description**

I have a simple compose file that creates a cluster with 1 server and 1 client. The server exposes a set of ports that the client connects to. I also have a desktop app locally (another client) that needs to connect to those ports.

Workaround:
The workaround I found was to say that the client exposes ports even though it doesn't:

``` yml
version: "3.4"
services:

  servers:
    image: 12345.dkr.ecr.us-west-1.amazonaws.com/matchserver:master
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "8888-8920:8888-8920"

  clients:
    image: 12345.dkr.ecr.us-west-1.amazonaws.com/clienttest:master
    command: --address servers test
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - "servers"
    ports:
      - "9000"
```

The problem is that without `ports: - "9000"`, the containers are not in the network as seen with `docker network inspect 1server1client_default` and the dockererized clients can't talk to the server. If neither service exports ports, it works fine. The problem is only when one does and the other does not.

**Output of `docker version`:**

```
Docker version 17.09.1-ce, build 19e2cf6
```

**Output of `docker info`:**

``` yml
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 213bsmdhw65dl76pugk1lmejy
 Is Manager: true
 ClusterID: qenpb148nujn8nfgg8cfumqza
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: EY33:7C5J:EE64:R22P:52KI:HMDS:IUDC:JRTO:MT3Z:5ATV:F5HI:WOCK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 84
 Goroutines: 178
 System Time: 2017-12-23T22:14:34.645633Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running Docker for Windows.

**Comment by thaJeztah** [comment]
Are you deploying the stack with `docker stack deploy` or with `docker-compose`? How is the client connecting to the servers? Using the service-name? Through the published port?

Can you reproduce the issue with standard images (e.g., just a standard `nginx` service)?

**Comment by ctaggart** [comment]
@thaJeztah, I'm using `docker stack deploy`. Here is how to reproduce it with this `docker-compose.moby35864`:
``` yml
version: "3.4"
services:

  servers:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "80:80"

  clients:
    image: alpine:3.5
    command: wget http://servers:80/index.html
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - "servers"
    # ports:
    #   - "9000"
```

I run these commands:
```
docker stack deploy -c docker-compose.moby35864.yml moby35864
docker service logs moby35864_clients
docker network inspect moby35864_default
docker stack rm moby35864
```

When port 9000 is commented out as above, I get:
```
docker service logs moby35864_clients
moby35864_clients.1.79d9o311cuse@moby    | wget: bad address 'servers:80'
```

If port 9000 is enabled on the client, I get:
```
docker service logs moby35864_clients
moby35864_clients.1.3hd667roa9ny@moby    | Connecting to servers:80 (10.0.0.2:80)
moby35864_clients.1.3hd667roa9ny@moby    | index.html           100% |*******************************|   612   0:00:00 ETA
moby35864_clients.1.3hd667roa9ny@moby    |
```
