### ISSUE TITLE
Docker swarm-scope macvlan problems on docker reload

### ISSUE THREAD

**Issue by denefoster** [moby/moby#35876]
**Description**

When in a Docker swarm with swarm scoped macvlan networks, a stack fails to initialise upon docker reload

**Steps to reproduce the issue:**
1. Setup a docker swarm, on each host create a config network as placeholder for swarm scoped macvlan overlay

Host 1
```
docker network create --config-only --subnet 10.140.0.0/20 --gateway 10.140.0.1 -o parent=ens161.140 --ip-range 10.140.0.0/24 whois_backend_local
```

Host 2
```
docker network create --config-only --subnet 10.140.0.0/20 --gateway 10.140.0.1 -o parent=ens224.140 --ip-range 10.140.1.0/24 whois_backend_local
```

On a swarm manager, create the overlay
```
docker network create -d macvlan --attachable --scope swarm --config-from whois_backend_local whois_backend_swarm
```
2. Deploy a stack using the overlay
```
cat docker-compose.yml
version: "3.4"
services:
  whois:
    image: whois-db
    deploy:
      placement:
        constraints:
          - "node.role == worker"
        preferences:
          - spread: "node.labels.dc"
      replicas: 9
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - /stor/containers/whoisd/asn_list.map:/acls/asn_list.map
      - /stor/containers/whoisd/country_list.map:/acls/country_list.map
    ports:
      - 1043
    environment:
      - "SERVICE_TAGS=whois-service"
      - "SERVICE_NAME=whois"
      - "SERVICE_1043_NETWORK=whois_backend_swarm"
    networks:
      - whois_backend_swarm
networks:
  whois_backend_swarm:
    external:
      name: whois_backend_swarm
```
3. Restart docker on a node
```
service docker reload
```

**Describe the results you received:**

```
Dec 26 11:06:56 legion dockerd[2720]: time="2017-12-26T11:06:56.701340309+13:00" level=error msg="Error handling plugin refcount operation" driver= error="plugin \"\" not found" mode=1
Dec 26 11:06:56 legion dockerd[2720]: time="2017-12-26T11:06:56.732899404+13:00" level=warning msg="Unable to locate plugin: , retrying in 1s"
Dec 26 11:06:57 legion dockerd[2720]: time="2017-12-26T11:06:57.733192248+13:00" level=warning msg="Unable to locate plugin: , retrying in 2s"
Dec 26 11:06:59 legion dockerd[2720]: time="2017-12-26T11:06:59.733529962+13:00" level=warning msg="Unable to locate plugin: , retrying in 4s"
```

And the service never comes up on the affected host

**Describe the results you expected:**

The stack to redeploy normally upon docker reload.

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems to be the same as https://github.com/moby/moby/issues/35099 which was closed without comment.

The sure-fire fix is to delete the stack, delete /var/lib/docker/network/files/local-kv.db on the affected node, recreate the config only network, and redeploy the stack. 

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce-rc4
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	6a2c058
 Built:	Wed Dec 20 15:58:21 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce-rc4
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	6a2c058
  Built:	Wed Dec 20 15:56:55 2017
  OS/Arch:	linux/amd64
  Experimental:	true```

**Output of `docker info`:**

```
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 13
Server Version: 17.12.0-ce-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: vn20ge15x4wi36973pn7nkvdp
 Is Manager: true
 ClusterID: mi7qu4jkfxivybqp4phd8uv5r
 Managers: 3
 Nodes: 10
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.251
 Manager Addresses:
  192.168.1.220:2377
  192.168.1.230:2377
  192.168.1.251:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67GiB
Name: legion
ID: DZQX:TT4I:GSXU:KWJG:SPUO:FXEN:M5XJ:OGKW:GGX7:I6FD:SDG6:KXMY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
