### ISSUE TITLE
How can I publush port just by docker-compose.yml  (swarm)?

### ISSUE THREAD

**Issue by eromoe** [moby/moby#36143]
Hello,

I found it would not automatically publish ports which defined in docker-compose.yml

For example:
```
version: '3'
services:
  mongo:
    image: ${PRIVATE_REGISTRY}/${MONGO_IMAGE}
    restart: always
    ports:
      - 11081:27017

  postgres:
    image: ${PRIVATE_REGISTRY}/${POSTGRES_IMAGE}
    restart: always
    container_name: basin-postgres
    environment:
      POSTGRES_USER: basin
      POSTGRES_PASSWORD: basin_pa44
      POSTGRES_DB: demo
    ports:
      - 11085:5432
```

From
https://stackoverflow.com/questions/38141739/docker-deploy-wont-publish-port-in-swarm

I saw `docker service update my-service --publish-add 80:80`

But I wonder how can I set the publish port by `docker-compose.yml` ? 

I google it but found nothing. If there is a document about this, please provide it and the example in the swarm section  https://docs.docker.com/engine/swarm/services/
