### ISSUE TITLE
Docker container restart flag ignored

### ISSUE THREAD

**Issue by FrenchBen** [moby/moby#36189]
**Description**

Docker run contains a `--restart` flag policy, which is as follow:
https://docs.docker.com/engine/reference/run/#restart-policies-restart
The `always` value is described as:
```
Always restart the container regardless of the exit status. When you specify always, the Docker daemon will try to restart the container indefinitely. The container will also always start on daemon startup, regardless of the current state of the container.
```
Doing so with Docker 17.12 doesn't seem to work anymore

**Steps to reproduce the issue:**
1. Start a container with the `--restart=always` policy 
```bash
$ docker run --name=ngin --restart=always -d -P nginx
```
2. Observe the container was started successfully:
```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
c94d57016837        nginx               "nginx -g 'daemon of…"   2 minutes ago       Up 2 minutes        0.0.0.0:32768->80/tcp   ngin
```
3. Restart your instance/dockerd and observe that the container doesn't come up:
```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$
```

**Describe the results you received:**
The container wasn't started after a `dockerd` restart

**Describe the results you expected:**
The container to be started on daemon start.

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to be related to the binary shipped in Docker for Mac, Docker for AWS, Docker for Azure

**Output of `docker version` from Broken LinuxKit:**
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:03 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:30 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker version` from Working Ubuntu on ec2:**
```
Client:
 Version:	1.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:11:05 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:09:37 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

/cc @justincormack @rn

**Comment by cpuguy83** [comment]
Can you share the daemon logs for this occurrence?

**Comment by FrenchBen** [comment]
@cpuguy83 with this being reproducible on Docker for Mac, do you need more logs?

**Comment by cpuguy83** [comment]
It's hard to tell as I have 18.02 which has a different bug here (fixed on master).

After restart:
```
➜  ~ docker start ngin
Error response from daemon: container "3e12e30024601d063a55793e8e35d36f6cbbaa7bc20dbdd837ad22c9e4b7677d": already exists
Error: failed to start containers: ngin
```

**Comment by cpuguy83** [comment]
I can reset to stable if needed, but if your able to get the logs it'd be super helpful.

**Comment by boynux** [comment]
I can't reproduce that in Mac, is there any specific configuration needed?

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: false
```
after daemon quit and start starting again:

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS                   NAMES
d2bedae9c513        nginx               "nginx -g 'daemon of…"   About a minute ago   Up About a minute               0.0.0.0:32768->80/tcp   ngin
```

**Comment by FrenchBen** [comment]
@boynux thanks for checking, looks like it may have been fixed/patched in recent releases.
I've been on the edge branch, which may have shown a different behavior. Confirmed to be working on `18.03.0-ce-rc1`

**Comment by cpuguy83** [comment]
Awesome!
@FrenchBen Should we close?

**Comment by FrenchBen** [comment]
Closing for now

**Comment by dperetti** [comment]
Hmm just happened to me again on Moby Linux 18.03.1-ce-aws1 stable.

**Comment by ericblade** [comment]
... i've had this happening for about 2 years now, some always restart, some only restart when commanded.

**Comment by boynux** [comment]
@ericblade can you provide more details about your setup and configuration, I want to reproduce that if possible and hopefully finding the issue

**Comment by ericblade** [comment]
Sure, i'll provide what I can

Presently running Docker Desktop for Windows 2.0.0.3, Engine 18.09.2, Compose 1.23.2

My docker-compose looks like:

````
version: '3'
services:
  mail:
    restart: always
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: randomstreasures.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "110:110"
      - "995:995"
      - "4190:4190"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mail/config:/tmp/docker-mailserver/
      - ./mail/config/sasl_passwd:/etc/postfix/sasl_passwd
      - ./mail/config/sasl_passwd.db:/etc/postfix/sasl_passwd.db
      - ./mail/config/eric.dovecot.sieve:/var/mail/randomstreasures.com/eric/.dovecot.sieve
      - ./data/certbot/conf:/etc/letsencrypt
    environment:
      - HOSTNAME=mail
      - DOMAINNAME=randomstreasures.com
      - CONTAINER_NAME=mail
      - DMS_DEBUG=1
      - SPOOF_PROTECTION=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_POP3=1
      - ENABLE_MANAGESIEVE=1
      - POSTMASTER_ADDRESS=eric@randomstreasures.com
      - SSL_TYPE=letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  mysql4:
    build: mysql4/mysql4
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lotddb

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx/conf.d:/etc/nginx/conf.d
      - z:\www:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    environment:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  nodered:
   image: nodered/node-red-docker:latest
   restart: always
   user: root
   volumes:
     - ./node-red/data:/data
   ports:
     - "1880:1880"

  mariadb:
    restart: always
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'z:\docker\phpbb\mariadb:/bitnami'
    networks:
      - phpbb

networks:
  phpbb:

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  jenkins_home:
    driver: local
````

mariadb, certbot, and mysql4 services always restart (despite certbot not actually having an always restart command), mail and nginx services only restart when explicitly ordered to with docker-compose up
