### ISSUE TITLE
Can not resolve a service on swarm overlay network.

### ISSUE THREAD

**Issue by eromoe** [moby/moby#36244]
I have below compose file

```
version: '3.2'
services:
  postgres:
    image: ${PRIVATE_REGISTRY}/basin/postgres:10.1
    networks:
      - default
      - proxy
    environment:
      POSTGRES_USER: basin
      POSTGRES_PASSWORD: basin_pa44
      POSTGRES_DB: demo
    ports:
      - 11085:5432

  demo:
    image: ${PRIVATE_REGISTRY}/bidspy/demo:0.1
    networks:
      - default
      - proxy
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://basin:basin_pa44@postgres:5432/demo
      - SECRET_KEY=12345
      - SPIDER_API_URL=basin-spider:5001
      - PROCESSOR_URL=extractor:12000
      - SCHEDULER_URL=scheduler:7000
      - DB_API_URL=repository:6000
      - TEST_MODE=0
      # - DJANGO_SETTINGS_MODULE=demo.settings.production
    deploy:
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=demo.basin.com
        - com.df.port=8000

networks:
  proxy:
    driver: overlay

  default:
    driver: overlay
```

demo is a django application.  It shows
```
could not translate host name "postgres" to address: Name does not resolve
```

I use  enviroment variable `DATABASE_URL=postgres://basin:basin_pa44@postgres:5432/demo` to set database connection string. 

At first, I think it is because `demo` started before `postgres`
I tried `docker service update --force bidspy_demo` to restart `demo`, same error. So I think it is a docker swarm network issue.
