### ISSUE TITLE
service in global mode running multiple times on same machine

### ISSUE THREAD

**Issue by oppianmatt** [moby/moby#36380]
I have a service that is set as global in the swarm. But I find that it sometimes runs multiple instances.

**Steps to reproduce the issue:**

In my docker-compose.yaml I have the following service:

```
  # varnish logger, runs on every host varnish runs on
  varnishncsa:
    image: registry.gitlab.pitchup.com/pitchup/varnishplus/master:90b98cf3-20180221-4798
    command: "/usr/bin/varnishncsa -n varnish1 -a -w /var/log/varnish/varnishncsa.log -f /etc/varnish/varnishncsa.format -b -c"
    environment:
      VARNISH_LOG_FORMAT_CHECKSUM: "ae40312a6fe35a0c3ec22bf04660383c807c1d7b"
    volumes:
        - 'varnishlib_tmpfs_vol:/var/lib/varnish'
        - '/var/log/varnish:/var/log/varnish'
        # TODO: bake the format into the docker image
        - '/etc/varnish/varnishncsa.format:/etc/varnish/varnishncsa.format'
        - /etc/group:/etc/group:ro
        - /etc/passwd:/etc/passwd:ro
    labels:
      - "logspout.exclude=true"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.varnish == true"
```

But other services are like that and aren't running multiple times, and so don't know how to reproduce it exactly. But this service consistently runs multiples. 

**Describe the results you received:**

Occasionally the service will be running multiple times. Output from docker ps showing:

```
Every 2.0s: docker ps --format table {{.Names}}\t{{.Status}}\t{{.Image}}                                                                                                                                                          Thu Feb 22 15:43:34 2018

NAMES                                                                       STATUS                  IMAGE
pitchup_celery_hotel_ads.3.yz4gqdp6gp1lv1kvhq3d812mj                        Up 11 hours             registry.gitlab.pitchup.com/pitchup/pitchup.com/master:c1d6738b-20180221-4830
pitchup_static.2.jz4rtf2umn391ob6o76ty52fq                                  Up 11 hours (healthy)   registry.gitlab.pitchup.com/pitchup/pitchup.com/master:c1d6738b-20180221-4830
pitchup_celery_paypal.2.1x694m61ii59k9mhnxwgi8fml                           Up 11 hours             registry.gitlab.pitchup.com/pitchup/pitchup.com/master:c1d6738b-20180221-4830
pitchup_varnishncsa.1dyo3dy20rfrhu4c2v6a9z3p2.9njwxnr531cxbls0k1bwuwgqj     Up 14 hours             registry.gitlab.pitchup.com/pitchup/varnishplus/master:90b98cf3-20180221-4798
pitchup_varnish_agent.1dyo3dy20rfrhu4c2v6a9z3p2.e9855kroh5jz3n09pvorch4s0   Up 21 hours             registry.gitlab.pitchup.com/pitchup/varnishplus/master:90b98cf3-20180221-4798
pitchup_vstatdprobe.1dyo3dy20rfrhu4c2v6a9z3p2.aeg6141lqx0vpbpd61apuafpe     Up 21 hours             registry.gitlab.pitchup.com/pitchup/varnishplus/master:90b98cf3-20180221-4798
pitchup_varnishncsa.1dyo3dy20rfrhu4c2v6a9z3p2.is7q3yb9ofvxs0ql9k7uik9py     Up 14 hours             registry.gitlab.pitchup.com/pitchup/varnishplus/master:90b98cf3-20180221-4798
```

**Describe the results you expected:**

I expect only one of the services running.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens really only for that service. Happens more often then not.

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 45
 Running: 37
 Paused: 0
 Stopped: 8
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 1dyo3dy20rfrhu4c2v6a9z3p2
 Is Manager: false
 Node Address: 213.138.116.237
 Manager Addresses:
  213.138.116.235:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.8GiB
Name: pu-frontend2.pitchup.com
ID: T3MJ:7HUM:M74V:AKLX:WRSK:JGB7:XU2T:VW35:CN4A:CI4Q:JN65:KEST
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box running ubuntu 16.04 part of a swarm cluster with 5 nodes.
