### ISSUE TITLE
More verbosity for "invalid reference format" message

### ISSUE THREAD

**Issue by synergiator** [moby/moby#36545]
On using a complex stack YAML (500+ lines) and environment variables e.g.

```
..
    zookeeper:
      image: ${IMAGE_ZOOKEEPER}
..
```
it can happen that a glitch in the YAML causes the message "invalid reference format", and this is very hard to debug. If possible, more reference to the error is required. We use yamllint to recognize indentation errors but this does not help.

Docker version 17.12.0-ce, build c97c6d6

For example:
`image label FOOBAR is not a vaid reference`

Workaround which worked for me: 
- launch stack
- observe launched services
- remove them from stack
- remove stack 
- if needed, repeat until you will see those problematic service definitions left containing invalid references

**Comment by new-guy** [comment]
Yes please!  I just spend 3 days debugging issues related to this `invalid reference format` error.  I was getting that error when trying to `docker stack deploy` with multiple compose files.  Originally, the compose files looked something like this:

backend-min.yml:
```
services:
  api:
    image: 'abcdocker/api:master'
```

hydra-override.yml:
```
services:
  api:
    deploy:
      stuff_about_deploying_to_swarm
```

This didn't work - it gave the the `invalid reference format` error.  I instead had to add the image key/value pair in hydra-override.yml like so:

backend-min.yml:
```
services:
  api:
    image: 'abcdocker/api:master'
```

hydra-override.yml:
```
services:
  api:
    image: 'abcdocker/api:master'
    deploy:
      stuff_about_deploying_to_swarm
```

If there was more detail in the error message, there probably would've been literal days of effort and frustration saved on my end.
