### ISSUE TITLE
Port publishing is broken in 17.12.1 Swarm Mode

### ISSUE THREAD

**Issue by dcharbonnier** [moby/moby#36578]
Brand-new machine setup with docker 17.12.1 the ingress network is not working.

```
~# docker --version
Docker version 17.12.1-ce, build 7390fc6
~# docker swarm init --advertise-addr eth0
Swarm initialized: current node (6zr0dv84kl0mu3cxsmeylrhs3) is now a manager.
To add a worker to this swarm, run the following command:
    docker swarm join --token SWMTKN-1-0x72iw33wq1x0tpyty0csol93qm63nk04lg7upvu7aulbm0rfw-dztx7e3su3kn2p1mqkwe64cem 10.8.62.205:2377
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
~# cd /home/portainer_app/
~# docker stack deploy -c portainer.yml  portainer
Creating network portainer_default
Creating service portainer_app
~# curl http://localhost:9000
^C # after waiting too much
```

The service is running, there is no problem with the service, the same stack work on a different swarm.

The compose file :
```
version: '3.2'
services:
  app:
    image: portainer/portainer:pr1722
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        monitor: 20s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - app:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  app:
    driver: local
```
