### ISSUE TITLE
Can not pull image again if registry mirror down suddenly

### ISSUE THREAD

**Issue by jindov** [moby/moby#36667]
**System information**
`docker version`:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:13 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

`docker exec v2-mirror registry --version`:
```
registry github.com/docker/distribution v2.6.2
```
Setup:

I hosted a registry to use as a proxy mirror for private repo:
`config.yml`:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
  username: myrepo
  password: abc@123
```
and my docker daemon.json
```
{
  "storage-driver": "aufs",
  "experimental" : true,
  "registry-mirrors": [ "http://10.16.1.11:5000" ]
}
```

And problem is:

It's worked perfectly with caching goal but, when I've pulled image from a that mirror, and the registry mirror was down somehow, docker pull will retry several times then got this error `repository myrepo/container_test not found: does not exist or no pull access`. I've tried to pull again but nothing better `docker pull  myrepo/container_test:master
Error response from daemon: repository myrepo/container_test not found: does not exist or no pull access`
Expectation:
When registry-mirror was down, it retry then pull from origin hub.

So, anyone has a best approach to handle it case?
Thanks,
Jin
