### ISSUE TITLE
volume nocopy failed for no local volume

### ISSUE THREAD

**Issue by rosebude** [moby/moby#36721]
nocopy option,  in volume section,  has no effect for external volume driver like vsphere:

First test volume from outside
compose file : ext.yml

```
version: "3.5"
services:
    hello-worldeu_1:
       image: tutum/hello-world
       volumes:
        - type: volume
          source: data_HELLO_EXT
          target: /etc
          volume:
           nocopy: false
       ports: 
         - target: 80
           mode: ingress
       deploy:
        replicas: 1
     
volumes:
  data_HELLO_EXT:
    name: data_HELLO_EXT@datastore
    external: true
```

```
docker volume create -d vsphere --name data_HELLO_EXT
docker stack deploy -c  compose file : ext.yml HELLO_EXT 
```
--> Volume is mounted but errors in application because /etc in the container is empty mapping by the volume.

And the next test volume local:
compose file: local.yml
```
version: "3.5"

services:
    hello-worldeu_1:
       image: tutum/hello-world
       volumes:
        - type: volume
          source: data_HELLO_LOC
          target: /etc
          volume:
           nocopy: false
       ports: 
         - target: 80
           mode: ingress
       deploy:
        replicas: 1
     
volumes:
  data_HELLO_LOC:
   external: true
```

```
docker volume create data_HELLO_LOC
docker stack deploy -c  compose file : local.yml HELLO_LOC 
```
--> Volume is mounted and appli is ok. Files in /etc, from the container are copied in the volume and the volume is mounted on /etc.

Possible  to use nocopy for volumes with no local driver ?

Docker Version: 17.12.0-ce
