### ISSUE TITLE
HTTPS of a NGINX container exposed on docker routing mesh

### ISSUE THREAD

**Issue by sujituk** [moby/moby#36847]
HTTPS of a NGINX container exposed on docker routing mesh

Im having a nginx container which I need to be https enabled. I have the certs (installed as part of image) and port mapping done so traffic on 8443 (HTTPS on routing mesh) should get fwded to my endpoint.

**Steps to reproduce the issue:**
1. Docker-compose
```
version: '3.0'

services:
  web:
    build:
      context: .
    deploy:
      labels:
        com.docker.ucp.access.label: /Shared/newdev
        com.docker.ucp.mesh.http.10002: internal_port=8443,external_route=https://apigateway.suffix.companyname.com:10002/
      mode: replicated
      placement:
        constraints:
        - node.labels.env==localdc
      replicas: 2
    image: apigateway
    networks:
      - ucp-hrm
    ports:
    - 10002:8443/tcp
networks:
  ucp-hrm:
    external: true
```
2. NGINX conf file
```
server {
      # Port at which API Gateway is listening
      listen 10002 ssl;

      ssl on;
      ssl_certificate /usr/local/nginx/ssl/cert.cer;
      ssl_certificate_key /usr/local/nginx/ssl/cert.key;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      server_name         *.suffix.companyname.com;

      # Location handling
      include locations.conf;
  }
```
I get a connection refused when I access https://apigateway.suffix.companyname.com:10002/healthcheck.

Im expecting the connection to go fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 18.03.0-ce, build 0520e24
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
