### ISSUE TITLE
Docker doesn't seem to add necessary iptables rule

### ISSUE THREAD

**Issue by nazar-pc** [moby/moby#36863]
**Description**

I have a physical NIC with a few IPs on it. I want to allow several processed in different containers to accept requests on any port on one of these IPs (like `--network host`, but only for one specific IP).
It is very hard to achieve at the moment and I'm aware of some already opened issues about this.

Currently I've got  following tricky config:
```yml
version: '2.3'
services:
  bootstrap-0:
    ...
    networks:
      external_ip:
        ipv4_address: a.b.c.d
    ...
  bootstrap-1:
    ...
    network_mode: "service:bootstrap-0"
    ...
networks:
  external_ip:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: a.b.c.d/26
          gateway: a.b.c.z
```

I don't like the way it is done, but this is the only way I was able to get this working... almost.

**The problem:**
I also needed `iptables -I DOCKER -d  a.b.c.d -j ACCEPT` and as far as I understand it, Docker had to add this rule automatically.

I've tried `macvlan` in multiple different ways, but I'm not a network engineer and couldn't get it working in any other way.

**Output of `docker version`:**
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 34
 Running: 24
 Paused: 0
 Stopped: 10
Images: 98
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 491
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29GiB
Name: ***
ID: ***
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine.
