### ISSUE TITLE
docker service deploy -c service.yml fails when port published in host mode

### ISSUE THREAD

**Issue by ajardan** [moby/moby#36934]
**Description**

When a service is deployed with ports published in "host" mode, a second deployment to update the service configuration will fail with this error:

Pending 27 minutes ago      "host-mode port already in use on 1 node"

**Steps to reproduce the issue:**
1. Create a service that publishes a port in host mode using a Docker Compose file service.yml
2. Deploy the service using docker deploy -c service.yml
3. Change service configuration in the service.yml
4. Try to deploy it again using docker deploy command

**Describe the results you received:**

The container fails to start with this error:

Pending 27 minutes ago      "host-mode port already in use on 1 node"
**Describe the results you expected:**

Expected the service to be deployed with updated configuration

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
$ docker info
Containers: 283
 Running: 19
 Paused: 0
 Stopped: 264
Images: 3970
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 10wt612mb6oidu4e9cund7k0g
 Is Manager: true
 ClusterID: lbqfpif6v1gowlgutpsuxit3l
 Managers: 7
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: **ip_hidden**
 Manager Addresses:
  **ip_hidden**
  **ip_hidden**
  **ip_hidden**
...
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.22GiB
Name: docker
ID: ZPU5:7UJ6:64G5:V3VH:2CBN:ZSLG:LLLA:CRBG:3AUR:7H2U:VTK5:XK2Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machines used

**Comment by dustinschultz** [comment]
I'm running into this as well. Is there a known workaround for this? Is there some way to "free" the host port ... shy of rebooting?

**Comment by ajardan** [comment]
Well, a solution is to do this in your service configuration:

```
deploy:
  update_config:
    order: stop-first
```

But this also means there's downtime during service deployment. I am also not sure this is fixable in any other way.

**Comment by Bezbran** [comment]
I'm running into this issue too (docker version:  18.05.0-ce, build f150324, running on AWS. 1 master node and 1 slave node, the service runs only on the slave node). 
But my service UpdateConfig configurations is already set to "Order": "stop-first".

**Comment by flybyray** [comment]
> Well, a solution is to do this in your service configuration:
> 
> ```
> deploy:
>   update_config:
>     order: stop-first
> ```
> But this also means there's downtime during service deployment. I am also not sure this is fixable in any other way.

That will not work in every case.
```yaml
---
version: '3.4'
services:
  s1:
    deploy:
      placement:
        constraints:
          - node.labels.onlyhost1==true
      replicas: 1
    image: 'someimage'
    networks:
      frontend:
        aliases:
          - s
    ports:
      -
        protocol: tcp
        published: 443
        target: 8443
        mode: host
  s2:
    deploy:
      placement:
        constraints:
          - node.labels.onlyhost2==true
      replicas: 1
    image: 'someimage'
    networks:
      frontend:
        aliases:
          - s
    ports:
      -
        protocol: tcp
        published: 443
        target: 8443
        mode: host
networks:
  frontend:
    external:
      name: some_frontend
```
