### ISSUE TITLE
Inter container network stops working in an unpredictable manner

### ISSUE THREAD

**Issue by leshik** [moby/moby#37050]
**Description**

The inter container network sometimes stops working in an unpredictable manner. Containers can ping each other but one can't access ports on another. Logs:

```
time="2018-05-13T11:59:55.377698881Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:04:55.377994248Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:09:55.577608613Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:14:55.777681960Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:19:55.977683502Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:24:56.177659635Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:29:56.377940711Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:34:56.577669562Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:39:56.777975698Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:44:56.984469489Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:49:57.177671692Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:54:57.377737236Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
time="2018-05-13T12:59:57.585415492Z" level=info msg="NetworkDB stats ci(6106b8d5a82a) - netID:hxafey4tm5ttib9pythjoui78 leaving:false netPeers:1 entries:2 Queue qLen:0 netMsg/s:0"
```

**Steps to reproduce the issue:**

I'm using pretty simple `docker-compose.yml` for Concourse CI as per https://github.com/concourse/concourse-docker. Not sure but I think the issue starts to appear in either `18.03.0-ce` or `18.03.1-ce` as I've never seen this before.

**Additional information you deem important (e.g. issue happens only occasionally):**

Might be related to #33589. It doesn't matter if the node is in the swarm or standalone mode, however.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 58
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-41-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.502GiB
Name: ci
ID: RYNL:WU74:BJC5:5NA3:RMNN:QALR:D7MH:PBI2:6XVD:YFYH:U4KH:EECZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is VM droplet at Digital Ocean.

**Comment by leshik** [comment]
Nope, got this again with `17.12.1~ce-0~ubuntu`. Any suggestions?

#### Details:

I'm using `Caddy` as a reverse proxy for SSL termination in front of `Concourse CI`. Here is its `Dockerfile`:

```
# stage 1
FROM golang:alpine as builder

RUN apk add --no-cache git

ARG caddy_version="0.10.14"

# caddy base
RUN set -ex; \
    git clone https://github.com/mholt/caddy /go/src/github.com/mholt/caddy; \
    cd /go/src/github.com/mholt/caddy; \
    git checkout tags/"v${caddy_version}" -b "v${caddy_version}"

# build
RUN set -ex; \
    go get github.com/caddyserver/builds; \
    cd /go/src/github.com/mholt/caddy/caddy; \
    CGO_ENABLED=0 go run build.go; \
    mv caddy /go/bin

# stage 2
FROM alpine

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/caddy /usr/local/bin/

ENV CADDYPATH /usr/local/etc/caddy
WORKDIR /srv
EXPOSE 80 443

COPY Caddyfile /srv/

ENTRYPOINT ["caddy"]
```

And here is my `Caddyfile`:

```
{$EXTERNAL_URL} {
  log stdout
  errors stderr
  root /srv/public

  tls

  header / Strict-Transport-Security "max-age=31536000;"

  proxy / {$PROXY_ENDPOINT} {
    websocket
    transparent
  }
}
```

After the `Caddy` container stopped communicating with `Concourse CI`, I restarted it and it helped.

Here is the full `docker-compose.yml` that I use if it matters:

```
version: '3'

services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes: ["/compose/concourse/data:/var/lib/postgresql/data"]

  web:
    image: concourse/concourse
    command: web --vault-url "${VAULT_URL}"
    depends_on: [db]
    ports: ["2222:2222"]
    volumes: ["/compose/concourse/keys/web:/concourse-keys"]
    restart: unless-stopped
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: "${BASIC_AUTH_USERNAME}"
      CONCOURSE_BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
      CONCOURSE_EXTERNAL_URL: "${EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_VAULT_CLIENT_TOKEN: "${VAULT_CLIENT_TOKEN}"
      CONCOURSE_AUTH_DURATION: 720h
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  worker:
    image: concourse/concourse
    privileged: true
    depends_on: [web]
    volumes:
      - /compose/concourse/keys/worker:/concourse-keys
      - /compose/concourse/volumes:/worker-state/volumes
    restart: unless-stopped
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    entrypoint: bash
    command:
      - -ec
      - |
        trap "concourse retire-worker --name `hostname`; exit" SIGTERM
        concourse worker &
        wait

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    command: -agree
    depends_on: [web]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    cap_add: [NET_BIND_SERVICE]
    volumes: ["/compose/caddy:/usr/local/etc/caddy"]
    environment:
      - PROXY_ENDPOINT=web:8080
      - EXTERNAL_URL

  prune:
    build: https://github.com/ahume/delete-stalled-concourse-workers.git
    depends_on: [web]
    command: /app
    restart: unless-stopped
    environment:
      CONCOURSE_USERNAME: "${BASIC_AUTH_USERNAME}"
      CONCOURSE_PASSWORD: "${BASIC_AUTH_PASSWORD}"
      CONCOURSE_URL: http://web:8080
```
