### ISSUE TITLE
Swarm - problem with routing mesh with service of same name in different networks

### ISSUE THREAD

**Issue by julienfastre** [moby/moby#37094]
**Description**

Using docker swarm, when two service have the same name **but** in different networks, the routing to the service randomly redirect to the container with same name, on other network.

**Steps to reproduce the issue:**

1. Create a "front" stack with nginx, redirecting to different services

```yaml
## ./front/docker-compose.yml
services:
  nginx: 
    image: nginx:1
    deploy:
      mode: global
    volumes:
      - /var/swarm/data/front_nginx/etc/nginx/sites:/etc/nginx/conf.d:ro
    ports:
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - front
      - logging_logging

networks:
  front:
    driver: overlay
    driver_opts:
      subnet: 10.0.0.0/24    

  logging_logging:
    external: true
```

Relevant parts for different nginx.conf

The service which will be create in step 2:

```
## /var/swarm/data/front_nginx/etc/nginx/sites/first_service.conf
server {
	listen 443 ssl http2;
	listen [::]:443 ;
	server_name first_service.example.com;


	location / {
	    proxy_pass  http://first_service_nginx:80;
        # ...
	}

}

```

```
## /var/swarm/data/front_nginx/etc/nginx/sites/second_service.conf
server {
	listen 443 ssl http2;
	listen [::]:443 ;
	server_name second_service.example.com;


	location / {
	    proxy_pass  http://second_service_nginx:80;
        # ...
	}

}

```

2. Create a second stack, with a first service and a PHP application

```yaml
## ./second_service/docker-compose.yml
version: '3'

services:
  php: 
    image: path/to/php:stable
    environment:
      # ...
    networks:
      - first_service
      - logging_logging
 
  nginx:
    image: path/to/nginx:stable
    links:
      - php
    networks:
      - first_service
      - front_front
# other stufss


networks:
  front_front:
    external: true

  logging_logging:
    external: true

  second_service:
    driver: overlay
    driver_opts:
      subnet: 10.0.64.0/24

```

Relevant parts for the `first_service_nginx`'s `nginx.conf` file:

```
# ...


http {


upstream phpfcgi {
    server php:9000;
    # server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
}

server {
    listen 80;


    # pass the PHP scripts to FastCGI server from upstream phpfcgi
    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass phpfcgi;
    }
}

}
```

3. Create a third stack with the same php service name:

```yaml
## ./second_service/docker-compose.yml
version: '3'

services:
  php: 
    image: path/to/another/php:stable
    environment:
      # ...
    networks:
      - first_service
      - logging_logging
 
  nginx:
    image: path/to/another/nginx:stable
    links:
      - php
    networks:
      - second_service
      - front_front
# other stufss


networks:
  front_front:
    external: true

  logging_logging:
    external: true

  second_service:
    driver: overlay

```

The nginx config file is the same.

4. starts the service

```bash
docker stack deploy -c second_service/docker-compose.yml --with-registry-auth second_service
docker stack deploy -c first_service/docker-compose.yml --with-registry-auth first_service
docker stack deploy -c front/docker-compose.yml --with-registry-auth front
```

**Describe the results you received:**

Sometimes, the request to first_service.example.com redirects to second_service.example.com.

Replacing the upstream part in nginx.conf in first_service_nginx and second_service_nginx solve the problem:

```
upstream phpfcgi {
    server first_service_php:9000;
    # server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
}
```

```
upstream phpfcgi {
    server second_service_php:9000;
    # server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
}
```

**Describe the results you expected:**

Redirecting request to correct stack.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
uqq2jgimsoi4lej9fhflvs5hg *   node0               Ready               Active              Reachable           18.03.1-ce
jm2ht73sixucs4h1v13laqrua     node1               Ready               Active              Reachable           18.03.1-ce
u83pyapi9tuz06j15d9d9441s     node2               Ready               Active              Reachable           18.03.1-ce
0yyijz6fh3g6fcvkh52l6rwxe     node3               Ready               Active              Leader              18.03.1-ce

```

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Hosted on OVH VPS.

**Comment by bard** [comment]
I had a similar situation. Instead of placing `first_stack_nginx` and `second_stack_nginx` on the `front_front` external network, try placing `front_nginx` on the `first_stack` and the `second_stack` network:

```
## ./front/docker-compose.yml
services:
  nginx: 
    # ...
    networks:
      - front
      - logging_logging
      - first_stack
      - second_stack
```
That solved the problem in my case although it certainly doesn't seem right that a database stack (or frontend stack in your case) would have to be redeployed if a new stack needs to access it.

Clue came from https://forums.docker.com/t/single-db-instance-with-multiple-apps/40106/9 (emphasis mine):

> If instead you’re trying to make this work as a swarm it becomes very easy. As a suggestion says above create an Overlay Network that all three will live on (database, app1 and app2) and attach each of your containers to that overlay network…or **if it’s important that app1 not be able to see app2 but both see the same database then create 2 overlay networks (say net1 and net2) then have the database app connect to BOTH networks but have app1 and app2 only connect to their specific network**.
