### ISSUE TITLE
docker stack deploy will not deploy a compose file with only networks. 

### ISSUE THREAD

**Issue by dnhutchins** [moby/moby#37229]
**Description**

When deploying multiple stacks that depend on shared networks, it would be nice to easily deploy non-service resources from a yml that does not include any service. As an example the following will not deploy the network resources:

networks_no_service.yml
```
version: "3.4"

networks:
  graylog:
    driver: overlay
  portainer:
    driver: overlay
  elastic:
    driver: overlay
  mail:
    driver: overlay
```

My current workaround is to include a scratch service with a replica count of 0 and attached to all the networks:

networks_with_service.yml
```
version: "3.4"
services:
  net-dummy:
    image: scratch
    networks:
      - graylog
      - elastic
      - mail
      - mysql
    deploy:
      replicas: 0

networks:
  graylog:
    driver: overlay
  elastic:
    driver: overlay
  mail:
    driver: overlay
  mysql:
    driver: overlay
```

**Steps to reproduce the issue:**
1. Create networks_no_service.yml and networks_with_service.yml from above.
2. Deploy the first with `docker stack deploy -c networks_no_service.yml net1`
3. Deploy the second with `docker stack deploy -c networks_with_service.yml net2`

**Describe the results you received:**

`docker stack ls`
```NAME                SERVICES
net2                1
```

I expected for the compose without a service to deploy the networks, without needing a service attached to it in the same yml.

**Output of `docker version`:**

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:34 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:43 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

I imagine this is probably true of volumes, or any other non-service resources too. 

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 81
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xdcn8gnbc0jz9yhuo6o4vwmx3
 Is Manager: true
 ClusterID: qcnxhkjmzou2i7952f1xyddgu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.2.15
 Manager Addresses:
  10.0.2.15:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-21-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.762GiB
Name: vagrant
ID: QX7C:UYYP:3ZA6:6MEG:6CER:ZUKF:LI3V:NRP3:3YCY:5UFX:3NKE:WO5T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
