### ISSUE TITLE
Strange behavior at swarm compose with ports mode: host

### ISSUE THREAD

**Issue by FalkNisius** [moby/moby#37254]
**Description**

I have a swarm with some managers and one of them is exposed to the net with an failover ip setted from outside. To expose the services of the swarm i use containers with deploy -> mode: global and ports -> mode: host, because using build in ingress routing, is losing the source ip with SNAT of the ingress router. The source ip of the traffic is needed for logging and fail2ban, to prevent brute force against secured endpoints.

First if I deploy following compose.yml:
```
version: "3.4"

services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == erv-node3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
```
with `docker stack deploy -c test.yml test` I get 
```
Creating network test_default
Creating service test_nginx
```
and `netstat -ltunp | grep 80` gives me `tcp6       0      0 :::80                   :::*                    LISTEN      14649/docker-proxy` like expected, all is fine.

Second, if I define to use the host network, with the follwoing compose.yml:
```
version: "3.4"

services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == erv-node3
    networks:
      - outside
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"

networks:
  outside:
    external:
      name: "host"
```
with `docker stack deploy -c test.yml test` I get 
```
Creating service test_nginx
```
without an own network and `netstat -ltunp | grep 80` gives me `tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16521/nginx: master`, the container is directly bound to host, what is for me much better, because I have not to intercept the DOCKER iptables chain with fail2ban. And I have no extra network (perhaps with the macvlan driver)

Third, yet becomes unexpected. I need a second network for the microservices they would exposed to nginx, with some vhost configurations. Simply `docker network create --driver=overlay --attachable  front` creates a network to connect the microservice stack with the exposing nginx. if I want use following compose.yml:
```
version: "3.4"

services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == erv-node3
    networks:
      - outside
      - front
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"

networks:
  outside:
    external:
      name: "host"
  front:
    external:
      name: front
```
with `docker stack deploy -c test.yml test` I get 
```
Creating service test_nginx
```
But the service never runs, docker says always `"container cannot be disconnected from host network or connected to host network"`in syslog. 

The third stack runs without the "outside" network, and bounds port 80 to the docker-proxy. 

I understand the second example is more or less a trick to prevent creating extra networks and to bypass the docker proxy. 
But should ports -> mode: host not always use the default host bridge without creating an own network like in example one?
Or should it bound the host ports direct to the container, like the second example?
Or can you decide if there more than one network which is used for host port mapping.

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: beegfs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 0pzc83p211sjsbwkyinp5x71y
 Is Manager: true
 ClusterID: ptcs67u7wy9z04m04kksu4cvk
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.135.51.178
 Manager Addresses:
  10.135.51.178:2377
  10.135.56.238:2377
  10.135.76.132:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-121-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: erv-node2
ID: Z527:VCVX:TKXQ:KXBW:IA3N:JB5A:6X7A:SOHF:D62A:UMAF:RNRN:I7YZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- running on Ubuntu 16.04 with kernel 4.4.0-121-generic, in a digital ocean droplet (vm)

**Comment by FalkNisius** [comment]
I think that explained it adequately. I found the publishing with external mode "host", I think at stack overflow, at the search to solve the SNAT problem from ingress routing. Perhaps the special behavior with this network name should be part of the official documentation. It is surprising, and seems to prevent adding other networks to the same service without an usefull error message.
Thanks.

**Comment by socheatsok78** [comment]
I recently ran into an issues where the below stack will result in only 2 published ports for the `target: 80`.

```yml
services:
  nginx:
    image: nginx
    ports:
      - mode: host
        target: 80
        published: 80
        protocol: tcp
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      - mode: host
        target: 80
        published: 8080
        protocol: tcp
```

## Docker Info

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```
