### ISSUE TITLE
Can't use a container as a DNS server to another container

### ISSUE THREAD

**Issue by r3pek** [moby/moby#37258]
**Description**

I'm trying to setup a stack using docker swarm and i need a caching nameserver for that stack (to prevent rate limiting some queries). Since I'm using docker swarm, this should be simple enough and I would just point the "dns" attribute in the docker-compose file to the dns container and get on with it, problem is, this isn't working. The dns container itself has no problems resolving names, but the other one can't resolve anything but internal dns names (container names)

**Steps to reproduce the issue:**
I have this docker-compose.yml file that can easily test what I'm saying:
```
version: "3.3"

services:
    test:
        image: alpine
        deploy:
            replicas: 1
        dns: 
            - unbound
        depends_on: 
            - unbound
        command: ping www.google.pt

    unbound:
        image: secns/unbound
        deploy:
            replicas: 1
        environment:
            - VERBOSITY=3
            - DO_IPV6=no
            - HIDE_IDENTITY=yes
            - HIDE_VERSION=yes
            - STATISTICS_INTERVAL=3600
```

**Describe the results you received:**
the "test" container is always failing

**Describe the results you expected:**
the "test" container shoul be running without any problem

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
$ docker info
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 18.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-8:1-125278-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 8.9GB
 Data Space Total: 107.4GB
 Data Space Available: 68.05GB
 Metadata Space Used: 17.43MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.13GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xxxxxx
 Is Manager: true
 ClusterID: xxxxxxx
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: xxxxxxxxxxxxxxxxx
 Manager Addresses:
  xxxxxxxxxxxxxxxxx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.453GiB
Name: xxxxxxx.xxxxxx.org
ID: 6UZE:5KD7:SGK2:XVGV:55WS:3JEO:ZLI2:AISZ:DSKW:RRJB:WQ2D:IWXZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 159
 Goroutines: 356
 System Time: 2018-06-10T14:00:35.62116062+01:00
 EventsListeners: 13
Registry: https://index.docker.io/v1/
Labels:
 provider=hetzner
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM from Hetzner.
