### ISSUE TITLE
Can't communicate correctly across 2 nodes through overlay network

### ISSUE THREAD

**Issue by devSwoop** [moby/moby#37510]
Hi everyone,

I'm discovering Docker Swarm and I'm struggling to deploy services in an overlay network (and make it work).
I'm using `docker stack deploy -c config.yml studio` with this __simple__ compose file
```yml
version: "3.4"
services:
  redis:
    image: redis
  db:
    image: postgres
networks:
  default:
    attachable: true
    driver: overlay
    internal: false
```
The services are well deployed across my 2 nodes (1 service on each node), but the weird thing starts now.
I run `watch -n 1 docker network inspect studio_default` on the manager to have real-time status of my network, and I noticed that in the `Peers` field, the worker node appears and disappears randomly, so the service deployed on the node is _"randomly available/reachable"_.
Why the node disconnects itself from the network (and reconnects) ?

I can (sometimes) ping from the manager container to the worker one when the node appears in the `Peers`, but I think I can't even ping from the worker to the manager...

What am I doing wrong :frowning: ?
