### ISSUE TITLE
Swarm stack file: order Additional property order is not allowed

### ISSUE THREAD

**Issue by thernstig** [moby/moby#37512]
**Description**
Using the 'order' keyword (nested under deploy: update_config:) does not work on docker version 18.03, even though it should according to https://docs.docker.com/compose/compose-file/#update_config

**Steps to reproduce the issue:**
1. Put this in a stack file called `docker-stack.yml`:
```yml
version: "3"
services:
  splash:
    image: scrapinghub/splash:3.2
    deploy:
      update_config:
        order: start-first
    networks:
      - splashnet
    ports:
      - "8050:8050"
networks:
  splashnet:
```
2. Execute the command:
```
host1:~$ sudo docker stack deploy --with-registry-auth -c docker-stack.yml project1
order Additional property order is not allowed
```

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: l8ttpvgh1zl480uexv5morogf
 Is Manager: true
 ClusterID: j0mzl7svib1ibcnzcoqfiqf8m
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-130-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: hidden
ID: OCM7:P3CI:GCHO:UFES:O7ZM:42QK:PTGK:G2QC:5FOE:KVCX:V4EH:3GVT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
You are using `version: '3'`, which is equivalent to `version: '3.0`, however, that option was added in [version 3.4 of the compose-file format](https://docs.docker.com/compose/compose-file/#update_config);

> Note: order is only supported for v3.4 and higher of the compose file format.

Change your version to 3.4 (or higher), and it should work;

```yaml
version: "3.4"
services:
  splash:
    image: scrapinghub/splash:3.2
    deploy:
      update_config:
        order: start-first
    networks:
      - splashnet
    ports:
      - "8050:8050"
networks:
  splashnet:
```


I'm closing this issue, because this is not a bug, but feel free to continue the conversation after I closed
