### ISSUE TITLE
Is docker stack deploy support to multiple set "deploy" parameter pretty on xx.yml 

### ISSUE THREAD

**Issue by lion-liu** [moby/moby#38186]
### hi brother
 i am using docker stack deploy -c xx.yml do start a stack cluster, now i facing some  trouble problem ,
can you help me ..  many thanks.. 😄 
 ### may i config this yml more prettily?
![image](https://user-images.githubusercontent.com/1003345/48335407-942a0780-e698-11e8-8857-f05d9cc53d9c.png)

### perhaps i can write this xxx.yml file like this

![image](https://user-images.githubusercontent.com/1003345/48336084-752c7500-e69a-11e8-8f53-db68945beddd.png)

**Comment by thaJeztah** [comment]
The compose-file schema 3 itself doesn't have the "extends" option that schema 2 had (see https://github.com/moby/moby/issues/31101), but you can use YAML "node anchors" (see the [YAML specification](http://yaml.org/spec/1.2/spec.html#id2785586))

```yaml
version: '3.7'
services:
  serviceA: &defaultservice
    image: nginx:alpine
    deploy: &deploy1
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  serviceB:
    image: nginx:alpine
    # Service B "copies" the deploy settings from Service A
    deploy: *deploy1

  # Service C "copies" everything from Service A
  serviceC: *defaultservice
```
