### ISSUE TITLE
Docker on Windows does not incorporate host network routes and interface metrics

### ISSUE THREAD

**Issue by mback2k** [moby/moby#38187]
**Description**
I am running Windows Docker Containers connected to internal and external overlay networks. Every container has two networks with only one being able to access the internet. Unfortunately inside the container both networks have a default route which is not the case on the host.

**Steps to reproduce the issue:**
1. Setup a host with two network interface of which only one has access to the internet with a default route: `route print`
```
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    public-gateway public-ip     15
         10.0.0.0        255.0.0.0         private-gateway         private-ip     16
```
2. Run a Docker container with the following network configuration:
```
      networks:
        dmz:
          driver: overlay
          driver_opts:
            com.docker.network.windowsshim.interface: Internet
          ipam:
            driver: default
            config:
              - subnet: "172.28.11.0/24"
        buildbot:
          driver: overlay
          driver_opts:
            com.docker.network.windowsshim.interface: Intranet
          ipam:
            driver: default
            config:
              - subnet: "192.168.11.0/24"
```
3. See that the networks in the container both have a default route and same metric: `docker exec my-container route print`
```
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0     192.168.11.1    192.168.11.13    271
          0.0.0.0          0.0.0.0      172.28.11.1     172.28.11.12    271
```

**Describe the results you received:**
Docker container is able to access the internet only randomly due to primary network interface being choosen at random.

**Describe the results you expected:**
Docker container should always be able to access the internet, because host routes and metrics should be considered inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
I think it would be good if the network interface metric could be specified via an option like `com.docker.network.windowsshim.metric`.

**Output of `docker version`:**

```
Client:
 Version:           18.03.1-ee-4
 API version:       1.37
 Go version:        go1.10.2
 Git commit:        0ded23c
 Built:             Thu Oct 25 00:41:52 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ee-4
  API version:      1.37 (minimum version 1.24)
  Go version:       go1.10.2
  Git commit:       0ded23c
  Built:            Thu Oct 25 00:56:17 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 64
Server Version: 18.03.1-ee-4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: active
 NodeID: ...
 Is Manager: false
 Node Address: ...
 Manager Addresses:
  ...
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter Version 1803 (OS Build 17134.345)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 12GiB
Name: ...
ID: ...
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Not relevant.

**Comment by mback2k** [comment]
After adding `internal: true` to the driver options of the Intranet network, the network interface still has a default route. Fixing this would at least allow one to separate between internal and external routing.

**Comment by mback2k** [comment]
I am currently using working around this issue / limitation by running the following PowerShell at the start of the container:
```
Get-NetIPAddress -IPAddress "172.28.11.*" | Get-NetIPInterface | Set-NetIPInterface -InterfaceMetric 15
Get-NetIPAddress -IPAddress "192.168.11.*" | Get-NetIPInterface | Set-NetIPInterface -InterfaceMetric 30 
```

**Comment by olljanat** [comment]
I just tested that this happens also on Windows Server 2019 + Docker 18.09 combination with this stack:
```yaml
version: "3.3"

services: 
  nano: 
    image: mcr.microsoft.com/windows/nanoserver:1809
    networks:
      - wan
      - lan
    command: ping -t 127.0.0.1

networks:
  wan:
    driver: overlay
  lan:
    driver: overlay
    internal: true
```
