### ISSUE TITLE
How to set dns name for service in swarm cluster

### ISSUE THREAD

**Issue by huikang** [moby/moby#38298]
Hi, I want to deploy a service in a swarm cluster that could be connected through the full dns name as follows
```yaml
services:
  web.example.com:
    image: nginx
    hostname: web.example.com
    ports:
      - "80"
      - "443"
    networks:
      - testpeer
```

The same yaml file used to work very well by ``docker-compose`` command line. However, when I adapt the file to a swarm cluster, I got the following error

```
ailed to create service test_web.example.com: Error response from daemon: rpc error: code = InvalidArgument desc = name must be valid as a DNS name component
```

I realize I could change the service name from ``web.example.com`` to ``web``. However, the issue of this solution is that in other containers they could not resolve the name, .e.g,``host web.example.com`` returns not found. Could anyone help on this? Thanks.
