### ISSUE TITLE
A swarm service never start if other services already spreaded the swarm

### ISSUE THREAD

**Issue by nevmerzhitsky** [moby/moby#38322]
**Description**

A service with reserved memory can not start at all in a swarm where it's possible when the service has a placement constraint and other services of the stack without placement constraints already spreaded a node where the service should be started.

**Steps to reproduce the issue:**

1. Make a swarm cluster with 2 nodes with 1GB RAM each
2. Create a systemd slice to Limit max memory for Docker Engine on each node (`/etc/systemd/system/limit-docker-memory.slice`):
```
[Unit]
Description=Slice with MemoryLimit=600M for docker
Before=slices.target

[Slice]
MemoryAccounting=yes
MemoryLimit=600M
```
3. Add this slice to Engine config (`/etc/docker/daemon.json`):
```
{
    "cgroup-parent": "limit-docker-memory.slice"
}
```
4. Restart the docker service (the steps about systemd slice are optional but them will safe you from hangs of the nodes while reproducing)
5. Create `docker-compose.yml`:
```yml
version: "3.7"

services:
  queue:
    image: rabbitmq:3.7-management
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          memory: 600M
      placement:
        constraints:
          - node.labels.datastore == true
    environment:
      - NODENAME=rabbit@queue
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=asdakjdajdjaskd
  little-one:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          memory: 50M
      mode: replicated
      replicas: 10
    image: python:3.7
    command: ["python", "-c", "'import time; time.sleep(30)'"]
```
6. Add label `datastore = true` to the one node
7. Deploy the stack: `docker stack deploy -c docker-compose.yml bugrep
`

**Describe the results you received:**

```bash
docker service ps bugrep_queue
ID                  NAME                         IMAGE                     NODE                DESIRED STATE       CURRENT STATE                ERROR                              PORTS
yvef6qs5996q        bugrep_queue.1       rabbitmq:3.7-management   ferrari             Shutdown            Complete about an hour ago
qwyj84l0ffkw         \_ bugrep_queue.1   rabbitmq:3.7-management   ferrari             Shutdown            Failed about an hour ago     "No such container: depth-scra…"
t5eu20doynec         \_ bugrep_queue.1   rabbitmq:3.7-management   ferrari             Shutdown            Complete 2 hours ago
s96rlw0yebq6         \_ bugrep_queue.1   rabbitmq:3.7-management   ferrari             Shutdown            Failed 2 hours ago           "starting container failed: fa…"
i6grvfr25xlf         \_ bugrep_queue.1   rabbitmq:3.7-management   ferrari             Shutdown            Shutdown 2 hours ago
```

**Describe the results you expected:**

I expected that the queue service will be start on node with label `datastore` and other tasks of the little-one service will be start on both nodes in the swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

All services have `RestartPolicy.MaxAttempts == 0` thus queue should be restarted infinitely.

My swarm nodes:
```bash
docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
p2evc4i15wdmy9r8g7oasvpts     etox                Ready               Active                                  18.06.1-ce
xy53m0qtynoqh8bflmmgcbo4x *   ferrari             Ready               Active              Leader              18.06.1-ce
kjo9raivguyfjek6nl943dgdp     infiniti            Ready               Active                                  18.06.1-ce
```

Their labels:
```bash
docker node inspect --pretty ferrari etox infiniti
ID:                     xy53m0qtynoqh8bflmmgcbo4x
Labels:
 - datastore=true
Hostname:               ferrari
Resources:
 CPUs:                  1
 Memory:                985.5MiB
Engine Version:         18.06.1-ce
...

ID:                     p2evc4i15wdmy9r8g7oasvpts
... NO LABELS ...
Hostname:               etox
Resources:
 CPUs:                  1
 Memory:                985.5MiB
Engine Version:         18.06.1-ce
...

ID:                     kjo9raivguyfjek6nl943dgdp
... NO LABELS ...
Hostname:               infiniti
Resources:
 CPUs:                  1
 Memory:                985.5MiB
Engine Version:         18.06.1-ce
...
```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 57
 Running: 5
 Paused: 0
 Stopped: 52
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xy53m0qtynoqh8bflmmgcbo4x
 Is Manager: true
 ClusterID: 43jelyis1xt8fjp2mc2bljr8k
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: ...
 Manager Addresses:
  ...:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-42-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.5MiB
Name: ferrari
ID: DRZM:HKE3:TE6V:6O36:UBC4:JSRO:PHK7:GLTG:UZZP:XFUH:E6HM:M3LH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduced on DigitalOcean droplets by $5 (1 vCPU, 1 GB RAM)
