### ISSUE TITLE
Why this container isn't in the ingress network?

### ISSUE THREAD

**Issue by GingerMoon** [moby/moby#38542]
** I am trying to deploy Hyperledger Fabric (byfn sample) via docker swarm.
In the compose file below, all the other services are both in ingress and net_byfn network, except the cli service which is only in net_byfn. I need to execute some fabric commands from within the cli container. But the result is, when I "docker exec -it cli-container bash", I am not able to access other containers via the IPs of other containers, which means if I execute those fabric commands, there are connection errors.  However, if I "dock exec -it other-containers bash", I am able to connect to other-containers(except the cli-container).**
```
version: '3.4'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:

networks:
  net_byfn:
    # external: true
    driver: overlay
    attachable: true

x-peer-base:
  &default-peer # environment and volume doesn't take effect here. 
  tty: true
  stdin_open: true
  image: hyperledger/fabric-peer:latest
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  command: /bin/bash # peer node start

services:

  orderer:
    image: hyperledger/fabric-orderer:latest
    tty: true
    stdin_open: true
    environment:
      - "constraint:node==manager1"
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash # orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      net_byfn:
        aliases:
          - orderer.example.com

  org1:
    # << : *default-peer
    tty: true
    stdin_open: true
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash # ./peer node start # 

    environment:
      # common environment
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net_byfn
      - FABRIC_LOGGING_SPEC=INFO:sccapi,ccprovider,discovery.lifecycle,endorser,lscc=debug
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # specific environment
      - "constraint:node==worker1"
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - FPGA_MOCK=0
      # - FPGA_SERVER_ADDR=172.17.0.1:50021
      - FPGA_SERVER_ADDR=127.0.0.1:10000
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.example.com:/var/hyperledger/production
        - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      net_byfn:
        aliases:
          - peer0.org1.example.com

  org2:
    # << : *default-peer
    tty: true
    stdin_open: true
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash # ./peer node start # 
    
    environment:
      # common environment
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net_byfn
      - FABRIC_LOGGING_SPEC=INFO:sccapi,ccprovider,discovery.lifecycle,endorser,lscc=debug
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # specific environment
      - "constraint:node==worker2"
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FPGA_MOCK=0
      # - FPGA_SERVER_ADDR=172.17.0.1:50021
      - FPGA_SERVER_ADDR=127.0.0.1:10000
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.example.com:/var/hyperledger/production
        - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      net_byfn:
        aliases:
          - peer0.org2.example.com

  cli:
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - "constraint:node==manager1"
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /dev/:/dev/
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../../payment-demo:/opt/gopath/src/github.com/hyperledger/fabric/peer/payment-demo
    depends_on:
      - orderer
      - org1
      - org2
    networks:
      net_byfn:
        aliases:
          - cli.example.com
```

As you see below, onle cli-container is not in ingress.
```
docker network inspect ingress
[
    {
        "Name": "ingress",
        "Id": "ibswi1xru23wk05j2qoiwqd0s",
        "Created": "2019-01-12T23:15:21.571399483-05:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": true,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "8a765e0302c20cbe16a3c50a9d7bdabaccfba8f604c6cf5c7a3cdcbd6c3117b3": {
                "Name": "afabric_org1.1.mfndjuu94fj5bf40phjsayvt9",
                "EndpointID": "f9b665a1ba2ded19e2eb4b89c09b5cbbfc790294d9e64e12b599bbbd882c58c9",
                "MacAddress": "02:42:0a:ff:02:e0",
                "IPv4Address": "10.255.2.224/16",
                "IPv6Address": ""
            },
            "9659da66e8a7676bffbf87781d81edc32c86053325cf11683be9549b1eacb645": {
                "Name": "afabric_orderer.1.5ljgwse53lkudptmc0n0plx47",
                "EndpointID": "79daab2021f4e08c79b22448067cc1cc20c9efc4baccfa62ce46f53d5b0d9c2a",
                "MacAddress": "02:42:0a:ff:02:de",
                "IPv4Address": "10.255.2.222/16",
                "IPv6Address": ""
            },
            "dcd8dbb1a3699eb3fb5c6fc704816f4eacf0b14045c7a54ab74258a9590430f6": {
                "Name": "afabric_org2.1.ipsuadh88sq0vv58q41trj15r",
                "EndpointID": "e074ba1cf5d11ef148286a78f394efebe3a86b9e32836be609d5a33a3aad635b",
                "MacAddress": "02:42:0a:ff:02:e2",
                "IPv4Address": "10.255.2.226/16",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "de0aad531449db9dc3ac8383bc0547b0daed3fed0893bea81f4e139eba6c4ef0",
                "MacAddress": "02:42:0a:ff:00:02",
                "IPv4Address": "10.255.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4096"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "314c7f608bbe",
                "IP": "10.100.7.11"
            }
        ]
    }
]

```
However, all of the containers are in the afabric_net_byfn network.
```
docker network inspect afabric_net_byfn
[
    {
        "Name": "afabric_net_byfn",
        "Id": "rip940cypmhs9ylq1rdb6dz6m",
        "Created": "2019-01-14T07:21:47.963407277-05:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.22.0/24",
                    "Gateway": "10.0.22.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "5fc4c6ab69c0abb00d18fb49505dbbaf24823d3e94b016f1c47c3b3b383c29d6": {
                "Name": "afabric_cli.1.rszku5za698mdi2txaq79qt2w",
                "EndpointID": "47e3698cfb65d2d8d4f93d9dc4e9639f9e242bd2478c44bcb03a62f391ae7030",
                "MacAddress": "02:42:0a:00:16:0a",
                "IPv4Address": "10.0.22.10/24",
                "IPv6Address": ""
            },
            "8a765e0302c20cbe16a3c50a9d7bdabaccfba8f604c6cf5c7a3cdcbd6c3117b3": {
                "Name": "afabric_org1.1.mfndjuu94fj5bf40phjsayvt9",
                "EndpointID": "fb844d80d3bbdfd96ca36133ef5e4b16094f1c966f89cd2e1f3dde8db6f23386",
                "MacAddress": "02:42:0a:00:16:06",
                "IPv4Address": "10.0.22.6/24",
                "IPv6Address": ""
            },
            "9659da66e8a7676bffbf87781d81edc32c86053325cf11683be9549b1eacb645": {
                "Name": "afabric_orderer.1.5ljgwse53lkudptmc0n0plx47",
                "EndpointID": "75421630252efe417baab8333eb65244fa4469f8503f4bbd9a2869df7faa7588",
                "MacAddress": "02:42:0a:00:16:03",
                "IPv4Address": "10.0.22.3/24",
                "IPv6Address": ""
            },
            "dcd8dbb1a3699eb3fb5c6fc704816f4eacf0b14045c7a54ab74258a9590430f6": {
                "Name": "afabric_org2.1.ipsuadh88sq0vv58q41trj15r",
                "EndpointID": "9da08a9dfb30450d967eae192a05361a2fc45d821ddd7bfaa9aedab5209aa7fc",
                "MacAddress": "02:42:0a:00:16:08",
                "IPv4Address": "10.0.22.8/24",
                "IPv6Address": ""
            },
            "lb-afabric_net_byfn": {
                "Name": "afabric_net_byfn-endpoint",
                "EndpointID": "f6521a98614448ebe5becd16a09f76ece98043293c125590d502df98c3ad6e1e",
                "MacAddress": "02:42:0a:00:16:04",
                "IPv4Address": "10.0.22.4/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4119"
        },
        "Labels": {
            "com.docker.stack.namespace": "afabric"
        },
        "Peers": [
            {
                "Name": "314c7f608bbe",
                "IP": "10.100.7.11"
            }
        ]
    }
]

```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:46:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:52:55 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: nfunq1y1f71dtvu7i5ns9zf5j
 Is Manager: true
 ClusterID: 65g4cxb9645l01tz0pk5l3amk
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.2.214
 Manager Addresses:
  192.168.2.214:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.79-boot2docker
Operating System: Boot2Docker 18.09.0 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 913.3MiB
Name: manager1
ID: C2QR:2HHN:72SU:LTAZ:3ZHE:2KQS:APCL:KPFF:F2NP:PRCQ:TIP3:DU3V
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=hyperv
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
