### ISSUE TITLE
Feature request: Provide .Node.Labels in service templating 

### ISSUE THREAD

**Issue by mback2k** [moby/moby#39071]
Hello everyone,

I would like to request the addition of the Docker node labels to [service templating](https://docs.docker.com/v17.12/edge/engine/reference/commandline/service_create/#create-services-using-templates). Just like service labels can be accessed during templating, I would like to access the labels of the node the task container is running on.

That would allow a small amount of node specific behaviour and configuration to be passed into service tasks. What do you think?

**Comment by chrisbecke** [comment]
Sometimes docker swarm is used to deploy - in turn - clustered services, and given the lack of CSI support the best way to achieve these is to deploy to a fixed set of nodes, with local mounts. And being able to use labels as a confguration point for this would be very useful:

```yaml
services:
  etcd:
    image: quay.io/etcd
    hostname: {{index .Node.Labels "etcd.host"}}
    deploy:
       replicas: global
       placement:
         constraints:
         - node.labels.etcd.host != null
```

Now if only there also was a way to test that a label was not set as a placement constraint.
