### ISSUE TITLE
Cannot ping docker-compose service from within a container on Windows 10

### ISSUE THREAD

**Issue by gillesgalipeau** [moby/moby#39110]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
Cannot ping docker-compose service from within a container on Windows 10.
Pinging the IP address of that service works.

**Steps to reproduce the issue:**
1. Create docker-compose-quick-servers.yml with the following content
```
version: '3.4'

services:
  server1:
    image: mcr.microsoft.com/windows/nanoserver
    container_name: Server_1
    entrypoint: ping -t localhost
  server2:
    image: mcr.microsoft.com/windows/nanoserver
    container_name: Server_2
    entrypoint: ping -t localhost
networks:
  default:
    external:
      name: nat
```
2. Run the docker containers: docker-compose -f .\docker-compose-quick-servers.yml up -d
3. Ping the other docker-compose service: docker exec Server_1 ping server2

**Describe the results you received:**
The ping fail. The same operation with the second service IP address works fine.

**Describe the results you expected:**
We should be able to ping services using its defined name.

**Additional information you deem important (e.g. issue happens only occasionally):**
It works fine in our prod environment (on Windows Server 2016).
 
**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.706)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.93GiB
Name: H198818
ID: HOKO:5CAS:SIQ2:SCLD:3TB7:A6GG:EH5X:763G:CBV5:UQMJ:BGSO:PF2Y
Docker Root Dir: E:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 36
 System Time: 2019-04-18T15:33:25.7898496-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```
