### ISSUE TITLE
Container internet access permanently broken after bad docker-compose.yml

### ISSUE THREAD

**Issue by passwordleak** [moby/moby#39335]
Previously, the network portion of docker-compose.yml reads:
```

networks:
    test:
        name: test
        ipam:
            config:
                - subnet: 172.19.0.0/16
```
The new config reads:
```

networks:
    host:
    test:
        name: test
        ipam:
            config:
                - subnet: 172.19.0.0/16
```
Furthermore, one of the new containers uses the new network:

```
     networks:
         test:
               ipv4_address: 172.19.0.2
         host:
```
Now, even when I revert back to the previous docker-compose.yml, remove the container that uses "host", remove all removable networks (bridge, host, and none are not removable), delete all images and volumes, and even reinstall docker, I am unable to access the outside internet with my docker containers. I even tried renaming test to test2 and then using that instead and still the same issue. The only fix is to remove it from the networks completely, so that it's no longer on the test network, but that breaks the application.

Any ideas how to fix this or why this causes persistent damage? Or maybe this isn't the root issue at all? 

**Output of `docker version`:**

```
Docker version 18.09.6, build 481bc77156
```

**Output of `docker info`:**

```

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 104
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.12.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: <redacted>
Name: <redacted>
ID: <redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtualbox and KVM
