### ISSUE TITLE
namespaces with userns_mode: 'host' and USER command in Docker file doesn't work with privileges

### ISSUE THREAD

**Issue by passwordleak** [moby/moby#39397]
**Description**

I am trying to get a vault container to run as a user rather than as root. Previously, I didn't have namespaces, so I used the USER command in the Docker file to run the process as user on the host. This mimics namespaces and I checked with `docker top` it runs as a user rather than as root. However, I am able to give it cap_add IPC_LOCK privileges and even though it runs as user, it can use that privilege. 

Because other containers use namespaces, I have to turn it on. However, to give the container the IPC_LOCK priv, it must be disabled for that host using userns_mode: 'host'. Even after disabling it, the container is unable to use the IPC_LOCK privilege. The privileged:true command also does not work. 
Removing the USER command will work, but it'll run as root, which is the goal to avoid. 
docker-compose.yml
```
 vault:
        entrypoint: sh /docker-entrypoint.sh server
        hostname: vault
        userns_mode: 'host'
        build:
            context: ./test
            args:
              USER_NAME: ${USERNAME}
              USER_ID: ${USERID}
        cap_add:
          - IPC_LOCK
        environment:
          - "VAULT_ADDR=http://0.0.0.0:8200"
        healthcheck:
          test: ["CMD", "sh", "/health-check.sh"]
          retries: 5
        networks:
            test:
                ipv4_address: 172.19.0.1

```
Dockerfile:
```
FROM vault
ARG USERNAME
ARG USERID

RUN adduser -DH -u ${USERID} ${USERNAME} && \
        setcap cap_ipc_lock=+ep $(readlink -f $(which vault)) && \
        chown -R ${USERNAME}:${USERNAME} /vault

USER ${USERNAME}
```

**Steps to reproduce the issue:**
1.docker-compose up --build
2.
3.

**Describe the results you received:**
vault container has error that it does not have IPC_LOCK permission. 

**Describe the results you expected:**
Vault container runs the exact same as if namespaces were not enabled.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             [redacted]
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            [redacted]
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 60
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73GiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: [redacted]
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM
