### ISSUE TITLE
Scroll Update Access Container Discontinues

### ISSUE THREAD

**Issue by arz-GW** [moby/moby#39459]
Description
when i use "docker stack deploy" to run a container on a node, and then Rolling update service, Continuous access to containers found transient connection failure.
I set up rolling updates and health checks, and the problem remains.

Steps to reproduce the issue:
     1.the yaml is like this:

```yaml
version: "3"
services:
  test-healthcheck:
    image: test-healthcheck-old:1
    ports:
      -  "2345:80"
    networks:
      - arz_net
    deploy:
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 1m
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  arz_net:
    external: true
```

2. Rolling update service

```
docker stack deploy -c test-healthcheck.yaml  test-healthcheck
```

3. Uninterrupted access to containers

```
 while true; do curl 127.0.0.1:2345 ;done

11111
11111
11111
11111
curl: (56) Recv failure: Connection reset by peer
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
11111
curl: (7) Failed connect to 127.0.0.1:2345; Connection refused
.....
new
new
```

Describe the results you expected:

i want to know the the cause of the problem and the ways to solve the problem.
I appreciate this very much

Additional information you deem important (e.g. issue happens only occasionally):

Output of docker version:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

Output of docker info:
Containers: 31
 Running: 14
 Paused: 0
 Stopped: 17
Images: 53
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 2zwq2kcpcycejcl1kyyqfrj1k
 Is Manager: true
 ClusterID: i693q20x89nxzy417a6g6txgx
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.0.92
 Manager Addresses:
  192.168.0.92:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: fc48a25bde6fb041aae0977111ad8141ff396438 (expected: 810190ceaa507aa2727d7ae6f4790c76ec150bd2)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.639GiB
```
