### ISSUE TITLE
Windows Swarm multiple overlay network DNS resolution issues

### ISSUE THREAD

**Issue by drnybble** [moby/moby#39539]
**Description**

Deploy a stack where a service is connected to more than one overlay network. It will not be able to resolve hostnames on some of the networks.

**Steps to reproduce the issue:**
[windns.zip](https://github.com/moby/moby/files/3398085/windns.zip)

Attached is a Dockerfile, services.yml file and GetAddrInfo.exe executable.

In my case I deployed it on a Swarm with three nodes so I had to push the image to my registry.

**Dockerfile**
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Disable DNS cache
RUN REG add "HKLM\SYSTEM\CurrentControlSet\services\Dnscache" /v Start /t REG_DWORD /d 4 /f

COPY ./GetAddrInfo.exe /

CMD Start-Sleep -Seconds 3600
```

**services.yml**
Customize this to match your image name. Placement was only so I could put the "central" container onto the machine where I had WireShark installed you can remove it.

```
version: "3.7"

services:
  central:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
        - node.labels.pa.replica1 == true
    image: p1dist1:5000/windns
    networks:
    - n1
    - n2
    - n3
  s1:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
        - node.labels.pa.replica1 == true
    image: p1dist1:5000/windns
    networks:
    - n1
  s2:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
        - node.labels.pa.replica2 == true
    image: p1dist1:5000/windns
    networks:
    - n2
  s3:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
        - node.labels.pa.replica3 == true
    image: p1dist1:5000/windns
    networks:
    - n3

networks:
  n1:
    driver: overlay
  n2:
    driver: overlay
  n3:
    driver: overlay
```

The GetAddrInfo.exe is just the statically compiled sample from https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo. Compile it yourself if you like.

So....

```
docker build -t p1dist1:5000 .
docker push p1dist1:5000
docker stack deploy -c .\services.yml windns
```
Now find the **central** container which is connected to services s1, s2, s3 through three different overlay networks n1, n2, n3 and run:

```
docker exec <id> C:\GetAddrInfo.exe s1 0
docker exec <id> C:\GetAddrInfo.exe s2 0
docker exec <id> C:\GetAddrInfo.exe s3 0
```

**Describe the results you received:**

So interestingly the **first** invocation succeeds for each host name. Using WireShark I can see a DNS request/response sent down **each** NIC. 

Then try it again, and subsequent invocations will succeed for only **one** hostname -- the one where the response is received first from Docker. In that case I also observe it sends a request only to the first NIC. 

For the "s2" and "s3" hostnames it sends a DNS request to each NIC; the responses are two failures and one success but nonetheless getaddrinfo fails with 11001 (host not found).

![windns](https://user-images.githubusercontent.com/4443016/61312633-d1fea300-a7c6-11e9-938f-f37068f14ecb.png)

Now also interesting, I restart the container:

```
docker service update windns_central --force
```

The behaviour remains that s1 sends a DNS request only to one NIC and succeeds, and s2 and s3 send requests to all NICS and getaddrinfo reports failure! I also tried restarting Docker and the HNS service which didn't change anything.

**Describe the results you expected:**
Resolving the hostname works when there are multiple overlay networks.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        b81f47481d
 Built:             06/27/2019 17:58:58
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       b81f47481d
  Built:            06/27/2019 17:57:09
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 36
Server Version: 18.09.7
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: active
 NodeID: v4qrriq19c48jlwyq8ka7xud9
 Is Manager: true
 ClusterID: rjhv11udbjq1711hb5xlrijmx
 Managers: 3
 Nodes: 3
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.21.13.86
 Manager Addresses:
  10.21.13.86:2377
  10.21.13.87:2377
  10.21.13.89:2377
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.529)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16GiB
Name: p1dist1
ID: UKVQ:THA3:7QQ7:UIQM:OPXE:7RJW:FZLM:HVJC:DWVY:UZ4G:63RD:BX7E
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 188
 System Time: 2019-07-16T09:41:05.8651639-07:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
