### ISSUE TITLE
NFS volume creation in a swarm stack lead to network error on remote worker node

### ISSUE THREAD

**Issue by FractalWire** [moby/moby#39662]
**Description**

I have a 2 nodes setup connected via VPN.
The manager node also have a NFS server running on it.
Here is a simple stack.yml file to deploy my swarm stack : 

<details>
<summary>stack.yml</summary>

```
version: '3.7'
networks:
    my-other-net:
        external: true
volumes:
    pg-data:
        driver: local
        driver_opts:
            type: nfs
            o: addr=10.0.110.2
            device: ":/srv/nfs/docker/pgdata"
    # test-pgsql:
    #     external: true
    portfolio-data:
        driver: local
        driver_opts:
            type: nfs
            o: addr=10.0.110.2
            device: ":/srv/nfs/docker/portfolio-2"
    # test-nfs:
    #     external: true
services:
    django:
        image: 127.0.0.1:5000/django-portfolio
        # networks:
        #     - my-other-net
        ports:
            - "8000:8000"
        volumes:
            - portfolio-data:/usr/src/app/portfolio-project
    pgsql:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pg-data:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        # networks:
        #     - my-other-net
```

</details>

Trying to deploy my services with this file, the services won't work if they are run on the remote worker node. Or rather, they will run, but throw me some network related error if I try to access it. Example:

```
$ psql -h 127.0.0.1 postgres postgres
psql: n'a pas pu se connecter au serveur : Connexion refusée
	Le serveur est-il actif sur l'hôte « 127.0.0.1 » et accepte-t-il les connexions
	TCP/IP sur le port 5432 ?
```

But they will work properly if they are run on the manager node.

Now, if I try to create some nfs volume : 

```
$ docker volume create -d local -o type=nfs -o o=addr=10.0.110.2 -o device=:/srv/nfs/docker/pgdata --name test-nfs
$ docker volume create -d local -o type=nfs -o o=addr=10.0.110.2 -o device=:/srv/nfs/docker/pgdata --name test-pgsql
```

and tweak my stack.yml file to use those two volumes, ~~my services will work properly even if they are run on the remote worker node.~~
Actually, it works only because it create a named volume on the remote host that has nothing to do with NFS. So my inspect below is not right, as it was inspecting volume on the manager local node.

<details>
<summary>ignore that</summary>

Some inspect of the volume created automatically by using stack deploy, and my volume created manually : 

Created by stack deploy : 
```
$ docker volume inspect portfolio_pg-data 
[
    {
        "CreatedAt": "2019-08-04T14:11:24+02:00",
        "Driver": "local",
        "Labels": {
            "com.docker.stack.namespace": "portfolio"
        },
        "Mountpoint": "/var/lib/docker/volumes/portfolio_pg-data/_data",
        "Name": "portfolio_pg-data",
        "Options": {
            "device": ":/srv/nfs/docker/pgdata",
            "o": "addr=10.0.110.2",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
```

Created manually : 

```
$ docker volume inspect test-pgsql 
[
    {
        "CreatedAt": "2019-08-04T13:59:43+02:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/test-pgsql/_data",
        "Name": "test-pgsql",
        "Options": {
            "device": ":/srv/nfs/docker/pgdata",
            "o": "addr=10.0.110.2",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
```

As you can see, except for the label, it looks very similar.

</details>

So I guess my real issue is that Docker on my remote worker node does not work properly with NFS.

But if I list the content of the mounted directory inside the container on the remote worker, I've got : 

```
$ docker container exec -it portfolio_pgsql.1.voujwjakrbrq2okedshhojzjw ls /var/lib/postgresql/data/pgdata
base	      pg_dynshmem    pg_notify	   pg_stat_tmp	pg_xlog
dummyfile     pg_hba.conf    pg_replslot   pg_subtrans	postgresql.auto.conf
global	      pg_ident.conf  pg_serial	   pg_tblspc	postgresql.conf
pg_clog       pg_logical     pg_snapshots  pg_twophase	postmaster.opts
pg_commit_ts  pg_multixact   pg_stat	   PG_VERSION	postmaster.pid
```

And I can see my 'dummyfile' created manually. So NFS actually works inside this container.
So the issue is still that I've got a weird network error when I use NFS mount and I try to access my services on the remote worker.

**Output of `docker version`:**

<details>
<summary>docker version manager node : </summary>

```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
</details>

<details>
<summary>docker version worker node :  </summary>

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

</details>

**Output of `docker info`:**

<details>
<summary>docker info manager node :  </summary>

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 83
 Server Version: 19.03.1-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: rl5uwqk9kosrqpljht6st2fud
  Is Manager: true
  ClusterID: a90g4285z47e8xgxyp4xar00l
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.110.2
  Manager Addresses:
   10.0.110.2:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.2.4-arch1-1-ARCH
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.664GiB
 Name: Stomatopoda
 ID: HZOY:SCC2:7ZHN:BLIK:SPHU:F5OR:R6WO:HZA2:JAVZ:65LI:AMIW:WMK7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: fractalwire
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</details>

<details>
<summary>docker info worker node : </summary>
 
```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: q70emxzk01cztp42kix10zq06
  Is Manager: false
  Node Address: 10.0.110.3
  Manager Addresses:
   10.0.110.2:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-55-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.5MiB
 Name: docker-node
 ID: 355W:PT7U:SDTV:XCRG:YUC3:DZVS:BJIP:33XV:FV2A:J4YT:F5JR:7U33
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Working with my local machine and a server on digital ocean connected via a VPN.
