### ISSUE TITLE
Raw credential spec in docker compose / docker stack

### ISSUE THREAD

**Issue by Drewster727** [moby/moby#39730]
## Description of the issue
It appears that docker supports passing crdential specs directly in a raw json format: https://github.com/moby/moby/pull/38777
I tested this out when running from the CLI and I can indeed create a swarm service and have it utilize the credspec json:
```
docker run --rm --security-opt "credentialspec=raw://<somejson>" mcr.microsoft.com/windows/servercore:ltsc2019 nltest /parentdomain
```

My issue here is that it seems either a bug or a missing feature that I cannot do this same thing in my compose/stack files. I mean... I may have a cluster of dozens of hosts, are we expected to deploy these cred specs to every host?? I'd rather pass them in my yml to tell the service what to do, rather than relying on a hard-set file system reference.

I know that this works:
```
version: "3.7"

services:
  cdm:
    image: mcr.microsoft.com/windows/servercore:servercore:ltsc2019
    credential_spec:
      file: cred-spec.json
```

but, I should be able to do this:
```
version: "3.7"

services:
  app:
    image: mcr.microsoft.com/windows/servercore:servercore:ltsc2019
    credential_spec:
       raw: "{ somejson: blah }"
```

Reference links:
https://github.com/moby/moby/pull/38777
https://github.com/moby/moby/pull/38632

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Enterprise
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        87b1f470ad
 Built:             07/16/2019 23:41:30
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       87b1f470ad
  Built:            07/16/2019 23:39:21
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Steps to reproduce the issue

1. Create a docker-compose.yml file
2. Add in a raw credential-spec json in the config area
3. it works in the CLI, but doesn't work on a stack deploy or compose up

### Observed result
raw isn't supported

@thaJeztah thoughts on this? Those PRs made me think this was possible, but apparently only for the CLI?

**Comment by thaJeztah** [comment]
@wk8 @dperny ptal

**Comment by thaJeztah** [comment]
actually; this implementation was for swarm/kubernetes services; don't think this was implemented for standalone compose, so that may be the issue (also, may be the compose-file 3.8 version, but I'd have to check)

**Comment by Drewster727** [comment]
@thaJeztah I actually am using swarm, but using compose.yml to do my deploys. Didn't seem to work in it's current form.

**Comment by Drewster727** [comment]
Added a PR to docker/compose repo for now -- https://github.com/docker/compose/issues/6842
Should just work with the CLI already providing support, I believe.

**Comment by dperny** [comment]
In Swarm mode, you can use docker configs as credential specs. This is supported with a `config://<config-name>` syntax. It was added in the version of compose included in the Docker CLI, but evidently forgotten in the docker-compose python version.

**Comment by Drewster727** [comment]
@dperny I have seen that referenced somewhere. However, does that mean I can use raw credential spec json as my config value?

I do see in the docs you can use a config to reference the file as such:
```
version: "3.8"
services:
  myservice:
    image: myimage:latest
    credential_spec:
      config: my_credential_spec

configs:
  my_credentials_spec:
    file: ./my-credential-spec.json|
```
but, you can't just provide a raw value instead of a file?
