### ISSUE TITLE
Error thrown by docker-compo

### ISSUE THREAD

**Issue by xichengliudui** [moby/moby#39796]
**Description**
May I ask how to describe the following command using `docker-compose`?
Like the following `docker run --rm` directly delete the container after running, using `docker-compose` how to describe?
```
 $ docker run --rm \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     kong:latest kong migrations bootstrap
```
So far I've described it this way, but I don't know what the command after `name:tag` in the code block means
```
version: "3.3"
services:
  initdb:
    networks:
       - "kong-net"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    image:  kong:latest kong migrations bootstrap
```
So it keeps failing, and the output looks like this: 
```
ERROR: no such image: kong:1.2.1+migrations+bootstrap: invalid reference format
```

**Describe the results you expected:**

```
I hope the docker-compose will start the container up properly
```

**Output of `docker version`:**

```
18.09.7
```

**Comment by xichengliudui** [comment]
Can you help me? Thank you very much

**Comment by thaJeztah** [comment]
This line looks to have some stray words after the image at the end (`kong migrations bootstrap`)

```yaml
image:  kong:latest kong migrations bootstrap
```

Which is what makes it fail.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to comment after I closed

**Comment by thaJeztah** [comment]
Missed this line in your first comment;

> but I don't know what the command after name:tag in the code block means


Everything after the image name are arguments / commands to run inside the container, so for the compose file, those go into the `command:`;

```yaml
version: "3.3"
services:
  initdb:
    networks:
       - "kong-net"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    image:  kong:latest
    command: ["kong", "migrations", "bootstrap"]
```

Or

```yaml
    command: kong migrations bootstrap
```

(haven't tried)
