### ISSUE TITLE
Resolving service name from a stack brings IPs of other services with same name in different stacks 

### ISSUE THREAD

**Issue by OsamaJBR** [moby/moby#40129]
## OS and Docker versions
```
root@n01 ~ # docker --version
Docker version 19.03.3, build a872fc2

root@n01 ~ # uname -a
Linux n01 4.15.0-65-generic #74~16.04.1-Ubuntu SMP Wed Sep 18 09:51:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@n01 ~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

## Docker Swarm Nodes
```
root@n01 ~ # docker node ls 
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
jcea2zspc9dec5j4tjbcu3toc *   n01                 Ready               Active              Leader              19.03.3
vx2tg98v6twsypxi10a0o4k6o     n02                 Ready               Active              Reachable           19.03.3
v9n26unndt4ly0xhwjvesh9d8     n03                 Ready               Active              Reachable           19.03.3
dga0d48az8xedq0i80go1sask     n04                 Ready               Active              Reachable           19.03.3
pydqgn608n4yenrqtqzczmi8u     n05                 Ready               Active              Reachable           19.03.3
```

## Stack File (wt-jmdx-crystal)
```
version: "3.3"
services:
  nginx:
    image: custom-nginx
    networks:
      - default
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:jmdx.xxxx.com"
  web:
    image: custom-web-image
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 256M
networks:
  traefik:
    external: true
  default:
    external: false
    driver: overlay

```
## Expected behavior:

Nginx should use web as upstream and forward requests to the service called web.

## Current behavior:

After upgrading swarm from 18.x to 19.03, nginx serivce forwards requests to different web services in other stacks.

## Debug:

From the nginx container, if I dig the ```web``` name service, it will return all IP address of other serives from different stacks

```
/ # dig web

; <<>> DiG 9.12.4-P2 <<>> web
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2705
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;web.                           IN      A

;; ANSWER SECTION:
web.                    600     IN      A       172.16.0.107
web.                    600     IN      A       172.16.0.118
web.                    600     IN      A       172.16.0.240
web.                    600     IN      A       172.16.1.122
web.                    600     IN      A       172.16.1.17
web.                    600     IN      A       172.16.0.224
web.                    600     IN      A       172.16.0.179
web.                    600     IN      A       172.16.1.19
```

But if I used the full name of the service STACKNAME_SERVICENAME it will work.

```
/ # dig wt-jmdx-crystal_web

; <<>> DiG 9.12.4-P2 <<>> wt-jmdx-crystal_web
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63138
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;wt-jmdx-crystal_web.            IN      A

;; ANSWER SECTION:
wt-jmdx-crystal_web.     600     IN      A       10.0.62.8

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Thu Oct 24 10:06:41 UTC 2019
;; MSG SIZE  rcvd: 70

```
