### ISSUE TITLE
docker stack deploy: overriding entrypoint with empty value

### ISSUE THREAD

**Issue by DrPyser** [moby/moby#40377]
**Description**
Ẁhen using `docker stack deploy -c stack.yml my_stack_name`, and using a service definition that sets the entrypoint to an empty string (`entrypoint: ""`) or an empty list(`entrypoint: []`), the entrypoint is not overriden. 

My service snippet in my stack file:
```
  my-service:
    image: my-image
    environment:
      <<: *my_environment
    working_dir: /home/me/myapp
    entrypoint: ""
    command: "alembic upgrade head"
    volumes:
      - ${KIOTO_MIGRATIONS_LOG_DIR:-/var/log/kioto/migrations}:/var/log/kioto
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==$KIOTO_NODE_HOSTNAME

```

Relevant output from `docker service inspect --pretty my_stack_my_service`:
```
ContainerSpec:
 Image:		my-image
 Args:		alembic upgrade head 
 Env:		(ommited)
 Dir:		/home/me/myapp
```

**Steps to reproduce the issue:**
1. create a stack file a service overriding the entrypoint
2. deploy the stack file
3. look at the service logs, inspect output and verify that the entrypoint was not overriden

**Describe the results you received:**
the service tries to use the entrypoint defined in the Dockerfile:
```
| sh: 0: Can't open entrypoint.sh
```

**Describe the results you expected:**
The entrypoint should be overridden(reset to the default)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
