### ISSUE TITLE
'network <id> not found' for swarm scoped bridge after reboot on rebooted node

### ISSUE THREAD

**Issue by Strum355** [moby/moby#40402]
**Description**
Standalone container (not swarm/stack/service) cant attach to Swarm scoped bridge network after node reboot. `network <id> not found`

4 node Swarm, 3 manager 1 worker.
1 consul client container deployed on each manager node, connected to a overlay swarm network `consul` and to one bridge swarm scoped network `consul_client` to allow connecting to consul server service (deployed in swarm) and for services to register with the consul client instances respectively.
1 Manager node was brought down for maintenance. On reboot, when starting the consul client container, the following error is seen:
```
Error response from daemon: network xp25crtny1sc5rxfuskl40oyw not found
Error: failed to start containers: consul_client_agent
```

Output of `docker network ls | grep xp25`:
`xp25crtny1sc        consul_client        bridge              swarm`

The consul clients on other nodes are connected to the consul_client networks (as visible by doing `docker network inspect consul_client` on each other node.). There is a Hashicorp Vault swarm service (single instance) connected to the consul_client network on a different node to the one that was rebooted. `docker network inspect consul_client` only shows the connected vault container on the node that it is running on. Intended behaviour? I digress

The consul cluster, server and client instances, are codified in an Ansible playbook, for which the client task is as follows:
```yaml
- name: Ensure Hashicorp Consul client agents
  become: yes
  docker_container:
    state: started
    name: consul_client_agent
    hostname: consul_client
    image: consul:1.6.1
    command: 'agent -config-file=/consul/config.hcl'
    restart_policy: always
    networks_cli_compatible: yes
    env:
      CONSUL_BIND_INTERFACE: eth1
    volumes:
      - /docker/consul-client/config.hcl:/consul/config.hcl
      - /docker-data/consul-client:/consul/data
    networks:
      - name: consul
      - name: consul_client
        aliases: consul_client
```

Running this on a fresh setup (no consul client instances, no `consul_client` network. Consul server instances may or may not exist as they arent in the consul_client network), this task runs successfully and the containers are started. After all, the instances on the non rebooted node are still running fine.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 22
  Paused: 0
  Stopped: 1
 Images: 127
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: nx7msiy2yyii0uth7j62dzx5a
  Is Manager: true
  ClusterID: w2ycrqcqm24ymxzrahhxx9cxm
  Managers: 3
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 84.39.234.54
  Manager Addresses:
   xx.yy.zzz.50:2377
   xx.yy.zzz.52:2377
   xx.yy.zzz.54:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.91GiB
 Name: boole
 ID: HJLX:HF2B:XI4Q:4I2P:GDCR:I7BE:W3UR:A4AA:7BGZ:JCIU:2NJB:TNZX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server
