### ISSUE TITLE
only when reboot , my container  mounting  error .

### ISSUE THREAD

**Issue by chenxiao1990** [moby/moby#40598]
**Description**
server : ubuntu 14.04 Lts
docker : Docker version 17.03.2-ce, build f5ec1e2

I user docker-compose  manager containers.
```
version: "3"
services:
  db:   # mysql  
    image: mysql:5.5 #  
    ports:
      - "3306"    #   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 190000000
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./localtime:/etc/localtime  #  
      - ./timezone:/etc/timezone #  
```
docker-compose up -d 
**It is ok !!! db running!!!**

then, i reboot the server.
when server begin runing . container auto run,then exited.
docker logs cotainterid  .
I found error 
```
oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/home/wm/gopingtai/localtime\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/f35aa5dd1518537f9ef25a00bd696aaa39207df223dbf812bc4a2f15b1b35c70/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/f35aa5dd1518537f9ef25a00bd696aaa39207df223dbf812bc4a2f15b1b35c70/merged/usr/share/zoneinfo/UCT\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
 
Then i delete  
      - ./localtime:/etc/localtime  #  
      - ./timezone:/etc/timezone #

docker-compose stop    /  docker-compose up -d 
It running well.
Then reboot server.
No error, but in folder ./mysql/db  files , not mounting success to container.
docker exec -it  id /bin/sh   
cd /var/lib/mysql  
no mounting files ....

**Comment by thaJeztah** [comment]
The error is this;

```
mounting "/home/wm/gopingtai/localtime"
to rootfs "/var/lib/docker/overlay2/f35aa5dd1518537f9ef25a00bd696aaa39207df223dbf812bc4a2f15b1b35c70/merged"
at "/var/lib/docker/overlay2/f35aa5dd1518537f9ef25a00bd696aaa39207df223dbf812bc4a2f15b1b35c70/merged/usr/share/zoneinfo/UCT"
caused "not a directory":
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Which means that likely at the time the container was started, `/home/wm/gopingtai/localtime` was not (yet) present; that file is likely created by another process, and there's a race condition between that process creating the file, and docker starting.

When using the short-hand (`-v <host-path>:<container-path>`) notation to bind-mount a path from the host, docker looks if the path exists (`/home/wm/gopingtai/localtime`), and if it doesn't exist, it creates the path on the host (assuming you want to bind-mount a directory) and mounts that directory in the container. If the container has a file in the target location (so not a directory), that will fail, and this error is shown.


You can use the long-form (`--mount`) syntax instead, which does not try to create the path on the host, but instead will refuse to start the container if the host-path was not found. In your case, the options would be something like:

```bash
--mount type=bind,source=/home/wm/gopingtai/localtime,target=/usr/share/zoneinfo/UCT
```
Full docs can be found here: https://docs.docker.com/storage/bind-mounts/

For compose, the equivalent would be:

```yaml
volumes:
      - type: bind
        source: /home/wm/gopingtai/localtimec
        target: /usr/share/zoneinfo/UCT
```

(docs here: https://docs.docker.com/compose/compose-file/#long-syntax-3)


This is not a bug, so I'm closing this issue, but feel free to continue the conversation
