### ISSUE TITLE
Error using empty value label to place deployment constraint

### ISSUE THREAD

**Issue by NicholasNoise** [moby/moby#40688]
**Description**

Documentation [declares](https://docs.docker.com/engine/reference/commandline/node_update/#add-label-metadata-to-a-node) that it is possible to specify a node label as a key with an empty value:
```
docker node update --label-add jobs worker1
```

But is there any way to use an empty node label to specify a placement constraint using yml file to deploy stack?

I've tried to configure it:
```
  jobs:
    image: ${REGISTRY}/eais/jobs:${TAG}
    ports:
      - 8083:55555
    deploy:
      update_config:
        delay: 60s
      resources:
        reservations:
          memory: 128M
        limits:
          memory: ${JOBS_LIMIT_MEMORY}
      placement:
        constraints:
          - node.labels.jobs == ''
```

It fails with an error: 
failed to create service EAIS_jobs: Error response from daemon: rpc error: code = Unknown desc = value '' is invalid
Similar variant like:
- node.labels.jobs == ""
-- node.labels.jobs
fail too with the same error or very alike one.

**Output of `docker version`:**

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 43
 Running: 37
 Paused: 0
 Stopped: 6
Images: 220
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: tz5adu8wxvaqy55q3cxj51n2t
 Is Manager: true
 ClusterID: me81f5k817mfd1d2hjfhusngr
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.130.5.126
 Manager Addresses:
  10.130.5.126:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.6GiB
Name: CPIS-WEBEAIS
ID: CA2V:NEPP:CZQV:727D:22HW:3YDE:Z5E3:7OB7:KYLR:2AJQ:DW7R:UEV7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy.ics.perm.ru:8080/
HTTPS Proxy: http://proxy.ics.perm.ru:8080/
No Proxy: localhost,127.0.0.1,.ics.perm.ru
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 dh.ics.perm.ru
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by chrisbecke** [comment]
And, as a counter point, if labels are acutally used to store data, then a placement constraint based on the label simply existing would be nice:

```yaml
   placement:
    constraints:
    - node.labels.service!=''
```
Even more powerful perhaps if "~=" introduced a regex based matcher.

```yaml
   placement:
    constraints:
    - node.labels.acme~='.+' # have some value
    - node.labels.region~=`east^` # deploy only to *-east labeled regions.
```
