### ISSUE TITLE
network name substitution

### ISSUE THREAD

**Issue by burtsevyg** [moby/moby#40819]
Network name substitution does not work.
Please, see details in:
https://devops.stackexchange.com/questions/6317/docker-compose-yml-make-network-name-configurable-via-environment-variable

**Comment by cpuguy83** [comment]
Does is perport to support name substituion?
Is this a feature request, bug report, doc fix request?
In the future please fill in the details requested in the issue template.

In any case, docker-compose is in https://github.com/docker/compose, so closing this here. Please open on the compose repo with all the relevant details.

Thanks!

**Comment by burtsevyg** [comment]
This is docker swarm problem in my case.

**Comment by cpuguy83** [comment]
Can you report to github.com/docker/cli?

**Comment by thaJeztah** [comment]
I think this should be possible already if you use the `name` property for the network.

In that case, the name you _reference_ the network as (within the stack) will be fixed, but the name of the actual network that's created will be customized.

Something like this;

```yaml
networks:
  mynetwork:
    name: ${STAGE_NAME}:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${STAGE_NETWORK_PREFIX}.0/24
```

Inside the compose file, you'd reference the network as "mynetwork", but `docker network ls` will show the custom name. Take into account that that name is not "namespaced" (i.e., not prefixed with the stack name), so multiple stacks using that same custom name could collide
