### ISSUE TITLE
windows container start failed: The directory name is invalid

### ISSUE THREAD

**Issue by junneyang** [moby/moby#41114]
start error log:
```
Error: failed to start container "filebeat": Error response from daemon: hcsshim::CreateComputeSystem filebeat: The directory name is invalid. (extra info: {"SystemType":"Container","Name":"filebeat","Owner":"docker","VolumePath":"\\\\?\\Volume{edbc4b2a-af74-11ea-9104-ebbbbe384499}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\filebeat","Layers":[{"ID":"85844e08-93e7-509d-9274-046cca3abb4c","Path":"C:\\ProgramData\\docker\\windowsfilter\\4c46f52c2b51927bf5d7fa2af989674ebbd78a6d869ccf968e51260bfdd24c21"},{"ID":"e1bf5e5e-779c-5adc-a29a-e985ff793b2e","Path":"C:\\ProgramData\\docker\\windowsfilter\\6f5df0e54f3f99fa1175b4f68242878e803c2ec4e49f9bfe216ef9ace47ac367"},{"ID":"5d96494e-a417-5162-9c96-76cbb1a6bd25","Path":"C:\\ProgramData\\docker\\windowsfilter\\7a154798d982ead51c449e7ab73b5e4927a05dd8ab4fdec6c9db65b87b959e19"},{"ID":"e74dbacd-b920-5586-90af-e5afe764c492","Path":"C:\\ProgramData\\docker\\windowsfilter\\5dcc76e6eb9520b020ca8093e978c27f653044962bf930c45cb2f5e8a03c7ec3"},{"ID":"a6d4fa47-5ccc-524f-b42c-cdd55a17ca06","Path":"C:\\ProgramData\\docker\\windowsfilter\\14c269b796fdda27cbc785ffd1e77cb839e264384411a4d92bb9615436bc48d3"},{"ID":"e140cf34-15cb-506d-9c42-99c5a22481f7","Path":"C:\\ProgramData\\docker\\windowsfilter\\5f4013f468559093ea52f7dd21f7fae3761ab2ab6eb5416109d3b728b51b8fb6"},{"ID":"33fe2564-c7ea-55d2-99b1-1e58483d59bc","Path":"C:\\ProgramData\\docker\\windowsfilter\\d4b05ce91be3fb2c8d432fc220b8a19c2f7daab807998e80eab7bc81eff50cc7"}],"ProcessorWeight":5000,"HostName":"filebeat-trvtw","MappedDirectories":[{"HostPath":"c:\\var\\log","ContainerPath":"c:\\var\\log","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\3396cb90-4fd8-4997-baf3-76e9d341ecd6\\volumes\\kubernetes.io~configmap\\config","ContainerPath":"c:\\app\\filebeat\\filebeat.yml","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\docker\\containers","ContainerPath":"c:\\programdata\\docker\\containers","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\3396cb90-4fd8-4997-baf3-76e9d341ecd6\\volumes\\kubernetes.io~secret\\filebeat-token-pph2j","ContainerPath":"c:\\var\\run\\secrets\\kubernetes.io\\serviceaccount","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"NetworkSharedContainerName":"6bbfdcb99e7d03ff31e332e74c47eaeb9a452383b25721831ccf6e376f02e07e"})
```

daemonset.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
      #  - /var/log/containers/*.log
        - C:\var\log\containers\*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                #logs_path: "/var/log/containers/"
                logs_path: "C:\var\log\containers\"
    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    #output.elasticsearch:
    #  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
    #  username: ${ELASTICSEARCH_USERNAME}
    #  password: ${ELASTICSEARCH_PASSWORD}
    # https://www.elastic.co/guide/en/beats/filebeat/current/kafka-output.html
    output.kafka:
      hosts: ["10.0.90.133:9093","10.0.90.136:9093","10.0.90.130:9093","10.0.90.134:9093","10.0.90.126:9093"]
      version: "0.11.0.0"
      username: "jason"
      password: "jason"
      topic: "paas-admin-log"
      enabled: true
      timeout: 30
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker-repo.vanke.com/k8s-vanke/docker.elastic.co/beats/filebeat:7.6.1-win
        imagePullPolicy: Always
        #args: [
        #  "-c", "/etc/filebeat.yml",
        #  "-e",
        #]
        env:
        #- name: ELASTICSEARCH_HOST
        #  value: elasticsearch
        #- name: ELASTICSEARCH_PORT
        #  value: "9200"
        #- name: ELASTICSEARCH_USERNAME
        #  value: elastic
        #- name: ELASTICSEARCH_PASSWORD
        #  value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #securityContext:
        #  runAsUser: 0
        #  # If using Red Hat OpenShift uncomment this:
        #  #privileged: true
        #resources:
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        volumeMounts:
        - name: config
          #mountPath: /etc/filebeat.yml
          mountPath: C:\app\filebeat\filebeat.yml
          #readOnly: true
          #subPath: filebeat.yml
        #- name: data
        #  #mountPath: /usr/share/filebeat/data
        #  mountPath: C:\app\filebeat\data
        - name: varlibdockercontainers
          #mountPath: /var/lib/docker/containers
          mountPath: C:\ProgramData\docker\containers
          #readOnly: true
        - name: varlog
          #mountPath: /var/log
          mountPath: C:\var\log
          #readOnly: true
      volumes:
      - name: config
        configMap:
          #defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          #path: /var/lib/docker/containers
          path: C:\ProgramData\docker\containers
      - name: varlog
        hostPath:
          #path: /var/log
          path: C:\var\log
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      #- name: data
      #  hostPath:
      #    #path: /var/lib/filebeat-data
      #    path: C:\var\lib\filebeat-data
      #    type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
```
