### ISSUE TITLE
Ingress ports are blinking during a deployment process 

### ISSUE THREAD

**Issue by IMMORTALxJO** [moby/moby#41368]
**Description**
Hi,
I have a 10 workers + 3 managers cluster ( 1,5k containers ), looks like ingress ports on nodes started to blink ( I believe during deployment processes only ), that causes Connection reset/timeouts waves. Ports are published by services with nginx ( 2-4 replicas ), with heathcheck, SIGQUIT exit signal and start-first policy. Docker version is 19.03.12, cluster have lots of deleteServiceInfoFromCluster errors in logs.

**Steps to reproduce the issue:**
I'm not sure if you can reproduce the issue, but these steps work on my cluster:
1. Deploy hello-world stack:
```
version: "3.7"

networks:
  default: ~

services:
  test:
    image: crccheck/hello-world:latest
    networks:
      - default
    ports:
      - 12345:8000
    healthcheck:
      test: ["CMD", "nc", "127.0.0.1", "8000"]
      interval: 15s
      timeout: 30s
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 8
      update_config:
        parallelism: 0
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        failure_action: pause
        order: start-first
```
2. Start service hello-world_test updating:
 ```while [[ 1 == 1 ]]; do docker service update --force hello-world_test; sleep 1;done;```
3. Run load test with 50rps on http://<node_address>:12345

**Describe the results you received:**
I ran tests for ten minutes and got:
```
1,231  +0   3.03% : 110 Connection timed out
285  +0   0.70% : 113 No route to host
17  +0   0.04% : 111 Connection refused
4  +0   0.01% : 104 Connection reset by peer
```

**Describe the results you expected:**
Service update is downtimeless under a load test

**Additional information you deem important**
During a load test on all workers and managers I got warnings and errors like:
```
time="2020-08-18T13:46:21.640931340Z" level=warning msg="rmServiceBinding cleanupServiceBindings hello-world_test c1e530abf1114ecc02f965aed6556cfe9e6629f55d5f4bea9d031a3b64387a54 aborted c.serviceBindings[skey] !ok"
...
time="2020-08-18T13:47:17.472586581Z" level=error msg="failed adding service binding for 5112320e703d81ef24d5a54557259030481cf9aaad396f3bad794dd042950c4b epRec:{hello-world_test.8.lryv0hxma2akepmg85aemr961 hello-world_test mqfijumm43s4b8v7jlsnibfh7 10.0.108.2 10.0.108.57 [] [test] [75aaa62b33f4] false} err:network 1ykphih3zhtrc847x8xaw4ioi not found"
```
Thought my networkdb is corrupted. I cleaned networkdb on a random worker, it didn't help, ports on this worker are still blinking during deployments, deleteServiceInfoFromCluster errors still appears in worker logs.
I have no issues with ingress, when no deployments processing.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 17
  Running: 12
  Paused: 0
  Stopped: 5
 Images: 20
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: o7mhskcgicradgrtda2kj75vq
  Is Manager: true
  ClusterID: bknezdiqmpsy2nwj4vj0imxwz
  Managers: 3
  Nodes: 13
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.10.10.58
  Manager Addresses:
   10.10.10.58:2377
   10.10.10.59:2377
   10.10.10.60:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-0.bpo.6-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
 Name: swarm-manager-01
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 365
  Goroutines: 492
  System Time: 2020-08-18T13:23:30.578287865Z
  EventsListeners: 13
 Registry: https://index.docker.io/v1/
 Labels:
  provider=generic
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal cluster

**Comment by thaJeztah** [comment]
- is the `~` after your default network (`default: ~`) actually in your file, or is that a typo?
- I see your configuration uses `parallelism: 0` (all instances of the services are updated at once); does changing that make a difference?

The warning comes from libnetwork; https://github.com/moby/libnetwork/blob/d503f05bdc666390fe87a05ddb4cd578abf60eb3/service_common.go#L323

Wondering if the error (`err:network 1ykphih3zhtrc847x8xaw4ioi not found`) relates to the `parallelism: 0`, and if that causes a race condition where the network is removed from the node when all tasks are shutdown, then causes the error when the new tasks are created. (That wouldn't match with the `start-first` though)

**Comment by IMMORTALxJO** [comment]
>is the ~ after your default network (default: ~) actually in your file, or is that a typo?

That's copy-paste from a workable file, it works, networks section could be omitted anyway.

>I see your configuration uses parallelism: 0 (all instances of the services are updated at once); does changing that make a difference?

Just tried parallelism 1/2 , looks like it doesn't matter, timeouts still exist =(

> that causes a race condition where the network is removed from the node when all tasks are shutdown

Tried to add global service **spread** to be sure that **hello-world_default** network exists on all nodes during the test ( final docker-compose.yaml ):
```
version: "3.7"

services:
  test:
    image: crccheck/hello-world:latest
    networks:
      - default
    ports:
      - 12345:8000
    healthcheck:
      test: ["CMD", "nc", "127.0.0.1", "8000"]
      interval: 15s
      timeout: 30s
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 8
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        failure_action: pause
        order: start-first

  spread:
    image: crccheck/hello-world:latest
    networks:
      - default
    healthcheck:
      disable: true
    deploy:
      mode: global
```
but timeouts still appear.

Noticed that manager-leader has rpc errors, as for me, quite strange that manager couldn't find network or service:
```
time="2020-08-18T20:16:02.969936613Z" level=debug msg="Calling GET /v1.40/networks/hello-world_default"
time="2020-08-18T20:16:02.970579161Z" level=debug msg="error handling rpc" error="rpc error: code = NotFound desc = network hello-world_default not found" rpc=/docker.swarmkit.v1.Control/GetNetwork
time="2020-08-18T20:15:50.669488964Z" level=debug msg="Calling GET /v1.40/services/hello-world_test?insertDefaults=false"
time="2020-08-18T20:15:50.669720767Z" level=debug msg="error handling rpc" error="rpc error: code = NotFound desc = service hello-world_test not found" rpc=/docker.swarmkit.v1.Control/GetService
time="2020-08-18T20:15:50.459404175Z" level=debug msg="error handling rpc" error="rpc error: code = NotFound desc = service hello-world_test not found" rpc=/docker.swarmkit.v1.Control/GetService
time="2020-08-18T20:15:50.458130914Z" level=debug msg="Calling GET /v1.40/services/hello-world_test?insertDefaults=false"
time="2020-08-18T20:15:50.458436717Z" level=debug msg="error handling rpc" error="rpc error: code = NotFound desc = service hello-world_test not found" rpc=/docker.swarmkit.v1.Control/GetService
time="2020-08-18T20:15:50.248202010Z" level=debug msg="error handling rpc" error="rpc error: code = NotFound desc = service hello-world_test not found" rpc=/docker.swarmkit.v1.Control/GetService
```
Also cluster logs `Network not found / Bulk sync to node XXX timed out / deleteServiceInfoFromCluster` errors quite often
<img width="300" alt="Screenshot 2020-08-18 at 23 40 06" src="https://user-images.githubusercontent.com/3237625/90563224-28999600-e1ac-11ea-9ac2-618d1caad909.png">
