### ISSUE TITLE
Is there a anyway hide veth interface on using docker-compose？

### ISSUE THREAD

**Issue by n1ngod** [moby/moby#41571]
I use docker-compose to create a application, it works well, but it will create many veth interface, the image expose a port even though i don't mapping this port.I only use the container alias to access this service. The following is a minimal example：
```
version: "3.0"
services:
  mysql: mysql:latest
  ...other options

  redis:
  redis: redis:latest
  ...other options

  web:
  image: xxxx
  ports:
    - "80:80"
  links:
    - mysql:mysql
    - redis:redis
  depends_on:
    - mysql
    - redis 
   ...other options
```
Execute docker-compose up -d, it will be create three veth interface and a briage. now i use many container to create my application, too many veth be created, maybe even more than 30. interface manager in linux gui show long long list.
Is there anyway not to generate so many virtual interface or hide them？
