### ISSUE TITLE
Rootless mode overwrites public IP to Docker's IP

### ISSUE THREAD

**Issue by hopkinskong** [moby/moby#41789]
**Description**

In rootless mode with `cap_net_bind_service` for `rootlesskit`, when running a nginx reverse proxy container, all connections from the public will result in the IP be `172.xx.0.1` rather than the real IP of clients.
Running in root mode will not have this issue.

**Steps to reproduce the issue:**
`docker-compose.yaml`
```
version: '2'

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "443:8443"
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      default:
      internal:
    depends_on:
      - some_service
    container_name: some_service_proxy
  some_service:
    build: .
    restart: always
    networks:
        default:
        internal:
    container_name: some_service
networks:
    default:
    internal:
        internal: true
```
1. (In rootless mode/non-root user) `docker-compose up`
2. When trying to access to the nginx container from the public, `logs/access.log` produces IP from `172.28.0.1`

**Describe the results you received:**
Running in rootless mode:
![image](https://user-images.githubusercontent.com/2718385/102121033-4aff9f80-3e7e-11eb-86cb-e3d82c4cf570.png)

**Describe the results you expected:**
Running in non-rootless (i.e Root) mode:
![image](https://user-images.githubusercontent.com/2718385/102121177-84380f80-3e7e-11eb-9161-17f2560eeb96.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 11
  Paused: 0
  Stopped: 4
 Images: 197
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-1029-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 953.4MiB
 Name: ip-XXX-XXX-XXX-XXX
 ID: 5EKI:E267:PLUD:6RCO:ENY6:JLRU:3BRJ:4X6T:FKYI:PUJ6:FI7K:GASP
 Docker Root Dir: /home/XXX/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running off from a AWS EC2 Instance, but I don't think it really matters.
Rootlesskit is installed manually with systemd user unit.

Not sure if it is related with https://github.com/docker/for-mac/issues/180
