### ISSUE TITLE
docker stack deploy to a remote host does not pass on ulimits

### ISSUE THREAD

**Issue by bgemmill** [moby/moby#41923]
**Description**

If we have ulimits defined for a service in a docker yml file:
```
version: "3"

services:
  test:
    image: debian
    command: /bin/bash -c "ulimit -a && sleep 15"
    ulimits:
      memlock: -1
    deploy:
      mode: replicated
```

calling docker like this will work correctly (as per https://github.com/docker/cli/pull/2712):
`docker stack deploy --compose-file docker-compose.yaml test`

But if we try to deploy non-locally, ulimits seem to get ignored:
`docker stack deploy -H=www.elsewhere.com:2376 --compose-file docker-compose.yaml test`

**Steps to reproduce the issue:**
1. deploy a socker stack yml file that specifies ulimits non-locally
2. observe ulimits not getting set by `docker service inspect --pretty test`

**Describe the results you received:**
The default memlock of 64k

**Describe the results you expected:**
Unlimited memlock

**Output of `docker version`:**

```
Docker version 20.10.2, build 2291f61
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 20.04.1 with the docker ppa
