### ISSUE TITLE
Networking - DNS collision when on same  external network.

### ISSUE THREAD

**Issue by mesudip** [moby/moby#41961]
**Description**

I am using a common network called frontend to connect any service to nginx service and auto-configure it there.
 
The compose file below will work as expected with no problem
```yaml 
networks:
   frontend:
     external: true
 server:
    image:...
    networks:
      frontend:
 dependent-api-service:
    image:...
    environment:
       COMPONENT_URL: http://server:8080
    networks:
      frontend:     
```

But if I decide to add another stack `stack2` with  a service `server` and connect it to network frontend. my `dependent-api-service` will see both the `stack1_server` and `stack2_server`  as `server` and it will get load balanced. Which is not intended.

Also, chainging configuration to `server.networks.frontend.aliases=['unique-name']` will make the ContainerSpec to have both `server` and `unique-name` to be added to that network instead of getting overridden.

My proposal is that when using external network, the service's  shouldn't be added as alias by default.  We can use `stackname_service` instead. If the user wants it to be same as service name, they can always add it to the list of alias

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
