### ISSUE TITLE
Product Support - User-defined healthchecks based on a specific log 

### ISSUE THREAD

**Issue by ansred** [moby/moby#42085]
Greetings,

I would like to use autoheal container for a user-defined healthchecks.
https://hub.docker.com/r/willfarrell/autoheal

For example, if I have qBittorrent and it's facing a specific log that causing issue to keep it running, I want autoheal to detect that log whenever it shows up and then restart that container.

Here is a detailed screenshot and log how it looks like:
https://github.com/linuxserver/docker-qbittorrent/issues/105

FYI:

sure, here is the docker compose I used for my setup

```
---
version: '2.4'
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - WEBUI_PORT=9080
    volumes:
      - /volume1/docker/qBittorrent/config:/config
      - /volume1/docker/qBittorrent/downloads:/downloads
    restart: unless-stopped
```

Network setup is going through another docker compose stack (gluetun) VPN container

Is that possible, and can advise please on what to edit the stack above in order to get it working as requested?

Thanks in advance
