### ISSUE TITLE
Error response from daemon: failed to create endpoint (...) on network (...): failed to add the host (veth...) <=> sandbox (veth...) pair interfaces: operation not permitted

### ISSUE THREAD

**Issue by zeling** [moby/moby#42107]
**Description**

**Steps to reproduce the issue:**
I can't reproduce this reliably, we only see this error message once over the past few months. The code that produces this error message looks like:
```
network, err := client.NetworkCreate(ctx, name, opts)
if err != nil {
  return fmt.Errorf("failed to create network: %v", err)
}
...
if err := client.NetworkConnect(ctx, network.ID, c.id, &settings);  err != nil {
  return fmt.Errorf("failed to attach network to container %s: %v", container.id, err)
}
....
if err := c.client.ContainerStart(ctx, c.id, types.ContainerStartOptions{}); err != nil {
  return fmt.Errorf("ContainerStart failed: %v", err)
}
```
**Describe the results you received:**

ContainerStart failed: Error response from daemon: failed to create endpoint ... on network ...: failed to add the host (veth...) <=> sandbox (veth...) pair interfaces: operation not permitted

**Describe the results you expected:**

I expect it to succeed. What could have contributed to this failure message?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:29 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux nvidia runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.9.12-050912-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.595GiB
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by patheticGeek** [comment]
Were you able to solve this issue? I am having the same issue.
I am using Archo linux, same thing works in Manjaro, Ubuntu and windows.

Command I'm running
```sh
pg-pc:  ~/.../backend/devsnest  |main ✓|
→ docker-compose -f docker-compose-dev.yml up mysql
Pulling mysql (mysql:)...
latest: Pulling from library/mysql
33847f680f63: Pull complete
5cb67864e624: Pull complete
1a2b594783f5: Pull complete
b30e406dd925: Pull complete
48901e306e4c: Pull complete
603d2b7147fd: Pull complete
802aa684c1c4: Pull complete
715d3c143a06: Pull complete
6978e1b7a511: Pull complete
f0d78b0ac1be: Pull complete
35a94d251ed1: Pull complete
36f75719b1a9: Pull complete
Digest: sha256:8b928a5117cf5c2238c7a09cd28c2e801ac98f91c3f8203a8938ae51f14700fd
Status: Downloaded newer image for mysql:latest
Creating mysql ... error

ERROR: for mysql  Cannot start service mysql: failed to create endpoint mysql on network devsnest_default: failed to add the host (veth8ae17d6) <=> sandbox (veth82d4dda) pair interfaces: operation not supported

ERROR: for mysql  Cannot start service mysql: failed to create endpoint mysql on network devsnest_default: failed to add the host (veth8ae17d6) <=> sandbox (veth82d4dda) pair interfaces: operation not supported
ERROR: Encountered errors while bringing up the project.
```

My `docker-compose-dev.yml` file
```yml
version: "3"
services:
  "backend":
    build: .
    ports:
      - "8000:3000"
    container_name: backend
    env_file:
      - '.env'
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devsnest
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis
```
