### ISSUE TITLE
Unexpected warning when using secrets in Docker Compose

### ISSUE THREAD

**Issue by chrischu** [moby/moby#42180]
**Description**

I am trying to add secrets to my Windows Docker container via Docker Compose and I got it to work, but now I get a weird warning starting the container:
![image](https://user-images.githubusercontent.com/447251/111973905-4262d900-8aff-11eb-88c0-cd84c613f092.png)

**Steps to reproduce the issue:**
1. When using the following Docker Compose file:
api.yml
```
version: "3.7"
services:
  api:
    image: api
    secrets:
      - source: all
        target: C:\secrets\ # defines where the secrets will be available in the container
secrets:
  all:
    file: ./secrets/
```
2. with the directory structure:
```
api.yml
secrets/
  secret
```
3. and running `docker-compose -f api.yml up`

**Describe the results you received:**
I get the warning:
![image](https://user-images.githubusercontent.com/447251/111973905-4262d900-8aff-11eb-88c0-cd84c613f092.png)

**Describe the results you expected:**
I expected no warning to show up.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried various other ways to use secrets (e.g. by not specifying a directory, but the path for every secret) but I couldn't get those solutions to work because of the following error messages:
When using
```
services:
   api:
     ...
   secrets:
      - secret
secrets:
  secret:
    file: ./secrets/secret   
```
```
ERROR: for bbea49dbfb24_api  Cannot create container for service api: invalid mount config for type "bind": invalid mount path: '/run/secrets/secret'
```
and when using
```
services:
   api:
     ...
   secrets:
      - source: secret
        target: C:/secrets/secret
secrets:
  secret:
    file: ./secrets/secret   
```
```
ERROR: for bbea49dbfb24_api  Cannot create container for service api: invalid mount config for type "bind": source path must be a directory
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:26:56 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 296
 Server Version: 20.10.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19042.867)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.85GiB
 Name: W1118
 ID: DO2B:NGB7:SEFO:KS4Z:ZQJV:23BI:BVGH:MBOK:2H5B:AL3P:DFAB:SPVR
 Docker Root Dir: D:\DockerData
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 29
  System Time: 2021-03-22T11:09:28.2863809+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It's a physical Windows machine with version:
![image](https://user-images.githubusercontent.com/447251/111975204-9d490000-8b00-11eb-8dd8-2dd1085f8fd5.png)
