### ISSUE TITLE
Feature: Expand service templates to include .Node.Labels

### ISSUE THREAD

**Issue by chrisbecke** [moby/moby#42597]
**Description**

When deploying replicated services, it is useful to have more properties than just the .Node.Hostname and .Node.ID available to service templates.

In the given example: .Node.Labels would allow a service (like etcd) to be given an id per swarm node that matches the requirements of the statically generated INITIAL_CLUSTER string.

```yaml
volumes:
  etcd-data:
    driver: local

services:
  etcd:
    image: quay.io/coreos/etcd:3.5
    hostname: etcd{{index .Node.Labels etcd.id}}
    volumes:
    - etcd-data:/data.etcd
    environment:
      ETCD_NAME: etcd{{index .Node.Labels etcd.id}}
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380;etcd2=http://etcd2:2380;etcd3=http://etcd3:3280
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.etcd.id != ''
```

Additionally, without #40688, the placement constraint would require a second label `etcd.enable==true`.
