### ISSUE TITLE
feature: disable network aliases per network

### ISSUE THREAD

**Issue by chrisbecke** [moby/moby#42603]
**Description**

When adding services to multiple common networks, ambiguous dependencies can be picked up.

This `stack.yml` file demonstrates the problem that happens in real production stacks. Inevitably, two services in a single stack, where one depends on another, share a private network for 1:1 communication.
However, they may also incidentally share a public network such as `traefik`, `prometheus`, that is used for ingress, logging or metrics gathering.

**Steps to reproduce the issue:**

```yaml
version: "3.9"

networks:
  private:
    driver: overlay
  public:
    name: public_network
    external: true

services:
  db:
    image: alpine
    command: ["tail", "-f", "/dev/null"]
    networks:
      public:
      private:

  api:
    image: alpine
    command: ["tail", "-f", "/dev/null"]
    networks:
      private:
      public:
```

1. docker stack deploy --compose-file docker-compose.yml test1
2. docker stack deploy --compose-file docker-compose.yml test2
3. docker service ps test1_api --no-trunc
4. docker exec -it test1_api.1.pbxd55yd0f6ccytvbl757fdgb sh
5. apk add bind-tools
6. dig tasks.db

**Describe the results you received:**

tasks.db returns an array of A records indicating that traffic would be load balanced between the api and the db's in the different stacks.

**Describe the results you expected:**

Each stack should have its own, private db replica(s).

**Discussion**

The only way to work around this, currently, appears to be to create an explicit (and different) alias on the desired network, and use that explicitly in any connection strings.

Additionally, when there are multiple networks connecting two containers, it seems entirely unclear which IPs networks dockers dns will chose, which will be problematic if the listening app is bound to a specific interface (eth0 etc).
