### ISSUE TITLE
Swarm services do not remove their dead containers

### ISSUE THREAD

**Issue by kostrzewa9ld** [moby/moby#42723]
<!--
If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

For more information about reporting issues, see
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#reporting-other-issues

---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------

The GitHub issue tracker is for bug reports and feature requests.
General support for **docker** can be found at the following locations:

- Docker Support Forums - https://forums.docker.com
- Slack - community.docker.com #general channel
- Post a question on StackOverflow, using the Docker tag

General support for **moby** can be found at the following locations:

- Moby Project Forums - https://forums.mobyproject.org
- Slack - community.docker.com #moby-project channel
- Post a question on StackOverflow, using the Moby tag

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

Swarm services deployed as stack on 3 nodes. After a reboot some services do not cleanup their dead containers. The number of dead, orphaned containers grow with each reboot.

**Steps to reproduce the issue:**
1. Setup swarm (with task history limit set to 2 to quickly identify orphaned containers)
2. Create overlay network (`docker network create --driver=overlay --attachable testnet`)
2. Deploy a couple of swarm services, e.g. by deploying stack from following compose file:
```
version: '3'
services:
  svc1:
    image: nginx
    networks: [testnet]
  svc2:
    image: nginx
    networks: [testnet]
  svc3:
    image: nginx
    networks: [testnet]
  svc4:
    image: nginx
    networks: [testnet]
  svc5:
    image: nginx
    networks: [testnet]
  svc6:
    image: nginx
    networks: [testnet]
  svc7:
    image: nginx
    networks: [testnet]
  svc8:
    image: nginx
    networks: [testnet]
  svc9:
    image: nginx
    networks: [testnet]
  svc10:
    image: nginx
    networks: [testnet]
  svc11:
    image: nginx
    networks: [testnet]
  svc12:
    image: nginx
    networks: [testnet]
  svc13:
    image: nginx
    networks: [testnet]
  svc14:
    image: nginx
    networks: [testnet]
  svc15:
    image: nginx
    networks: [testnet]

networks:
  testnet:
    external: true
```
3. Reboot nodes, wait for services to come up, repeat

**Describe the results you received:**

After multiple reboots dead containers pile up on the machines, e.g.:
```
ssh 10.9.4.156 sudo docker ps -a | wc -l                                                                                                                                                                                                                                                                          
311
```

**Describe the results you expected:**
The number of containers for each service is maximally the value set for swarm task history limit.


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
First discovered on version 18.09.5 but reproduced on the latest one.

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 310
  Running: 5
  Paused: 0
  Stopped: 305
 Images: 1
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 2ivrzu7pxa8uex84efkqohesp
  Is Manager: true
  ClusterID: v0homa5t81ckt1mew4ak9n96p
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 2
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.9.4.156
  Manager Addresses:
   10.9.4.156:2377
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.64GiB
 Name: node-10-9-4-156
 ID: AQTE:ZA2H:JRBH:RNMU:AJ5U:PNKL:GTAF:YCQ5:BJQM:ROCT:HMLL:MQV7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMs on KVM with CentOS Linux release 7.7.1908 (Core) (kernel as outputted by `docker info`)
