### ISSUE TITLE
Same IP address for 2 containers from resolver

### ISSUE THREAD

**Issue by TheBestPessimist** [moby/moby#43016]
**Description**

Related: https://discourse.linuxserver.io/t/nginx-upstream-app-works-when-app-contains-underscores-but-not-with-dashes/3557/

I am using linuxserver/swag for nginx + my docker-compose containers.

I am using a bridge network to link all of them together:

```
docker network create nginx-common
```

I have 2 docker compose containers running and the only difference between them is the container_name:

Main app `telegram-bot`:
```yaml
version: "2.4"
services:
  telegram-bot:
    # container_name: telegram_bot  # ✅  
    container_name: telegram-bot  # ❌ 

    image: thebestpessimist/duplicacy-utils-telegram-bot:latest
    restart: unless-stopped
    mem_limit: 80m
    environment:
      WEBSERVER_ADDRESS:
      WEBHOOK_ROUTE:
      TELEGRAM_API_TOKEN:
      CERTIFICATE_PATH:

networks:
  default:
    external: true
    name: nginx-common
```

Test app `telegram-bot-test`:
```yaml
version: "2.4"
services:
  telegram-bot:
    # container_name: telegram_bot_test # ✅ 
    container_name: telegram-bot-test # ❌ 
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest
    restart: unless-stopped
    mem_limit: 80m
    environment:
      WEBSERVER_ADDRESS:
      WEBHOOK_ROUTE:
      TELEGRAM_API_TOKEN:
      CERTIFICATE_PATH:

networks:
  default:
    external: true
    name: nginx-common
```

**Steps to reproduce the issue:**

1. Run the containers at the same time, on the bridge network
2. Ping the 2 containers from inside the swag container

**Describe the results you received:**

when pinging from inside the swag container, sometimes those 2 containers have the same IP:
```
root@racknerd-c53fac:~# docker exec swag ping telegram-bot -c 1
PING telegram-bot (172.21.0.4): 56 data bytes
64 bytes from 172.21.0.4: seq=0 ttl=64 time=0.191 ms
```
```
root@racknerd-c53fac:~# docker exec swag ping telegram-bot-test -c 1
PING telegram-bot-test (172.21.0.4): 56 data bytes
64 bytes from 172.21.0.4: seq=0 ttl=64 time=0.290 ms
```

this leads to nginx proxy passing to the "correct host, but wrong IP" (see at the end of the lines):

```
91.108.6.103 - - [14/Nov/2021:17:55:00 +0000] "POST https://duplicacy-utils.tbp.land/telegram/TELEGRAM_UPDATE_WEBHOOK_ROUTE HTTP/2.0" 200 0 "-" "-" 0.248 PROXY: "telegram-bot:13337 172.21.0.4:13337"
91.108.6.103 - - [14/Nov/2021:17:55:08 +0000] "POST https://duplicacy-utils.tbp.land/telegram/TELEGRAM_UPDATE_WEBHOOK_ROUTE HTTP/2.0" 200 0 "-" "-" 0.255 PROXY: "telegram-bot:13337 172.21.0.4:13337"
91.108.6.103 - - [14/Nov/2021:17:55:12 +0000] "POST https://duplicacy-utils.tbp.land/telegram/TELEGRAM_UPDATE_WEBHOOK_ROUTE HTTP/2.0" 200 0 "-" "-" 0.181 PROXY: "telegram-bot:13337 172.21.0.3:13337" # this one has the wrong IP for the correct host
```

Nnginx uses the following resolver (since the pings are also not working correctly this might not help, but here it is anyway):
```
resolver 127.0.0.11 ipv6=off valid=3s;
```
Also explained in https://discourse.linuxserver.io/t/nginx-upstream-app-works-when-app-contains-underscores-but-not-with-dashes/3557/5

**Describe the results you expected:**

ping and resolver should give different IPs for each container/hostname.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@racknerd-c53fac:/tmp# docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@racknerd-c53fac:/tmp#

```

**Output of `docker info`:**

```
root@racknerd-c53fac:/tmp# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-90-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.844GiB
 Name: racknerd-c53fac
 ID: 4QZK:E4PM:ZAOZ:V7I5:KQUP:DNOL:WT7D:PEH7:SOAH:UHZR:7RL2:VLOJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
root@racknerd-c53fac:/tmp#
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

One thing which I noticed is that if i use underscores in the name `_`, instead of dashes `-`, the IPs are always (?) resolved correctly. See the emoji in my example (the ✅ and ❌) , along with the whole discussion on linuxserver forum.

**Comment by thaJeztah** [comment]
Does it work correctly if you change the service name for one of them to something else?

I see both `telegram-bot` services are connected to the `nginx-common` network, and while the container name is changed, those services will likely also be resolvable by their service name (`telegram-bot`). Possibly something gets mixed up because of that for the network-scoped aliases as well.

**Comment by TheBestPessimist** [comment]
@thaJeztah, do you want something different than my last paragraph in OP?

to summarize using underscores (`_`) seems to work, while using dashes (`-`) does not work:

```
container_name: telegram_bot_test # ✅ this seems to work
```

```
container_name: telegram-bot-test # ❌ this doesn't not work
```

**Comment by TheBestPessimist** [comment]
This issue happens on version 19.03.latest as of 2021-11-14 (yesterday).

**Comment by thaJeztah** [comment]
> do you want something different than my last paragraph in OP?

Your example is setting explicit / fixed names for the _containers_ that are created, but when using compose, compose also adds network-scoped aliases for services.

For example;

```yaml
services:
  foo:
    image: bar
```

The above will;

- Create a network named `projectname_default`
- Create a container named (e.g.) `projectname_foo`, that's attached to the `projectname_default` network
- Create a network-scoped alias `foo` on the `projectname_default` network

So the container created for the `foo` service will be discoverable on the `projectname_default` network as `projectname_foo` and `foo`

In your case (below is a simplified version of your project);

```yaml
services:
  telegram-bot:
    # container_name: telegram_bot  # ✅  
    container_name: telegram-bot  # ❌ 
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest

networks:
  default:
    external: true
    name: nginx-common
```

Compose will:

- Use the existing `nginx-common` network as default network (instead of `projectname_default`
- Create a container named `telegram-bot` that's attached to the `nginx-common` network
- Create a network-scoped alias `telegram-bot` on the `nginx-common` network

The last bullet is what _may_ cause issues, because both projects have a `telegram-bot` service, and both use the `nginx-common` network, so as a result, resolving `telegram-bot` may resolve to either the container for the first project, or the service for the second project. And I'm wondering if that's what's causing the issue here.

**Comment by TheBestPessimist** [comment]
> because both projects have a `telegram-bot` service

I'm not trying to be an ass here, just checking if you missed something:

My 2 services have different `contaner names`, so why would that cause problems?

names:


Service 1: `telegram-bot`
```yaml
services:
  telegram-bot:
    container_name: telegram-bot  # ❌ 
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest

networks:
  default:
    external: true
    name: nginx-common
```

Service 2: `telegram-bot-test`
```yaml
version: "2.4"
services:
  telegram-bot:
    container_name: telegram-bot-test # ❌ 
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest

networks:
  default:
    external: true
    name: nginx-common
```

**Comment by thaJeztah** [comment]
> My 2 services have different contaner names, so why would that cause problems?

Compose always creates a network-scoped alias based on the _service name_ inside the docker-compose file; both stacks / compose-files have the same name for the service.

> The problem is most of the traffic is directed to Service 2: telegram-bot-test.

Due to the alias, service 2 can be resolved _both_ as `telegram-bot-test` and as `telegram-bot`, so it's more likely to receive network traffic, as it will be resolved to "both".

> I would expect most of the traffic to be directed to Service 1: telegram-bot, because this one has a shorter name

Shorter name should not matter here; DNS does not resolve to prefixes, only full names (it can resolve to partial names, but delimited by `.`, in combination with dns "search" suffices).

In your example, `telegram-bot` is resolving alternating between two IP-addresses. What are the IP-addresses for those containers if you inspect them?

```bash
docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "IPAddress"}}' telegram-bot
docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "IPAddress"}}' telegram-bot-test
```

I suspect in your example, `telegram-bot-test` is `172.21.0.4`, and `telegram-bot` is `172.21.0.3`

So resolution of `telegram-bot-test` is `correct, because it's the only container that will be resolved by that name, but for `telegram-bot`, you'll get a round-robin response for both (`telegram-bot` and `telegram-bot-test`) containers.

Here's (roughly) the equivalent of what's created with those two compose projects; create a network `nginx-common`, and two containers attached with different names, but _both_ containers also have an network-scoped alias for their service name (`telegram-both`), which is the same for both:

```bash
docker network create nginx-common
docker run -d --name telegram-bot      --network=nginx-common --network-alias=telegram-bot nginx:alpine
docker run -d --name telegram-bot-test --network=nginx-common --network-alias=telegram-bot nginx:alpine
```

- Container `telegram-bot` can be resolved by its name (`telegram-bot`) and the alias (`telegram-bot`) (which is based on the service name in the compose file, and happens to be the same as the container name)
- Container `telegram-bot-test` can be resolved by its name (`telegram-bot-test`) and the alias (`telegram-bot`)

So _both_ containers can be resolved through `telegram-bot`, in which case, the DNS will shuffle / round-robin the order in which the IP-addresses are returned.

So in the situation above;

- resolving `telegram-bot-test` will return the IP-address for container `telegram-bot-test`
- resolving `telegram-bot` will round-robin IP-addresses for either container.

In the above situation; the first container has `172.21.0.2`, and the second 172.21.0.3

```bash
docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "IPAddress"}}' telegram-bot
172.21.0.2

docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "IPAddress"}}' telegram-bot-test
172.21.0.3
```

But both containers have `telegram-bot` as network-scoped alias:

```bash
docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "Aliases"}}' telegram-bot
[telegram-bot 9fcff2987979]

docker container inspect --format '{{index .NetworkSettings.Networks "nginx-common" "Aliases"}}' telegram-bot-test
[telegram-bot 76a75d3c99d8]
```


When starting a container attached to the `nginx-common` network, and resolving `telegram-bot-test`, it is resolved to `172.21.0.3`:

```bash
docker run -it --rm --network=nginx-common alpine

/ # nslookup -type=A telegram-bot-test
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot-test
Address: 172.21.0.3

/ # nslookup -type=A telegram-bot-test
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot-test
Address: 172.21.0.3

/ # nslookup -type=A telegram-bot-test
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot-test
Address: 172.21.0.3
```

But `telegram-bot-test` resolves to both `172.21.0.3` and `172.21.0.3`, and the order in which those IP-addresses are returned can be different with each resolve;

```bash
/ # nslookup -type=A telegram-bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot
Address: 172.21.0.3
Name:	telegram-bot
Address: 172.21.0.2

/ # nslookup -type=A telegram-bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot
Address: 172.21.0.2
Name:	telegram-bot
Address: 172.21.0.3

/ # nslookup -type=A telegram-bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot
Address: 172.21.0.2
Name:	telegram-bot
Address: 172.21.0.3
```

### Using underscores

Remove the existing containers, and create new ones, this time using underscores for the container names (note that the _aliases_ will still be created by compose, based on the service name);

```bash
docker rm -fv telegram-bot telegram-bot-test

docker run -d --name telegram_bot      --network=nginx-common --network-alias=telegram-bot nginx:alpine
docker run -d --name telegram_bot_test --network=nginx-common --network-alias=telegram-bot nginx:alpine
```

Using underscores should not make a difference when resolving `telegram-bot`, which will still be a round-robin result;

```bash
docker run -it --rm --network=nginx-common alpine

/ # nslookup -type=A telegram-bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot
Address: 172.21.0.2
Name:	telegram-bot
Address: 172.21.0.3

/ # nslookup -type=A telegram-bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram-bot
Address: 172.21.0.3
Name:	telegram-bot
Address: 172.21.0.2
```

But if your proxy uses the container name for resolution (so `telegram_bot` and `telegram_bot_test`), it will return the expected container, because for those there's no ambiguity (there's no `telegram_bot` alias for either of the containers), so resolving those will only return a single IP:

```bash
docker run -it --rm --network=nginx-common alpine

/ # nslookup -type=A telegram_bot
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram_bot
Address: 172.21.0.2

/ # nslookup -type=A telegram_bot_test
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	telegram_bot_test
Address: 172.21.0.3
```

**Comment by TheBestPessimist** [comment]
> Compose always creates a network-scoped alias based on the _service name_ inside the docker-compose file

Please excuse my stupidity. I read `service name`, but always thought of the `container name`. I apologize for wasting your time, albeit i learned something new today :).


I can confirm this works:



Service 1: `telegram-bot`
```yaml
services:
  telegram-bot:
    container_name: telegram-bot
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest

networks:
  default:
    external: true
    name: nginx-common
```

Service 2: `telegram-bot-test`
```yaml
version: "2.4"
services:
  telegram-bot-test: # this is the only change: old: telegram-bot, new: telegram-bot-test
    container_name: telegram-bot-test
    image: thebestpessimist/duplicacy-utils-telegram-bot:latest

networks:
  default:
    external: true
    name: nginx-common
```
