### ISSUE TITLE
Push (PATCH) does not provide auth token

### ISSUE THREAD

**Issue by Coronon** [moby/moby#43159]
**Description**

I am running my own registry and build my own auth provider, which works just fine. When pushing an image to the repo everythin works as expected, I am only experiencing issues with the `PATCH` request, as it does not provide authorization through the barer token, where as the prior `POST` request does.

**Steps to reproduce the issue:**
1. Tag an image so that it uses a custom registry `docker.example.com/hello-world`
2. `docker push docker.example.com/hello-world`

**Describe the results you received:**
`unauthorized: authentication required`

**Describe the results you expected:**
The push goes through

**Additional information you deem important (e.g. issue happens only occasionally):**

This may be related to #43158
Everything except the `PATCH` request works as expected (checked with tcpdump)
I am running the registry with the following settings:
```yaml
version: '3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://code.mydomain.com:8000/auth/docker
      REGISTRY_AUTH_TOKEN_SERVICE: docker.mydomain.com
      REGISTRY_AUTH_TOKEN_ISSUER: auth.mydomain.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/auth/auth_cert-pub.pem
    volumes:
      - /home/worker/docker_registry/certs/auth_cert-pub.pem:/certs/auth/auth_cert-pub.pem
      - /home/worker/docker_registry/data:/var/lib/registry
```

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.118GiB
 Name: docker-desktop
 ID: TXLL:G5L4:EORF:PG6G:TFWY:GXV2:U7NO:Z4CO:U536:A325:7JF2:OHK3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker desktop on windows _20H2 (OS Build 19042.1466)
