### ISSUE TITLE
After upgrade Docker Desktop to the latest version, WSL2 will crash when starting elasticsearch container.

### ISSUE THREAD

**Issue by GGXXLL** [moby/moby#43198]
**Description**

I just updated Docker Desktop to the latest version [4.4.4 (73704)], and nothing else has changed. 

When starting elasticsearch container, WSL2 will crash and need restart.

And i tried other containers (mysql, etcd, kafka...), The same situation did not occur.

**Steps to reproduce the issue:**
1. The docker-compse.yaml
```yaml
version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes: 
      - 'kafka:/bitnami/kafka'
  redis:
    container_name: redis
    image: 'redis:latest'
    ports: 
      - '6379:6379'
    volumes: 
      - 'redis:/usr/local/etc/redis'
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
    volumes: 
      - 'mysql:/var/lib/mysql'
  mongo-single:
    container_name: mongo-single
    image: 'mongo:latest'
    ports: 
      - '27017:27017'
    volumes: 
      - 'mongo-single:/data/db'
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    command: mongod --port 27017 --shardsvr --replSet rs1
    ports: 
      - '27017:27017'
    volumes: 
      - 'mongo:/data/db'
  mongo-slave:
    container_name: mongo-slave
    image: 'mongo:latest'
    command: mongod --port 27017 --shardsvr --replSet rs1
    ports: 
      - '27018:27017'
    volumes: 
      - 'mongo-slave:/data/db'
    depends_on: 
      - mongo
  etcd:
    container_name: etcd
    image: 'quay.io/coreos/etcd:latest'
    ports: 
      - '2379:2379'
      - '2380:2380'
    volumes: 
      - 'etcd:/etcd-data'
    command: 
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=node1 
      - --initial-advertise-peer-urls=http://node1:2380 
      - --listen-peer-urls=http://0.0.0.0:2380 
      - --advertise-client-urls=http://node1:2379 
      - --listen-client-urls=http://0.0.0.0:2379 
      - --initial-cluster 
      - node1=http://node1:2380
  bitnami-etcd:
    container_name: bitnami-etcd
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379
    ports:
      - 2379:2379
    volumes: 
      - 'bitnami-etcd:/etcd-data'
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports: 
      - '8123:8123'
      - '9000:9000'
    volumes: 
      - clickhouse:/var/lib/clickhouse
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
      - consul-server:/consul/data
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
      - consul-client:/consul/data
    networks:
      - consul
    command: "agent"
    depends_on: 
      - consul-server
  neo4j:
    image: neo4j
    container_name: neo4j
    volumes: 
      - neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio:/data'
networks:
  consul:
    driver: bridge
volumes: 
  redis: {}
  mysql: {}
  kafka: {}
  es: {}
  mongo: {}
  mongo-slave: {}
  mongo-single: {}
  etcd: {}
  clickhouse: {}
  consul-client: {}
  consul-server: {}
  bitnami-etcd: {}
  neo4j: {}
  jaeger: {}
  minio: {}
```

**Describe the results you received:**
```
docker-compose up es
[+] Running 2/2
 - Volume "workspace_es"  Created                                                                                                                                                                                0.0s 
 - Container es           Created                                                                                                                                                                                0.2s 
Attaching to es
EOF
```

**Describe the results you expected:**
WSL2 does not crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 14
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: FJKZ:6PD6:KDC2:PHIT:EQQL:KCII:MPDC:6DYA:Q4ER:F5LP:HCUR:LNX7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://ym67tcxn.mirror.aliyuncs.com/
  https://registry.docker-cn.com/
  http://hub-mirror.c.163.com/
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Supply: I am using Windows11 (10.0.22000.438)
