### ISSUE TITLE
Docker Swarm encrypted overlay network don't work with current Debian kernel 5.10.103-1

### ISSUE THREAD

**Issue by MichaelMFrost** [moby/moby#43359]
**Description**

After upgrade Kernel from 5.10.0-11-amd64 #1 SMP Debian 5.10.92-2 to 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 the encrypted
overlay network bewteen the nodes ends in error.

**Steps to reproduce the issue:**
1. Use: The Current Debian Kernel (5.10.0-12-amd64  SMP Debian 5.10.103-1)
2. Use: Docker 20.10.13
3. docker network create -d overlay --opt encrypted=true TestNet
4. Start containers with the network

**Describe the results you received:**
- No TCP Connection between the containers possible
- Log output:

Mar 10 14:18:31 srv01 dockerd[1297]: time="2022-03-10T14:18:31.277303894+01:00" level=warning msg="Failed Adding rSA{Dst: 10.55.2.11, Src: 10.55.2.10, Proto: esp, Mode: transport, SPI: 0xd457eb22, ReqID: 0xd0c4e3, ReplayWindow: 0, Mark: <nil>, OutputMark: 0, Ifid: 0, Auth: <nil>, Crypt: <nil>, Aead: {Name: rfc4106(gcm(aes)), Key: , ICV length: 64}, Encap: <nil>, ESN: false}: invalid argument"

Mar 10 14:18:31 srv01 dockerd[1297]: time="2022-03-10T14:18:31.277371111+01:00" level=warning msg="Failed Adding fSA{Dst: 10.55.2.10, Src: 10.55.2.11, Proto: esp, Mode: transport, SPI: 0x29ad0c9a, ReqID: 0xd0c4e3, ReplayWindow: 0, Mark: <nil>, OutputMark: 0, Ifid: 0, Auth: <nil>, Crypt: <nil>, Aead: {Name: rfc4106(gcm(aes)), Key: , ICV length: 64}, Encap: <nil>, ESN: false}: invalid argument."

Mar 10 14:18:31 srv01 dockerd[1297]: time="2022-03-10T14:18:31.277415765+01:00" level=warning msg="Adding fSP{{Dst: 10.55.2.10/32, Src: 10.55.2.11/32, Proto: 17, DstPort: 4789, SrcPort: 0, Dir: dir out, Priority: 0, Index: 0, Action: allow, Ifindex: 0, Ifid: 0, Mark: (0xd0c4e3,0xffffffff), Tmpls: [{Dst: 10.55.2.10, Src: 10.55.2.11, Proto: esp, Mode: transport, Spi: 0x29ad0c9a, Reqid: 0xd0c4e3}]}}: invalid argument"

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker-ce 20.10.13

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by grichner** [comment]
Hi Michael,

the same problem did happen on Amazon linux 2.
Version 5.10.93 and all kernel before work with IP-Sec encryption in a swarm multihost network... 
but since version 5.10.96 (08.02.2022) no traffic is sent to another node... so we set the kernel to the last working one.

Here is a sample to reproduce the toppic for an amazon linux 2:
1. Setup 2 Instances with amazon linux 2:
```
yum update -y ## in case the image is old and didn't have the latest SEC-updates
yum install -y yum-utils ##needs:restarting package
## always get the latest AWS Software even if the ami does (or does not)  
amazon-linux-extras install -y epel kernel-ng
yum install -y aws-cfn-bootstrap hibagent mlocate vim-enhanced bind-utils jq wget docker s3fs-fuse pv mc iotop net-tools nload amazon-efs-utils parallel fpart deltarpm
systemctl set-default multi-user.target ## default runlevel to non graphical
systemctl enable docker
systemctl restart docker
```
reboot the instances and do a swarm init and the corresponding join of the second node.
now you have installed the latest linux kernel - at time of writing 5.10.102.

2. now we can build a cluster with a simple enhanced container.
docker-compose.yaml:
```
# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yaml aws-grid --with-registry-auth --prune`
# Stop with `docker stack rm aws-grid`
 
version: '3.9'
 
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: "true"
 
services:
  node01:
    image: grichner/httpd-test
    deploy:
      placement:
        constraints:
          - node.hostname==node1.hostname.goes.here
      replicas: 1
      update_config:
        parallelism: 1
        delay: 120s
        order: start-first
      resources:
        reservations:
          memory: 300M
 
  node02:
    image: grichner/httpd-test
    deploy:
      placement:
        constraints:
          - node.hostname==node2.hostname.goes.here
      replicas: 1
      update_config:
        parallelism: 1
        delay: 120s
        order: start-first
      resources:
        reservations:
          memory: 300M
```
the above image was build the following way...
Dockerfile:
```
FROM httpd:latest
RUN apt-get update
RUN apt-get install -y curl tcpdump
```
(docker build .) or use mine from docker.io if you don't want to build it for yourself....

3. deploy the stack:
`docker stack deploy -c docker-compose.yaml aws-grid --with-registry-auth --prune`

4. get the running kernel version of all nodes:
<img width="1522" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158385495-cb06d93e-2099-4588-a6ec-bfb8cca8fa6b.png">

5. and than execute the following on one of the node-instances:
<img width="1209" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158390718-09e8796e-fce2-4fbb-a5b3-b939a5dc4036.png">
<img width="1526" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158391533-42ba4295-7de6-4a68-816a-3734bda856d0.png">
... as you can see it does **not** work

6. Now we set the last working kernel back in place:
```
# Install kernel in case not yet available
sudo yum install -y kernel-5.10.93-87.444.amzn2.x86_64
# Set the default boot image
sudo grubby --set-default /boot/vmlinuz-5.10.93-87.444.amzn2.x86_64
# Set up yum to ignore kernel* updates
sudo sh -c 'echo "exclude=kernel*" >> /etc/yum.conf'
```
reboot all node-instances (init 6)
AND
check the new running kernel version:
<img width="1535" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158393340-1fc816af-8124-4b7e-b653-873166ad4fab.png">
<img width="1544" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158393864-4c082bfc-0404-45d7-9db8-b066eb9b2c59.png">


7. than execute the curl again against the other node:
<img width="1219" alt="grafik" src="https://user-images.githubusercontent.com/33449338/158394333-3fd6efdd-c77b-4353-9240-aa3559b5de27.png">

as you can see it works now....

the problem seems to correlate to the kernel version >5.10.93
