### ISSUE TITLE
After an update to 20.10.14 containers no longer get NET_ADMIN capability

### ISSUE THREAD

**Issue by rluetzner** [moby/moby#43420]
**Description**

After updating to 20.10.14 overnight my Pi-Hole container stopped working. From the error message it looks like the container is missing NET_ADMIN capabilities, but they are present in the docker-compose file.
I triple checked that the pihole/pihole image was not updated overnight and retried everything with
- the latest image,
- and the previous image version released.

I was not yet able to test this on different systems, but rebooting and redeploying the whole docker-compose setup from scratch did not resolve the issue. The only thing that's changed on the system between yesterday to today was the update to the latest Docker version 20.10.14.

I only tested this with a docker-compose setup and did not yet have the time to transform this into a `docker run` command.

**Steps to reproduce the issue:**
1. Use docker-compose to deploy Pi-Hole and Cloudflared from the docker-compose.yml given below.
2. Log in to Pi-Hole
3. Enable the DHCP server in Pi-Hole's settings.
4. An (!) error sign will show up pretty quickly in the UI and Pi-Hole will show itself as being disabled.
5. Clicking the error sign will lead to a page displaying error logs with a message stating "missing required capability NET_ADMIN".

```yaml
---
version: '3.9'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      pihole_network:
      zz_dns_over_https:
        ipv4_address: 172.31.31.199
    ports:
      - "53/tcp"
      - "53/udp"
      - "67/udp"
      - "80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'REDACTED'
      ServerIP: REDACTED
      IPv6: 'true'
      PIHOLE_DNS_: 172.31.31.200#5054
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    depends_on:
      - cloudflared
    restart: unless-stopped

  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    networks:
      zz_dns_over_https:
        ipv4_address: '172.31.31.200'
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: REDACTED.0/24
        gateway: REDACTED
        ip_range: REDACTED/32
  zz_dns_over_https:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.31.0/24
```

**Describe the results you received:**

See steps above.

**Describe the results you expected:**

The Pi-Hole container should have all the required capabilites as they are defined in the docker-compose.yml.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happened right after updating to Docker 20.10.14

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:13 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:11 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)

Server:
 Containers: 24
  Running: 12
  Paused: 0
  Stopped: 12
 Images: 42
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.103-v7l+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 7.458GiB
 Name: raspberrypi
 ID: YEZC:JQ7N:NRCK:SNOA:53IW:5HCX:YOXD:QGFW:2AFG:FOA4:NZR4:BPYN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical on a Raspberry Pi 4B with 8GB RAM.

docker-compose version:

```
Docker Compose version v2.3.3
```
