### ISSUE TITLE
We recently encountered a similar issue on Azure, i.e. containers could ping containers on other nodes, but other traffic would hang indefinitely (e.g. curl, mysql, etc.).  Our issue was resolved by a different solution than those presented in this thread, so I'm posting it here for completeness/awareness.

### ISSUE THREAD

**Issue by dejeroWilliamScott** [moby/moby#43443]
Similar to #41775, we have observed incomplete network connectivity on Docker Swarm nodes (i.e. ICMP traffic succeeded for non-local nodes, but non-ICMP traffic hangs until timeout).  This has RCA'd to an interaction between the latest version of the Azure Linux Kernel for Ubuntu 18.04.
```
# functional
Linux test-vm-4 5.4.0-1072-azure #75~18.04.1-Ubuntu SMP Wed Mar 2 14:41:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 
# breaks cross-node traffic
Linux test-vm-5 5.4.0-1073-azure #76~18.04.1-Ubuntu SMP Thu Mar 10 11:17:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 
```
Downgrading the Kernel to 5.4.0-1072 (shown removing the 1073 version) restored cross-node container connectivity,
```
 sudo apt remove \
  linux-azure-5.4-cloud-tools-5.4.0-1073 \
  linux-azure-5.4-headers-5.4.0-1073 \
  linux-azure-5.4-tools-5.4.0-1073 \
  linux-modules-5.4.0-1073-azure \
  linux-modules-extra-5.4.0-1073-azure
sudo reboot
```
Interestingly, this connectivity loss is only present with encrypted networks.  
```
version: '3.7'

networks:
  encrypted:
    attachable: true
    driver: overlay
    driver_opts:
      encrypted: ""
  unencrypted:
    attachable: true
    driver: overlay

services:
  encrypted:
    image: "nginxdemos/hello"
    deploy:
      mode: global
    networks:
      - encrypted
    stdin_open: true
    tty: true
  unencrypted:
    image: "nginxdemos/hello"
    deploy:
      mode: global
    networks:
      - unencrypted
    stdin_open: true
    tty: true
```

_Originally posted by @dejeroWilliamScott in https://github.com/moby/moby/issues/41775#issuecomment-1079253961_
