### ISSUE TITLE
docker swarm network alias on service with replica > 1 doesn't get removed when switching alias to another service

### ISSUE THREAD

**Issue by firecow** [moby/moby#43528]
```shell
uname -r 5.13.0-40-generic
Docker version 20.10.14, build a224086
```

```yml
# docker-compose.yml
version: '3.8'
networks:
  default:
    attachable: true
services:
  api:
    image: ubuntu
    command: sleep infinity
    deploy:
      replicas: 2
    networks:
      default: { aliases: [testalias] }
  hola:
    image: ubuntu
    command: sleep infinity
```

```shell
docker stack deploy -c docker-compose.yml teststack
```

In another terminal call this docker run, to access `dig`
```shell
docker run --rm -it --network teststack_default abrander/looking-glass watch dig testalias
```

Now switch the alias to `hola` service

```yml
# docker-compose.yml
version: '3.8'
networks:
  default:
    attachable: true
services:
  api:
    image: ubuntu
    command: sleep infinity
    deploy:
      replicas: 2
  hola:
    image: ubuntu
    command: sleep infinity
    networks:
      default: { aliases: [testalias] }
```

```shell
docker stack deploy -c docker-compose.yml teststack
```

Now take a look at your `dig` and be very confused :smile: 

If  `api` doesn't have replicas > 1, this bug does not happen.
 

A `ping testalias` from within looking-glass will reveal that every other try, the host is unresolvable.
