### ISSUE TITLE
Feature request: Allow configuring how replicas are deployed in docker swarm.

### ISSUE THREAD

**Issue by jerrac** [moby/moby#43937]
### Description

Let me configure how my replicas are deployed. Specifically let me tell Swarm to deploy them one at a time. I can do that when running updates or rollbacks, but I can't do it when starting a stack for the first time. (At least as far as I've been able to test and search...)

My specific use case is a MariaDB cluster. One replica needs to be started first so that the other replicas can join the cluster instead of bootstrapping their own. I imagine this would be useful for any stateful cluster application.

Ideally I'd write something like:

```yaml
services:
  statefulclusterapp:
    image: statefulclusterapp:1.2.3
    deploy:
      replicas: 3
      deploy_config:
        parallelism: 1
      update_config:
        parallelism: 1
      
```

Alternatively, we could just treat deploy the same as update, so `update_config` would apply during deployment.

When looking for similar issues or requests, I did find: https://github.com/moby/moby/issues/31333. I did not contribute there because my request is specifically about deployment of replicas, not dependencies between services.

Thanks in advance for any consideration of my idea!

And thanks for making Docker in the first place. It's an amazing tool. :)
