### ISSUE TITLE
overlay networking seems to be broken on Ubuntu 22.04

### ISSUE THREAD

**Issue by s4ke** [moby/moby#44457]
### Description

overlay networking seems to be broken on Ubuntu 22.04

### Reproduce

Currently this bug was verified with these (non minimal) steps:

1. Change Ubuntu 22.04 VM to use iptables-legacy instead of nftables
2. Create a docker swarm on Ubuntu 22.04 with more than one node
3. Remove default ingress network, create with encryption turned on
4. Set up docker socket proxy using tecnativa/docker-socket-proxy (really just any docker container, but this is easier to reproduce for my case as this is from a real world example)
```
version: "3.8"

services:
  docker_socket_proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      docker_socket_proxy:
        aliases:
          - docker.socket.proxy.local

    environment:
      CONTAINERS: 1
      SERVICES: 1
      SWARM: 1
      NODES: 1
      NETWORKS: 1
      TASKS: 1
      VERSION: 1

    deploy:
      mode: global
      update_config:
        order: stop-first
        parallelism: 1
      rollback_config:
        order: stop-first
        parallelism: 1
      restart_policy:
        condition: on-failure

      placement:
        preferences:
          - spread: node.labels.host
        constraints:
          - node.role==manager
      
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

networks:
  docker_socket_proxy:
    driver: overlay
    attachable: true
    name: docker_socket_proxy
    driver_opts:
      encrypted: ""
```
5. Launch docker container on traefik-public network `docker run --rm -it --network docker_socket_proxy docker sh`
6. Run `ping docker.socket.proxy.local` - Works
7. Run `DOCKER_HOST=tcp://docker.socket.proxy.local:2375 docker ps` - Hangs

Console Output:
```
/ # ping docker.socket.proxy.local
PING docker.socket.proxy.local (10.1.0.2): 56 data bytes
64 bytes from 10.1.0.2: seq=0 ttl=64 time=0.586 ms
64 bytes from 10.1.0.2: seq=1 ttl=64 time=0.103 ms
^C
--- docker.socket.proxy.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.103/0.344/0.586 ms
/ # DOCKER_HOST=tcp://docker.socket.proxy.local:2375 docker ps
error during connect: Get "http://docker.socket.proxy.local:2375/v1.24/containers/json": dial tcp: lookup docker.socket.proxy.local: Try again
/ # DOCKER_HOST=tcp://10.1.0.2:2375 docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED              STATUS                    PORTS      NAMES
61a77209e0ee   docker                                 "docker-entrypoint.s…"   About a minute ago   Up About a minute                    jovial_perlman
044845395d27   docker:latest                          "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes                         charming_lederberg.1.xsjz289m6c25o3cxkzdenlca8
1baa4d896d67   traefik:v2.9                           "/entrypoint.sh trae…"   17 minutes ago       Up 17 minutes (healthy)   80/tcp     traefik_public_traefik_ingress.1.16jn4sq73p34r5g9cpfg8f77t
7e621a6a8ba6   tecnativa/docker-socket-proxy:latest   "/docker-entrypoint.…"   17 minutes ago       Up 17 minutes             2375/tcp   docker_socket_proxy_docker_socket_proxy.n107s8riublsi1ddqoqgl0ycn.ucly2dtswtx37nt4eihulwnnt
/ # 
```

### Expected behavior

overlay networking should work like 20.04 on 22.04

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: syslog
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: n107s8riublsi1ddqoqgl0ycn
  Is Manager: true
  ClusterID: ut15xlsdxbk4rpidhxhwpfuvv
  Managers: 3
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.2
  Manager Addresses:
   192.168.1.2:2377
   192.168.1.3:2377
   192.168.1.4:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-52-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.738GiB
 Name: manager-1
 ID: IEKS:KH3N:5B6X:QJE4:VTSV:SY23:3ZVR:ZMPO:CAFR:SLLJ:LUY3:JS2V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.18.0.0/16, Size: 24
```

### Additional Info

The swarm was automatically set up on Hetzner via:

https://github.com/neuroforgede/swarmsible
https://github.com/neuroforgede/swarmsible-hetzner
https://github.com/neuroforgede/swarmsible-example
