### ISSUE TITLE
Feature request: support templating in labels

### ISSUE THREAD

**Issue by bluepuma77** [moby/moby#44981]
### Description

According to [Docker service docs](https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates) templates are only supported in 3 flags:
- hostname
- mount
- env

It would be great to have templates also supported in `labels`. This would enable for example individual host URLs per node when using Traefik as reverse proxy:
```
  whoami:
    image: traefik/whoami:v1.8
    networks:
      - proxy
    deploy:
      mode: global
      labels:
        - traefik.http.routers.whoami.rule=Host(`{{.Node.Hostname}}-whoami.example.com`)
```
A lot of configuration is based on labels these days, so this would really be helpful for Docker user.

Related issues that would make this feature request even more useful: 
Moby: [Provide .Node.Labels in service templating](https://github.com/moby/moby/issues/39071)
SwarmKit: [docker service create template support for Node labels](https://github.com/moby/swarmkit/issues/2942)
