### ISSUE TITLE
UPnP support: docker daemon talk with router to do NAT automatically.

### ISSUE THREAD

**Issue by mercuriete** [moby/moby#45029]
### Description

I as a user I want to be able to configure the NAT on my router transparently.

example:
```
version: '3.8'
services:
  web:
    image: some-image
    ports:
      - '80:80'
```
if I do a docker-compose up -d, the behaviour is creating a container with a port being exposed.
the problem is that port is not exposed to the internet inside a IPv4 network inside a home router.

### Expected behaviour:
After exposing the port 80 on the host, the docker daemon will talk with the router using UPnP to create a new NAT rule to expose the same port on the internet ip of this router, redirecting to the host.
