### ISSUE TITLE
DinD cgroupv2 problem inside K8s

### ISSUE THREAD

**Issue by erichorwath** [moby/moby#45378]
### Description

Let's assume you have: 
- cgroupv2 only OS (e.g. Ubuntu 22.04 or [gardenlinux 934.7](https://github.com/gardenlinux/gardenlinux/releases/tag/934.7))
- A running Kubernetes cluster (e.g. Kind) on that OS
- Create a DinD pod with memory limits

Then create a container inside this DinD pod and it can consume more memory than the actual DinD pod is allowed to have...

### Reproduce

Make sure your K8s node OS is cgroupv2 only: 
``` 
mount | grep cgroup2
```
should return: `cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)`

Then deploy Dind-pod to your Kluster:
```
apiVersion: v1
kind: Pod
metadata:
    name: dind
spec:
    containers:
      - name: dind
        image: docker:dind
        resources:
            requests:
                cpu: 10m
                memory: 300Mi
            limits:
                cpu: 2
                memory: 300Mi
        securityContext:
            privileged: true
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
    volumes:
      - name: docker-graph-storage
        emptyDir: {}     
```

Then start some container inside the dind pod and consume more than 300 MB:
```
kubectl exec -it dind -- sh
docker run -it ubuntu bash
cat /dev/zero | head -c 400000000 | tail
```

### Expected behavior

Process should have been killed. Also K8s metrics server is reporting wrong numbers.
On Ubuntu 20 everything works as expected.

### docker version

```bash
fails also with latest Docker version
```

### docker info

```bash
see description
```

### Additional Info

This "DinD in K8s" approach is a typical use case for self-hosted Github Runners on K8s with the Actions Runner Controller:
https://github.com/actions/actions-runner-controller/issues/2284
We use it in our pipeline to spin up ephemeral Kind clusters which are running in the runner+dind pod.

**Comment by erichorwath** [comment]
update with `docker:24.0.5-dind-alpine3.18`:
- ✅ killing works 
- ❌ K8s metrics server reports still wrong numbers, although `docker stats` and `top` are showing the right values

**Comment by Shaked** [comment]
@erichorwath 

> update with `docker:24.0.5-dind-alpine3.18`:
> 
> * ✅ killing works
> * ❌ K8s metrics server reports still wrong numbers, although `docker stats` and `top` are showing the right values

Did the killing of the pod work for you? I am trying to do something similar from within a container that runs in a DinD, but when I try to stress test it, I only see the consumption of the pod going up but the pod stays the same:

```
Every 0.1s: kubectl top pods
01:54:21 2023

NAME                                  CPU(cores)   MEMORY(bytes)
tmp-dind-deployment-55c7ffd6f-dzjbd   2m           91Mi

Every 0.1s: kubectl top nodes                                                                                                        shakedm2.local: Wed Oct  4 01:54:32 2023

NAME                                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
aks-dfwc2a0-42121511-vmss00006x       7749m        99%    7690Mi          32%
````

The deployment:

```
export SPECIFIC_NODE=... 
k apply -f -<<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmp-dind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmp-dind
  template:
    metadata:
      labels:
        app: tmp-dind
    spec:
      containers:
      - name: tmp-dind
        image: docker:dind
        resources:
          requests:
              cpu: 10m
              memory: 300Mi
          limits:
              cpu: 200m
              memory: 300Mi
        securityContext:
          privileged: true
        tty: true
      nodeSelector:
        kubernetes.io/hostname: $SPECIFIC_NODE
EOF
```

Then within the pod: 

```
keti tmp-dind-deployment-55c7ffd6f-dzjbd -- sh
docker buildx create --driver=docker-container --platform "linux/arm64,linux/amd64" --name mirrored --use --bootstrap

docker exec -it buildx_buildkit_mirrored0 sh
apk add stress-ng

stress-ng --vm 4 --vm-bytes 1G --timeout 120s &
``` 

As you can see the memory usage of the pod is very low although I am executing from it but the node's memory is almost at 100%. 

Ideally the pod should die at this point, but actually nothing happens. 

The DinD image is `docker.io/library/docker@sha256:f28ffd78641197871fea8fd679f2bf8a1cdafa4dc3f1ce3e700ad964aac2879a` which is: `docker 24.0.6-dind sha256:f28ffd78641197871fea8fd679f2bf8a1cdafa4dc3f1ce3e700ad964aac2879a   ab82f02ad750`

Any idea how I could make this work?

**Comment by dgl** [comment]
As I wrote over on https://github.com/kubernetes/kubernetes/issues/119853#issuecomment-1938042934 you can see what is happening with `systemctl status` on the K8s node itself:

```
$ sudo systemctl status
[...]
  systemd: 253.5-1ubuntu6
   CGroup: /
           ├─1803258 bpfilter_umh
           ├─docker
           │ └─9207737cd20ff309d023da579d810f84ffb7d9bcdebb4b527ba26d14160f1bf8
           │   └─1811232 /bin/sh
           ├─init.scope
           │ └─1 /lib/systemd/systemd --system --deserialize=44
           ├─kubepods.slice
           │ ├─kubepods-besteffort.slice
           │ │ ├─kubepods-besteffort-pod79227834_afc5_4f67_bf05_594a0d4d36bb.slice
           │ │ │ └─crio-b8733da86dee2260690fa0405587ed3beb9d3dca01f39297008529b4a8654743.scope
           │ │ │   ├─1803200 docker-init -- dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /c
erts/server/key.pem
           │ │ │   ├─1803539 dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key
.pem
           │ │ │   ├─1803555 containerd --config /var/run/docker/containerd/containerd.toml
           │ │ │   ├─1808552 /bin/sh
           │ │ │   ├─1811194 docker run -it alpine
           │ │ │   └─1811212 /usr/local/bin/containerd-shim-runc-v2 -namespace moby -id 9207737cd20ff309d023da579d810f84ffb7d9bcdebb4b527ba26d14160f1bf8 -address /var/run/docker/containerd/containerd.so
ck
```

See the top level "docker", something within the container has moved that outside of the pod's initial cgroup and right outside of the Kubernetes pod hierarchy (`kubepod.slice`). One potential workaround for this is to use `unshare -C` to start docker within a cgroup namespace, however alpine's unshare command doesn't have that option. Another option is to run systemd within the container, as that deals with cgroups v2 hierarchy correctly. (Obviously neither of those options are particularly easy or even possible on Alpine right now, it might be easiest to change this image to be based on a distro using systemd.)

(As I mentioned on the k8s issue, long term Kubernetes will support user namespaces, which can provide a more secure way to run workloads like this, I actually do have kind running on such a setup, but it needs [a WIP patch](https://github.com/cri-o/cri-o/pull/7614) and currently only works on cri-o.)

**Comment by heyleke** [comment]
duplicating comment from https://github.com/kubernetes/kubernetes/issues/119853 here:

I've successfully worked around the issue by making sure the dind-daemon does not escape the kubepods.slice cgroup namespace:

`unshare -C bash -c "umount /sys/fs/cgroup/ && \ mount -t cgroup2 cgroup /sys/fs/cgroup/ && \ /usr/local/bin/dockerd-entrypoint.sh &" `
(the remount is required for the process to see the correct view on sysfs cgroup type)

**Comment by rdeaton-freenome** [comment]
I just wanted to confirm that @heyleke's solution here works for me as well. The one caveat not mentioned is that the busybox version of `unshare` does not support `unshare -C` even at its latest version (1.36.1 as of time of writing). For others who are trying to get this working in the future, the latest alpine version of `util-linux` does include a version of `unshare` with cgroup support.

**Comment by ejnarvala** [comment]
I'm a bit out of my depth here, but we seem to be experiencing a [similar issue](https://github.com/game-ci/unity-builder/issues/540) that we suspect is caused by this issue.

I was wondering if anyone could provide example code on how they implemented this fix.
> `unshare -C bash -c "umount /sys/fs/cgroup/ && \ mount -t cgroup2 cgroup /sys/fs/cgroup/ && \ /usr/local/bin/dockerd-entrypoint.sh &"`

Where was this command was added? Was a new dockerfile created based on the dind image and this command added to it?

**Comment by rlees85** [comment]
Also hitting this problem, can't tell if its a Docker or Kubernetes problem. Thank you @heyleke for the work-around! Its got us up and running anyway.

```
#!/bin/sh -e
################################################################################

set -o pipefail

################################################################################

apk add --no-cache util-linux

################################################################################

tee "/docker-launcher-second-stage.sh" <<SECONDSTAGE
umount "/sys/fs/cgroup"
mount -t "cgroup2" cgroup "/sys/fs/cgroup"
exec "/usr/local/bin/dockerd-entrypoint.sh" ${@}
SECONDSTAGE

chmod 500 "/docker-launcher-second-stage.sh"

################################################################################

exec unshare --cgroup "/bin/sh" -c "/docker-launcher-second-stage.sh" ${@}

################################################################################
```

**Comment by thaJeztah** [comment]
cc @tianon any ideas if we need changes to the  dind script used here?

**Comment by Denton-L** [comment]
If you're using dockerd, passing in `--cgroup-parent=docker` makes use of the pod's cgroup instead of the global `/docker` cgroup.

**Comment by Denton-L** [comment]
In one-linerish form without having to mess about with configmap mounts:

```yaml
- name: dind
  image: public.ecr.aws/docker/library/docker:dind
  command:
    - /bin/sh
    - -c
    - >-
      apk add --no-cache util-linux &&
      unshare --cgroup /bin/sh -c 'umount /sys/fs/cgroup && mount -t cgroup2 cgroup /sys/fs/cgroup && /usr/local/bin/dockerd-entrypoint.sh "$0" "$@"'
      "$0" "$@"
  args:
    - dockerd
    - --host=unix:///var/run/docker.sock
    - --group=$(DOCKER_GROUP_GID)
 ```
