### ISSUE TITLE
ipvlan interfaces do not support custom mac address assignment

### ISSUE THREAD

**Issue by nazar-pc** [moby/moby#45880]
### Description

After https://github.com/moby/libnetwork/issues/2334 I decided to create one network and use it in multiple containers rather than defining macvlan network in each `docker-compose.yml`, however I hit this bug:
```
Error response from daemon: failed to create endpoint X on network lan: ipvlan interfaces do not support custom mac address assignment
```

Which is not true!

### Reproduce

Have `lan` network interface on the host, then create `lan` docker network:
```
docker network create -d ipvlan -o ipvlan_mode=l2 -o parent=lan --subnet=192.168.1.0/24 --gateway=192.168.1.1 lan
```

Then try to create container as follows:
```
version: "3"

services:
  x:
    image: ubuntu
    networks:
      lan:
        ipv4_address: 192.168.1.5
    mac_address: 52:54:00:7c:00:00

networks:
  lan:
    external: true
```

You'll get mentioned error.

### Expected behavior

Consider this similar `docker-compose.yml` that also created macvlan network, but internally rather than using external. This way there is no such error and container does get correct MAC address!

```
version: "3"

services:
  x:
    image: pihole/pihole:2023.05.2
    networks:
      lan:
        ipv4_address: 192.168.1.5
    mac_address: 52:54:00:7c:00:00

networks:
  lan:
    driver: macvlan
    driver_opts:
      ipvlan_mode: l2
      parent: lan
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
```

As far as I can tell, this is literally equivalent, but there must be some difference I don't see. And I can't define this macvlan in every `docker-compose.yml` because of https://github.com/moby/libnetwork/issues/2334

### docker version

<details>

```bash
Client:
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.20.4
 Git commit:        ef23cbc4315ae76c744e02d687c09548ede461bd
 Built:             Fri May 12 13:54:36 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

</details>

### docker info

<details>

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.4.1-0-edge
 Operating System: Alpine Linux v3.18
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: localhost
 ID: 8056c202-7465-4e56-a605-49e136366808
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</details>
