### ISSUE TITLE
Containers unreachable when they are connected by multiple networks and some of them have icc=false

### ISSUE THREAD

**Issue by eriktews** [moby/moby#46162]
### Description

When two containers *a* and *b* are attached to more than one network, for example an uplink network having `com.docker.network.bridge.enable_icc=false` and another internal network, then *a* can sometimes not reach *b* when the internal DNS server returns the IP address of *b* on the uplink network. However it is still technically possible for *a* to reach *b* by using a different IP address.

### Reproduce

Run `docker-compose up` with the following file:

```
version: '3'

services:
  pinga:
   image: arunvelsriram/utils
   networks:
     - interconnect
     - uplink
   command: ["bash", "-c", "sleep 2; ping pingb"]

  pingb:
    image: arunvelsriram/utils
    networks:
     - uplink
     - interconnect
    command: ["bash", "-c", "ping 8.8.8.8; sleep 60"]


networks:
  uplink:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
  interconnect:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
    internal: true
```

We can now see that *b* is able to ping *8.8.8.8*, but *a* can't ping *b*.

### Expected behavior

I expect that I see *a* being able to ping *b* and *b* being able to ping *8.8.8.8*. However *a* can't ping *b* since the DNS server seems to return the IP address of *b* on the *uplink* network that doesn't supper *inter container connectivity*.

### docker version

```bash
Client:
 Version:           20.10.25+dfsg1
 API version:       1.41
 Go version:        go1.20.6
 Git commit:        b82b9f3
 Built:             Mon Jul 17 08:24:02 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       5df983c
  Built:            Mon Jul 17 08:24:02 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 96
 Server Version: 20.10.25+dfsg1
 Storage Driver: btrfs
  Build Version: Btrfs v6.3.2
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+b1
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.4.0-1-amd64
 Operating System: Debian GNU/Linux trixie/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.27GiB
 Name: yogi
 ID: G26P:K3SN:CG3S:F3QF:EWDO:HUV2:RSEB:RHG7:KVH2:CYKY:36PH:IOY4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: etews
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.10.0.0/16, Size: 24
```
