### ISSUE TITLE
Failed to create task for container

### ISSUE THREAD

**Issue by Impre-visible** [moby/moby#46490]
### Description

Hi, I have a docker-compose.yml, when I do "docker compose up -d" I have an error, here's my output :
```
impre@armstrong:~/Dockarr/downloads-vpn$ docker compose up -d
[+] Running 9/9
 ✔ Container vpn           Started  0.1s
 ✔ Container sonarr        Created  0.1s 
 ✔ Container rutorrent     Created  0.1s 
 ✔ Container qbittorrent   Created  0.0s 
 ✔ Container lidarr        Created  0.0s 
 ✔ Container radarr        Created  0.0s 
 ✔ Container prowlarr      Created  0.0s 
 ✔ Container flaresolverr  Created  0.0s
 ✔ Container jackett       Created  0.0s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/630422/ns/net: no such file or directory: unknown
```

### Reproduce

1. docker compose up -d

### Expected behavior

`docker compose up -d` should start all my containers

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 16
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-32-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.17GiB
 Name: armstrong
 ID: 1fdd606f-b488-4828-ac59-9140bfeb9187
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

here's my docker-compose.yml

<details>

```yaml
version: '3.2'

services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
     - label:disable
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
#      - autoheal=true
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    networks:
     - vpn-network
    dns:
     - 84.200.69.80
     - 8.8.8.8
     - 9.9.9.9
    ports :
     - 8586:8586 # WebUI qbittorrent
     - 9117:9117 # WebUI jackett 
     - 7878:7878 # WebUI radarr
     - 8989:8989 # WebUI sonarr
     - 8191:8191 # Flaresolver
     - 8080:8080 # WebUI rutorrent
     - 9696:9696 # WebUI prowlarr
     - 8686:8686 # WebUI Lidarr
    devices:
     - /dev/net/tun:/dev/net/tun
    volumes:
     - /home/impre/Dockarr/downloads-vpn/vpn/config:/vpn
     - /home/impre/Dockarr/downloads-vpn/vpn/scripts:/scripts
    command: '-f "" 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.me"]
      interval: 60s
      timeout: 15s

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rutorrent
#   labels:
#     - com.centurylinklabs.watchtower.enable=true
#     - autoheal=true
    depends_on:
      - vpn
    env_file:
      - "./rtorrent-rutorrent.env"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    network_mode: "service:vpn"
    volumes:
      - /home/impre/Dockarr/downloads-vpn/rutorrent/data:/data
      - /home/impre/Dockarr/downloads-vpn/rutorrent/passwd:/passwd
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads
      - /media/impre/4Tb/Films:/media/film
      - /mnt/8tb/Séries:/media/series
      - /mnt/8tb/Musiques:/media/musiques
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 40000
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "service:vpn"
    depends_on:
      - vpn
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
#      - autoheal=true
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/prowlarr/config:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/sonarr/config:/config
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
      - /mnt/8tb/Séries:/media/series
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/radarr/config:/config
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
      - /media/impre/4Tb/Films:/media/films
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/jackett/config:/config
      - /home/impre/Dockarr/downloads-vpn/jackett/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: "service:vpn"
    depends_on:
      - vpn
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
#    labels:
#     - autoheal=true
#     - com.centurylinklabs.watchtower.enable=true
    depends_on:
     - vpn
    network_mode: "service:vpn"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
     - WEBUI_PORT=8586
    volumes:
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/config:/config
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads
     - /media/impre/4Tb/Films:/media/films
     - /mnt/8tb/Séries:/media/series
     - /mnt/8tb/Musiques:/media/musics
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    labels:
     - autoheal=true
     - com.centurylinklabs.watchtower.enable=true
    depends_on:
     - vpn
    network_mode: "service:vpn"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
     - /home/impre/Dockarr/downloads-vpn/lidarr/config:/config
     - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
     - /mnt/8tb/Musiques:/media/musics
    restart: unless-stopped

networks:
  vpn-network:
    external: true
    name: vpn-network
```

</details>

( https://pastebin.com/94vK4TTN )

**Comment by rishiraj88** [comment]
@Impre-visible , does this help for clue:
https://github.com/aws/amazon-vpc-cni-k8s/issues/707

?

**Comment by Impre-visible** [comment]
> @Impre-visible , does this help for clue: [aws/amazon-vpc-cni-k8s#707](https://github.com/aws/amazon-vpc-cni-k8s/issues/707)
> 
> ?

I looked at that, I don't see what u want me to do ?

**Comment by thaJeztah** [comment]
> Hi, I have a docker-compose.yml, when I do "docker compose up -d" I have an error, here's my output :

First of all, can you provide more context to how you ran into this problem?

- Were you able to successfully run this compose-file before on your machine?
- If so, what happened since? (for example, did the problem occur after upgrading Docker Engine (or other parts of your system), did the problem happen after a restart of your machine?)
- If you were able to run this compose-file successfully before, are you able to strip-down the compose file to the _bare minimum_, and provide a minimal version that still reproduces the problem?

--------

In the mean-time, let's do a break-down of the error first;

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/630422/ns/net: no such file or directory: unknown
```

The actual error comes from all the way down from the OCI runtime (`runc`), or even "lower": it tried to access a networking-namespace, and that namespace was (no longer) there:

- `Error response from daemon` this is from the docker CLI to inform you the error came from the daemon (Docker Engine)
- `failed to create task for container`: this is where the error was produced in the docker daemon: this is the containerd _client_ receiving an error from `containerd`
- `failed to create shim task`: this is the error returned by containerd; it got an error when creating the container's "shim"
- `OCI runtime create failed`: this was where the error occurred in containerd: containerd instructed the OCI runtime to initialize the container, which failed
- `runc create failed`: this error comes from the OCI runtime (`runc` in this case)
- `unable to create new parent process`:
- `namespace path: lstat /proc/630422/ns/net: no such file or directory: unknown`

That error (`lstat /proc/630422/ns/net: no such file or directory`) seems to indicate that `runc` tried to start the container in a networking-namespace, but the networking namespace didn't exist.


So I had a quick look at the compose-file (and posted the content of it in the description as well, in case the pastebin link expired)

Breaking down the compose-file;

- there's a `vpn` service, which has ports mapped for each of the other service
- all other service use the `vpn` service's network namespace (`network_mode: "service:vpn"`)

The last bullet is important here: it means that no network namespace is created for any of the containers: all of the containers run their network stack inside the vpn's container, and all of them will have the same IP-address. However, for that to work, the `vpn` service must be running successfully, because if the `vpn` container fails, its networking namespace is gone (and because of that: the networking namespace for all containers).

The compose-file _does_ have a `depends_on: [vpn]` for each container, which means that compose _should_ wait for the `vpn` service to be running before continuing with the other containers will only do so _when starting_ them; it's possible that the `vpn` service fails _while_ starting any of the other containers, in which case its networking-namespace will be gone (which can cause all other containers that share the namespace to fail). That would explain the error you're seeing;

```
namespace path: lstat /proc/630422/ns/net: no such file or directory: unknown
```

(note that the `vpn` container also has a `healthcheck`; I'm not sure if the `depends_on` check if the `vpn` service is _healthy_ before continuing, and the healthcheck may also fail after the vpn serviced is started).

So what's the cause for this? This is where my initial questions come in:

> First of all, can you provide more context to how you ran into this problem?
> 
> - Were you able to successfully run this compose-file before on your machine?
> - If so, what happened since? (for example, did the problem occur after upgrading Docker Engine (or other parts of your system), did the problem happen after a restart of your machine?)
> - If you were able to run this compose-file successfully before, are you able to strip-down the compose file to the _bare minimum_, and provide a minimal version that still reproduces the problem?


The first question is important: the compose-file you're running is quite complex (more later), and there's many things that could go wrong in it. But before looking at that, it's important to know _did it ever work on your machine?_ So that we can exclude "did something happen?" (second question) or "did it never work?"


Which brings us to the last bullet: the compose file is complex, and has many potential spots that could cause issues, some of which may depend on the "state" of your machine:

First, the `vpn` service itself: I see that container is given additional privileges;

- it runs with `CAP_NET_ADMIN`
- it is granted access to the host's `/dev/net/tun` (through a bind-mount)
- Selinux is disabled (`security_opt: [label:disable]`)

While I don't initially think that's the root-cause, it's important to know that giving a container access to files "on the host", and giving it additional capabilities means that "holes are punched" in the container's sandbox: this means that the container _may_ be able to change state of the host.

The `vpn` service also is attached to a `vpn-network`:

```yaml
    networks:
     - vpn-network
```

That network is defined as "external", which means that Docker Compose will _not_ create the network if it doesn't exist, and it requires the network to be present before it starts (so depending on the machine to be in a specific state);

```yaml
networks:
  vpn-network:
    external: true
    name: vpn-network
```

Finally, the `vpn` service (and all other services) both depend on environment-variables to be set (to configure which user to run as, and which timezone to use);

```yaml
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
```

In addition to bind-mounting paths from the host, some of which seem to be on _separate filesystems_ (`/mnt/...`), and may fail if those filesystems are not mounted, or are unmounted during the container's lifecycle, for example;

```yaml
    volumes:
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/config:/config
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads
     - /media/impre/4Tb/Films:/media/films
     - /mnt/8tb/Séries:/media/series
     - /mnt/8tb/Musiques:/media/musics
```
