### ISSUE TITLE
Make service.extends.file  also include the override.yml 

### ISSUE THREAD

**Issue by typoworx-de** [moby/moby#46725]
### Description

Actually it's possible to define a service which extends from another docker-compose.yml & service like this:

```
services:
  foo:
    extends:
     service: bar
     file: ../bar/docker-compose.yml
```

Currently an (optionally) existing .override.yml is ignored, which may exist as: `../bar/docker-compose.override.yml`
It would be awesome if this could also be included in context of foo.extends.file.

I even think it could be a handy feature to implement this as optional argument `include` just like the root-include. Furthermore it should be possible to make the defined files allow to fail in case they don't exist (eventually using an attribute allowing to ignore missing includes, but not invalid syntax?
