### ISSUE TITLE
root include ignores variables

### ISSUE THREAD

**Issue by typoworx-de** [moby/moby#46726]
### Description

Actually using ìnclude` like follows ignores variables like $HOME (and also .env, I think). It would be very useful if the included files would support existing variables to make this feature more reliable.

For example sometimes i use $HOME to refer for a specific bind-mount volume. This is actually not possible using root-include's which may be required to distribute such a volume-configuration for multiple docker-compose files using the same volume. This renders the use of include's useless, as they are ment to deduplicate configuration-fragments.

```
include:
 - foo.yml
 - bar.yml

services:
  foobar:
    image: foobar
```
