### ISSUE TITLE
depends_on long syntax doesn't work in swarm mode

### ISSUE THREAD

**Issue by am97** [moby/moby#46827]
### Description

The following Compose file (based on [depends_on doc](https://docs.docker.com/compose/compose-file/05-services/#depends_on)) works correctly with `docker compose`, but not with `docker stack deploy`:

```yml
services:
  web:
    image: alpine
    command: sleep 3600
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: pg_isready -q -U postgres || exit 1
```

`docker stack deploy` gives the following error with the latest Docker beta (25.0.0-beta.1):

```
services.web.depends_on must be a list
```

### Reproduce

1. `docker run -d --name d25 --privileged docker:25.0.0-beta.1-dind`
2. `docker exec -it d25 sh`
3. Put the previous Compose file in `docker-compose.yml`
4. `docker stack deploy -c docker-compose.yml test`

### Expected behavior

The stack should be deployed. The task for the `web` service should not start until the `db` container is healthy

### docker version

```bash
Client:
 Version:           25.0.0-beta.1
 API version:       1.44
 Go version:        go1.21.3
 Git commit:        2b521e4
 Built:             Mon Nov 13 16:48:31 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0-beta.1
  API version:      1.44 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       6af7d6e
  Built:            Mon Nov 13 16:50:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.8
  GitCommit:        8e4b0bde866788eec76735cc77c4720144248fb7
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.0-beta.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 25.0.0-beta.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8e4b0bde866788eec76735cc77c4720144248fb7
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.9-200.fc38.x86_64
 Operating System: Alpine Linux v3.18 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.49GiB
 Name: b148a0067439
 ID: 71c07691-439d-490d-b9d9-6643a537754c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by am97** [comment]
In fact, even short syntax isn't working as expected in swarm mode. I use the following file:

```yml
services:
  web:
    image: alpine
    command: sleep 3600
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: pg_isready -q -U postgres || exit 1
```

The stack is deployed without errors, however the `web` service is started before the `db` service:

```
~ # docker ps
CONTAINER ID   IMAGE           COMMAND        CREATED         STATUS         PORTS     NAMES
8ce7ac57257b   alpine:latest   "sleep 3600"   5 seconds ago   Up 4 seconds             test_web.1.tff6ojq460hsz42c9rqi0nwh7
~ # docker stack ps test
ID             NAME         IMAGE                NODE           DESIRED STATE   CURRENT STATE              ERROR     PORTS
w77akrg7ez51   test_db.1    postgres:14-alpine   31c5c8a2b0f0   Running         Preparing 12 seconds ago             
tff6ojq460hs   test_web.1   alpine:latest        31c5c8a2b0f0   Running         Running 9 seconds ago                
```

If `depends_on` isn't intended to be supported in swarm mode, there should be at least a warning at runtime, and somewhere in the docs
