### ISSUE TITLE
Inconsistency in `depends_on` with `service_healthy` Condition Across Different Docker Versions

### ISSUE THREAD

**Issue by cubxxw** [moby/moby#47134]
### Description

**Description:** We are experiencing inconsistencies in the behavior of the `depends_on` configuration with the `service_healthy` condition in our Docker Compose setups across different production environments. Specifically, in some instances, services that depend on other services with health checks are starting before those dependencies have reached a healthy state.

**Documentation Reviewed:**

- [Control startup order in Compose](https://docs.docker.com/compose/startup-order/)
- [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/compose-file-v3/)

**Issue:** The documentation states that `depends_on` can be used with `service_healthy` to ensure a service starts only after its dependencies are healthy. However, in practice, we've found that this does not consistently work across various Docker and Docker Compose versions. Some services start even if their dependencies haven't reached a healthy state yet. 
This behavior is unpredictable and varies based on the Docker and Docker Compose versions used.

**Request for Information:**

1. Is there a specific version of Docker or Docker Compose where the integration of health checks with `depends_on` (`service_healthy` condition) is known to work consistently?
2. Are there any known issues or limitations with this functionality in certain versions of Docker or Docker Compose that might explain the observed inconsistencies?
3. Could you provide guidance or best practices on ensuring consistent behavior of `depends_on` with health checks across different environments?

**Environment Details:**

- We are observing this issue across various environments with different Docker and Docker Compose versions. Specific version details can be provided if needed.

**Impact:** This inconsistency is impacting our production deployments, as services are not starting in the required order, leading to potential application failures.

**Additional Context:** Any additional context or similar experiences from the community would be greatly appreciated, as this will help us better understand the scope and potential solutions to this issue.

### Reproduce

```
docker compose up -d
```

My docker compose yaml:

```
  prometheus:
    image: prom/prometheus:${PROMETHEUS_IMAGE_VERSION:-v2.48.1}
    container_name: prometheus
    hostname: prometheus
    restart: always
    depends_on:
      openim-server:
        condition: service_healthy
    volumes:
      - "${DATA_DIR:-./}/openim-server/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "${DATA_DIR:-./}/openim-server/config/instance-down-rules.yml:/etc/prometheus/instance-down-rules.yml"
    ports:
      - "${PROMETHEUS_PORT:-19090}:9090"
    networks:
      openim-server:
        ipv4_address: ${PROMETHEUS_NETWORK_ADDRESS:-172.28.0.10}
```

### docker version

```bash
linux: ubuntu16
```

### docker info

```bash
todo
```
