### ISSUE TITLE
v25.0.1 : Network not work correctly in project start

### ISSUE THREAD

**Issue by neerfix** [moby/moby#47290]
Original issue: https://github.com/docker/cli/issues/4842

### Description

Since updating to Docker version 25.0.1, I've encountered an error with my Traefik saying, 'Could not resolve host: xxx.xxxxxxxx.local' for 'http://xxx.xxxxx.local/me'.

I spent the entire day trying to solve this problem, and finally found a solution. By creating a new temp network in the project and reinstalling it with docker compose up -d, my original network started working again and I resolved the 'Could not resolve host' issue.

However, the problem is not consistently present. In some of my projects, the issue persists, while in others, Traefik and the network function normally.

### Reproduce

Setting Up Traefik: Configure Traefik to use your existing Docker network. It is after this setup that you might encounter the mentioned error ("Could not resolve host").
Reproducing the Problem: Attempt to access a specific service or route managed by Traefik. At this point, you should encounter the "Could not resolve host" error.
Creating a New Temporary Network: Create a new Docker network named temp. This can be done using Docker commands or Docker Compose.
Reinstalling with Docker Compose: Run docker compose up -d to redeploy your services using the newly created temp network.
Testing the Solution: After redeployment, try accessing the same service or route through Traefik again. If the solution is effective, the "Could not resolve host" error should no longer occur. This step verifies whether the new network setup resolves the issue.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:23 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 32
  Running: 28
  Paused: 0
  Stopped: 4
 Images: 49
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-15-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 30.78GiB
 Name: LINUX25
 ID: d5f34c19-4626-4449-8e44-ee960d2641b5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

In this exemple, `admin` can't resolve host `api.xxx.local`

First project, the `docker-compose.yml` of `Admin` : 
```yml
version: "3.8"

services:
  app:
    image: ardeveloppement/system:2
    container_name: connect-admin_app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.connect-admin.rule=Host(`admin.xxx.local`)"
      - "traefik.http.routers.connect-admin.entrypoints=web"
      - "traefik.http.routers.connect-admin.service=connect-admin"
      - "traefik.http.services.connect-admin.loadbalancer.server.port=80"
    environment:
      ENVIRONMENT: 'development'
      APP: nuxt
      NUXT_COMMAND: yarn dev
    env_file:
      - .env
    volumes:
      - ".:/srv/app/"
      - "./var/logs/nginx:/var/log/nginx"
    networks:
      - default
      - traefik-proxy
    external_links:
      - reverse-proxy:auth.xxx.local
      - reverse-proxy:api.xxx.local
      - reverse-proxy:static.xxx.local
      - reverse-proxy:customizr.xxx.local
      - reverse-proxy:customizer-api.xxx.local
      - reverse-proxy:catalog.xxx.local
      - reverse-proxy:universe-api.xxx.local

networks:
  traefik-proxy:
    external: true
```

----

The second project, the `docker-compose.yml` of  `core-api`: 

```yml
version: '3.8'

services:
  app:
    image: core-api:dev
    build:
      context: .
      dockerfile: docker/code/Dockerfile.local
    container_name: core-api_app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.core-api.rule=Host(`api.xxx.local`)"
      - "traefik.http.routers.core-api.entrypoints=web"
      - "traefik.http.routers.core-api.service=core-api"
      - "traefik.http.services.core-api.loadbalancer.server.port=80"
    environment:
      PHP_FPM_MEMORY_LIMIT: 512M
      PHP_FPM_MAX_EXECUTION_TIME: "120"
      SYMFONY_ENV: dev
      # docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' core-api_app
      XDEBUG_CONFIG: "remote_host=172.18.0.1"
      PHP_XDEBUG_REMOTE_PORT: "9001"
      PHP_IDE_CONFIG: "serverName=xdebug-core-api"
    env_file:
      - blackfire.env
      - system.env
    volumes:
      - ".:/srv/app"
    networks:
      - default
      - traefik-proxy
      - behat
      - amqp
    external_links:
      - reverse-proxy:smtp.xxx.local
      - reverse-proxy:auth.xxx.local
      - reverse-proxy:customizr.xxx.local
      - reverse-proxy:customizer.xxx.local
      - reverse-proxy:customizer-api.xxx.local
      - reverse-proxy:static.xxx.local
      - reverse-proxy:catalog.xxx.local
      - reverse-proxy:api.xxx.local
      - reverse-proxy:digital-media.xxx.local
      - reverse-proxy:mercure.xxx.local
      - reverse-proxy:universe-api.xxx.local
      - reverse-proxy:universe.xxx.local
    ports:
      - 9001

  db:
    image: mysql:5.6 # Be Careful in 5.7 passwords expire
    container_name: core-api_db
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
      MYSQL_USER: core
      MYSQL_PASSWORD: core
    volumes:
      - "./:/srv/app"
      - "./data/mysql/db:/var/lib/mysql"
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    networks:
      - default
      - monitoring
    ports:
      - "127.0.0.1:4406:3306"

  redis:
    image: redis:alpine
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data/redis:/data"
    networks:
      - default
      - redis
    ports:
      - 6359:6379

  blackfire:
    container_name: blackfire
    image: blackfire/blackfire
    restart: always
    env_file:
      - blackfire.env
    networks:
      - default

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-fluorine
    environment:
      VNC_NO_PASSWORD: 1
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - behat
    external_links:
      - app:api.cospirit-connect.local
    ports:
      - "4444:4444"
      - "5901:5900"

  novnc:
    image: ardeveloppement/novnc:1.0.0
    networks:
      - behat
    ports:
      - "6080:8081"

networks:
  behat:
  traefik-proxy:
    external: true
  monitoring:
    external: true
  redis:
    external: true
  amqp:
    external: true
```

----

`$ docker network inspect traefik-proxy`

```bash
[
    {
        "Name": "traefik-proxy",
        "Id": "901e5dcad04f9e3b402e71e9dad651fc951fe47f27e113a3946e276a2dfe47e6",
        "Created": "2024-01-31T13:47:24.803364696+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.112.0/20",
                    "Gateway": "192.168.112.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0ade53b1d7b4573e15942177caa7c06b16abe0fde613ee5246bcd78bf791ec0e": {
                "Name": "universe-client_app",
                "EndpointID": "08f75e5c3fb539c4858295900d53c536401975721f34247504cd850548075319",
                "MacAddress": "02:42:c0:a8:70:06",
                "IPv4Address": "192.168.112.6/20",
                "IPv6Address": ""
            },
            "231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f": {
                "Name": "connect-admin_app",
                "EndpointID": "2a19aa8b13902c8a005ad13f9631b696b88c7d53eb4121a82e355cfd9c81f5b7",
                "MacAddress": "02:42:c0:a8:70:04",
                "IPv4Address": "192.168.112.4/20",
                "IPv6Address": ""
            },
            "27a33a6d662a760d51810310bdef804a3bd71f3e690391f5f0fd7839f15bdb6c": {
                "Name": "static_app",
                "EndpointID": "93a6ba41d9e2f4d0ef3c39b0f9da2470c1562a1987e661cb15d06433dc7688ce",
                "MacAddress": "02:42:c0:a8:70:05",
                "IPv4Address": "192.168.112.5/20",
                "IPv6Address": ""
            },
            "9610ffab83044a4e194223510e76df8ca7d7cac6c3a54339ef25a4f18d644171": {
                "Name": "core-api_app",
                "EndpointID": "291de55b57e85d07344c8581fcfc5cb676c7287b92a954e21c3d38585ca369d3",
                "MacAddress": "02:42:c0:a8:70:02",
                "IPv4Address": "192.168.112.2/20",
                "IPv6Address": ""
            },
            "aa52d0308c5c6051a7d06d5bbd01a794468a2ce335c9d03f3a9477a981ce85c7": {
                "Name": "customizer-client_app",
                "EndpointID": "6ce46cd20fa1eca89dc203aea2fe958121a7f8de8d56f1698ed352ec3f21d165",
                "MacAddress": "02:42:c0:a8:70:03",
                "IPv4Address": "192.168.112.3/20",
                "IPv6Address": ""
            },
            "ab34d9e223cc208958a9b3a5b341d0d5bdc3d6e86b02e5504fa00c83e303ae8a": {
                "Name": "influxdb",
                "EndpointID": "ff3a776bdcfabb1d85c8fff179339ddfe63db07c5370b6c7e49b585c2ece8f7c",
                "MacAddress": "02:42:c0:a8:70:08",
                "IPv4Address": "192.168.112.8/20",
                "IPv6Address": ""
            },
            "adb2261610d9d8118fbe59cace0edb98082fc4f94d432e65bfc1546d3a9188b1": {
                "Name": "universe-api_app",
                "EndpointID": "f5cb315ce871e3c5e8fc341f25475059b98a498b6befe5cc5fb0ac11c4609d35",
                "MacAddress": "02:42:c0:a8:70:07",
                "IPv4Address": "192.168.112.7/20",
                "IPv6Address": ""
            },
            "bdac4aed83531cbddb7e50debc9a90e9fde9c883c0ffb349c2cf248e0b66292a": {
                "Name": "auth_app",
                "EndpointID": "b25c75b7b3a21e174bc76582cee25d9bbf6296f542f765a4aaf16d46c21e32a3",
                "MacAddress": "02:42:c0:a8:70:0a",
                "IPv4Address": "192.168.112.10/20",
                "IPv6Address": ""
            },
            "c4e8350147d9462118fedac95fced5cd0c61c837fcfccc20f421c04c92b915ac": {
                "Name": "selenium-hub",
                "EndpointID": "3762e8f90b5a484cd8f38ef4c00c5d983f685aa9398f0eef98f979bf1bc8fe92",
                "MacAddress": "02:42:c0:a8:70:09",
                "IPv4Address": "192.168.112.9/20",
                "IPv6Address": ""
            },
            "d13e8dc48521529887d3a6a41dcc8d542e00d62a6d93028d1b2a8b73e09922d1": {
                "Name": "reverse-proxy",
                "EndpointID": "a82fcd4fec80324b903bf4e8ecd1ea8e83a1d1b74fd6f586a5ed36d63db83134",
                "MacAddress": "02:42:c0:a8:70:0c",
                "IPv4Address": "192.168.112.12/20",
                "IPv6Address": ""
            },
            "e2f3c14db667c146b1bc2a0df78659eb9e1b42f37691d4c77c3424d3500f4229": {
                "Name": "customizer-api_app",
                "EndpointID": "51f61cc850e5b67c91d221b7bb43c2b90d8b3cea2a7e600bc06943564996e0d1",
                "MacAddress": "02:42:c0:a8:70:0b",
                "IPv4Address": "192.168.112.11/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
---- 
`$ docker inspect 231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f`

```bash
[
    {
        "Id": "231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f",
        "Created": "2024-02-01T08:58:22.13189286Z",
        "Path": "/root/entrypoint",
        "Args": [
            "supervisord",
            "--configuration",
            "/etc/supervisor/app.conf"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 82938,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-02-01T10:35:53.76616273Z",
            "FinishedAt": "2024-02-01T10:35:53.225351739Z"
        },
        "Image": "sha256:889773541c27679548ac00e85c15aca94c75e04c4a491aac00f0abe7241c1a1e",
        "ResolvConfPath": "/var/lib/docker/containers/231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f/hostname",
        "HostsPath": "/var/lib/docker/containers/231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f/hosts",
        "LogPath": "/var/lib/docker/containers/231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f/231244b41ea4d6696ee2ec0f4e514e5adca797c97807427295b63c18207d460f-json.log",
        "Name": "/connect-admin_app",
        "RestartCount": 3,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/nicolas/projects/admin:/srv/app:rw",
                "/home/nicolas/projects/admin/var/logs/nginx:/var/log/nginx:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "admin_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/863130bf7c882eb25a100a9b6b13a700f76cbf71a9766f0d11587d250e8bfcde-init/diff:/var/lib/docker/overlay2/6d3400eefa28d79df01253c2efcd848eb4ea1473fda6b25102ef0191601c4a17/diff:/var/lib/docker/overlay2/2563caf1528f5fa33cde9064c592c951a98b10ee3ca5ef0ac8031fcfea06f28f/diff:/var/lib/docker/overlay2/f54f6948a1487210fdcd68b77d9a990ca7fe6f5549fc9c3e659c2a9f593d4194/diff:/var/lib/docker/overlay2/e3c857806b6a4d9cffd1f32b876043f80308a9d26f0a5d0612c9a06fb4ea6f64/diff:/var/lib/docker/overlay2/77a3d67c4bcb1a41885adcc177b1d65ed3b869e8c6b7a5214c18e92a62a189a3/diff:/var/lib/docker/overlay2/19480c464bc543cd9542aa7c718004d23d49af4584bc686c7fe3b0ef81ee9bcf/diff:/var/lib/docker/overlay2/69f2e54779311504cfcece2fa2c50ffc9e15171056cc9a889b721fff48e06b1a/diff:/var/lib/docker/overlay2/f79f4a5719a91c66b65df235e5d943b74650ebd70421111b799fb7629cff1186/diff:/var/lib/docker/overlay2/aa58153123ad121702a519f516e6c287ba75db68c478032cf3f0baa2b15dadf1/diff",
                "MergedDir": "/var/lib/docker/overlay2/863130bf7c882eb25a100a9b6b13a700f76cbf71a9766f0d11587d250e8bfcde/merged",
                "UpperDir": "/var/lib/docker/overlay2/863130bf7c882eb25a100a9b6b13a700f76cbf71a9766f0d11587d250e8bfcde/diff",
                "WorkDir": "/var/lib/docker/overlay2/863130bf7c882eb25a100a9b6b13a700f76cbf71a9766f0d11587d250e8bfcde/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/nicolas/projects/admin",
                "Destination": "/srv/app",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/nicolas/projects/admin/var/logs/nginx",
                "Destination": "/var/log/nginx",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "231244b41ea4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NUXT_ENV_API_URL=http://customizer-api.cospirit-connect.local",
                "NUXT_ENV_UNIVERSE_URL=http://universe-api.cospirit.local",
                "NUXT_ENV_UNIVERSE_CLIENT_URL=http://universe.cospirit.local",
                "NUXT_ENV_CATALOG_API_URL=http://catalog.cospirit-connect.local",
                "NUXT_ENV_CORE_API_URL=http://api.cospirit-connect.local/app_dev.php",
                "NUXT_ENV_AUTH_URL=http://auth.cospirit-connect.local",
                "NUXT_ENV_ADMIN_URL=http://admin.cospirit-connect.local",
                "NUXT_ENV_STATIC_URL=http://static.cospirit-connect.local/index_dev.php",
                "NUXT_ENV_CUSTOMER_URL=http://customer.cospirit-connect.local/app_dev.php",
                "NUXT_ENV_CUSTOMIZER_API_URL=http://customizer-api.cospirit-connect.local",
                "NUXT_ENV_CUSTOMIZER_URL=http://customizer.cospirit-connect.local",
                "NUXT_ENV_STATIC_APPLICATION_ID=arconnect-doccustomizer",
                "NUXT_ENV_STATIC_ORDERABLE_FOLDER=arconnect",
                "APP_CORS_ALLOW_ORIGIN=^https?:\\/\\/[a-z0-9\\-]+\\.cospirit\\-connect\\.local$",
                "APP_LOG_PATH=stdout",
                "APP_VERSION_SERVICES_URL=http://services.cospirit-connect.local",
                "CUSTOMIZER_URL=http://customizer.cospirit-connect.local",
                "SELENIUM_HUB_URL=selenium-hub.cospirit.local",
                "NIGHTWATCH_ENV=chromeHeadless",
                "DEBUG=nuxt:*",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "ENVIRONMENT=development",
                "APP=nuxt",
                "NUXT_COMMAND=yarn dev",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHP_VERSION=7.4",
                "PHP_MODULES_EXTRA=",
                "PHP_DATE_TIMEZONE=UTC",
                "NGINX_DIRECTIVES=[\"gzip\", \"error\", \"assets\"]",
                "SYSTEM_TIMEZONE=Etc/UTC"
            ],
            "Cmd": [
                "supervisord",
                "--configuration",
                "/etc/supervisor/app.conf"
            ],
            "Image": "ardeveloppement/system:2",
            "Volumes": {
                "/srv/app": {},
                "/var/log/nginx": {}
            },
            "WorkingDir": "/srv/app",
            "Entrypoint": [
                "/root/entrypoint"
            ],
            "MacAddress": "02:42:ac:19:00:02",
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "a3d5f3fc02f180756a3eb0b61d36cc46c969acb6f5e7d6e4910bba772dcd8bb6",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "admin",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/nicolas/projects/admin",
                "com.docker.compose.service": "app",
                "com.docker.compose.version": "1.27.4",
                "maintainer": "AR Developpement <support-arconnect@cospirit.com>",
                "traefik.docker.network": "traefik-proxy",
                "traefik.enable": "true",
                "traefik.http.routers.connect-admin.entrypoints": "web",
                "traefik.http.routers.connect-admin.rule": "Host(`admin.cospirit-connect.local`)",
                "traefik.http.routers.connect-admin.service": "connect-admin",
                "traefik.http.services.connect-admin.loadbalancer.server.port": "80"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "977debc6b493955b976247849afb36fd089fab401844d3685f6cb8b5798c6c40",
            "SandboxKey": "/var/run/docker/netns/977debc6b493",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "admin_default": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": [
                        "app",
                        "231244b41ea4"
                    ],
                    "MacAddress": "02:42:ac:19:00:02",
                    "NetworkID": "25413d11b1b9cdd23b1178e47d41b3fc8155decd97c58ef59ae3533a974644b1",
                    "EndpointID": "b90c9b5505561db4f5edbe26bedd1cbd8ca95ee7f98bfb2266afdb751b7f1e4d",
                    "Gateway": "172.25.0.1",
                    "IPAddress": "172.25.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "connect-admin_app",
                        "app",
                        "231244b41ea4"
                    ]
                },
                "traefik-proxy": {
                    "IPAMConfig": null,
                    "Links": [
                        "reverse-proxy:api.cospirit-connect.local",
                        "reverse-proxy:auth.cospirit-connect.local",
                        "reverse-proxy:catalog.cospirit-connect.local",
                        "reverse-proxy:customizer-api.cospirit-connect.local",
                        "reverse-proxy:customizr.cospirit-connect.local",
                        "reverse-proxy:static.cospirit-connect.local",
                        "reverse-proxy:universe-api.cospirit.local"
                    ],
                    "Aliases": [
                        "app",
                        "231244b41ea4"
                    ],
                    "MacAddress": "02:42:c0:a8:70:04",
                    "NetworkID": "901e5dcad04f9e3b402e71e9dad651fc951fe47f27e113a3946e276a2dfe47e6",
                    "EndpointID": "2a19aa8b13902c8a005ad13f9631b696b88c7d53eb4121a82e355cfd9c81f5b7",
                    "Gateway": "192.168.112.1",
                    "IPAddress": "192.168.112.4",
                    "IPPrefixLen": 20,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "connect-admin_app",
                        "app",
                        "231244b41ea4"
                    ]
                }
            }
        }
    }
]
```

----

`The content of /etc/resolv.conf, from the container where Traefik is running, when the issue occurs ;`
```
search xxx.org
nameserver 127.0.0.11
options ndots:0
```
