### ISSUE TITLE
Inconsistent connectivity with `internal` networks in 25.0.3

### ISSUE THREAD

**Issue by thespad** [moby/moby#47354]
### Description

Since upgrading from 24.x to 25.0.3 I'm seeing inconsistent connectivity when using `internal` docker networks.

For example I have an internal network:
```yaml
  yacht-dockerproxy:
    name: yacht-dockerproxy
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.24/29
```
And attempting to ping from one container on this network to another fails, either by hostname or IP. If I change it to `internal: false` then communication works again.

However, if I change it instead to, for example:
```yaml
  yacht-dockerproxy:
    name: yacht-dockerproxy
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.24/29
```
Then communication *also* works.

I've removed all networks and containers, restarted the docker service, but the same issue persists.

Is it possible that this could be a factor?
```
 Default Address Pools:
   Base: 172.20.0.0/16, Size: 24
```

### Reproduce

1. Create an `internal` network with multiple attached containers
2. Attempt to ping/curl/etc between containers
3. If necessary change the assigned subnet and retest

### Expected behavior

Internal networks should reliably allow inter-container communication

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /home/****/.docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 65
  Running: 65
  Paused: 0
  Stopped: 0
 Images: 60
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc crun
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-94-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: docker2
 ID: 67LS:QX2S:7P4H:CTCH:IGKD:4BKW:6HYY:46PB:LHNR:IXBV:CDSP:FXXJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: *****
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Default Address Pools:
   Base: 172.20.0.0/16, Size: 24
```

**Comment by robmry** [comment]
Hi @thespad - thank you for raising this separate ticket. I've been unable to reproduce the problem ... I tried four subnets on Ubuntu 22.04.3, with docker 25.0.3.

Please could you grab the output of `docker network inspect` for a broken network, and `docker inspect` for a pair of containers that are unable to ping each other?

Also `ip a`, and `route -n` from inside those containers - if you can repro with an image that has those tools (like 'alpine', or anything based on it).

Do the ping or curl commands fail immediately with an error, or time out / get stuck waiting for responses?

(I don't think the default pool is likely to be related. Specifying a subnet means it's not used for the network, and it doesn't overlap with the subnets in your example.)

**Comment by thespad** [comment]
Sure. So:
```yaml
services:
  test1:
    image: lscr.io/linuxserver/baseimage-alpine:3.19
    container_name: test1
    networks:
      - test-net
    security_opt:
      - no-new-privileges=true

  test2:
    image: lscr.io/linuxserver/baseimage-alpine:3.19
    container_name: test2
    networks:
      - test-net
    security_opt:
      - no-new-privileges=true

networks:
  test-net:
    name: test-net
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.32/29
```
test1:
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
1287: eth0@if1288: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:13:00:22 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.34/29 brd 172.19.0.39 scope global eth0
       valid_lft forever preferred_lft forever
```
```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
172.19.0.32     0.0.0.0         255.255.255.248 U     0      0        0 eth0
```
```
# ping test2
PING test2 (172.19.0.35): 56 data bytes
^C
--- test2 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
```
test2:
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
1289: eth0@if1290: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:13:00:23 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.35/29 brd 172.19.0.39 scope global eth0
       valid_lft forever preferred_lft forever
```
```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
172.19.0.32     0.0.0.0         255.255.255.248 U     0      0        0 eth0
```
```
# ping test1
PING test1 (172.19.0.34): 56 data bytes
^C
--- test1 ping statistics ---
9 packets transmitted, 0 packets received, 100% packet loss
```
`inspect`s for each container + network
[test1.txt](https://github.com/moby/moby/files/14201791/test1.txt)
[test2.txt](https://github.com/moby/moby/files/14201792/test2.txt)

[test-net.txt](https://github.com/moby/moby/files/14201793/test-net.txt)

Let me know if you need anything additional.
