### ISSUE TITLE
OOM when the memory limit is higher

### ISSUE THREAD

**Issue by michaelact** [moby/moby#47418]
### Description

In `dmesg -T` or linux diagnostic messages, it indicates that the container was shut down due to running out of memory.
```
[Tue Feb 20 19:15:36 2024] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/e9d912458f1530f0d9f586ab3bdca1015f45cbb5cd59cddde 5 a33d7714fda280,task=python,pid= 2953 , liquid=999
[Tue Feb 20 19:15:36 2024] Out of memory: Process stopped 2953 (python) total-vm:8142876kB, anon-rss:6719676kB, file-rss:4kB, shmem-rss:0kB, UID:999 pgtables: 13660kB oom_score_adj:0
```
Above log shows `total-vm:8142876kB`, or equal to 7952.027344 mB. I expect memory to run out if memory reaches the configured memory limit, which is `mem_limit: 15740m`. I can also confirm that the memory limit in the container is set at around 16 GB:
```
$ cat /sys/fs/cgroup/memory/docker/e9d912458f1530f0d9f586ab3bdca1015f45cbb5cd59cddde/memory.limit_in_bytes
16504586240
```

### Reproduce

Run `docker compose up -d`.

## Docker Compose Configuration
```
version: "3.7"
services:
  serving:
    image: example (hide)
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    pids_limit: 100
    restart: on-failure:5
    mem_limit: 15740m
    env_file:
      - .env
    ports:
      - 5000:5000
    healthcheck:
      test: curl -o /dev/null -s -w '%{http_code}' http://localhost:5000/health_check
      start_period: 30s
      timeout: 3s
      retries: 10

networks:
  default:
    external: true
    name: example (hide)
```

### Expected behavior

Out of memory will occur if the memory limit is reached.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:17:53 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.9
  Git commit:       9dbdbd4
  Built:            Fri May  5 21:17:53 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-1103-aws
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.37GiB
 Name: example
 ID: QBHA:AQC5:AGLG:BCQJ:KZWX:5WPT:D7C4:TXGK:PKDK:KJBV:VSDY:573T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No swap limit support
```

## System specification
```
$ uname -a
Linux example-hide 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ free -mh
              total        used        free      shared  buff/cache   available
Mem:            15G        3.1G        9.4G        924K        2.9G         11G
Swap:            0B          0B          0B
```
