### ISSUE TITLE
mac_address is being ignored with external network, networks.mac_address doesn't seem to work either

### ISSUE THREAD

**Issue by NonaSuomy** [moby/moby#47467]
### Description

This was working fine around September 2023 with moby as it fixed an issue main docker packages were all of a sudden having issues setting mac_address at that time. I then had an issue with a plugin saying my docker client was using an older version of 1.13.1 instead of 1.24 above. I then said well let's update the docker package (forgetting I had moby installed) which overwrote the install of moby. Instead of fixing the wrong version issue, I created again the mac_address not applying to the containers again.

I later figured out the plug version issue and fixed it. Now I am left with the mac_address not applying again.

I tried to compile moby again but it didn't fix it this time.

Someone pointed out that the placement of mac_address has moved to under networks after version 25. I attempted to put it there but get an error that it should not be put there.

https://docs.docker.com/compose/compose-file/05-services/#mac_address-1
```
mac_address
Available with Docker Compose version 2.24.0 and later.

mac_address sets a MAC address for the service container.

Note Container runtimes might reject this value (ie. Docker Engine >= v25.0). In that case, you should use networks.mac_address instead.
```

When I try placing mac_address under the docker service it processes it but it just gives it a random MAC like it wasn't there.  

When I place it under the networks it won't start with the error shown in the comment at the end of the config below:

### Reproduce

```yaml
# Portainer Container for Docker
version: '3.9'

services:
  portainer:
    container_name: portainer
    hostname: portainer
    #image: portainer/portainer-ce:latest
    image: portainerci/portainer:2.20
    restart: 'no'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    #restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/libvirt/images/sas/docker-storage/portainer/portainer-data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    mac_address: de:ad:be:ef:00:01 # Ignores this.
    networks:
      - dhcp
networks:
  dhcp:
    name: dbrv100
    external: true
    #mac_address: de:ad:be:ef:00:01 #ERROR: networks.dhcp Additional property mac_address is not allowed
```

docker compose up

### Expected behavior

Should apply the right MAC address set in the compose not a random one.

### docker version

```bash
Client:
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629222
 Built:             Thu Feb  1 10:50:44 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          dev
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.7
  Git commit:       HEAD
  Built:            Wed Feb 28 00:02:42 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8.m
 runc:
  Version:          1.1.12
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.6
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 28
  Running: 0
  Paused: 0
  Stopped: 28
 Images: 55
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge ghcr.io/devplayer0/docker-net-dhcp:golang host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d200ca3811ff6096eb8.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.7.6-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: hypervisor001
 ID: PIOS:MFUC:XNOX:7MXH:6SU7:67CC:FKJK:JKNP:L3LX:S7CG:YWQM:UKQJ
 Docker Root Dir: /var/lib/libvirt/images/sas/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  0.0.0.0:5000
  localhost:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info
```json
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "34db0f15b3aab4ae72a914c3d71c70c0ca2f8325a383053dc0cf53f665c78b4a",
            "SandboxKey": "/var/run/docker/netns/34db0f15b3aa",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "dbrv100": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "portainer",
                        "5c67b73c3bca"
                    ],
                    "MacAddress": "fe:37:ed:41:a3:de",
                    "NetworkID": "0bae16efd85f9c4ba4656774be8acc713537bceebcb212b16af223487ecd2de0",
                    "EndpointID": "09e233f27cad6b6203ce9203978e8a665c2253153077c75997aebc80e94a127c",
                    "Gateway": "10.0.1.1",
                    "IPAddress": "10.0.1.42",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "portainer",
                        "5c67b73c3bca"
                    ]
                }
            }
```

You can see it got a random MAC not the one set in the yaml: "MacAddress": "fe:37:ed:41:a3:de",

**Comment by NonaSuomy** [comment]
Figured it out should be formed like this

```yaml
version: '3.8'
services:
  nginx:
    image: nginx:latest
    networks:
      dhcp:
        mac_address: de:ad:be:ef:00:01
networks:
  dhcp:
    name: dbrv100
    external: true
```

Looks like it is working now yay!

```json
            "Networks": {
                "dbrv100": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": [
                        "mactest-nginx-1",
                        "nginx",
                        "############"
                    ],
                    "MacAddress": "de:ad:be:ef:00:01",
                    "NetworkID": "0b...",
                    "EndpointID": "75...",
                    "Gateway": "10.0.42.1",
                    "IPAddress": "10.0.42.121",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "mactest-nginx-1",
                        "nginx",
                        "############"
                    ]
                }
            }
```
