### ISSUE TITLE
Getting "error while resolving symlinks in base directory" when using subpath

### ISSUE THREAD

**Issue by reynhartono** [moby/moby#47707]
### Description

Getting the following error when using the subpath feature on a CIFS volume

`
Error response from daemon: error while resolving symlinks in base directory "/var/lib/docker/volumes/volume_name/_data": lstat /var/lib/docker/volumes/volume_name/_data: stale NFS file handle
`

### Reproduce

1. Create a docker compose file
```
volumes:
  a_cifs_volume:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=password
      device: //hostname/share

services:
  busybox:
    image: busybox
    container_name: busybox
    volumes:
      - type: volume 
        source: a_cifs_volume
        target: /subpath
        volume:
          subpath: subpath
```
2. Run `docker compose up -d`
3. Update the CIFS volume options on docker-compose.yml file
```
volumes:
  a_cifs_volume:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=password,uid=1000,gid=1000,file_mode=0755,dir_mode=0755
      device: //hostname/share

services:
  busybox:
    image: busybox
    container_name: busybox
    volumes:
      - type: volume 
        source: a_cifs_volume
        target: /subpath
        volume:
          subpath: subpath
```
4. Run `docker compose down -v`
5. Run `docker compose up -d`

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:17:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:48 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /home/username/.docker/cli-plugins/docker-compose

Server:
 Containers: 12
  Running: 7
  Paused: 0
  Stopped: 5
 Images: 12
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-101-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.752GiB
 Name: 
 ID: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
