### ISSUE TITLE
OpenAPI Spec: v1.46: TmpFsOptions has incorrect Options

### ISSUE THREAD

**Issue by mook-as** [moby/moby#48048]
### Description

The new `TmpfsOptions.Options` that landed in #46809 has a slightly incorrect definition.

### Reproduce

The current OpenAPI definition is:
https://github.com/moby/moby/blob/418eed6e4e1a453f9779ad5407b26dbedace83be/docs/api/v1.46.yaml#L445-L462

(This is also the current content in `api/swagger.yaml`)
The matching golang definition:
https://github.com/moby/moby/blob/418eed6e4e1a453f9779ad5407b26dbedace83be/api/types/mount/mount.go#L122-L126

Since it's a `[][]string`, there should only be two levels of `array` in the OpenAPI spec.  Also, the outermost level `array` shouldn't have `properties:` (it should have `items:` instead).

### Expected behavior

```yaml
          Options:
            description: |
              The options to be passed to the tmpfs mount. An array of arrays.
              Flag options should be provided as 1-length arrays. Other types
              should be provided as as 2-length arrays, where the first item is
              the key and the second the value.
            type: "array"
            items:
              type: "array"
              minItems: 1
              maxItems: 2
              items:
                type: "string"
            example:
              [["noexec"]]
```

### docker version

```bash
By inspection, at commit 418eed6e4e1a453f9779ad5407b26dbedace83be
```

### docker info

```bash
N/A
```
