### ISSUE TITLE
Docker-27.0.2: "invalid pool request: Pool overlaps with other one on this address space"

### ISSUE THREAD

**Issue by Ruppsn** [moby/moby#48069]
### Description

When deploying 2 different services that create two default overlay networks the pools overlap. 

`docker network ls`

```
g95ig8djzy7x   hello2_default    overlay   swarm
ctaqjrn0vn8l   hello_default     overlay   swarm
```

`docker network inspect hello_default`

```
[
    {
        "Name": "hello_default",
        "Id": "ctaqjrn0vn8lg34cr4dkyxy1w",
        "Created": "2024-06-27T12:14:34.070599327+02:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
...
```

`docker network inspect hello2_default`

```
[
    {
        "Name": "hello2_default",
        "Id": "g95ig8djzy7xkn3usy56aiqhs",
        "Created": "2024-06-27T10:14:41.019271831Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
```

### Reproduce

1. `docker stack deploy -c docker-compose.yml hello`

docker-compose.yml
```
version: '3.9'
services:
    helloworld:
        # This will set the hostname to helloworld-ReplicaID
        hostname: "helloworld-{{.Task.Slot}}"
        # The image, we will use a helloworld http image
        image: strm/helloworld-http
        # We will expose the service at port 8080 on the host
        ports:
            - "8080:80"
        # Docker Swarm configuration deployment configurations!
        deploy:
            # We want to replicate our service...
            mode: replicated
            # And it will have two instances of the container!
            replicas: 2
```

2. `docker stack deploy -c docker-compose2.yml hello2`

docker-compose2.yml
```
version: '3.9'
services:
    helloworld:
        # This will set the hostname to helloworld-ReplicaID
        hostname: "helloworld-{{.Task.Slot}}"
        # The image, we will use a helloworld http image
        image: strm/helloworld-http
        # We will expose the service at port 8081 on the host
        ports:
            - "8081:80"
        # Docker Swarm configuration deployment configurations!
        deploy:
            # We want to replicate our service...
            mode: replicated
            # And it will have two instances of the container!
            replicas: 2
```

3. Get Errors for the second deployment:

`docker service ps hello_helloworld`

```
ID                          NAME                 IMAGE                                                                                                 NODE      DESIRED STATE   CURRENT STATE            ERROR     PORTS
pnogka48shpgl7lhms9h8larz   hello_helloworld.1   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Running         Running 10 minutes ago             
t2wi1mqqdslsdw4d7y18s2ydq   hello_helloworld.2   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Running         Running 10 minutes ago  
```

`docker service ps hello2_helloworld`

```
ID                          NAME                      IMAGE                                                                                                 NODE      DESIRED STATE   CURRENT STATE             ERROR                                                                        PORTS
qf0yfoi0bxtfk48slavtitdam   hello2_helloworld.1       strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Ready           Rejected 3 seconds ago    "invalid pool request: Pool overlaps with other one on this address space"   
t6g1c0u9p7g4c226qo07eovo0    \_ hello2_helloworld.1   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 8 seconds ago    "invalid pool request: Pool overlaps with other one on this address space"   
lqam7vqx9sx82louvox1kqedb    \_ hello2_helloworld.1   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 13 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"   
s97npp0s9qnhbcmioumae0xpi    \_ hello2_helloworld.1   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 18 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"   
t89ma0jtv63sjcspaa77o6nox    \_ hello2_helloworld.1   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 23 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"   
tznzhppotx9h0s5zjl7220b94   hello2_helloworld.2       strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Ready           Rejected 3 seconds ago    "invalid pool request: Pool overlaps with other one on this address space"   
ockjm2cee6geoqttd2bl92w8h    \_ hello2_helloworld.2   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 8 seconds ago    "invalid pool request: Pool overlaps with other one on this address space"   
n0kt0gemzt4ej6mlk31kwqe58    \_ hello2_helloworld.2   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 13 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"   
3kbmsmf1pwqgoshylkmuinsr6    \_ hello2_helloworld.2   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 18 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"   
agyzys3aagtk3q9nku401mbfs    \_ hello2_helloworld.2   strm/helloworld-http:latest@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45   covm76    Shutdown        Rejected 23 seconds ago   "invalid pool request: Pool overlaps with other one on this address space"  
```

### Expected behavior

It should work like in docker-26.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.2
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        912c1dd
 Built:             Wed Jun 26 18:49:12 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       e953d76
  Built:            Wed Jun 26 18:47:31 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 62
 Server Version: 27.0.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: mc6ov250a0vkagiou6qgkwzmr
  Is Manager: true
  ClusterID: r47x9p70ppopcr59qafure1co
  Managers: 1
  Nodes: 1
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 30 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: xxxx
  Manager Addresses:
   xxxx:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-207.156.6.el9uek.x86_64
 Operating System: Oracle Linux Server 9.4
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 34.79GiB
 Name: covm76
 ID: ddd25d58-cbdf-4859-97ae-601b888171e1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Testet under Oracle Linux 8 and 9 and Ubuntu 24. Same result
