### ISSUE TITLE
Memory Leak in Docker 27.0.3

### ISSUE THREAD

**Issue by MrPowerGamerBR** [moby/moby#48144]
### Description

After I updated to Docker 27.0.3 (I do not remember what was the older version, sorry, I upgraded my dedicated servers when the RegreSSHion exploit happened, but technically the older version is a version between 10/01/2024 (when the system was installed) and 01/07/2024 (when I upgraded all packages)) the `dockerd` daemon is leaking memory like crazy, in two of my dedicated servers `dockerd` ends up eating so much memory that containers end up getting OOM'd by the system

![image](https://github.com/moby/moby/assets/9496359/3e257f9c-bef9-436f-ba7e-be2806b81394)

If I restart Docker, the `dockerd` memory usage drops to ~200MB, and then keeps increasing and increasing and increasing...

### Reproduce

*I don't know how to reproduce this yet*

### Expected behavior

That `dockerd` does not eating up so much memory.

### docker version

```bash
Docker version 27.0.3, build 7d4bcd8
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 68
  Running: 68
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-41-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 125.7GiB
 Name: saiyan-seeker
 ID: 3ae68731-57aa-49b8-bc88-c007cbcc3059
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 20
   Base: 192.168.0.0/16, Size: 24
```

### Additional Info

Yeah, this issue doesn't really help a lot to figure out what is actually the issue... When I was looking at other comments, I found out that there is a way to create a heap dump of the `dockerd` process, but the link on how to do it is unavailable and it a mirror is not available on the Wayback Machine, so I wonder if someone has a working link about how to do it? https://github.com/moby/moby/issues/39916#issuecomment-532156804

**Comment by MrPowerGamerBR** [comment]
Figured out how to heap dump Docker!

`curl -v --silent -XGET --unix-socket /run/docker.sock http://localhost/debug/pprof/heap > /srv/docker-heap-dump`

**Sources:**

* https://sleeplessbeastie.eu/2021/12/13/how-to-query-docker-socket-using-curl/
* https://github.com/moby/moby/issues/42125#issuecomment-7997898

**In Use Objects:**
![docker_inuse_objects](https://github.com/moby/moby/assets/9496359/cf242275-ae60-4d91-93fa-e5983fe70245)

**In Use Space:**
![docker_in_use_space](https://github.com/moby/moby/assets/9496359/a6bd4cb5-6eb9-473d-bf4a-4912b58f2f80)

**Alloc Space**
![docker_alloc_space](https://github.com/moby/moby/assets/9496359/112cc594-7adf-46cd-8d93-93c014f607d7)

**Alloc Objects:**
![docker_alloc_objects](https://github.com/moby/moby/assets/9496359/58a99ac5-8bec-41bf-9454-5f7cbb7ce452)

By the way, can I share the heap dump file, or does it contain sensitive secrets?

**Comment by MrPowerGamerBR** [comment]
There is only one dedicated server that I have that isn't affected by that memory leak, but that dedicated server only has two  containers running, and both are PostgreSQL containers. They have another key difference that other dedicated servers do not have: none of the two containers running on that dedicated server have health probes (Docker Compose's `healthcheck`) set up.

```yml
version: "3.9"
services:
  powercms:
    image: ghcr.io/mrpowergamerbr/powercms@sha256:22262da1468bb3bdd775027da3b2d6cdcaf69859fa1c9b245d414713b4b4b093
    network_mode: service:tailscale
    volumes:
      - type: bind
        source: ./content/
        target: /content
    environment:
      JAVA_TOOL_OPTIONS: "-verbose:gc -XX:+UnlockExperimentalVMOptions -Xmx1G -Xms1G -XX:+UseG1GC -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/br/"] # What command will be used to check if the system is healthy or not
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      tailscale:
        condition: service_healthy
  tailscale:
    hostname: powercms
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    volumes:
      - "./tailscale_var_lib:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
      - net_raw
    command: tailscaled
```

Could it be related to health checks? A lot of my containers are set up like this, with a Tailscale service container running alongside it.

But then again, the heap dump shows that it is something related to http requests, so it is probably not it... but idk I don't know about go.
