### ISSUE TITLE
Allow Docker Plugins to use specific Docker Networks at Runtime

### ISSUE THREAD

**Issue by aek** [moby/moby#48542]
### Description

Using Docker plugins it will be extremely useful to use user defined Docker Networks to be able to access some container resources internally without the need to publish the container ports to the Host.
For example let's take the plugin `grafana/loki-docker-driver`. Docs at: https://grafana.com/docs/loki/latest/send-data/docker-driver/
Also I have develop a Docker Volume Plugin for Redis
I'm using those drivers in a Docker Compose Service like this:

compose.yaml
```yaml
services:
  my_service_name:
    image: my_repo/my_service_image
    scale: 1
    restart: always
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-tenant-id: 08e0077a-fcb1-49b8-9966-d16fe7d218e0
    volumes:
    - type: volume
      source: redis_sessions
      target: /opt/sessions
volumes:
  redis_sessions:
    name: redis_sessions
    driver: redis
    driver_opts:
      db: '0'
      host: localhost
      port: '6379'
      folder: ''
```
The Redis and Loki services that I'm targeting are also running as Docker Containers in other Compose Projects. For that to work I need to define in their correspondent compose.yaml the export of the Redis port "6379:6379" and Loki port "3100:3100" to be available to the Host to be accessible at localhost at first test. Now if I wanna use the Docker Compose Services for Loki and Redis in another server I would need to make it available in a Reverse Proxy or allow the communication for those ports on the Network to be able to use the Services as the backend for the Loki and Redis Plugins

What I Picture as a better solution is:
1- The possibility to be able to attach my containers to the plugins network if there is a way to create a network for the plugin. I haven't found any references of this possibility
If I could create a new network that could be attached to the plugin at runtime or during the plugin install. 
I have reviewed the plugin config and it have a network config and since I control some plugins I could modify their config to use the network bridge but mostly all the third party plugins already developed came with the network type host so that it's not a proper solution.

compose.yaml
```yaml
services:
  my_service_name:
    image: my_repo/my_service_image
    scale: 1
    restart: always
    logging:
      driver: loki
      networks:
      - loki
      options:
        loki-url: http://my_loki_container_name:3100/loki/api/v1/push
        loki-tenant-id: 08e0077a-fcb1-49b8-9966-d16fe7d218e0
    volumes:
    - type: volume
      source: redis_sessions
      target: /opt/sessions
networks:
  redis:
    name: redis
    driver: bridge
    external: true
  loki:
    name: loki
    driver: bridge
    external: true
volumes:
  redis_sessions:
    name: redis_sessions
    networks:
    - redis
    driver: redis
    driver_opts:
      db: '0'
      host: my_redis_container_name
      port: '6379'
      folder: ''
```
This way when the Plugin it's used it have everything to be running the proper user defined networks in the volume and logging configuration 

2- The possibility to join the Plugin requests to the Service container networks context to be able to resolve other containers that could be able to be discovered from the service container. 

compose.yaml
```yaml
services:
  my_service_name:
    image: my_repo/my_service_image
    scale: 1
    restart: always
    logging:
      driver: loki
      options:
        loki-url: http://my_loki_container_name:3100/loki/api/v1/push
        loki-tenant-id: 08e0077a-fcb1-49b8-9966-d16fe7d218e0
    networks:
    - redis
    - loki
    volumes:
    - type: volume
      source: redis_sessions
      target: /opt/sessions
networks:
  redis:
    name: redis
    driver: bridge
    external: true
  loki:
    name: loki
    driver: bridge
    external: true
volumes:
  redis_sessions:
    name: redis_sessions
    driver: redis
    driver_opts:
      db: '0'
      host: my_redis_container_name
      port: '6379'
      folder: ''
```
 The idea it's to attach the Compose Service that will use the Loki and Redis Plugins to the Networks of the Redis and Loki  Services and allow the Plugin to discover the resources available in those Networks. In this case it should be able to resolve **my_loki_container_name** to the Loki Compose Service Container and **my_redis_container_name** to the Redis Compose Service Container. 
So the plugin requests in this option needs to run with the networks attached like any other container.
I have tried to find a way to run the plugins as Compose Services like I have seen [here](https://github.com/gopher-net/docker-ovs-plugin?tab=readme-ov-file) with some modifications but docker doesn't let me pull a docker plugin image to be used as a Compose Service. I also haven't found many references about how to run a plugin as a container since that could be a solution if I could be able to associate the plugin container with the required networks and use those networks to resolve other containers.

---
All of this is also useful when you run your containers on an overlay network so your plugin locally could be able to discover container services associated to the overlay network

Please if there is something i'm missing out that could help to bring light to this feature or if there is a potential workaround that I'm not aware of, please share your inputs here
