### ISSUE TITLE
Support wildcards with bind mounts

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [moby/moby#48765]
### Description

Bind mounts is the most convenient feature that suits my needs for a particular container. However, since there is no possibility to use wildcards, it can turn into a mess.

I have hundreds of files that should be bound to a directory. I can't bind a full directory because the whole content of the directory will be overwritten.  The application code is closed so there is no possibility to make application work with other supplementary directory. So I have to do the following thing:

```
volumes:
    - type: bind
      source: ${HOME}/custom_file1.txt
      target: /server/Data/custom_file1.txt
    - type: bind
      source: ${HOME}/custom_file2.txt
      target: /server/Data/custom_file2.txt
```

It gets messy when there are plenty of them. It could be useful to have the ability to use wildcards with bind mount like this:

```
volumes:
    - type: bind
      source: ${HOME}/*
      target: /server/Data/
```

Means, everything in the "${HOME}" directory should be bound to the "/server/Data/" directory as separate files with the same corresponding names.
