### ISSUE TITLE
Make Docker overlay network use a custom overlay network as the default for eth0 instead of the ingress network

### ISSUE THREAD

**Issue by seqwait** [moby/moby#48941]
### Description

how to Make Docker overlay network use a custom overlay network as the default for eth0 instead of the ingress network.
```

version: '3.8'
services:
  app:
    image: praqma/network-multitool
    environment:
      DUBBO_IP_TO_REGISTRY: "{{.Service.Name}}"
      JAVA_OPTS: "-Xms512M -Xmx2048M"
      RUN_OPTS: "--spring.profiles.active=prod --app.name=app"
    ports:
      - target: 18081
        published: 18081
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      my_overall:
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.my.app == yes"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first

networks:
  my_overall:
    external: true
    name: my_overall
    attachable: true

```
