### ISSUE TITLE
Deprecate `VOLUME` instruction for future removal

### ISSUE THREAD

**Issue by polarathene** [moby/moby#49482]
### Description

**NOTE:** https://github.com/moby/moby/issues/43190 proposes an opt-out feature. This issue instead proposes deprecating/removing the behaviour of `VOLUME` in containers. I'm not entirely sure if this is the right repo to propose this.

If choosing to reject/close, please do consider at least updating the docs from Sep 2014, along with differences with Docker Compose.

---

The [`VOLUME` instruction](https://docs.docker.com/reference/dockerfile/#volume) should be deprecated?
- Containers **already persist state internally** until the container is destroyed (_for example, an image upgraded to a new tag_).
- Proper persistence externally **should be explicit**.
- The [docs cite performance as another benefit](https://docs.docker.com/engine/storage/volumes/#when-to-use-volumes) of volumes, but does an implicit volume make sense when performance actually matters? (_explicit bind mount or [named / anonymous volume](https://docs.docker.com/engine/storage/volumes/#named-and-anonymous-volumes) indicate the intent far better?_)

I recall a long time ago `VOLUME` served a useful purpose due to limitations at the time, but I'd appreciate reasoning for what pragmatic value implicit volume creation offers today? My experience when I encounter this with images is often problematic as detailed below.

I'm not too familiar with compatibility outside of Docker, but ~~apparently [Kubernetes doesn't leverage it](https://kodekloud.com/community/t/declaring-volume-in-docker-file-behaviour-in-kubernetes-world/424501)~~ (_**EDIT:** [seems to be a bug](https://github.com/kubernetes/kubernetes/issues/128500)_), [Podman does](https://docs.podman.io/en/v5.1.1/markdown/podman-run.1.html#image-volume-bind-tmpfs-ignore).

---

Anonymous volumes are created when an image has a `VOLUME` instruction. They will initialize by copying any of the existing content at the mount point (_unlike a bind mount volume which typically replaces content at the mount point_):
  - With `docker run --rm ...`, each container instance started will create a new anonymous volume. Without the `--rm`, these will accumulate pointlessly (_as they would with `-v /explicit-anonymous`_).
  - Docker Compose behaves differently, with additional logic to preserve the same anonymous volume across instances of the ~~container~~ service for a given compose project (_see caveats section below_).

---

The `VOLUME` instruction provides **no value** to an image. It **only causes problems**.

If there is a valid scenario in the wild where images should continue to use `VOLUME` rather than have persistence configured explicitly by the user with their container tool (_Docker, Podman, Kubernetes, etc_), it would be appreciated to document that more clearly.

For detailed justification, please see [my previous write-up](https://github.com/ory/hydra/issues/3683) on this subject. I've also taken time to illustrate more context below.

## Examples

Problematic behaviour due to implicit anonymous volumes:

- Docker Compose - Unintentional first-in first-served creation
  - Occurs when the anonymous path of a service is shared and the image for that service changes to another with the same anonymous path.
  - See reproduction below in the "caveats" section.
- [Docker Compose preventing a clean slate](https://github.com/kanidm/kanidm/pull/2948):
  - Associated anonymous volume is difficult to identify via CLI unless the container is still available to inspect.
  - `docker compose down` / `docker compose up --force-recreate` destroy a container but the anonymous volume persists. (_**EDIT:** `--renew-anon-volumes` can be used since Compose 2.29.3 (Sep 2024), for prior releases of Compose must be explicitly paired with `--force-recreate`_)
    - `docker volume prune` can alternatively be used, as the default is only for anonymous volumes not attached to a container. This is brute-force in the event there are detached anonymous volumes that you do want to keep (_but cannot identify_).
- [Example of implicit 2GB disk usage per container instance](https://github.com/rspamd/rspamd/issues/4400#issuecomment-1745881053):
  - In this scenario the image has seeded the volume path with a large dataset.
    - Implicitly creating volumes with that data copied rarely makes sense, especially when it's duplicated/accumulated.
    - Delays container startup due to copy. Similar to Rootless containers (_unrelated to `VOLUME`, my experience is limited with rootless but I've seen similar copy behaviour with Podman such as with `--uidmap`_).
  - This concern is not applicable to images published with an empty `VOLUME` dir.

---

### `docker-library` specific

There are various (stale?) issues across `docker-library` repos requesting removal of `VOLUME` (_[mongo](https://github.com/docker-library/mongo/issues/306#issuecomment-1990769910), [postgres](https://github.com/docker-library/postgres/issues/404#issuecomment-427325278), [mysql](https://github.com/docker-library/mysql/issues/255), [redis](https://github.com/docker-library/redis/issues/140)_), but these continue to be unresolved for 6-8 years since their creation.

If `VOLUME` were to be ignored for containers, it could still be useful as a hint in a `Dockerfile`, communicating metadata similar to the `EXPOSE` instruction (_and an option to explicitly leverage that_).

[This comment](https://www.reddit.com/r/docker/comments/l7hbzd/comment/gl9bskl/) suggests that `VOLUME` would be useful for the convenience of mounting an anonymous volume without users having to do so explicitly, to avoid a problem scenario with CoW storage writes (_I'm not familiar enough here, but I don't think a container's internal storage is making more than one copy as a file is overwritten repeatedly?_).

### Docker "Best Practices" docs on image building

Docker docs ["Best Practices" page for building images](https://docs.docker.com/build/building/best-practices/#volume (_advice [since **Sep 2014**](https://github.com/docker/docs/blob/d9fd5f6199aebb9ea784f5b23ec97b960f89f3d4/docs/sources/articles/dockerfile_best-practices.md?plain=1#L272), lacking additional context to back this advice_)

> _You should use the `VOLUME` instruction to expose any database storage area, configuration storage, or files and folders created by your Docker container. You are strongly encouraged to use `VOLUME` for any combination of mutable or user-serviceable parts of your image._
> 
> _For more information about `VOLUME`, see [Dockerfile reference for the VOLUME instruction](https://docs.docker.com/reference/dockerfile/#volume)._

Given the Sep 2014 date, I'm pretty sure that advice is outdated and better practices for this today.. yet the Best Practice docs continue to endorse it which can be misleading to image maintainers? Since 2014, this advice is more likely to be referring to volumes for persistence in general... IIRC support for bind mounts and even named volumes outside of `Dockerfile` arrived at a later date?

I assume these volumes are effectively bind mounts (_docs could better indicate that?_), but [according to this](https://www.reddit.com/r/docker/comments/l7hbzd/comment/gl7z2iw/) the current default storage driver (_OverlayFS2, may differ with host_) in many cases shouldn't have much performance overhead concerns. Perhaps that was more of a problem in the past before this became the default storage driver (_which it has been for some time IIRC?_).

### Docker Compose caveats

Docker Compose does not appear to document the divergence in expectation of removing anonymous volumes when their associated container is destroyed (`docker compose down` / `docker compose rm <service name>`).
- https://docs.docker.com/reference/compose-file/services/#volumes
- https://docs.docker.com/reference/compose-file/volumes/

`docker compose up` does have a CLI option as a workaround with [`-V` / `--renew-anon-volumes`](https://docs.docker.com/reference/cli/docker/compose/up/) (_**NOTE:** For Compose V2, between 2.0.0 to 2.29.3 (Sep 2024) this feature [implicitly depended upon an explicit `--force-recreate`](https://github.com/docker/compose/issues/10774#issuecomment-2343228571)_), but there is no equivalent to [`docker compose run --rm`](https://docs.docker.com/reference/cli/docker/compose/run/) for when containers are stopped.

Here's a reproduction worth noting. With the explicit anonymous volume, it's less surprising, but I doubt many users would expect the implicit `VOLUME` behaviour when switching images?

```yaml
# 1st run no output as /example is empty,
# 2nd run volume has persisted data, even if container is a fresh instance via `--force-recreate`
# 3rd run change the service image, new container is forced created implicitly,
#         and the same volume is persisted.
# 4th run change the service name, now a new anonymous volume is created. Undocumented.
#
# NOTE: If the images have the same `VOLUME /example` instruction when built,
# they too will share the same persisted volume if `image` changes between them under the same service name
# An explicit anonymous volume at the same path in `compose.yaml` can be added or removed,
# it shares the same anonymous volume as the individual images `VOLUME /example` does.
services:
  example:
    image: alpine #debian:12-slim
    volumes:
      - /example
    command: /bin/sh -c 'ls /example && touch /example/hello-world'
```

```Dockerfile
# Optionally build each of these to change the compose service image used:
# Remove the compose anonymous volume, both images will still share the anonymous volume
FROM alpine AS v-alp
VOLUME /example

FROM debian:12-slim AS v-deb
VOLUME /example
```

In practice, usage of anonymous volumes are more likely in environments that discard everything afterwards (_test suites_), or implicitly inherited via an image `VOLUME` instruction.
- Users wanting to [ensure implicit anonymous volumes are cleared](https://github.com/docker/compose/issues/10774#issuecomment-2342381094) (_because the implicit persistence is not desired in the first place_)
- Users requesting [opt-out via daemon config](https://github.com/moby/moby/issues/43190) (_as otherwise requires providing an explicit bind mount or named volume to avoid creating anonymous volumes_)

Users are less likely to check for such, so when coupled with the Docker Compose behaviour described above, in the event a common service name is used (_eg: `db` / `web`_) and the image is changed, implicit `VOLUME` usage can be prone to mishaps if not careful to use `--renew-anon-volumes` / `docker compose down && docker volume prune`.

Or more commonly, if an image with `VOLUME` is used and relied upon for all/some state persistence.. Upgrading an image to a new release may fail [like in this case](https://github.com/kanidm/kanidm/pull/2948) when the user is not expecting data to be carried over to a new image/container.

---

Here are some DB images with overlapping `VOLUME` paths:

- `/data`:
  - https://github.com/docker-library/mongo/issues/721
  - https://github.com/redis/docker-library-redis/issues/433
  - https://github.com/valkey-io/valkey-container/issues/50
- `/var/lib/mysql`:
  - https://github.com/docker-library/mysql/issues/1101
  - https://github.com/MariaDB/mariadb-docker/issues/639

The [Docker docs direct users](https://docs.docker.com/compose/support-and-feedback/samples-for-compose/#awesome-compose-samples) to the Github `awesome-compose` repo, which has [extensive use of services named `db`](https://github.com/search?q=repo%3Adocker%2Fawesome-compose%20db%3A&type=code) with different DB images listed above.

It's probably common to see elsewhere too, where a user may try with one image initially that the example provides (_like [this one with no explicit anonymous volume](https://github.com/docker/awesome-compose/blob/18f59bdb09ecf520dd5758fbf90dec314baec545/wasmedge-mysql-nginx/compose.yml#L22-L25)_), and then switch to another (_such as mongo to valkey_) as they adapt the example to their own project, but leave the service name as-is. I can see that being problematic in some scenarios (_with valkey/redis perhaps some incompatible or subtle differences, existing data implicitly carried over concern aside_).

**Comment by polarathene** [comment]
### Docker Compose caveats

Docker Compose does not appear to document the divergence in expectation of removing anonymous volumes when their associated container is destroyed (`docker compose down` / `docker compose rm <service name>`).
- https://docs.docker.com/reference/compose-file/services/#volumes
- https://docs.docker.com/reference/compose-file/volumes/

`docker compose up` does have a CLI option as a workaround with [`-V` / `--renew-anon-volumes`](https://docs.docker.com/reference/cli/docker/compose/up/) (_**NOTE:** For Compose V2, between 2.0.0 to 2.29.3 (Sep 2024) this feature [implicitly depended upon an explicit `--force-recreate`](https://github.com/docker/compose/issues/10774#issuecomment-2343228571)_), but there is no equivalent to [`docker compose run --rm`](https://docs.docker.com/reference/cli/docker/compose/run/) for when containers are stopped.

Here's a reproduction worth noting. With the explicit anonymous volume, it's less surprising, but I doubt many users would expect the implicit `VOLUME` behaviour when switching images?

```yaml
# 1st run no output as /example is empty,
# 2nd run volume has persisted data, even if container is a fresh instance via `--force-recreate`
# 3rd run change the service image, new container is forced created implicitly,
#         and the same volume is persisted.
# 4th run change the service name, now a new anonymous volume is created. Undocumented.
#
# NOTE: If the images have the same `VOLUME /example` instruction when built,
# they too will share the same persisted volume if `image` changes between them under the same service name
# An explicit anonymous volume at the same path in `compose.yaml` can be added or removed,
# it shares the same anonymous volume as the individual images `VOLUME /example` does.
services:
  example:
    image: alpine #debian:12-slim
    volumes:
      - /example
    command: /bin/sh -c 'ls /example && touch /example/hello-world'
```

```Dockerfile
# Optionally build each of these to change the compose service image used:
# Remove the compose anonymous volume, both images will still share the anonymous volume
FROM alpine AS v-alp
VOLUME /example

FROM debian:12-slim AS v-deb
VOLUME /example
```

In practice, usage of anonymous volumes are more likely in environments that discard everything afterwards (_test suites_), or implicitly inherited via an image `VOLUME` instruction.
- Users wanting to [ensure implicit anonymous volumes are cleared](https://github.com/docker/compose/issues/10774#issuecomment-2342381094) (_because the implicit persistence is not desired in the first place_)
- Users requesting [opt-out via daemon config](https://github.com/moby/moby/issues/43190) (_as otherwise requires providing an explicit bind mount or named volume to avoid creating anonymous volumes_)

Users are less likely to check for such, so when coupled with the Docker Compose behaviour described above, in the event a common service name is used (_eg: `db` / `web`_) and the image is changed, implicit `VOLUME` usage can be prone to mishaps if not careful to use `--renew-anon-volumes` / `docker compose down && docker volume prune`.

Or more commonly, if an image with `VOLUME` is used and relied upon for all/some state persistence.. Upgrading an image to a new release may fail [like in this case](https://github.com/kanidm/kanidm/pull/2948) when the user is not expecting data to be carried over to a new image/container.

---

Here are some DB images with overlapping `VOLUME` paths:

- `/data`:
  - https://github.com/docker-library/mongo/issues/721
  - https://github.com/redis/docker-library-redis/issues/433
  - https://github.com/valkey-io/valkey-container/issues/50
- `/var/lib/mysql`:
  - https://github.com/docker-library/mysql/issues/1101
  - https://github.com/MariaDB/mariadb-docker/issues/639

The [Docker docs direct users](https://docs.docker.com/compose/support-and-feedback/samples-for-compose/#awesome-compose-samples) to the Github `awesome-compose` repo, which has [extensive use of services named `db`](https://github.com/search?q=repo%3Adocker%2Fawesome-compose%20db%3A&type=code) with different DB images listed above.

It's probably common to see elsewhere too, where a user may try with one image initially that the example provides (_like [this one with no explicit anonymous volume](https://github.com/docker/awesome-compose/blob/18f59bdb09ecf520dd5758fbf90dec314baec545/wasmedge-mysql-nginx/compose.yml#L22-L25)_), and then switch to another (_such as mongo to valkey_) as they adapt the example to their own project, but leave the service name as-is. I can see that being problematic in some scenarios (_with valkey/redis perhaps some incompatible or subtle differences, existing data implicitly carried over concern aside_).
