### ISSUE TITLE
Permissions of new parent directories no longer are executable by default

### ISSUE THREAD

**Issue by tobyjwebb** [moby/moby#49851]
### Description

When copying files in a `Dockerfile` using `--chmod=` with a destination path that contains a new directory, the permissions are applied to the new directory also (which can be problematic if the `--chmod` does not include the executable bit set).

This behavior has changed recently, breaking some of our Docker images after updating to the latest Docker version. Was this behavior change intended?

### Reproduce

1. `Dockerfile`:

```Dockerfile
FROM alpine:latest
COPY --chmod=0644 Dockerfile /new/path/
```

2. Run `docker build -t testing .`
3. Run `docker run --rm testing ls /new -l`

### Expected behavior

I would expect the newly created directory to have the executable bit set (this is the behavior of Docker 28.0.4, at least), however, with the latest version of Docker (28.1.1), `drw-r--r--` mode is being set (which corresponds to what was defined in the `--chmod`):

Good:
```
❯ docker run --rm testing ls /new -l
total 0
drwxr-xr-x    1 root     root            20 Apr 23 06:52 path
```
Bad:
```
❯ docker run --rm testing ls /new -l
total 0
drw-r--r--    2 root     root            24 Apr 23 07:04 path
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:54:03 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:20 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-503.23.2.el9_5.x86_64
 Operating System: Rocky Linux 9.5 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 959.9MiB
 Name: intms
 ID: 326898a1-852a-4e2f-956f-f8142c1ae33f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Note that a possible solution to this issue could include implementing a chmod parameter for the directories (`COPY --chmod=0644 --dir-chmod=0755 foo /bar/baz/qux`?)

**Comment by tculp** [comment]
I just ran into this as well. For testing building against different docker engine versions I used this docker-compose file
```
version: "3"
services:
  docker-daemon:
    container_name: "my-docker-daemon"
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: "docker:28.1.0-dind-alpine3.21"
    networks:
      "my-network":
        aliases:
          - "docker"
    privileged: true

  docker-client:
    command: sh -c 'while [ 1 ]; do sleep 1000; done'
    container_name: "my-docker-client"
    depends_on:
      - "docker-daemon"
    environment:
      DOCKER_HOST: "tcp://docker:2375"
    image: "docker:latest"
    networks:
      "my-network": {}
    volumes:
      - ${PWD}:/build
    working_dir: /build

  docker-daemon-locked:
    container_name: "my-docker-daemon-old"
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: "docker:28.0.4-dind-alpine3.21"
    networks:
      "my-network":
        aliases:
          - "docker-old"
    privileged: true

networks:
  "my-network":
    name: "my-network"
```
and
`export DOCKER_HOST="tcp://docker:2375"; docker build --no-cache -t test . && docker run -it --rm test ls -la`
vs
`export DOCKER_HOST="tcp://docker-old:2375"; docker build --no-cache -t test . && docker run -it --rm test ls -la`
