### ISSUE TITLE
Regression in network interface order with multiple interfaces per container

### ISSUE THREAD

**Issue by peterhoneder** [moby/moby#50095]
### Description

Hi all!

This commit introduced a regression in interface order in case containers have multiple interfaces:
https://github.com/moby/moby/pull/47406/commits/fe856b94b5149718b1a7f369220608846fea32bc

The root cause is this line:
https://github.com/moby/moby/pull/47406/commits/fe856b94b5149718b1a7f369220608846fea32bc#diff-f4518e0bed6f8eb7b8a0f874650ddacc308fd0bfce6f0c69878ddf59086c1b28R432

which results in iterating the map in random order (this is golang's standard behavior by design). So if a container then relies on interfaces being added in the requested order, it will instead get an arbitrary order.

This is very simple to repro (see below) and the fix is also trivial since it just requires to iterate the map by sorted key order.

See the additional info for a proposed bugfix.

### Reproduce

use this docker compose file:

```
services:
  edge-os-1:
    image: alpine:3.21.2
    command: >
      sh -c "
        set -xe
        sleep 1
        ip a
        # test if the IP of eth1 is correctly set to the value from this docker compose file
        [ \"$(ifconfig eth1 | sed -n 's/.*inet addr:\\([0-9.]*\\).*/\\1/p' | tr -d '\\n')\" = '192.168.34.4' ] && echo IP_OK || exit 1
      "
    networks:
      aaa_dummy:
      bbb_uplink_network:
        ipv4_address: 192.168.34.4
      ccc_lan_bridge_1_1:

networks:

  default:
    ipam:
      config:
        - subnet: "172.18.0.0/24"
  aaa_dummy:
    ipam:
      config:
        - subnet: "172.18.1.0/24"
  bbb_uplink_network:
    ipam:
      config:
        - subnet: "192.168.34.0/24"
  ccc_lan_bridge_1_1:
    ipam:
      config:
        - subnet: "172.18.3.0/24"
  ccc_lan_bridge_1_2:
    ipam:
      config:
        - subnet: "172.18.4.0/24"
```

then call: ```docker compose up```
You now have a certain chance that the interface order is correct and the test reports "IP_OK", but in the majority of cases it will just fail. Just run it a few times to see how often it happens.

### Expected behavior

The expected behavior is, that if interfaces are added similar to the docker compose from the repro steps, they are added in the correct order. Which in the example of the repro steps is:
- aaa_dummy -> eth0
- bbb_uplink_network -> eth1
- ccc_lan_bridge_1_1 -> eth2

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:38 2025
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:38 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 55
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-25-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 12.76GiB
 Name: ubuntu
 ID: c4fa2672-c03f-49ed-a1c1-2bfcae7ea705
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 43
  System Time: 2025-05-28T00:13:49.413911198+02:00
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The bug was introduced in docker version 28.

The bugfix could be this patch (based on tag 28.1.1):
```
iff --git a/daemon/container_operations.go b/daemon/container_operations.go
index d8e07cb4d1..bcc8340c51 100644
--- a/daemon/container_operations.go
+++ b/daemon/container_operations.go
@@ -7,9 +7,11 @@ import (
        "context"
        "errors"
        "fmt"
+       "maps"
        "net"
        "os"
        "runtime"
+       "slices"
        "strings"
        "time"
 
@@ -434,7 +436,8 @@ func (daemon *Daemon) allocateNetwork(ctx context.Context, cfg *config.Config, c
        for n, epConf := range ctr.NetworkSettings.Networks {
                networks[n] = epConf
        }
-       for netName, epConf := range networks {
+       for _, netName := range slices.Sorted(maps.Keys(networks)) {
+               epConf := networks[netName]
                cleanOperationalData(epConf)
                if err := daemon.connectToNetwork(ctx, cfg, ctr, netName, epConf); err != nil {
                        return err
```

I validated it using a larger patch that adds some traces:
```
diff --git a/daemon/container_operations.go b/daemon/container_operations.go
index d8e07cb4d1..4f61804f29 100644
--- a/daemon/container_operations.go
+++ b/daemon/container_operations.go
@@ -7,9 +7,11 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"maps"
 	"net"
 	"os"
 	"runtime"
+	"slices"
 	"strings"
 	"time"
 
@@ -427,6 +429,11 @@ func (daemon *Daemon) updateContainerNetworkSettings(ctr *container.Container, e
 }
 
 func (daemon *Daemon) allocateNetwork(ctx context.Context, cfg *config.Config, ctr *container.Container) (retErr error) {
+	ctx, span := otel.Tracer("").Start(ctx, "daemon.allocateNetwork", trace.WithAttributes(
+		attribute.String("container.ID", ctr.ID),
+		attribute.String("container.Name", ctr.Name),
+	))
+	defer span.End()
 	start := time.Now()
 
 	// An intermediate map is necessary because "connectToNetwork" modifies "container.NetworkSettings.Networks"
@@ -434,7 +441,18 @@ func (daemon *Daemon) allocateNetwork(ctx context.Context, cfg *config.Config, c
 	for n, epConf := range ctr.NetworkSettings.Networks {
 		networks[n] = epConf
 	}
-	for netName, epConf := range networks {
+	for _, netName := range slices.Sorted(maps.Keys(networks)) {
+		epConf := networks[netName]
+
+		// trace netName of every iterated network
+		span.AddEvent("connectToNetwork", trace.WithAttributes(
+			attribute.String("netName", netName),
+			attribute.String("epConf.MacAddress", epConf.MacAddress),
+			attribute.String("epConf.NetworkID", epConf.NetworkID),
+			attribute.String("epConf.EndpointID", epConf.EndpointID),
+			attribute.String("epConf.IPAddress", epConf.IPAddress),
+		))
+
 		cleanOperationalData(epConf)
 		if err := daemon.connectToNetwork(ctx, cfg, ctr, netName, epConf); err != nil {
 			return err
```
