### ISSUE TITLE
Support new OCI spec for Network Devices

### ISSUE THREAD

**Issue by aojea** [moby/moby#50251]
### Description

Recently OCI added support for Linux Network Devices https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#network-devices , and runc implemented it in https://github.com/opencontainers/runc/pull/4538.

The design of the feature was done to have a similar UX with the existing feature for Linux devices, that `docker` implements using the `--device` flag.

The proposal is to add a new `--netdevice` flag that leverages this new OCI feature.

The use cases for this new feature are on containerized application that consumes the interfaces directly, that is completely different of `docker networks`, where the abstraction is a higher level.

A common use case are in GPU applications that consume RDMA devices, something like

```
docker run --gpus=all --device=/dev/infiniband/uverbs0 --device=/dev/infiniband/rdma_cm --netdevice mlx5_0
```

**Comment by aojea** [comment]
@akerouanton @thaJeztah I was reading the slcand issue and also had a situation this week this feature could have helped me.

if you are able to provide me some hints / straw man sketch on how you envision this implementation I'm able to dedicate some time

**Comment by vvoland** [comment]
Hmm I think this can already work through CDI now (assuming  a runtime with `linux.netDevices` support, such as runc 1.4.0 or newer).

For example:

```yaml
cdiVersion: "1.1.0"
kind: "example.com/network"

devices:
  - name: "wan"
    containerEdits:
      netDevices:
        - hostInterfaceName: "eno2"
          name: "wan0"
```

This can be requested through the existing `--device` flag:

```console
docker run --device example.com/network=wan...
```
